- agent/util-scripts/move-results
They are currently looking for "pbench" which does not work,
so version and release are "unknown" in the agent string.
> Fix yum calls to look for pbench-agent.

- agent/base
- agent/tool-scripts/perf
- agent/tool-scripts/sar
Running pbench in a container requires elevated privileges in order for
perf record -a and iostat device name resolution to work. Create helper
functions to do a container_sanity_check and warn users if privileges
will not allow perf record -a and/or iostat to work properly.
Change-Id: I1c1cdbb16ed29b74d5e1d696009ae0871c3d2a0d
> Elevated container privs required for dev names

- agent/base
- agent/tool-scripts/perf
- agent/tool-scripts/sar
Reverts distributed-system-analysis/pbench#25
Backing this out temporarily while we finish verifying that we have properly open-sourced the first round of code.
> Revert "Elevated container privs required for dev names"

- bgtasks/config/run.conf.example
- bgtasks/pbench/bin/pbench-backup-tarballs
- bgtasks/pbench/bin/pbench-base.sh
- bgtasks/pbench/bin/pbench-copy-sosreports
- bgtasks/pbench/bin/pbench-edit-prefixes
- bgtasks/pbench/bin/pbench-index
- bgtasks/pbench/bin/pbench-unpack-tarballs
- bgtasks/pbench/bin/unittests
We now use a configuration file for the sosreport user/host/dir rather
than just leaving it as an example of the reader, and also clean
various comments in the scripts.
> Use configuration file for sosreport dest

- agent/base
This makes the rpm version for check_install_rpm function
optional. There are cases where we may not know which version of the
package we want to install. This happens when we are requesting
packages that pbench does not build/maintain. An example of this is
systemtap.
> Make rpm version arg option for check_install_rpm

- agent/util-scripts/register-tool
It's important that register-tool include the tool options when making
the call to the tool-specific script. Sometimes installing that tool
requires those options, like with systemtap.
> register-tool includes tool options w tool script

- agent/util-scripts/neutron
> Neutron functions creating, wiring-up ports to OVS

- agent/bench-scripts/gold/pbench_uperf/test-00.txt
- agent/bench-scripts/gold/pbench_uperf/test-01.txt
- agent/bench-scripts/pbench_uperf
- agent/bench-scripts/unittests
We had removed configtools from the pbench report and moved it to its
own repository, so now we just require it to be installed and available
for the unit tests.  As a result, we just needed to remove the in-tree
build of configtools performed by the unit test script.
And fix the pbench_uperf option processing which was emitting a debug
message for "--" instead of just recognizing the termination of the
options.
> Get the bench-scrips unit-tests working

- agent/bench-scripts/pbench_dbench
The unit test for dbench will mostly pass, but fails every once in a
while due to the random order in which the dbench commands are run,
since it is putting them in the background and waiting for them all to
finish in parallel. For unit tests, it is sufficient to have
sequential behavior for now.
This is a bit of a hack, as we have to enable the dbench command with
knowledge of the presence of unit test execution.
> Remove random output of dbench unittests

- agent/util-scripts/edit-prefix
- agent/util-scripts/metadata-log
Make metadata-log and edit-prefix use the new package name
when gathering version/release info.
> Fix package name: pbench --> pbench-agent

- README.md
the hyperlinks had the prefix "http://" missing.. [`distributed-system-analysis.github.io/pbench/` was pointing to `https://github.com/distributed-system-analysis/pbench/blob/master/distributed-system-analysis.github.io/pbench/pbench-agent.html` as an extended param, instead of directing to `http://distributed-system-analysis.github.io/pbench/`
> correct hyperlinks for Guide (add http://)

- agent/util-scripts/activate-local-installation
Add script to copy the local config file and pbench keyfile
to their proper places.
The idea is that the generic pieces (pbench-agent and configtools)
will exist as packages based on upstream code.
The local bits (the local config file and the keyfile) will exist in
an internal package only: this package will have dependencies on the other
two, so when installed or updated, it will pull in those two if
necessary. Then it will stash the local bits in some place and call
this script in the post-install phase to copy them to their final
resting place.
> Add generic script to activate local installation.

- bgtasks/pbench/bin/pbench-unpack-tarballs
Make pbench-unpack-tarballs chmod directories to at least 555
and files to at least 444.
Rationale: sometimes, results directories are moved into the pbench
results directory, before move-results is called to copy the whole
thing over. There have been cases where perms on those directories
were tight enough that the results were not visible on the web. The
above modes should be enough to alleviate that problem.
> Make permisssions on unpacked files/directories more liberal.

- bgtasks/pbench/bin/pbench-unpack-tarballs
Make pbench-unpack-tarballs chmod directories to at least 555
and files to at least 444.
Rationale: sometimes, results directories are moved into the pbench
results directory, before move-results is called to copy the whole
thing over. There have been cases where perms on those directories
were tight enough that the results were not visible on the web. The
above modes should be enough to alleviate that problem.
Fixed creation of $TMP/$hostname - this was removed from
pbench-base.sh and moved to this file in another branch, but the
deployed scripts were of mixed origin.
> Make permisssions on unpacked files/directories more liberal (continuation of PR#84)

- .travis.yml
- agent/util-scripts/metadata-log
This emulates the behavior of collect-sysinfo, which
is a good thing.
> Make metadata-log create the directory if necessary.

- agent/base
- agent/bench-scripts/user-benchmark
- agent/util-scripts/metadata-log
metadata-log is supposed to be called at the beginning of a run (with
a "beg" argument) and again at the end of the run (with an "end"
argument). Most bench scripts call it through collect-sysinfo.
user-benchmark is an exception: it calls it explicitly at the
beginning and through collect-sysinfo at the end. User scripts are a
problem (as usual).
Make metadata-log "end" check for the existence of the metadata.log
file and if not, make it call metadata_log_start explicitly to write
the file. Since the timestamp cannot be obtained from the date command
at that point, we make it use the $date variable that the base script
sets. That should make sure that we have a reasonable metadata.log file
if metadata-log "end" is called.
Since we use UTC for all other timestamps, make all timestamps be …
> Make sure that metadata.log is complete.

- agent/bench-scripts/pbench_fio
missing -r option in list of short options. 
There was
-r|--ramptime
and
-r|--runtime
what caused nothing to be executed when -r was called. After defining it in
option list,this lead to another issue due to having -r at two places (ramptime/runtime)
Added "r" in list of short optins, and removed -r for --ramptime, left for --runtime
> Updated pbench_fio,there was missing -r short option in options

- agent/bench-scripts/pbench_fio
fio supports <load_generator_ip>.filename file format  in case only --directory is passed ( instead of -d|--target )
Updated pbench_fio to accept --directory option which will leave it up to fio to create filenames at --directory location 
Original state where fio filename was predefined ( with -d|--target ) is preserved
> pbench_fio to support <load_generator_ip>.filename format 

- agent/config/pbench-agent.conf.example
- agent/util-scripts/move-results
Replace the explicit value in move-results with a getconf of
the value in the config file.
> Define results_host_info_url in config file.

- agent/util-scripts/activate-local-installation
- doc/Makefile
- doc/pbench-agent.org
Change ownership to pbench.pbench (or whatever is specified
in the config file - pbench.pbench is the default).
Change mode of id_rsa file to 640 - that allows anybody in
the pbench group to call move/copy-results successfully.
> Adjust ownership/mode of "activation" files.

- agent/bench-scripts/pbench_fio
Default fio value for numjobs is 1. pbench_fio inherits this value too without possibility to change it. This patch enables pbench_fio to accept numjobs parameter to have desired value if necessary.
If not specified, then pbench_fio will use default of
numjobs=1
It is desired when running i/o tests sometimes to have more than 1 job (numjobs) 
@ndokos @atheurer @portante please review and ack/nack. Thank you
> enable pbench_fio to accept numjobs parameter  

- agent/bench-scripts/postprocess/fio-postprocess
Some versions of fio produce an extra disk-stats array.
This change makes the postprocess script ignore the extra array
if present.
> Ignore extra disk-stats array if present.

- agent/bench-scripts/pbench_fio
line 75 : there was typo ... in #105 we fixed this but this was not removed. Here fixed
line 307: function fio_install was changed in a way not to install fio in case there is already fio binary installed.This helps to run pbench_fio with fio versions different than $ver specified in pbench_fio. This change now applies on fio clients too
line 322: modified fio_install not to install fio on client  / test machines if
--noinstall=y
specified 
if --noinstall is ommited from command line, previous state was preserved - it will go to client machines and and install fio on them 
line 465: in /opt/pbench-agent/base we have $ssh_opts defined and that variable is then used by ssh. In pbench_fio we had ssh_options instead of ssh_opts. Fixed that typo
line 487: changed to support multiple jobs when …
> updated pbench_fio with below changes 

- server/pbench/bin/gold/test-5.txt
- server/pbench/bin/pbench-unpack-tarballs
- server/pbench/bin/unittests
This is only a half-measure (or less): if there are multiple tarballs waiting
to be processed, it will process them in increasing size order, so
the short ones will finish sooner. But once a long one is encountered,
everything will be queued behind it, until it is finished. But it's a simple
change, already implemented and tested in pbench-index.
It also takes care of the (unlikely) event of long command lines.
> Sort the list of tarballs by size before processing.

- .travis.yml
Not sure why it was not required on the old infrastructure, but
it seems to be necessary on the new one.
> Need to run apt-get update for travis-ci.

- agent/tool-scripts/datalog/oc-datalog
- agent/tool-scripts/datalog/pprof-datalog
- agent/tool-scripts/kvm-spinlock
- agent/tool-scripts/oc
- agent/tool-scripts/postprocess/oc-postprocess
- agent/tool-scripts/postprocess/pprof-postprocess
- agent/tool-scripts/pprof
Unifying #132, #126 , #137  in one PR 
oc - oc - Openshift Developer and Administrator Client
this tool will collect
oc get [ rc nodes ep pods pv pvc svc projects cs ] -o wide - every 10 seconds
and
oc get ev -o wide - only once at end of test
to start it
register-tool --name=oc
data will be collected in .txt format
pprof will collect profile data for OSE master ( atomic-openshift-master ) or OSE node ( atomic-openshift-node )
By default will collect data for atomic-openshift-master in case started with
register-tool --name=pprof
To profile atomic-openshift-node start pbench tools with
register-tool --name=pprof -- --profile=cpu --osecomponent=node
profile can be: cpu or mem
osecomponent can be : master or node, default is master
--- --- this is limitation of pprof ----
not possible to …
> pprof and oc tools 

- .travis.yml
- server/pbench/bin/unittests
The travis build environment (ubuntu precise) supports python3.2
only. Recent pip apparently has *stopped* supporting python3.2.
We had to go through hoops to make the previous environment work,
but that is now broken. So we go through a different set of hoops
that make the build work, but there now seem to be unit test failures
that were not there before: they are under investigation.
> Fix travis build.

- .travis.yml
- agent/base
It only output the first one, but it is called with "$@",
which expands to multiple arguments.
Opportunistically, delete duplicate run of util-scripts unittests
from .travis.yml.
> Make debug_log deal with all its arguments.

- agent/tool-scripts/perf
We found some cases where when a longer run (1hour) was run on a system with 32GB of RAM, that the post-processing step of the perf data would be OOM-killed by the kernel.  When post-processing fails, the system is left in an awkward state that needs to be cleaned up, and it also may prevent the collection of remotely-registered data recordings.
We already set the perf recording frequency to 100Hz when we enable callgraphs.  This patch sets the perf frequency to 100Hz by default to reduce the sampling size.  In my experience this won't cause a loss of fidelity in trace data.
> reduce sampling interval for perf to 100Hz

- agent/tool-scripts/kvm-spinlock
turbostat doesn't work inside a KVM guest, so do not allow it to be registered as a tool.  This lets us keep the same default tool-set but special-case when pbench is being run inside kvm.
Strangely enough, turbostat works OK on EC2 but I'm not sure I trust the data.
Tested like so:
```
pbench-agent-0.36-5g439ab75.noarch (plus this PR)
KVM
0
pbench is running inside a KVM guest.  Disabling turbostat.
For some reason this tool could not be installed
0
```
> disable turbostat when running inside a KVM guest

- agent/tool-scripts/oc
- agent/tool-scripts/pprof
pprof tool to collect openshift profile data using pprof
usage :
register-tool --name=pprof -- --osecomponent=<master|node> --interval=X
register-tool --remote=<remote-machine> -- --osecomponent=<master|node> --interval=X
interval defaults to 10 seconds if not specified.
oc - openshift client will collect oc data for "rc ep pods pv pvc svc cs,nodes, ev"
usage:
register-tool --name=oc
> "pprof" and "oc" tools

- agent/util-scripts/pbench-clear-tools
The label was being removed when any tool was removed.
It now sticks around until all tools are removed.
Issue #189.
> pbench-clear-tools: fix label removal.

- agent/bench-scripts/contrib/pbench-bzt
Added a description in the beginning of the file similar to the one found in the other bench tools.
Removed yaml (PyYaml) dependency. pbench_bzt now uses/generates json scenario files.
Added initial platform detection code.
Move pbench-bzt to bench-scripts/contrib: it will be moved
to bench-scripts/ (which is in the PATH) when it conforms
to the standard conventions. Right now, it's just a convenience
wrapper.
> Add blazemeter taurus script to bench-scripts/contrib.

- agent/bench-scripts/gold/pbench-uperf/test-00.txt
- agent/bench-scripts/gold/pbench-uperf/test-01.txt
- agent/bench-scripts/pbench-cyclictest
- agent/bench-scripts/pbench-dbench
- agent/bench-scripts/pbench-fio
- agent/bench-scripts/pbench-iozone
- agent/bench-scripts/pbench-linpack
- agent/bench-scripts/pbench-migrate
- agent/bench-scripts/pbench-netperf
- agent/bench-scripts/pbench-specjbb2005
- agent/bench-scripts/pbench-uperf
The RPMs have been renamed to pbench-* but the RPM check was
still using the unadorned name.
Fix unit tests.
> Fix the calls to check_installed_rpm in all the benchmarks.

- agent/tool-scripts/oc
-> fixed typo
-> if decided to start too, instructed to install 'expect' package - necessary for unbuffer
> modified oc script - typo fix

- server/pbench/bin/pbench-base.sh
This is in the spirit of keeping everything that is
not necessary for primary storage or visualization off
the distributed file system.
> Store cron job script logs in the local file system.

- server/pbench/bin/gold/test-5.txt
- server/pbench/bin/pbench-unpack-tarballs
pbench-unpack-tarballs creates a list file of tarballs it
is going to process in this run, sorts it and then goes
through it, but it does not delete it.
Add a trap to remove it.
> Clean up the list file.

- web-server/v0.3/css/jschart.css
- web-server/v0.3/js/jschart.js
- Orginally I used the CSS outline-* properties to construct the
permanent outlines around the legend rectangle that are not modified
by event actions such as mouse overs and dataset hiding and this
worked fine in Chrome.  It turns out that these properties are
ignored by Firefox in the SVG context and even in Chrome if the page
is zoomed they do not scale properly since they are not actual
vector objects.
- This bug fix replaces the CSS outline-* properties with a secondary
vector element that is independently controlled.  Visually the
primary vector element (which responds to mouse events) is located
inside the secondary element (which ignores mouse events).  In order
to distinguish between the two elements the secondary element has a
visible stroke and an invisible fill.
> Update the jschart legend rectangle outlining code to work with Firefox and vector zooming

- agent/util-scripts/pbench-kill-tools
> Wrong link for pbench-kill-tools.

- web-server/v0.3/css/jschart.css
- web-server/v0.3/js/jschart.js
This simplifies the formatting a lot and should pave the way for future advancements.
@ndokos This is what I was alluding to when we briefly discussed the way formatting is done.
@portante I'm hopeful that this will assist in some of the future efforts you talked about with respect to reskinning things.
Details:
- This update pushes as much formatting as possible into the
stylesheet and then just turns classes on and off on the fly for
dynamic elements.
- A big part of this update is switching from D3's
selection.attr("class", ...) API call to using the
selection.classed(...) API call which allows for classes to be
flipped on and off.
- There are also some minor formatting changes included to fix some
minor issues in a few places.
> Long overdue cleanup of the jschart style and class code

- agent/util-scripts/pbench-sysinfo-dump
Today sosreport collects both the ethtool -c and ethtool -g output we were collecting directly.  We are removing to avoid duplicate data.
See also #264.
> Remove duplicate data collected by sosreports

- agent/tool-scripts/pprof
- updated pprof to point to correct package name for "go" it is "golang", not "go"
- added tool_bin to point to /usr/bin/go
> Updated pprof to point to correct package name for "go"

- agent/tool-scripts/kvm-spinlock
The condition should be -gt, not -ge (in both instances).
> Fix condition for warning of already running tools.

- agent/base
- agent/tool-scripts/kvm-spinlock
Also be sure we don't leak the `rc` variable value out of the
`check_install_rpm` function, and be sure we capture its return value for
`kvm-spinlock`'s exit status.
We also address some whitespace formatting issues with `kvm-spinlock`, and use proper pbench logging methods where applicable.
Enhances #286.
> Using turbostat in a VM is just a warning

- agent/bench-scripts/pbench-fio
When I tried running pbench-fio in distributed mode with --client= syntax, I got this:
verifying clients have fio installed
bash: /opt/pbench-agent/bench-scripts/pbench_fio: No such file or directory
So I suspect it used to be called pbench_fio and then this changed, but it didn't get changed here.  Rather than changing it to pbench-fio, I used **$script_name** so it won't happen again.  Does this happen to any other benchmarking tools with --client option?
> use correct benchmark name

- agent/bench-scripts/pbench-fio
fixes issue #333, providing an option to specify a file containing a list of clients
> Add --client-file option to specify a list of clients

- agent/bench-scripts/pbench-fio
- agent/bench-scripts/templates/fio.job
- agent/bench-scripts/templates/make-fio-jobfile.py
This is by no means a complete template infrastructure but it works for the default `pbench-fio` options, and for a few sample configuration files I tried out. I've included fio's new histogram options in the default config file.
Commit message starts here:
Templating prototype for `pbench-fio`, using config files to specify
fio parameters. The order of precedence used is as follows: (from high
to low)
- Command line options already given to pbench-fio
- Fio job file given with `--job-file`
The defaults in agent/bench-scripts/templates/fio.job match the existing
defaults Additionally the template currently has the following two special
semantics:
- '$target' gets replaced with each of the specified targets, ultimately
making a copy of each of the job file sections with '$target' in
their …
> Templating prototype for pbench-fio

- agent/bench-scripts/pbench-fio
- agent/bench-scripts/postprocess/fio-postprocess
- agent/bench-scripts/postprocess/fio-postprocess-viz.py
This does the following:
- Calls `fiologparser_hist.py`
- Generates jschart / html of those results
Note that without PR #342 this changes nothing because it checks for `log_hist_msec` being in the job file created before doing anything.
Implements Issue #343.
> fio postprocessing

- agent/bench-scripts/pbench-user-benchmark
The user script can then use it to squirrel away bits and pieces of
interesting information.
This commit partially addresses issue #349.
> Make the run directory available to the called user script.

- agent/tool-scripts/pprof
This PR obsoletes #309
Add pprof heap collection in addition to the current cpu profile support (TODO: options to add separately)
Includes changes in #309 but do not put the tool in the background. That was working (sort of) before because the profile collection tool samples for 30 seconds. The heap tool does not - if you put it in the background it will just hard loop. Run the tool like other pbench tools instead.
Change default timeout to 60 seconds which is sufficient for most tests.
This was tested during the CNCF horizontal cluster runs.
@ekuric @vikaslaad PTAL (and close #309 if you agree).This PR obsoletes #309
> Add pprof heap support

- agent/bench-scripts/postprocess/moongen-postprocess
- A run may require multiple 'final validation' phases when performing
a binary search if a validation fails.  When processing the file,
reset the arrays each time a final validation is found to remove
samples from an earlier attempt.
- Most of the output that moongen-postprocess looks for is only
produced once a validation phase passes so it will only be found
once.  However, if a throughput-latency run is made the latency
output is produced on every validation attempt so this fix is
required to avoid the parser from including latency data from failed
validations.
> Process only the last moongen validation phase

- agent/bench-scripts/pbench-moongen
This adds two options to pbench-moongen to control queue and task load
- Use --mpps-per-queue=<int> to tell MoonGen how many millions of
packets per second (Mpps) can be driven by a single queue.
- Use --queues-per-task=<int> to tell MoonGen how many queues to be
used by each.
Combined these two options determine how many Mpps can be driven by a
single task.  The default values (--mpps-per-queue=5 and
--queues-per-task=3) mean that a single task can drive 15Mpps which is
enough to saturate a single 10Gbit connection with a unidirectional
packet stream (about 14.88Mpps).
> Add new MoonGen queue control options

- agent/bench-scripts/postprocess/BenchPostprocess.pm
non-zero value when doing substitution in BenchPostprocess::get_uid
- It is possible that the value of the hash element is zero in which
case checking it's value will fail the if statement.  By checking
for the elements existence it's value is irrelevant, as it should
be.
- Result output from pbench-moongen has port IDs of zero which where
not being substituted into the uid because of this bug.
> Check for the existence of the hash element rather than it having a

- agent/bench-scripts/pbench-fio
- agent/bench-scripts/postprocess/fio-postprocess
- agent/bench-scripts/postprocess/fio-postprocess-viz.py
- agent/bench-scripts/templates/make-fio-jobfile.py
Implements all the fixes I mentioned in Issue #313. Works for me with both configparser and ConfigParser, and latest upstream fio (which has a new option added to fiologparser_hist.py to take in the fio job file).
> Fixes to fully handle epoch time

- server/pbench/bin/gold/test-2.txt
- server/pbench/bin/gold/test-3.txt
- server/pbench/bin/gold/test-4.txt
- server/pbench/bin/gold/test-5.txt
- server/pbench/bin/gold/test-6.txt
- server/pbench/bin/gold/test-6a.txt
- server/pbench/bin/gold/test-6b.txt
- server/pbench/bin/gold/test-6c.txt
- server/pbench/bin/gold/test-6d.txt
- server/pbench/bin/gold/test-7.1.txt
- server/pbench/bin/gold/test-7.2.txt
- server/pbench/bin/gold/test-7.3.txt
- server/pbench/bin/gold/test-7.4.txt
- server/pbench/bin/gold/test-7.5.txt
- server/pbench/bin/gold/test-7.6.txt
- server/pbench/bin/gold/test-7.7.txt
- server/pbench/bin/gold/test-8.txt
- server/pbench/bin/pbench-backup-tarballs
- server/pbench/bin/test-bin/mailx
- server/pbench/bin/test-bin/rsync
- server/pbench/bin/unittests
Make rsync produce some stats (in addition to the list of files)
and send the stats as notification mail.
Also exclude the TODO/TO-INDEX/etcf directories from the backup: they
cause permissions problems (but I think the underlying reason is that
we have different UIDs for pbench on the two systems involved).
> Add mail notification to pbench-backup-tarballs

- server/pbench/bin/gold/test-6.4.txt
- server/pbench/bin/gold/test-6.txt
- server/pbench/bin/pbench-base.sh
- server/pbench/bin/pbench-rsync-satellite
- server/pbench/bin/pbench-rsync-satellite-process-work-queue
- server/pbench/bin/pbench-unpack-tarballs
This addresses issue #277. The code has been tested in production, with the exception of the tarball/md5 deletion from the satellite. The files ranged from 1MB to almost 4GB in size, with typically a few thousand small files and a handful of big ones: no problems were found. It has not been added to the crontab in production, but that's ready to go at a moment's notice. The default frequency is nightly.
> Rsync tarballs from satellite servers to a production server.

- agent/util-scripts/pbench-clear-tools
- agent/util-scripts/pbench-collect-sysinfo
- agent/util-scripts/pbench-list-tools
- agent/util-scripts/pbench-postprocess-tools
Issue #273.
Check for spurious subdirectories/files of the tools-<group> directory
in pbench-{start,stop,postprocess}-tools and skip them with a warning.
Ditto for pbench-list-tools and pbench-collect-sysinfo. Modify
pbench-clear-tools to remove any such subdirectories (it already
removed spurious files in addition to bona fide tools).
> Check for spurious files/subdirectories of tools-<group> dir

- agent/bench-scripts/pbench-moongen
- This allows pbench-moongen to set the destination MAC addresses for
the ports that packets are sent on.
- This feature is neccessary for environments such as SRIOV and
non-direct connect.
> Add --dst-macs option to pbench-moongen

- agent/bench-scripts/drop-cache-example.sh
- agent/bench-scripts/pbench-fio
This PR addresses issue #381 .  The first commit adds a --cache-drop-script option to pbench-fio.  I made a decision not to try to pass a cache dropping command in its entirety in this option because of the potential for syntax mayhem in parsing quoted strings within quoted strings, etc.  Instead the user just passes the pathname of an executable script file, which is responsible for knowing which hosts to drop cache on and how to do that.  ok?
The 2nd commit is an example of a cache dropping script for a Ceph (ceph-ansible-based) cluster.  It uses ansible to fire cache dropping command on all OSD hosts.  It is there for documentation purposes but does not have to be put in the RPM.  It has been tested.
> Pbench fio cache drop

- agent/base
- agent/bench-scripts/gold/pbench-fio/test-04.txt
- agent/bench-scripts/gold/pbench-fio/test-05.txt
- agent/bench-scripts/gold/pbench-fio/test-06.txt
- agent/bench-scripts/gold/pbench-uperf/test-00.txt
- agent/bench-scripts/gold/pbench-uperf/test-01.txt
- agent/bench-scripts/pbench-fio
- agent/util-scripts/gold/pbench-register-tool/test-00.txt
Needed *on the controller only* for fiologparser_hist.py.
Issue #382
> Check for and install python-pandas

- agent/tool-scripts/sar
11.4.1 and 11.5.1 have pidstat problems that @mffiedler ran into.
> Downgrade required version of sysstat to 11.2.0

- agent/util-scripts/pbench-clear-tools
Fixes issues #402 and #415. In the longer term, we plan to get rid of short-form options: see issue #418.
> Fix short-form -n option in pbench-clear-tools

- agent/config/pbench-agent.cfg.example
Fix incorrect addressing of 'webserver' variable that would prevent rendering host_info_url setting.
> Fix incorrect addressing of 'webserver' variable

- agent/tool-scripts/oc
OpenShift event collection should be for all namespaces.   The current approach only gets the events for whatever the current namespace happens to be.   Treat node and event collection separately.
cc: @ekuric 
Tested on OpenShift 3.3 and 3.4
> Event collection has to be for all namespaces

- agent/bench-scripts/postprocess/fio-postprocess
See issue #421 for an explanation of why a fix was needed.  This 1-line fix simply passes the fio job file to the fiologparser_hist.py program so that it can extract the histogram logging interval.  This is very important for generating the correct percentiles over the correct time intervals.  If you don't pass this, the program will not work.
> Fiologparser hist needs job file

- agent/bench-scripts/postprocess/fio-postprocess-viz.py
fiologparser_hist.py generates 95th-percentile latency in its output table as the 3rd-to-last column, but the graph generated from this data does not include the 95th-percentile curve, as you can see it's easy to add.
> add 95th percentile to fio histogram-derived latency graph

- agent/bench-scripts/postprocess/fio-postprocess-viz.py
fio typically reports latencies in microseconds and outputs timestamps for latency logs in milliseconds since the start of the test.  These may not be ideal units for everyone, but at least the axis labels are now consistent with the data.
> use correct units for fio histogram-derived latency graph

- web-server/v0.3/js/jschart.js
- As the name imples, controls for miscellaneous aspects of jschart
can be placed here.
- Initially this panel consists of a toggle control (on/off) that
determines whether the datasets can be sorted dynamically in the
table.
- The table sorting control defaults based on the construction of the
chart, that is if dataset sorting is enabled (the default) then
table sorting is enabled.  If dataset sorting is disabled in the
chart construction then table sorting starts disabled.  While
related, these two ideas are subtly different.  Dataset sorting, if
chart construction allows for it, allows datasets to be re-ordered
based on their average values (high-to-low) and if it is disabled
then datasets are ordered based on load order.  This affects the
order of the datasets in the chart legend and …
> Add a "Misc. Controls" panel to the jschart table

- agent/bench-scripts/postprocess/moongen-postprocess
- The latency processing failed previously if the rate was not a
floating point value.
- Addresses #432
> Fix a latency processing bug in moongen-postprocess

- web-server/v0.3/js/jschart.js
- Two function calls are missing a mandatory argument.
- This addresses pbench issue #453
> Correct invalid jschart API calls

- contrib/ansible/openshift/README.md
- contrib/ansible/openshift/pbench_register.yml
- contrib/ansible/openshift/register.sh
This playbook registers pbench tools including sar, pidstat, iostat, oc, pprof on openshift cluster. It registers tools only when they haven't been registered yet.
> playbook to register pbench-tools on openshift cluster

- server/pbench/bin/gold/test-8.txt
- server/pbench/bin/pbench-server-activate-create-results-dir-structure
Create TMP and LOGS directory.
Fix up selinux labels if necessary.
Fix unit test.
Issue: #461
> Fill gaps in server installation

- server/pbench/bin/gold/test-10.txt
- server/pbench/bin/pbench-rsync-satellite
Turn remote command errors into an error exit for ssh. Then check
the status of the ssh command.
Issue #449
> Check ssh status in pbench-rsync-satellite

- server/pbench/bin/pbench-index
It should work in all cases:
- when unit-testing in development environment
- when python3 is explicitly available
- when python3 is available through SCL
Issue #463
> Fix invocation of index-pbench

- server/pbench/bin/pbench-server-activate-create-results-dir-structure
This did not cause a unit test failure, but it did output an error
to stderr in the travis-ci environment. This fix prevents that
output.
> Check whether selinuxenabled exists before calling it

- server/pbench/bin/index-pbench
pretty much $SUBJECT (backstory: unit tests behave differently on Travis CI vs when they're run locally)
> correct timezone to UTC while os.stat'g tb fname

- server/pbench/bin/pbench-server-activate-create-results-dir-structure
That leads to deadlock. Instead we require the packages in the RPM.
Issue #530.
> Do not try to yum install packages to provide semanage/restorecon

- server/pbench/bin/gold/test-8.txt
- server/pbench/bin/pbench-base.sh
- server/pbench/bin/pbench-index
- server/pbench/bin/pbench-server-activate
- server/pbench/bin/pbench-server-activate-create-results-dir-structure
- server/pbench/bin/pbench-server-activate-start-httpd
- server/pbench/bin/pbench-server-activate-web-server
- server/pbench/bin/pbench-unpack-tarballs
- server/pbench/bin/test-bin/ln
- server/pbench/bin/test-bin/systemctl
- server/pbench/bin/unittests
With these changes, server installation requires
installing two RPMs (pbench-server-internal and pbench-web-server)
and two manual steps:
- Install public key into pbench users authorized_keys file.
- Enable the generated crontab after inspection.
Changes:
Uncomment the chown of $pbench_dir:
Not sure why that was commented out, but it is necessary.
Add -Z option to mv:
When moving the results from the tmp directory to incoming/, with
selinux enabled, the files need to be relabeled as httpd_content_t
in order to allow httpd to access them. `mv -Z' does that and it does
not create any problems on non-selinux-enabled systems.
Add script to start httpd:
Add a script to start httpd and make the appropriate links into the
document root. Call the script from the postinstall …
> Final changes for automating server installation

- agent/base
The format is YYYY-MM-DD and is now shared between the timestamp
function and the date variable in agent/base.
More importantly, this makes pbench-metadata-log use that same format
for the start_run and end_run fields: the indexer assumes this format,
but we will fix up these fields if necessary in the back-end as a
stop-gap.
> Fix the timestamp format

- agent/bench-scripts/pbench-user-benchmark
- agent/util-scripts/pbench-collect-sysinfo
- agent/util-scripts/pbench-remote-sysinfo-dump
- agent/util-scripts/pbench-sysinfo-dump
By default collect-sysinfo collects kernel_config, block, libvirt, sos and block. This commit will allow users to choose whether to collect sysinfo or not. This also adds ability to pass the info to be collected as comma separated values when starting a benchmark run. Ara which helps in tracking ansible runs is also available as an option.
> Add support to pbench-collect-sysinfo to collect only the info requested

- server/pbench/bin/index-pbench
New function fix_date_format(ts) takes a timestamp string and
massages it (if necessary) into the form yyyy-mm-ddThh:MM:SS[.ns].
It is called in four places to make sure that timestamp strings
out of the metadata log are in the right format.
> Fix up dates to put them in standard format

- agent/ansible/ara/ara.yml
- agent/base
- agent/util-scripts/gold/pbench-collect-sysinfo/test-23.txt
- agent/util-scripts/gold/pbench-collect-sysinfo/test-24.txt
- agent/util-scripts/pbench-collect-sysinfo
- agent/util-scripts/pbench-sysinfo-dump
This will allow us to collect ara data from the remotes involved in a benchmark run so that we will be able to view the dashboard when the results are moved to the pbench server.
> Add support to collect-sysinfo to collect ara data

- agent/bench-scripts/pbench-fio.md
- agent/bench-scripts/pbench-uperf.md
This documentation describes how to use pbench-uperf and pbench-fio as they exist today, including why these tools exist and what problems they solve.  This PR does not cover what changes should be done to these tools in the future, but we can always update these files or Nick can directly update user guides, etc.
> Bengland2 pbench fio doc

- contrib/ansible/openshift/README.md
- contrib/ansible/openshift/pbench_register.yml
By default, tools are registered on two of the nodes. This commit
enables users to choose whether to register tools on two or all of
the nodes.
> Add flexible way to register tools on 2 or all nodes

- contrib/ansible/openshift/pbench_register.yml
pbench-controller needs to have kube config for cluster loader to
generate pods on openshift master.
> Add support to fetch kube config from master

- agent/bench-scripts/gold/pbench-user-benchmark/test-09.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-10.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-11.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-12.txt
- agent/bench-scripts/pbench-user-benchmark
- agent/bench-scripts/postprocess/user-benchmark-wrapper
- agent/bench-scripts/test-bin/mock-postprocess/user-benchmark-wrapper
- agent/bench-scripts/test-bin/user-benchmark-script
- agent/bench-scripts/unittests
This commit creates a user-benchmark-summary.json if not created by the benchmark run and adds info about the duration if not provided by callee.
> Add support to user-benchmark to add run info to metadata.log, emit a json file to be indexed

- contrib/containerized-pbench/README.md
- contrib/containerized-pbench/dockerfiles-jump_node/Dockerfile
- contrib/containerized-pbench/dockerfiles-jump_node/config
- contrib/containerized-pbench/dockerfiles-jump_node/inventory
- contrib/containerized-pbench/dockerfiles-jump_node/pbench-agent.cfg
- contrib/containerized-pbench/dockerfiles-jump_node/pbench.service
- contrib/containerized-pbench/dockerfiles-jump_node/script.sh
- contrib/containerized-pbench/dockerfiles-jump_node/vars
- contrib/containerized-pbench/dockerfiles-pod/Dockerfile
- contrib/containerized-pbench/dockerfiles-pod/mount.sh
- contrib/containerized-pbench/dockerfiles-pod/pbench-pod.service
- contrib/containerized-pbench/openshift-templates/pbench-agent-daemonset.yml
This commit adds:
- openshift template to launch pbench-agent pod as daemonset
- dockerfiles for running containerized pbench-agent on the jump node
acting as a controller
- dockerfiles for running containerized pbench-agent on the
openshift cluster
- Readme which explains about how to get this working on openshift
> Add containerized pbench agent for openshift environments

- agent/bench-scripts/postprocess/generate-benchmark-summary
- When producing reports in generate-benchmark-summary (TXT, HTML, or
CSV) ensure that the iterations are processed in the proper order
(which is defined by their numerical iteration identifier).
- This addresses #592
> generate-benchmark-summary: process iterations in numerical order

- agent/tool-scripts/oc
Add option --show-labels into oc get nodes command.
The labels are useful when checking pbench results.
Eg, Openshift cluster can use labels to tell the role of the nodes.
> Show labels of oc-nodes

- agent/bench-scripts/unittests
- agent/util-scripts/unittests
The unit test names are the indices of the cmds/tools associative
array. If a unittests script is called without arguments, instead of
assuming that the tests are numbered within a sequential range, derive
the complete set of names from the indices of the array and sort them
(otherwise, they appear in hashtable ("random") order).
Modified bench-scripts and utils-scripts unittests accordingly.  The
server unittests script already did that, the tools/postprocess
unittests script uses whatever it finds in the samples subdirectory,
so it does not need this treatment.
> Do not assume that unit tests are sequentially numbered

- contrib/containerized-pbench/README.md
- contrib/containerized-pbench/dockerfiles-jump_node/config
- contrib/containerized-pbench/dockerfiles-jump_node/script.sh
- contrib/containerized-pbench/dockerfiles-jump_node/vars
pbench-agent container runs pbench-clear-results and pbench-move-results
commands before and after each benchmark run. This commit fixes it to
run the commands only when the move_results and clear_results vars are
set to true in the vars file. This will allow us to move, clear the
results only when we want to.
> Run move, clear results only when the respective variables are set

- contrib/ansible/openshift/README.md
- contrib/ansible/openshift/pbench_register.yml
- contrib/ansible/openshift/register.sh
This commit will allow us to:
-  register tools on the cns nodes under [glusterfs] group
-  register tools on the nodes with the following label
openshift_node_labels="{'region': 'infra'} in the inventory
along with the last two nodes when register_all_nodes is set
to False in the inventory.
> Register tools on OpenShift infra, cns nodes

- agent/tool-scripts/datalog/prometheus-metrics-datalog
- agent/tool-scripts/prometheus-metrics
- By default prometheus-metrics tool uses cert, key located at
/etc/origin/master on the master node of OpenShift cluster, fetches
the metrics exposed by prometheus endpoint running on port 8443. This
commit will enable us to ping endpoints running on different ports,
which need different certs.
- User can pass the certs, port as arguments while registering the tool
like pbench-register-tool --name=prometheus-metrics -- --inventory=
/path/to/inventory --port <port> --cert=/path/to/cert --key=/path/to/key
- prometheus-metrics-tool checks if go is installed, if yes it won't
check if GOPATH is set. It sets the GOPATH only when go is not
installed. This commit fixes that.
- Instead of modifying user's .bashrc, this will set the GOPATH, adds
the binaries to the PATH variable only while running …
> Parameterize certs and port for prometheus-metrics

- server/pbench/bin/pbench-rsync-satellite
FIX #614 
The subject and the body was very confusing of the ssh failure mail which was sent to recipients. As the subject only says "remove failure" in the subject and have list of tarballs reported "OK" in the body of message. 
So changed it to better understand that tarballs were transferred successfully, but they are not removed from the satellite because ssh failed.
> Update the subject and body message of ssh failure mail

- agent/bench-scripts/postprocess/BenchPostprocess.pm
- Check for the existence of the hash element rather than it having a
value which evaluates as true.
- It is possible that the value of the hash element will evaluate as
false in which case checking it's value will fail the if
statement. By checking for the elements existence it's value is
irrelevant, as it should be.
- This bug was previously fixed by PR #346 but then accidentally
reverted by PR #434.
> Fix a subsitution bug in BenchPostprocess::get_uid

- agent/tool-scripts/prometheus-metrics
- Update installation steps of prom2json to match with the changes
made in upstream prometheus/prom2json.
- This also fixes tool_cmd to use single quotes to preserve the literal
value within the quotes.
> Modify installation steps of prom2json

- agent/tool-scripts/postprocess/pidstat-postprocess
Commas in commands cause problems with CSV files, so we nuke them.
Fixes #623.
> pidstat-postprocess: nuke commas from commands.

- .travis.yml
- agent/bench-scripts/pbench-user-benchmark
- agent/bench-scripts/unittests
- agent/tool-scripts/prometheus-metrics
- Prometheus-metrics tool uses the same cert, key and port for all the
endpoints in the inventory file passed. This will enable it to have
different certs, port for each endpoint.
- User can define the port, cert, key to be used by a particular
endpoint in the inventory like host port=prometheus_port 
cert=/path/to/cert key=/path/to/key
- Add support to run unit tests on ubuntu.
> Add support to use different certs, port for each endpoint, run unit tests on ubuntu

- agent/bench-scripts/postprocess/uperf-postprocess
Depending on the perl version, these port labels might
be represented as intergers or strings.  Aggregate
metrics also use "all" as the port label, so let's just
force all port labels to be strings.  Port labels are
not processed as numbers anyway, even though they happen
to be a number (in most cases).  Forcing strings also
ensures the different perl versions should always produce
strings for this data when converting to JSON.
> uperf-postprocess: force port_labels to be strings

- agent/tool-scripts/prometheus-metrics
- contrib/ansible/openshift/pbench_register.yml
This commit
- renames the result files to include port to avoid conflicts.This case
arises when we are monitoring the same endppoint but with a different
port. An example use case would be monitoring apiserver and
kubelet which expose metrics on port 8443 and 10250 respectively.
- disables passing port, certs on command line.
> Rename result files to include port to avoid conflicts

- agent/util-scripts/pbench-collect-sysinfo
This commit fixes the following:
when default is passed as a syinfo option, pbench-sysinfo-dump
collects just block info since it finds space separated values
instead of comma separated values.
> Pass sysinfo opts as comma separated values

- agent/tool-scripts/user-tool
- Two calls to wait are required because the initial trap breaks out
of the first wait prematurely, requiring a second wait to avoid
exiting prior to the tool handling the SIGTERM gracefully.
- Addresses #658
> pbench-user-tool: pass SIGTERM to the tool for graceful handling

- agent/bench-scripts/pbench-fio
- agent/bench-scripts/samples/pbench-agent.cfg
- agent/bench-scripts/unittests
- agent/config/pbench-agent.cfg.example
FIX #579 
Fedora 24 (and maybe later) has python2-pandas and python3-pandas packages, but no python-pandas.
pbench-fio on the other hand tries to install the latter. So now the script will install package
according to the distro.
> Update the script to check distro before installing python-pandas.

- agent/util-scripts/pbench-move-results
When compressing large amounts of data collected by Pbench or other tools that add data to Pbench directories, the current method of compressing data uses only a single thread.  This can cause significant delays during test runs when compressing the data and copying them to a safe location on a Pbench server.  I propose to utilise as many cores as possible and use the xz -T0 option as tar seems to support only a single thread of execution when compressing data.  I have drastically reduced the pbench-copy-results times by doing this from a couple of hours to nearly "couple of hours"/number of cores available during the last OpenShift testing in the scale lab.
> Use xz with multi-threaded support when copying/moving results.

- agent/tool-scripts/haproxy-ocp
Removing check_install_rpm atomic-openshift-clients due to containerized environments.  Just checking for OpenShift oc client and refusing to register when the client is not present. /cc @chaitanyaenr
> Removing check_install_rpm atomic-openshift-clients, just checking for oc.

- agent/tool-scripts/oc
Containerized environments won't have openshift rpm's. So instead
of checking for atomic-openshift-client, we can check if oc is
installed. Usually oc client is installed only on the master node,
even if the oc client is installed on rest of the nodes,
pbench-ansible will make sure oc tool is installed only on the
master.
> Check for oc client instead of openshift rpm's

- contrib/ansible/openshift/pbench_register.yml
The builtin {{ inventory_file }} outputs relative path instead of
absolute path. This commit fixes it by using {{ inventory_dir }}/
{{inventory_file}}.
Fixes #681
> Fix ansible 2.4 compatibility issues

- server/pbench/bin/pbench-move-unpacked
- server/pbench/bin/pbench-unpack-tarballs
There were some syntax errors in pbench-unpack-tarball & pbench-move-unpacked. This patch will rectify those errors.
> pbench-unpack-tarball & pbench-move-unpacked: Rectify different syntax errors

- server/pbench/bin/pbench-satellite-cleanup
It will now log the start and end of the process, as well as the number of tarballs
it cleaned up. And admins will get mail on any removal failure.
> Update the pbench-satellite-cleanup script to not create empty logdir on every run

- server/pbench/bin/gold/test-8.txt
- server/pbench/bin/pbench-server-activate-create-results-dir-structure
chown -R is too expensive to do on the pbench directories. Just make
sure that the top level directories are chown'ed correctly.
Also, fix the unit test for this change.
> pbench-server-activate-create-results-dir-structure: Avoid chown -R

- agent/tool-scripts/datalog/prometheus-metrics-datalog
- agent/tool-scripts/prometheus-metrics
- contrib/ansible/openshift/README.md
This commit:
- Modifies the tool to monitor the endpoints under prometheus-metrics
group instead of masters.
- Makes the tool more generic by not assuming default certs, port.
> Refactor  prometheus-metrics tool to be more generic

- server/pbench/bin/pbench-sync-satellite
There was some undefined variable named $host, which is outside the loop. That's why it is unrecognizable which results in an error.
Now I have updated the script to calculate total processed as well as failed md5 in a different way so that it will not be required the host variable. As well as updated some logs destination too.
> pbench-sync-satellite: rectify the undefined host outside the loop

- server/pbench/bin/gold/test-10.txt
- server/pbench/bin/gold/test-11.txt
- server/pbench/bin/pbench-sync-satellite
- server/pbench/bin/unittests
The final three lines are supposed to go to the log, not the error log.
> pbench-sync-satellite: do not send non-errors to error log

- server/pbench/bin/pbench-unpack-tarballs
If $UNPACK_DIR and $TMP are the same directory, there is
a name conflict between the $list file and the $tmp directory.
Fix it by making the list file live under $tmp.
> pbench-unpack-tarballs: fix conflicting file names.

- server/pbench/bin/gold/test-10.txt
- server/pbench/bin/gold/test-11.txt
- server/pbench/bin/pbench-sync-satellite
The list of files to check should be a subset the list that came
from the satellite in the current run of the script. It was
calculated incorrectly by checking the files in the archive
directory.
A few other changes:
- apply the trap to QUIT and INT signals, as well as to EXIT.
- try to rmdir the run directory under logs: this will succeed if the
directory is empty. If it is not, we keep it and suppress the rmdir
error message.
- Remove -v from the tar extraction. That printed the list of files
before the start message which was confusing.
- Echo the md5 list on each iteration: this will print the list of files
for each host on a separate line.
- Fix unit test gold files 10 and 11.
> pbench-sync-satellite: fix the file list for md5 checking

- server/pbench/bin/pbench-dispatch
- server/pbench/bin/pbench-unpack-tarballs
The prefix file has to be handled by the first script in the chain,
i.e. pbench-dispatch. Previously, it was handled by pbench-unpack-tarballs,
but that now leads to a race, since unpacking and other processing happens
simultaneously.
Move the handling of the prefix file from pbench-unpack-tarballs to
pbench-dispatch. There is still some handling in pbench-unpack-tarballs
because the results path has to take the prefix into account.
> pbench server: fix race with prefix file.

- server/pbench/bin/pbench-server-activate-create-crontab
Some servers are known in the config file by a name different than
what `hostname -f` returns on that server.  In such cases, the sanity
check in create-crontab prevents the crontab from being created.
Relax the check so that it gets not only the name of the host but an
alternate "real" name from the config file. We compare the result of
`hostname -f` against both: if one of them matches, we produce a
crontab, but if both fail, we don't.
> pbench-server-activate: relax hostname check

- server/pbench/bin/pbench-move-unpacked
This is a workaround for a job pool problem: it seems that a
job termination message gets lost, so occasionally the script hangs with
a job pool process trying to read the next job from the job pool
queue, but there *is* no next job. This seems to happen *only* when
there is no work to be done.
Check if there is anything to be done: if not, exit immediately
without creating the job pool.
> pbench-move-unpacked: work around job pool hang

- contrib/ansible/openshift/pbench_register.yml
openshift ansible doesn't support using the latest ansible version
which is 2.4. This commit will add support to use older ansible versions
till the issue is fixed.
> Add older ansible version < 2.4 support to pbench-ansible

- server/pbench/bin/pbench-move-unpacked
- server/pbench/bin/pbench-unpack-tarballs
Fixes #691 
It will rectify the sorting error in pbench-move-unpacked, right now It sorts by size of the link (i.e. the length of the target name), rather than the size of the target.
> pbench-move-unpacked: rectify broken sort by size

- agent/util-scripts/pbench-move-results
Fixes #605.
Using the option gets the name of the server where the results will
be sent, prints it on stdout and exits.
> pbench-move-results: add --show-server option

- agent/tool-scripts/kvm-spinlock
- agent/tool-scripts/pcp
- agent/tool-scripts/perf
- agent/tool-scripts/prometheus-metrics
- agent/tool-scripts/sar
- agent/tool-scripts/strace
- agent/tool-scripts/systemtap
- agent/tool-scripts/user-tool
pbench-stop-tools will fail unless there are some tools running.
This commit will modify pbench-stop-tools to warn when there are
no pids to kill instead of failing since we would want to run it
to ensure that there are no tools running before registering the
tools.
Fixes #636
> pbench-stop-tools will warn instead of failing with a non-zero exit code

- agent/tool-scripts/lockstat
This commit:
- Adds a check which makes sure CONFIG_LOCK_STAT is set before
registering the tool.
- Enables, disables collection when the tool is started, stopped
respectively.
- Fixes typos in the lockstat tool-script.
Fixes #709
> Fix lockstat tool

- agent/base
- agent/bench-scripts/gold/pbench-fio/test-19.txt
- agent/bench-scripts/pbench-fio
- agent/bench-scripts/samples/pbench-agent.cfg
- agent/bench-scripts/unittests
- agent/config/pbench-agent.cfg.example
Fixes #718
Fixes #723
Multiple targets are mishandled in the generation of the fio
jobfile. This commit fixes the generation of the jobfile.
The pre-iteration-script option was left out of the getopts string, so
it is not recognized as a legitimate option (although the rest of the
implementation is fine). This commit adds the option to getopts.
Add a unit test for the option handling. A unit test for the jobfile
generation is TBD.
> pbench-fio: fix pre-iteration-script and targets option handling.

- agent/util-scripts/gold/pbench-collect-sysinfo/test-24.txt
- agent/util-scripts/pbench-collect-sysinfo
This commit changes collect-sysinfo script to consider "all" and "default"
differently. When user passes "all" as the sysinfo option, it will collect
all the available sysinfo options including ara; when no option or
"default" is passed, it collects the default set of options.
> Fix collect-sysinfo to treat "all" and "default" options differently

- agent/util-scripts/pbench-sysinfo-dump
This commit avoids printing the sysinfo type being collected so
that the printed message doesn't end up in the tar ball, thereby
corrupting it.
> pbench-sysinfo-dump: Avoid printing logs to stdout to avoid tar ball corruption

- agent/bench-scripts/gold/pbench-fio/test-04.txt
- agent/bench-scripts/gold/pbench-fio/test-05.txt
- agent/bench-scripts/gold/pbench-fio/test-06.txt
- agent/bench-scripts/templates/fio.job
There is no reason to put non-workload parameters like "log_hist_msec" in the per-target section of the job file, where they get repeated for each target.  This fix makes the job file much shorter and easier to read.
> move non-workload params to global section

- agent/bench-scripts/gold/pbench-fio/test-17.txt
- agent/bench-scripts/gold/pbench-fio/test-18.txt
- agent/bench-scripts/pbench-fio
- agent/bench-scripts/templates/make-fio-jobfile.py
Allow user to change histogram logging interval, and change default to 10 seconds.   This change in default  means that most users will see histogram logs now even if they use a small test time , where before they were getting empty histogram logs.  This depends on a previous fio fix to not segfault when retrieving histogram logs, this is in fio 3.3.
> add param histogram-interval-msec, default 10 sec not 60

- server/pbench/bin/pbench-move-unpacked
pbench-unpack-tarballs is supposed to leave the following structure in place
for pbench-move-unpacked to handle:
- an unpacked tarball in tmp
- a symlink to it in $incoming
- a symlink to *that* in $results
When pbench-move-unpacked runs, it finds all the tarballs
in move-unpacked state and for each tarball, it would
- copy the unpacked tarball from tmp to $incoming.copy
- rm the $incoming symlink
- mv $incoming.copy $incoming
- change the state of the tarball
If all goes well, this works. But pbench-move-unpacked occasionally
got a failure in one of those steps that caused it to not finish
processing a tarball. It would then lather, rinse and repeat, but
would not be able to get out of the rut, because a step would fail,
the state would *not* be changed, and the same tarball(s) would be …
> pbench-move-unpacked: fix long-standing bug

- server/pbench/bin/gold/test-8.txt
- server/pbench/bin/pbench-server-activate
- server/pbench/bin/pbench-server-activate-create-results-dir-structure
- server/pbench/bin/pbench-server-activate-setup-results-host-info
- server/pbench/bin/pbench-server-activate-start-httpd
Fixes #739.
The main script, and various sub-scripts it calls, exited when something failed, leaving the rest of the work undone. That causes problems when installing.
Do as much of the work as possilbe: do not exit on errors. They are
going to be reported when the server is installed.
Fix unit test.
> pbench-server-activate*: do no exit on failures

- server/pbench/bin/pbench-move-unpacked
The $prefix variable was uninitialized. Initialize it using the
same code sequence that pbench-unpack-tarballs uses.
Fixes #756.
> pbench-move-unpacked: initialize $prefix.

- agent/bench-scripts/postprocess/fio-postprocess
- agent/tool-scripts/postprocess/gold/fio-0/result/reference-result/csv/fio_clat.csv
- agent/tool-scripts/postprocess/gold/fio-0/result/reference-result/csv/fio_lat.csv
- agent/tool-scripts/postprocess/gold/fio-0/result/reference-result/csv/fio_slat.csv
- agent/tool-scripts/postprocess/gold/fio-0/result/reference-result/fio-average.txt
- agent/tool-scripts/postprocess/gold/fio-0/result/reference-result/result.json
- This ensures profiles with multiple jobs are properly handles since
before only jobs with id=1 were processed
> fio-postprocess: treat fio jobs as separate clients

- server/pbench/bin/pbench-move-unpacked
A previously-thought "impossible" situation happened: even though
pbench-unpack-tarball should create an $incoming symlink (in the
case when we are unpacking in a local fs, before moving it to the
dfs afterwards), we have seen situations where $incoming has been
a directory and also now a situation where $incoming does not exist
at all. The directory case was handled in PR #755, which also added
the catch-all case that was deemed impossible.
This commit qualifies that case: if $incoming exists in some form
other than symlink or directory, we deem it impossible and return
an error. If it does not exist at all, we wonder why but we go on
and finish the processing (which creates it as a directory).
> pbench-move-unpacked: fix bug.

- agent/tool-scripts/postprocess/gold/prometheus-metrics/json/metrics.json
- agent/tool-scripts/postprocess/prometheus-metrics-postprocess
We don't need go_memstats_last_gc_time_seconds in the json generated
by prometheus-metrics tool to be indexed into elasticsearch.
> Ignore go_memstats_last_gc_time_seconds metric during postprocess

- agent/util-scripts/gold/pbench-collect-sysinfo/test-23.txt
- agent/util-scripts/gold/pbench-collect-sysinfo/test-24.txt
- agent/util-scripts/pbench-collect-sysinfo
- agent/util-scripts/pbench-sysinfo-dump
Fixes #738.
Add a security-mitigations option to pbench-collect-sysinfo
and enable it by default.
The option makes pbench-sysinfo-dump look for relevant files in
/sys/kernel/debug/x86 and, if any are found, collect their contents in
a (new) security-mitigation.txt file.
> pbench-collect-sysinfo: collect security mitigation data

- agent/util-scripts/pbench-agent-config-activate
Allow more than one config file to be copied when installing.
This will allow us to split the config file into a small environment-specific
one and a larger default one that applies to all environments.
> pbench-agent-config-activate: allow more than one config file

- agent/bench-scripts/gold/pbench-fio/test-04.txt
- agent/bench-scripts/gold/pbench-fio/test-05.txt
- agent/bench-scripts/gold/pbench-fio/test-06.txt
- agent/bench-scripts/pbench-fio
- agent/bench-scripts/samples/pbench-agent.cfg
- agent/bench-scripts/templates/fio.job
Put default values in the config file: do not hardwire them into the script.
For now, just the version and histogram_interval_msec are treated. The rest will follow if everything works according to plan.
Also the rest of the scripts will be treated the same way at some point.
Fix the unit tests.
Fixes #741.
>  pbench-fio: put defaults in config file

- server/pbench/bin/pbench-move-unpacked
Fixes #771
If a symlink in results/ points to an existing directory in incoming/,
then trying to recreate the symlink will instead create a spurious
symlink in the incoming/ directory, resolving to itself.
Remove the existing symlink in results/ before recreating it.
> pbench-move-unpacked: do not create spurious links

- contrib/ansible/openshift/pbench_register.yml
This commit registers default tool-set on the controller needed to
monitor the runs including openshift-ansible.
> pbench-ansible: monitor controller or jump host

- server/pbench/bin/pbench-satellite-cleanup
Now it will check whether the prefix file is available or not
before doing a cat of the perfix file.
> Fix the checking of prefix file available

- server/pbench/bin/pbench-backup-tarballs
- server/pbench/bin/pbench-base.sh
- server/pbench/bin/pbench-clean-up-dangling-results-links
- server/pbench/bin/pbench-copy-sosreports
- server/pbench/bin/pbench-dispatch
- server/pbench/bin/pbench-dispatch-inotify
- server/pbench/bin/pbench-edit-prefixes
- server/pbench/bin/pbench-index
- server/pbench/bin/pbench-inotify
- server/pbench/bin/pbench-move-unpacked
- server/pbench/bin/pbench-satellite-cleanup
- server/pbench/bin/pbench-sync-package-tarballs
- server/pbench/bin/pbench-sync-satellite
- server/pbench/bin/pbench-unpack-tarballs
- server/pbench/bin/pbench-unpack-tarballs-inotify
- server/pbench/bin/unittests-inotify
- server/pbench/lib/config/pbench-inotify.service.example
Fixes #665 #786 
pbench-dispatch is running as a cron job, scheduled every minute. That
adds a minute of latency to the processing. It's a simple script that
examines the TODO subdirs under each controller for tarball symlinks;
when it finds one, it checks its MD5 and dispatches it for further
processing.
Instead of running it as a cron job, we are now running it as a service:
constantly checking, using inotify, for new tarballs in all the TODO
subdirs. When it sees a new tarball, it will do exactly what it does now:
check MD5 and dispatch it appropriately.
pbench-unpack-tarballs is also running as a cron job, scheduled every minute. So now we are runnning this also as a service. It will do exactly what it does now.
> Pbench cron job scripts: now run as a service.

- agent/util-scripts/pbench-move-results
- server/pbench/bin/pbench-base.sh
- server/pbench/bin/pbench-server-set-result-state
Resolves #786.
Implement a result state setting script on the server side. The
script hides the implementation of state from the agent.
Modify pbench-move-results on the agent side to call the script,
so that it does not have to know the details of the state change.
> Server-side result state setting script.

- server/pbench/bin/pbench-inotify
Missed one instance where it is treated as a string.
> Fix DEBUG test.

- agent/bench-scripts/gold/pbench-user-benchmark/test-07.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-08.txt
- agent/bench-scripts/pbench-user-benchmark
This commit adds a --pbench_post flag in pbench_user_benchmark script.
It accepts a path to any script and runs it after postprocessing. 
A sample use case would be run a binary which will add some files 
in the result directory.
> Add support to run additional scripts after postprocessing

- agent/bench-scripts/pbench-user-benchmark
This is needed to use pbench vars defined in the user-benchmark-script.
> user-benchmark: evaluate the contents of pbench-post flag

- agent/tool-scripts/datalog/openvswitch-datalog
- agent/tool-scripts/postprocess/openvswitch-postprocess
openvswitch tool: track the number of MAC addresses learned for each port
- Queries OVS and counts the MAC addresses that have been learned on
each switch port.
- Uses an inline awk script to convert the data returned from OVS
(which is potentially *a lot* of output) into something small and
easily consumable during postprocessing.
> Openvswitch

- agent/bench-scripts/pbench-trafficgen
- Make sure arguments that are specified to be passed through (coming
after --) have priority over arguments that are automatically
determined by the script.  This allows the user to override the
default behavior, if required.
> pbench-trafficgen: ensure passthrough argument priority

- contrib/ansible/openshift/README.md
- contrib/ansible/openshift/pbench_register.yml
- contrib/ansible/openshift/register.sh
- Openshift-labeler had been modified to determine the role a node plays
in the openshift cluster by looking at the labels on the nodes instead
of inventory. So instead of looking for the infra label in the inventory
we can have a infra group.
- Also modifies to monitor first two nodes by default instead of last two
nodes.
> Modify pbench-ansible to monitor nodes under infra group

- contrib/ansible/openshift/pbench_register.yml
openshift-labeler takes care of looking at the labels on the openshift nodes 
and generate a tooling inventory needed by pbench-ansible. The template used
by the QE jenkins job needs to be modified similar to setup-tooling jobto use 
openshift-labeler as the playbook is going to fail without it.
> Add a note about need to add openshift-labeler support to openshift-qe template

- agent/util-scripts/pbench-sysinfo-dump
- server/pbench/bin/pbench-index
pbench-sysinfo-dump: silence the grep if no files are found by the glob.
pbench-index: initialize index_content.
> Bug fixes.

- server/pbench/bin/pbench-base.sh
- server/pbench/bin/pbench-index
- server/pbench/bin/pbench-report-status
- server/pbench/lib/config/pbench-server-default.cfg.example
- server/pbench/lib/config/pbench-server.cfg.example
Fixes for pbench-report-status:
- get rid of timezone in timestamp - ES did not like it.
- use dots instead of dashes in the index name.
Modify example config files: split into pbench-server-default.cfg and pbench-server.cfg.
Add script-dir to config file.
pbench-base.sh: add script-dir to PATH, so that all the scripts can execute pbench-report-status.
pbench-index: when setting subj, use double quotes so the variables inside the strings will be
expanded.
> pbench-report-status: fix it and make it findable for execution.

- agent/bench-scripts/gold/pbench-user-benchmark/test-07.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-08.txt
- agent/bench-scripts/pbench-user-benchmark
Like `--pbench-post`, we add a hook to be run before tools are
started. This gives us a chance do work knowing the `benchmark_run_dir`
and `benchmark_results_dir` locations, but before tools are started to
avoid disturbing tool data.
We also move the invocation of the `user-benchmark-wrapper` script until
after the `--pbench-post` script is invoked so that we can move work
generating result data outside of the tool data collection.
> Add --pbench-pre hook for UB; move wrapper

- server/pbench/bin/gold/test-6.4.txt
- server/pbench/bin/gold/test-6.txt
- server/pbench/bin/gold/test-9.1.txt
- server/pbench/bin/gold/test-9.2.txt
- server/pbench/bin/gold/test-9.3.txt
- server/pbench/bin/gold/test-9.4.txt
- server/pbench/bin/gold/test-9.5.txt
- server/pbench/bin/pbench-report-status
- server/pbench/bin/pbench-verify-backup-tarballs
- server/pbench/bin/test-bin/pbench-report-status
- server/pbench/bin/unittests
The base problem with `pbench-verify-backup-tarballs` is actually with `pbench-report-status` which fails to work because the directory path to the log file is not created when a script does not invoke, `log_init`.  The first patch addresses this problem.
The second patch adds to the unit tests the contents of the report-status payload itself.
The third patch adds proper logging to the `pbench-verify-backup-tarballs` command so that we don't get a cron job email with the output of stderr and the report status email.
> Add a proper log environment for verify-backup-tarballs

- server/pbench/bin/gold/test-9.2.txt
- server/pbench/bin/gold/test-9.3.txt
- server/pbench/bin/gold/test-9.4.txt
- server/pbench/bin/gold/test-9.5.txt
- server/pbench/bin/pbench-verify-backup-tarballs
In an attempt to speed up the verification process we have parallelized
the checks of the archive (primary) and the backup directories.
In addition, instead of comparing the output of the md5sum commands, we
compare the content of the combined md5sum files (which are kept in
sorted order by making sure the list of controllers is sorted before
processing, and leveraging "ls"'s sorted output.
> Parallelize archive directory checks; compare file lists

- server/pbench/bin/gold/test-6.4.txt
- server/pbench/bin/gold/test-6.5.txt
- server/pbench/bin/gold/test-6.6.txt
- server/pbench/bin/gold/test-6.txt
- server/pbench/bin/pbench-backup-tarballs
- server/pbench/bin/test-bin/rsync
- server/pbench/bin/test-bin/rsync.sed
- server/pbench/bin/unittests
We post-process the rsync output to make it comparable for unit tests.
> Enable actual use of rsync

- server/pbench/bin/gold/test-12.txt
- server/pbench/bin/pbench-server-prep-shim-001
- server/pbench/bin/pbench-sync-package-tarballs
Fixes issue #875.
Deploying v0.51 servers uncovered two bugs:
- pbench-server-prep-shim-001: the script processes tarballs that are
sent by a version-001 agent. The latter creates a
TODO/tarball.tar.xz link to signal that the tarball is ready to be
processed. The shim should remove that link after processing, but it
does not. Consequently, it encounters that link on every future
iteration and complains about it.
The fix is to remove the link. The only problem that might arise is
if the link removal fails: in that case, the script complains but
since it cannot remove it, it will continue encountering it and
complaining about it.
- pbench-sync-package-tarballs: this script is called (remotely on a
satellite server) by pbench-sync-satellite. The script set its
config file like this:
export …
> Fixes for two bugs discovered when deploying the server

- agent/bench-scripts/gold/pbench-fio/test-20.txt
- agent/bench-scripts/pbench-fio
- agent/bench-scripts/pbench-uperf
- agent/bench-scripts/pbench-user-benchmark
We also ensure that only one iteration is tracked for user-benchmark.
Fixes #879.
> Properly initialize the benchmark iteration file

- server/pbench/bin/gold/test-3.txt
- server/pbench/bin/gold/test-4.txt
- server/pbench/bin/gold/test-5.txt
- server/pbench/bin/gold/test-7.10.txt
- server/pbench/bin/gold/test-7.11.txt
- server/pbench/bin/gold/test-7.12.txt
- server/pbench/bin/gold/test-7.4.txt
- server/pbench/bin/gold/test-7.5.txt
- server/pbench/bin/gold/test-7.6.txt
- server/pbench/bin/gold/test-7.7.txt
- server/pbench/bin/gold/test-7.8.txt
- server/pbench/bin/gold/test-7.9.txt
- server/pbench/bin/index-pbench
- server/pbench/bin/pbench-index
- server/pbench/bin/state/config/pbench-index.cfg
- server/pbench/bin/unittests
The performance problem with indexing is two-fold:
* we accumulate all generated records into one big list before we start indexing, which is really bad
* we have observed 10s of GBs of memory used when indexing large amounts of data
* to fix, we just need to use the streaming bulk methods and improve the error handling
* in order to ensure error handling for Elasticsearch is good, we need source IDs for all documents ahead of time to make it easier to handle retrying operations when an ES instance is overloaded
Along the way, we have attempted to improve the error handling so that we index as much as possible, report errors better, and report them succinctly.
> Fix indexing performance and enhance error handling

- server/pbench/bin/unittests
And we make TMPDIR available for all tests.
> Ensure UTC for timezone in unittests

- server/pbench/bin/gold/test-7.10.txt
- server/pbench/bin/gold/test-7.11.txt
- server/pbench/bin/gold/test-7.12.txt
- server/pbench/bin/gold/test-7.4.txt
- server/pbench/bin/gold/test-7.5.txt
- server/pbench/bin/gold/test-7.6.txt
- server/pbench/bin/gold/test-7.7.txt
- server/pbench/bin/gold/test-7.8.txt
- server/pbench/bin/gold/test-7.9.txt
- server/pbench/bin/index-pbench
- server/pbench/lib/pbench/__init__.py
We fix the default "read timeout" to be very large so that we don't
timeout prematurely and retry needlessly for template operations.
We have enhanced the error handling so that we don't always assume we
get a response object, and we dump out error messages that are
unexpected for now.
We also add the new es_put_template wrapper which properly handles the
retries.
> Fix indexing work to improve error handling

- server/pbench/bin/index-pbench
It is not sufficient to use an OrderedDict in all cases to get passing
unittests in different environments, because accessing the list of
files via the file system can also yield a non-alphabetical order of
the tool names.
We just have sort the templates by tool name before we invoke the
template creation method.
> Attempt to ensure unit tests pass in all env

- server/pbench/bin/gold/test-6.4.txt
- server/pbench/bin/gold/test-6.5.txt
- server/pbench/bin/gold/test-6.6.txt
- server/pbench/bin/gold/test-6.txt
- server/pbench/bin/pbench-base.sh
- server/pbench/bin/pbench-copy-sosreports
Fixes #907 
This PR will add the missing state transition for copy-sos-reports
i.e `COPIED-SOS`. 
It will also remove the `DONE` state transition because it is not being used by any server scripts, not anymore. There was a duplicate `TO-UNPACK` state transition name, that is also removed now.
> pbench-copy-sosreports: fix the wrong state transition name

- server/pbench/bin/gold/test-12.txt
- server/pbench/bin/gold/test-13.txt
- server/pbench/bin/gold/test-14.txt
- server/pbench/bin/gold/test-15.txt
- server/pbench/bin/gold/test-3.txt
- server/pbench/bin/gold/test-4.txt
- server/pbench/bin/gold/test-5.txt
- server/pbench/bin/gold/test-6.4.txt
- server/pbench/bin/gold/test-6.5.txt
- server/pbench/bin/gold/test-6.6.txt
- server/pbench/bin/gold/test-6.txt
- server/pbench/bin/gold/test-9.1.txt
- server/pbench/bin/gold/test-9.2.txt
- server/pbench/bin/gold/test-9.3.txt
- server/pbench/bin/gold/test-9.4.txt
- server/pbench/bin/gold/test-9.5.txt
- server/pbench/bin/pbench-report-status
The ES  date parser does not like it.
> pbench-report-status: snip off the -UTC part of the timestamp

- server/pbench/bin/gold/test-2.txt
- server/pbench/bin/pbench-index
Fixes #870 
`pbench-index` does
`test -d $ARCHIVE || doexit "Bad ARCHIVE=$ARCHIVE"`
before calling log_init; everybody else does it after calling `log_init`. This PR will fix the inconsistency.
> Fix Inconsistent reporting of missing ARCHIVE directory

- server/pbench/bin/index-pbench
Fixes #886
Now, optparse handles only the cli options that have been passed, whereas argparse also covers the arguments passed on cli along with options passed. Therefore, the output was quite different from optparse output.
paser.parse_args() returns a namespace object that also has the file name that has passed onto the cli, whereas optparse returns a Values object.
After, the supplying of optparse output, there are multiple invocations of those options in main(). Therefore, it appeared more optimal to serialize the output of argparse.
> Validated argparse with optparse

- server/pbench/bin/pbench-unpack-tarballs
When move-unpacked runs in parallel with unpack-tarballs in the same controller, the `find` and `chmod` commands end up getting errors as a result of the files being moved out from underneath their operation.  This change to use the `$resultname` explicitly avoids that.
> Simple fix to avoid conflicts with move unpacked

- server/pbench/bin/gold/test-0.1.txt
- server/pbench/bin/gold/test-0.txt
- server/pbench/bin/pbench-base.sh
- server/pbench/bin/state/test-0.1.setup
- server/pbench/bin/state/test-0.reset
- server/pbench/bin/state/test-0.setup
- server/pbench/bin/unittests
`TOP`, `TMP`, and `LOGSDIR` are now required for all scripts, since all
of them rely on their existence.  `TOP` is checked first because often
`TMP` and `LOGSDIR` are defined in relation to `TOP`.  All three checks
happen in `pbench-base.sh`.
> Require TOP & LOGSDIR in addition to TMP

- server/pbench/bin/pbench-server-prep-shim-001
- server/pbench/bin/pbench-server-prep-shim-002
If a `mv` of 2 files fails, it is possible for the move to have successfully
moved the first file, but not the second one.  We change to using `cp` instead
so that we can consistently clean up during the error handling.
> Copy two files instead of move two files

- server/pbench/bin/pbench-sync-package-tarballs
We remove the unused and unnecessary log directory creation step since it ends up creating thousands of directories, 1,440 to exact, every day.  This will eventually reek havoc with a file system.
> Stop creating the unnecessary log directory

- agent/tool-scripts/postprocess/openvswitch-postprocess
- The Signature Match Cache (SMC) is a newish cache feature in OVS.
Proper handling of this data lets the user see SMC cache hit
behavior and avoids the tool spewing messages about unrecognized
lines.
> openvswitch-postprocess: add support for SMC hit data

- agent/config/pbench-agent-default.cfg.example
- agent/config/pbench-agent.cfg.example
Fixes #961 #960 
This PR will fix the following conf file issues:
1. Fix the current agent config file which uses the wrong results host version.
2. Fix the missing pbench agent config default example file.
> Fix the agent conf files

- agent/bench-scripts/postprocess/fio-postprocess
- In newer versions of Perl the existing syntax results in the
following error:
"Experimental keys on scalar is now forbidden at <file> line <line #>"
> fio-postprocess: fix Perl syntax bug

- agent/base
- agent/bench-scripts/pbench-fio
- agent/bench-scripts/samples/pbench-agent.cfg
- agent/config/pbench-agent-default.cfg.example
- agent/config/pbench-agent.cfg.example
- agent/util-scripts/samples/pbench-copy-results/test-31/opt/pbench-agent/config/pbench-agent.cfg
Fixes issue #1005.
Pandas handling has been previously removed from pbench-fio.
This commit removes all the other traces of pandas that were left
over.
> Remove pandas-related stuff.

- agent/bench-scripts/gold/pbench-fio/test-17.txt
- agent/bench-scripts/gold/pbench-fio/test-18.txt
- agent/bench-scripts/pbench-fio
- agent/bench-scripts/unittests
Fixes #872
The `--directory` option does nothing: it has been subsumed
by the `--targets` option. Remove it completely.
> Remove `--directory` option from pbench-fio.

- web-server/v0.4/package.json
- web-server/v0.4/src/components/GlobalHeader/index.js
- web-server/v0.4/src/index.js
- web-server/v0.4/src/models/dashboard.js
- web-server/v0.4/src/models/global.js
- web-server/v0.4/src/models/search.js
- web-server/v0.4/src/routes/Dashboard/ComparisonSelect.js
- web-server/v0.4/src/routes/Dashboard/Controllers.js
- web-server/v0.4/src/routes/Dashboard/Results.js
- web-server/v0.4/src/routes/Dashboard/RunComparison.js
- web-server/v0.4/src/routes/Dashboard/Summary.js
- web-server/v0.4/src/routes/Search/SearchList.js
- web-server/v0.4/src/services/dashboard.js
- web-server/v0.4/src/services/global.js
The dashboard redux service will query the prefix value for a run before building the url to fetch result.json docs from the production environment.
This also improves the index selection workflow by removing ranges and allowing users to select specific indices to query run documents. This required a restructuring of redux services by moving specific dispatched actions to the `global` service in order to provide data at the appropriate scope throughout the dashboard.
> Query prefix field in run document for summary visualization

- web-server/v0.4/.webpackrc.js
- web-server/v0.4/README.md
- web-server/v0.4/src/services/global.js
Reference the node environment status in order to configure
appropriate endpoints and public paths for development and
production environments.
> Reduce overhead for local dev by using node environment vars

- agent/util-scripts/pbench-postprocess-tools
Based on a review for #1018, refactor a bit to clean up.
First and foremost, the handling of a missing non-default tool group has been fixed so that we emit an error and do nothing for a bad tool group.  This avoids collecting data under a tool group that does not exist.
We use `remote_hostname` everywhere instead of `remote` in certain places.
We added some comments and removed a level of indentation in one place that was not needed.
> A few cleanups to pbench-postprocess-tools

- agent/util-scripts/gold/pbench-move-results/test-33.txt
- agent/util-scripts/pbench-move-results
- agent/util-scripts/samples/pbench-move-results/test-33/pbench/pbench-user-benchmark_ndk-test-1_2019.01.01T12.00.44/bad-metadata.log
- agent/util-scripts/unittests
Going forward, if a pbench result does not have a metadata.log file
present, then we are not going to try to handle that result. This
will avoid problems that arise from not being able to index the data
from the result to use in various user interfaces (Kibana, Grafana,
and the pbench UI itself).
> Ensure pbench-move/copy-results only works with metadata.log

- agent/tool-scripts/postprocess/SysStat.pm
- agent/tool-scripts/postprocess/pidstat-convert
- agent/tool-scripts/postprocess/pidstat-postprocess
- agent/tool-scripts/postprocess/unittests
- agent/tool-scripts/sar
- Skips redundant data in pidstat output at runtime
- Stores data by PID/cmd
- Create a perl module for sysstat processing
- include a subroutine to return all pidstat attributes for v11.2
See original at #1035.
> Reduce pidstat space by 90%

- agent/bench-scripts/gold/pbench-user-benchmark/test-07.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-08.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-09.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-10.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-11.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-12.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-23.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-24.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-25.txt
- agent/bench-scripts/pbench-user-benchmark
- agent/bench-scripts/test-bin/user-benchmark-script
- agent/bench-scripts/unittests
Sometimes users will have to run a program that can't tolerate capturing
stderr to a file for whatever reason.  The new flag, `--no-stderr-capture`,
gives the users control over that behavior.
> Add --no-stderr-capture flag to pbench-user-benchmark

- agent/bench-scripts/pbench-gen-iterations
- agent/bench-scripts/pbench-run-benchmark
- agent/bench-scripts/pbench-run-benchmark-sample
- agent/bench-scripts/postprocess/fio-postprocess-cdm
- agent/config/benchmark/fio.json
- agent/lib/PbenchAnsible.pm
- agent/lib/PbenchCDM.pm
- agent/tool-scripts/postprocess/iostat-postprocess-cdm
- agent/util-scripts/pbench-import-cdm
- Fix metric generation for fio
- Tweak the 'begin' value for fio metrics such that it does not overlap
with previous metric's 'end' value
- Add --user-tags/USER_TAGS to pbench-run-benchmark and user.tags in run doc
- Eliminate excessive use of quotes in pbench-run-benchmark and pbench-gen-iterations
- Ensure the benchmark directory does not have spaces
- Use the correct CDM version in all documents
> Several fix-ups for CDM and pbench-run-benchmark

- web-server/v0.4/src/index.js
Removes the # between the host name and dashboard routes
by using the HTML5 History API.
> Use createBrowserHistory to manage session history

- agent/base
- agent/tool-scripts/perf
- agent/tool-scripts/perf.README
- agent/tool-scripts/postprocess/perf-postprocess
- agent/tool-scripts/postprocess/unittests
- agent/util-scripts/gold/pbench-register-tool-set/test-11.1.txt
- agent/util-scripts/gold/pbench-register-tool-set/test-11.2.txt
- agent/util-scripts/gold/pbench-register-tool-set/test-11.3.txt
Fixes #1058.
We address the problem of generating per-CPU data taking too long by forking each CPU data generation into its own process to run at whatever level parallelism the host can afford.
We also:
* Fix up the `tool-scripts/postprocess/gold/index.html` with the missing `.html` files
* Fix the `jstack`/`jmap` unit tests to include the generated `.html` files
* Address some minor comment cleanups in `perf-postprocess`
* Provide a minimal fix to parallelize the perf per-CPU report generation
* Provide a more complete refactoring of the `perf` tool to address both reduce the use of `pushd`/`popd` pairs
> Fix perf pp tool

- agent/bench-scripts/postprocess/fio-postprocess-cdm
- agent/bench-scripts/postprocess/trafficgen-postprocess-cdm
- agent/lib/PbenchCDM.pm
- agent/tool-scripts/postprocess/iostat-postprocess-cdm
We had the wrong field name used (hostname) when creating metric documents
> Metric fix for CDM: host instead of hostname

- agent/bench-scripts/gold/pbench-user-benchmark/test-09.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-10.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-11.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-12.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-23.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-24.txt
- agent/bench-scripts/gold/pbench-user-benchmark/test-25.txt
- agent/bench-scripts/pbench-user-benchmark
- agent/util-scripts/gold/test-tool-trigger/test-19.txt
- agent/util-scripts/pbench-tool-trigger
For pbench-user-benchmark and pbench-tool-trigger, don't use reference-result, use
sample1 instead for the result directory name.  Then create the symlink to sample1
using reference-result.
Fixes #1093.
> Don't use reference-result directly, use sample1

- server/bin/gold/test-7.16.txt
- server/bin/index-pbench
Since index-pbench already extracts the entire pbench tar ball into a
temporary directory, instead of using the tarfile object's "extractfile"
method, which creates an in-memory copy of the file, use the extract
copy.
> Use the already extracted sosreports

- server/bin/index-pbench
- server/bin/pbench-index
- server/bin/unittests
Prior to this change, if the indexing job has more than one tar ball to
index, index-pbench will extract each tar ball it works on, leaving the
extracted contents to be cleaned up by pbench-index. This works well for
one or two tar balls, but if we have a large set of tar balls to work
through this can be problematic.
This change makes it so that index-pbench properly cleans up the
extracted tar ball before exiting.  We modify pbench-index to give a
dedicated sub-directory to index-pbench so that we can detect problems.
We also modify the unit test harness to detect when any server script
leaves data around in its given TMPDIR.
> Ensure indexing properly cleans up extracted tar balls

- agent/bench-scripts/pbench-cyclictest
- agent/bench-scripts/pbench-iozone
- agent/bench-scripts/pbench-linpack
- agent/bench-scripts/pbench-migrate
- agent/bench-scripts/pbench-specjbb2005
- agent/util-scripts/pbench-tool-trigger
We fix references in the less-used benchmark scripts, cyclictest, iozone,
linpack, migrate, and specjbb2005.
We also fix a wayward comment in pbench-tool-trigger.
Further fixes for #1093.
> Further fixes to stop using reference-result directly

- web-server/v0.4/README.md
- web-server/v0.4/src/models/dashboard.js
- web-server/v0.4/src/models/global.js
- web-server/v0.4/src/pages/Dashboard/Results.js
- web-server/v0.4/src/pages/Dashboard/RunComparison.js
- web-server/v0.4/src/pages/Dashboard/Summary.js
- web-server/v0.4/src/services/dashboard.js
* Handle both new and old field names (requires PR #1073 for new field names)
* Adding some error handling when we don't get our expected data
* Strip trailing slashes in the configured URLs in case somebody makes a mistake
* Instead of using the configured prefix, use the `incoming` URL which does not need the `run.prefix` value
> Some minor behavior changes for field names and use of incoming URL

- web-server/v0.4/src/models/dashboard.js
- web-server/v0.4/src/pages/Dashboard/ComparisonSelect.js
- web-server/v0.4/src/pages/Dashboard/Controllers.js
- web-server/v0.4/src/pages/Dashboard/Results.js
- web-server/v0.4/src/pages/Dashboard/RunComparison.js
- web-server/v0.4/src/pages/Dashboard/Summary.js
- web-server/v0.4/src/services/dashboard.js
- web-server/v0.4/src/utils/utils.js
Use one common code for fetching and parsing iteration data (`queryIterations` and `parseIterationData`).
We also fix the sorting to behave correctly on all the pages by sharing the same sort method.
We reduce the number of calls to `setState()` to avoid repeated renderings of the page unnecessarily.
Depends on PR #1112.
> Use only query iterations

- web-server/v0.4/src/models/global.js
- web-server/v0.4/src/pages/Dashboard/Controllers.js
- web-server/v0.4/src/pages/Search/SearchList.js
Two arrays were being used to track the value and position
of a selected month. This is now referencing only the month
value and references the month string as a key within the
`<Select.Option>` child component.
> Remove 'selectorIndices' logic for simple month selection

- web-server/v0.4/src/pages/Search/SearchList.js
Converts the selected result to an array for parsing
within the Summary page component. Previously this was
passed as an object which caused an error.
This follows the same workflow presented from the row
onClick method in the Results component.
> Reference selectedResults as an array from SearchList

- agent/tool-scripts/bpftrace
---- 
This is for tracking purpose. I used the existing jmap tool to base this. Need your inputs/reviews on implementing the post-processing and other features needed for pbench. 
Here's the sample stdout from a run, which uses a basic bpftrace program, [syscount.bt](https://github.com/iovisor/bpftrace/blob/master/tools/syscount.bt): 
```
Attaching 3 probes...
Counting syscalls... Hit Ctrl-C to end.
Top 10 syscalls IDs:
@syscall[202]: 82215
@syscall[186]: 157832
@syscall[232]: 176516
@syscall[38]: 183350
@syscall[7]: 228544
@syscall[20]: 253303
@syscall[8]: 284114
@syscall[1]: 311635
@syscall[0]: 465967
@syscall[47]: 682795
Top 10 processes:
@process[grep]: 72991
@process[cut]: 75418
@process[Chrome_IOThread]: 89515
@process[Chrome_ChildIOT]: 100151
@process[code]: 167427
@process[sh]: …
```
> Add bpftrace to pbench-agent-tools

- web-server/v0.4/package.json
- web-server/v0.4/src/components/Button/index.js
- web-server/v0.4/src/components/GlobalHeader/index.js
- web-server/v0.4/src/components/MonthSelect/index.js
- web-server/v0.4/src/components/RowSelection/index.js
- web-server/v0.4/src/components/SearchBar/index.js
- web-server/v0.4/src/components/Table/index.js
- web-server/v0.4/src/models/dashboard.js
- web-server/v0.4/src/pages/Dashboard/Controllers.js
- web-server/v0.4/src/pages/Dashboard/Results.js
- web-server/v0.4/src/pages/Search/SearchList.js
This first pass in an effort to reduce page component rerenders represents one of three steps to enhance component performance:
1. Destructure page components by reorganizing logic into subcomponents (SearchBar, MonthSelect, RowSelection, Table, etc).
2. Group Redux actions and reducers to reorganize information needed for dashboard entry points that require page initializing (Controllers and Search)
3. Compare previous props and state values to prevent page rerenders using shouldComponentUpdate() or converting components to PureComponent
> Destructure page components for reducing component rerenders.

- web-server/v0.4/config/config.js
- web-server/v0.4/package.json
- web-server/v0.4/src/app.js
- web-server/v0.4/src/global.js
- web-server/v0.4/src/layouts/BasicLayout.js
- web-server/v0.4/src/pages/Dashboard/Controllers.js
- web-server/v0.4/src/pages/Dashboard/Results.js
- web-server/v0.4/src/pages/Search/SearchList.js
Redux Persist takes the state object and saves it to the persisted
storage (LocalStorage) for reference throughout multiple sessions.
This adds a configuration for setting up a base PersistGate in order
to capture state changes to the Redux store.
> Integrate redux persist for persisting and rehydrating redux store

- .travis.yml
- server/bin/unittests
We also ensure that for now TravisCI runs server tests serially to avoid
not emitting output for more than ten minutes triggering the TravisCI auto
kill feature.
> Add env var for server unit test parallelism

- web-server/v0.4/src/models/dashboard.js
- web-server/v0.4/src/models/search.js
- web-server/v0.4/src/pages/ComparisonSelect/index.js
- web-server/v0.4/src/pages/ComparisonSelect/index.test.js
- web-server/v0.4/src/pages/Controllers/index.js
- web-server/v0.4/src/pages/Results/index.js
- web-server/v0.4/src/pages/Results/index.test.js
- web-server/v0.4/src/pages/RunComparison/index.js
- web-server/v0.4/src/pages/RunComparison/index.test.js
- web-server/v0.4/src/pages/Search/index.js
- web-server/v0.4/src/pages/Summary/index.js
- web-server/v0.4/src/services/dashboard.js
- web-server/v0.4/src/services/search.js
This PR modifies redux store logic for tracking a single selected controller or multiple selected controllers for visualization throughout the pbench dashboard. In addition, this PR improves the search view UX to apply or reset filters once the user has made their selection on the filters pane.
Users are now able to select multiple results from their search query and launch a run to run comparison that may have originated from more than one controller.
> Launch run comparison across multiple controllers using search view

- web-server/v0.4/src/app.js
- web-server/v0.4/src/models/dashboard.js
- web-server/v0.4/src/models/global.js
- web-server/v0.4/src/models/search.js
- web-server/v0.4/src/pages/ComparisonSelect/index.js
- web-server/v0.4/src/pages/Controllers/index.js
- web-server/v0.4/src/pages/Results/index.js
- web-server/v0.4/src/pages/RunComparison/index.js
- web-server/v0.4/src/pages/Search/index.js
- web-server/v0.4/src/pages/Summary/index.js
For handling persistence of the redux store, selected configuration
data needs to be stored in the global reducer while the dashboard
namespace is blacklisted to avoid local caching.
Previously, caching of the dashboard namespace was causing conflicts
with an edge case where server side data was being updated but was not
reflected in persisted user sessions.
> Restructure selected dashboard components in redux store

- agent/tool-scripts/postprocess/pidstat-convert
Fixes https://github.com/distributed-system-analysis/pbench/issues/1164
- using $cmd for filenames would sometimes not work
- md5_hex should not have problems when used as a filename
- $cmd to md5 stored in memory and not needed later
> pidstat-convert: use md5 for filenames

- web-server/v0.4/package.json
Husky automatically creates git hook scripts as part of `.git/hooks`
when the developer runs `yarn` to install package dependencies. Husky
will trigger `npm run lint-staged` which runs both prettier and linting
commands configured by their respective `.prettierrc` and `.eslintrc`
files.
> Integrate Husky for pre-commit git hook management via package.json

- web-server/v0.4/src/utils/parse.js
Fixes an issue where the closest sample was not being assigned for indexed
data with key `closest sample` as opposed to `closest_sample`
> Fix closest sample assignment to iteration metadata in preprocessing

- web-server/v0.4/README.md
- web-server/v0.4/src/pages/document.ejs
`index.ejs` has been moved to `/pages/document.ejs` according to UmiJS conventions
> Resolve 404 error for loading dashboard favicon assets

- agent/util-scripts/pbench-sysinfo-dump
Starting with version 3.5.1, the `general` plugin was removed, having
it functionality moved into other existing plugins, and two new plugins
added, `date` and `host`.  The collection of `/proc/stat` was in the
`general` plugin, but was moved to the `process` plugin.  We don't add
the `process` plugin at this point because it was not on our original
list.  A separate commit should propose the addition of such a plugin.
In the mean time, we add the collection of the `date` and `host`
plugins now.
The `lsbrelease` plugin was renamed to `release`.
See also the sosreport commit: [971b958](https://github.com/sosreport/sos/commit/971b9581779da20384f0a4d8de5177c0b87d6892)
Fixes #1161.
> Fix use of sosreport for version 3.5.1 and later

- .gitmodules
- agent/base
- agent/bench-scripts/gold/test-benchmark-clis/test-CL.txt
- agent/config/pbench-agent-default.cfg
- agent/util-scripts/gold/pbench-collect-sysinfo/test-23.txt
- agent/util-scripts/gold/pbench-collect-sysinfo/test-24.txt
- agent/util-scripts/pbench-collect-sysinfo
- agent/util-scripts/pbench-sysinfo-dump
Stockpile is as part of collect sysinfo to gather system information
about controller and registered remotes. Eventually, collect sysinfo
will be replaced with stockpile once it has support to gather all
the info that it's collecting.
Fixes #915
> Add support to run stockpile along with collect sysinfo

- agent/util-scripts/pbench-sysinfo-dump
We reference the `pbench_install_dir` environment variable instead of
fetching it from the config file directly since `base` provides it.
We also fix a few tabs vs spaces issues, and add the "item" which was
in error when looping through the list of sysinfo items to execute.
> Reference pbench_install_dir enviroment variable

- agent/base
A recent commit, 7d57f5e2 (PR #1204), introduced an error check for the `pbench_run` directory's existence when the automatic creation of that directory is expected.
Restore the automatic directory creation.
Fixes #1219.
> Restore creation of pbench_run directory

- web-server/v0.4/src/pages/RunComparison/index.js
- web-server/v0.4/src/pages/RunComparison/index.test.js
- web-server/v0.4/src/utils/parse.js
- This PR includes visualization for describing the percent differences across generated clusters for a run comparison. 
- This will enhance the summary bar graph displayed showing mean values for each cluster.
> Matrix visualization for increase/decrease in percentage for comparison cluster

- web-server/v0.4/src/components/TableFilterSelection/index.js
- web-server/v0.4/src/utils/parse.js
`TableFilterSelection` listens for port changes and finds the aggregate hostname and port selection for default display in the comparison select page.
> Filter iteration hostname & ports by `all` keyword on component update

- web-server/v0.4/README.md
- web-server/v0.4/config/router.config.js
- web-server/v0.4/mock/datastoreConfig.js.example
- web-server/v0.4/src/common/menu.js
- web-server/v0.4/src/models/explore.js
- web-server/v0.4/src/pages/Explore/index.js
- web-server/v0.4/src/services/explore.js
Users may launch collected dashboard sessions from the shared
session table which includes details regarding session IDs, created
times, and description.
This page adds a new datastoreConfig field for the GraphQL server.
> Integrate Explore page for discovering and launching shared dashboard sessions

- agent/bench-scripts/pbench-run-benchmark-sample
- agent/lib/PbenchAnsible.pm
- agent/lib/PbenchBase.pm
- agent/util-scripts/pbench-output-monitor
When pbench-run-benchmark launches a process via PbenchAnsible.pm the output of that process is buffered within Ansible until the process exits.  In order to be able to monitor a benchmark while it is running these patches introduce a monitor script that is used as a wrapper around the benchmark process.  This wrapper takes special care to preserve the distinctly separate STDERR and STDOUT data streams while allowing the user to attach to a screen session on a/the client (named pbench-output-monitor) to view the output in real time with identical separation of output streams.
In the monitor, each benchmark process has it's STDERR and STDOUT redirected to named pipes via tee.  Using tee ensures that the output is preserved in the Ansible workflow as is currently done.  A bash process is …
> pbench-run-benchmark monitor

- agent/bench-scripts/pbench-uperf
Fixes an inconsistency between using:
* `pbench-uperf`
* `pbench-uperf --runtime=60`
The first will run a test for 60 seconds, the second will add 6 seconds of padding and run it for 66 seconds.
Fixes #1227.
> Fix uperf runtime padding

- server/lib/pbench/__init__.py
Fixes #1250.
The timestamp() method should return a string of the form
YYYY-MM-DDThh:mm:ss-TZ
It does that for unit tests with a hardcoded string, but for the "real"
case, it was returning a timestamp with microseconds added and no TZ.
Modify it to use the tstos() function in the latter case.
TBD: Change it in the unit test case to return `tstos(0)', i.e. the Unix
Epoch date: 1970-01-01T00:00:00-GMT. That will require wholesale changes
to the unit test gold files however, so postpone that change for the next
release.
> Modify PbenchConfig.timestamp() to return string in proper format

- web-server/v0.4/src/pages/Controllers/index.js
- web-server/v0.4/src/pages/Search/index.js
Avoids completely blacklisting the `global` namespace while
querying up to date config data for deployed dashboard instance
> Query dashboard datastoreConfig on page entrypoints

- server/bin/gold/test-7.8.txt
- server/bin/pbench-index.py
Newer versions of sosreport no longer generate the "hostname*" files
under the `sos_commands/general/` directory, since the `general`
sosreport plugin was removed. Now the "hostname*" files are found
under the `sos_commands/host/` directory.
> Verify handling of sosreports with host directory

- web-server/v0.4/src/app.js
In order to maintain unique dashboard deployments across one host, a unique local storage key is required for the dashboard to read separate Redux data stores. This PR resolves issue #1270.
> Create local storage key via window pathname

- server/bin/gold/test-7.0.1.txt
- server/lib/mappings/run-toc-entry.json
- server/lib/settings/run.json
Uses the "`path_hierarchy`" tokenizer for the directory and link fields of the table-of-contents JSON documents. The tokenizer creates multiple tokens out of paths, e.g. the path "`/home/foo/bar/file.txt`" would end up with four tokens when indexed into Elasticsearch [1]:
* `/home`
* `/home/foo`
* `/home/foo/bar`
* `/home/foo/bar/file.txt`
[1] https://www.elastic.co/guide/en/elasticsearch/reference/1.7/analysis-pathhierarchy-tokenizer.html
> Add path analyzer for indexing ToC data

- agent/bench-scripts/gold/pbench-fio/test-14.txt
- agent/bench-scripts/gold/pbench-fio/test-17.txt
- agent/bench-scripts/gold/pbench-fio/test-18.txt
- agent/bench-scripts/gold/pbench-fio/test-19.txt
- agent/bench-scripts/gold/pbench-fio/test-21.txt
- agent/bench-scripts/gold/pbench-fio/test-26.txt
- agent/bench-scripts/gold/pbench-fio/test-27.txt
- agent/bench-scripts/gold/pbench-fio/test-29.txt
- agent/bench-scripts/gold/pbench-trafficgen/test-22.txt
- agent/bench-scripts/pbench-cyclictest
- agent/bench-scripts/pbench-dbench
- agent/bench-scripts/pbench-iozone
- agent/bench-scripts/pbench-linpack
- agent/bench-scripts/pbench-migrate
- agent/bench-scripts/pbench-netperf
- agent/bench-scripts/pbench-specjbb2005
- agent/bench-scripts/pbench-trafficgen
- agent/bench-scripts/pbench-uperf
- agent/bench-scripts/pbench-user-benchmark
- agent/bench-scripts/test-bin/mock-cmd
- agent/bench-scripts/unittests
This PR addresses a problem in bench-scripts/unittests and associated problems. There are three commits:
- the first commit fixes the script and modifies some gold files to accommodate those fixes. That uncovers the failures that should have been there, but were not, when PR#1261 was tested.
- the second commit fixes  pbench-uperf and pbench-user-benchmark so that the unit tests all pass.
- the third commit applies the same fix to all the other bench scripts (which have no unit test coverage).
> Problems while testing v0.63 release candidate

- agent/bench-scripts/pbench-run-benchmark
- agent/bench-scripts/postprocess/generate-benchmark-summary
- agent/lib/PbenchBase.pm
- agent/tool-scripts/postprocess/gold/generate-benchmark-summary-0/result.json
- Give each iteration a unique name based on it's unique benchmark
parameters.
- The unique names are picked up by generate-benchmark-summary and
allow the iterations to be identified in the resulting summary
reports.
> fixup iteration naming for pbench-run-benchmark

- agent/lib/PbenchBase.pm
- Without this metadata log entry you cannot use pbench-move-results
to upload the data.
> PbenchBase.pm: add required metadata log for benchmark run name

- agent/util-scripts/gold/pbench-copy-results/test-31.txt
- agent/util-scripts/gold/pbench-move-results/test-33.txt
- agent/util-scripts/pbench-copy-result-tb
- agent/util-scripts/pbench-make-result-tb
- agent/util-scripts/pbench-move-results
- agent/util-scripts/unittests
We now have separate commands for "making a result tar ball" and for "moving" a result tar ball", `pbench-make|move-result-tb`. By breaking this command up into its loop components, we can use those components for other purposes, e.g. allowing a caller to invoke "make" and "move" in different environments.
One such intended use is to drive server side testing where an existing set of tar balls can be "moved" repeatedly to verify a staging environment.
> Decompose pbench-move-results into "make" and "move" components

- agent/bench-scripts/pbench-run-benchmark
- agent/bench-scripts/postprocess/generate-benchmark-summary
- agent/bench-scripts/postprocess/process-iteration-samples
- The logic that finds the closest samples index for an iteration
needs to be updated to properly handle different indexing schemes.
For example, the old pbench style of indexing starts at 1
(ie. sample1) while the new pbench-run-benchmark style of indexing
starts at 0 (ie. sample0).
- Update the hyperlinks that are generated for the HTML output from
generate-benchmark-summary to use the $iteration_name_format to
properly recreate the iteration name.
> update the closest samples index handling

- agent/util-scripts/gold/test-tool-trigger/test-19.txt
- agent/util-scripts/pbench-postprocess-tools
- First, the -i option is documented but was not actually processed
(--iteration was).
- Second, when killing the tools for a tool group the iteration number
is not relevant so remove it from the equation.  We always want the
tools from the specified tool group to be killed no matter what the
current iteration is.  This also makes iteration numbering schemes
irrelevant when killing tools.
> pbench-*-tools: fixup some iteration related issues

- .gitignore
- contrib/ansible/dashboard/README.md
- contrib/ansible/dashboard/config.json.j2
- web-server/v0.4/config.json.j2
We also add a convenience link to the `config.json.j2` to make it easier to use the scripts, and add an ignore the generated `dist` directories.
Further, we now ignore patch files from git format-patch, and ignore `run-unittests.log` files.
> Update README for using dashboard playbooks

- web-server/v0.4/src/pages/RunComparison/index.test.js
- web-server/v0.4/src/utils/parse.js
Fixes #1208 
Currently when a comparison of pbench-fio produced data is made using the dashboard it is labeled as using the iops_sec metric but the data that is displayed is actually from the clat metric. This fixes the data display to primary metric instead of clat metric.
> Fixes dashboard comparison of fio runs rendering incorrect metric

- server/ansible/roles/pbench-server-activate-create-results-dir-structure/tasks/main.yml
- server/ansible/roles/pbench-server-vars/tasks/main.yml
Get rid of the fs-version-001 item when creating the reception areas.
The config file now provides the prefix
".../pbench-local/pbench-move-results-receive/fs-version", so we only
need to append the version number "002" with a dash in between.
> Fix the creation of the reception area(s)

- server/ansible/roles/pbench-server-activate-create-results-dir-structure/tasks/main.yml
- server/ansible/roles/pbench-server-activate-setup-results-host-info/tasks/main.yml
Missed renaming of pbench_reception_dir_prefix in one place.
Make the version string "002" a string, otherwise it is an int
and loses the leading zeros.
> Fix two bugs in server ansible playbooks.

- server/bin/gold/test-7.0.1.txt
- server/lib/mappings/server-reports.json
- server/lib/pbench/indexer.py
- server/lib/settings/result-data.json
Don't index result.json files that are not lists. This lets us safely
ignore user-benchmark results that create result.json files which are
not in the expected format without recording them as errors.
There are cases where tools are partially defined in a metadata.log
file, but there are no actual tools listed.  In those cases, we don't
want to issue an error, we just want to skip indexing tools for that
host.
> Further fixes for indexing

- web-server/prisma/datamodel.prisma
- web-server/prisma/package.json
Prisma was reporting the following issue during url generation for run comparison pages: `Error: Value for field config is too long.` This error was preventing pbench dashboard from saving config data to our postgres db.
Upgrading and redeploying the Prisma service with the latest version and migrating the datamodel schema to support syntax changes as part of the version bump has resolved this error.
> Upgrade Prisma service to v1.34 to enable storage of large string values

- web-server/v0.4/README.md
- web-server/v0.4/src/app.js
- web-server/v0.4/src/models/datastore.js
- web-server/v0.4/src/models/global.js
- web-server/v0.4/src/pages/ComparisonSelect/index.js
- web-server/v0.4/src/pages/Controllers/index.js
- web-server/v0.4/src/pages/Explore/index.js
- web-server/v0.4/src/pages/Results/index.js
- web-server/v0.4/src/pages/RunComparison/index.js
- web-server/v0.4/src/pages/Search/index.js
- web-server/v0.4/src/pages/Summary/index.js
- web-server/v0.4/src/utils/utils.js
Separates user selected data and datastore data into separate stores of
`global` and `datastore`. The `datastore` Redux model is now blacklisted
to support constant updates to server side data.
> Reference application data via static `appName` field in `app.js`

- .gitignore
- contrib/ansible/dashboard/README.md
- contrib/ansible/dashboard/inventory
We are updating the `README.md` for the dashboard to fix up a few incorrect references to variable names expected by the `config.json.j2` template.  We also adjust the sample `inventory` file.
Lastly, we ignore the `.yarnrc` and `.npmrc` files to avoid folks inadvertently checking them into the code base.
> Enhance ansible dashboard README

- web-server/v0.4/config/config.js
Currently the default application history configuration against dashboard deployments produces page not found errors. Hash history will enable the storing of all path information within the hash of the URL.
> Specify the application history type to use hash history

- agent/bench-scripts/postprocess/BenchPostprocess.pm
Fixes https://github.com/distributed-system-analysis/pbench/issues/1336
-Aggregate metrics start with a dataset with many keys being
assigned to "all", but this should not be the case for 'timeseries',
which is used to reference an array.
> Don't assign "all" to timeseries array when creating aggregate

- .gitmodules
Stockpile moved to cloud-bulldozer organization.
Following https://github.com/cloud-bulldozer/stockpile/issues/59
> fixed stockpile cloning

- .travis.yml
- run-e2etests
- web-server/v0.4/e2etests
- web-server/v0.4/mock/api.js
- web-server/v0.4/package.json
- web-server/v0.4/src/e2e/controllers.e2e.js
- web-server/v0.4/src/e2e/results.e2e.js
- web-server/v0.4/src/e2e/search.e2e.js
- web-server/v0.4/src/models/dashboard.js
- web-server/v0.4/src/pages/Controllers/index.js
- web-server/v0.4/src/pages/Results/index.js
- web-server/v0.4/src/utils/utils.js
**Summary**
In order to facilitate the automation of unit tests and e2e tests within a single environment (Travis CI), the `.travis.yml` config will execute jobs within a build matrix for both tests. The `Unit Tests` job will be executed for the pbench agent, server, and dashboard unit tests under `./unittests`. The `E2E Tests` job will be executed for the pbench dashboard e2e tests under `./e2etests`. 
Each build matrix initializes the required environment for running the type of test defined within the outer bash scripts. Each bash script invokes the respective test being executed for a specific component of the platform e.g. pbench dashboard unit tests invokes `yarn test`. 
Migration of E2E tests to Travis CI is now made possible by utilizing request intercepting made available via …
> Enhance puppeteer e2e tests to use request API for intercepting requests

- web-server/v0.4/mock/api.js
- web-server/v0.4/src/e2e/search.e2e.js
- web-server/v0.4/src/models/search.js
- web-server/v0.4/src/pages/Results/index.js
- web-server/v0.4/src/pages/Search/index.js
**Summary**
Enforces the use of the `@metadata.controller_dir` field across run comparison initiation points (Result and Search views). Selecting a result row from the Result page now finds the result `key` property for building the `selectedResults` data structure within the `dashboard` Redux model.
> Reference @metadata.controller_dir when querying result.json files

- web-server/v0.4/src/components/Button/index.test.js
- web-server/v0.4/src/components/Table/index.test.js
```
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line 
components/Table  |      100 |      100 |      100 |      100 |                   |
index.js          |      100 |      100 |      100 |      100 |                   |
```
```
File               |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line 
components/Button  |      100 |      100 |      100 |      100 |                   |
index.js           |      100 |      100 |      100 |      100 |                   |
```
> Adds snapshot test for Table and Button component

- web-server/v0.4/src/components/TimeseriesGraph/index.test.js
```
File                             |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line 
components/TimeseriesGraph       |      100 |       100 |      100 |      100 |              |
index.js                       |      100 |       100 |      100 |      100 |      
```  
Coverage reports are currently retrieved in Jest by running the following command:` umi test ./src/components ./src/pages --verbose --maxWorkers=1 --runInBand "--coverage"`
> Adds unit test for TimeseriesGraph component

- web-server/v0.4/src/pages/ComparisonSelect/index.js
- web-server/v0.4/src/pages/Results/index.js
- web-server/v0.4/src/utils/parse.js
**Summary** 
Changes to result object references via array index caused issues with selecting rows within the `ComparisonSelect` page component. By utilizing the `selectedRows` named variable from the `onSelect()` and `onSelectAll()` row selection properties for ant design's Table API, we can access row data without having to keep track of the index selected by the user. This pattern has also been applied to the `Results` page component and resolves selecting all rows in a table from the table header.
> Utilize "selectedRows" from onSelect and onSelectAll callback

- server/bin/gold/test-0.1.txt
- server/bin/gold/test-0.2.txt
- server/bin/gold/test-0.txt
- server/bin/pbench-base.py
When reporting bad configuration file errors, add the name of the config file that failed.
> Report which config file failed

- server/bin/gold/test-24.txt
- server/bin/pbench-server-activate-create-crontab
- server/bin/state/test-24.config/pbench-server.cfg
- server/bin/unittests
- server/lib/config/pbench-server-default.cfg
Fixes #1307 
The fix eliminates `shims` option in the `[pbench-prep]` section of `pbench-server-default.cfg` and adress the use of it in `pbench-server-activate-create-crontab` with the help of
`pbench-move-results-receive-versions` from the `[pbench-server]' section.
> Eliminates shims option from the [pbench-prep] section of pbench-server-default.cfg

- web-server/v0.4/src/components/MonthSelect/index.js
- web-server/v0.4/src/models/dashboard.js
- web-server/v0.4/src/models/global.js
- web-server/v0.4/src/pages/ComparisonSelect/index.js
- web-server/v0.4/src/pages/RunComparison/index.js
**Summary**
`onSelectChange()` now references the result index rendered within the `ComparisonSelect` page in order to prevent overwriting of iteration metadata. Previously, this was causing run comparison clusters to represent single iterations per cluster.
> Prevent overwriting of iteration data by referencing result index

- web-server/v0.4/src/components/RowSelection/index.test.js
```
File                             |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line 
components/RowSelection          |      100 |      100 |      100 |      100 |                   |
index.js                         |      100 |      100 |      100 |      100 |                   |
```
> Adds Unit test for RowSelection Component

- agent/bench-scripts/gold/test-benchmark-clis/test-CL.txt
- agent/bench-scripts/pbench-trafficgen
- The repository name was changed a long time ago but the previous
name continued to work for backwards compability.  Recently this has
caused some confusion so go ahead and update the code to be
consistent with reality.
> pbench-trafficgen: point to the updated trafficgen repository location/name

- server/bin/gold/test-11.txt
- server/bin/gold/test-5.2.txt
- server/bin/pbench-sync-satellite.sh
Fixes #975 
This PR works on cleaning the logs directory if there are no errors.
> cleanup-log-directory

- agent/util-scripts/gold/eval/test-48.txt
- agent/util-scripts/pbench-add-metalog-option
- agent/util-scripts/unittests
Fixes #1329 
The problem is that configparser Interpolation (https://docs.python.org/3/library/configparser.html#configparser.InterpolationError) uses `%` as a marker for the interpolation construct `%(option)s` which replaces the construct by the value of the option. Configparser Interpolation does not accept the `%` symbol in any other context unless it is escaped as a double percent sign. So when we write a value with '%', ex: "30%" in any config file, this error in thrown. To fix this error, whenever the user enters a value that includes a  `%` char,  it will be converted into `%%` (double percent sign) which interpolation treats as a literal single percent sign.
> metalog-%-error

- server/bin/gold/test-2.txt
- server/bin/gold/test-3.txt
- server/bin/gold/test-4.txt
- server/bin/gold/test-5.1.txt
- server/bin/gold/test-5.2.txt
- server/bin/gold/test-5.txt
- server/bin/gold/test-9.1.txt
- server/bin/gold/test-9.2.txt
- server/bin/gold/test-9.3.txt
- server/bin/gold/test-9.4.txt
- server/bin/gold/test-9.5.txt
- server/bin/gold/test-9.6.txt
- server/bin/gold/test-9.7.txt
- server/bin/pbench-verify-backup-tarballs.py
To remove the redundant fetch of the MD5 values we added those methods to
the BackupObject class which let's us store the accummulated values in the
object for use later.
We also enhance the report formating so that we get separartion between
sub-sections of the report, and a summary of the timings for all the
phases.
> Remove redundant fetch of MD5s from verify backup

- web-server/v0.4/mock/api.js
- web-server/v0.4/src/components/MonthSelect/index.js
- web-server/v0.4/src/e2e/search.e2e.js
- web-server/v0.4/src/models/search.js
- web-server/v0.4/src/pages/Search/index.js
- web-server/v0.4/src/services/search.js
**Summary**
Selected runs within the Search page component are now "preserved" within the component state when the user executes a search query and later "committed" when the user initiates a run comparison or executes a new search query. 
In addition, the search filters aggregated via the Elasticsearch mappings have been moved under the search input in order to provide enhanced viewability of the search results table.
> Preserve search state to enable multi-controller search

- agent/util-scripts/gold/test-add-metalog-%-option/test-48.txt
- agent/util-scripts/test-bin/test-add-metalog-%-option
- agent/util-scripts/unittests
Fixes #1329
The problem is that configparser Interpolation (https://docs.python.org/3/library/configparser.html#configparser.InterpolationError) uses % as a marker for the interpolation construct %(option)s which replaces the construct by the value of the option. Configparser Interpolation does not accept the % symbol in any other context unless it is escaped as a double percent sign. So when we write a value with '%', ex: "30%" in any config file, this error in thrown. To fix this error, whenever the user enters a value that includes a % char, it will be converted into %% (double percent sign) which interpolation treats as a literal single percent sign.
This PR deals with the testcase of the problem
> Rewritten metalog-%-error testcase

- agent/util-scripts/gold/pbench-register-tool-set/test-11.1.txt
- agent/util-scripts/gold/pbench-register-tool-set/test-11.10.txt
- agent/util-scripts/gold/pbench-register-tool-set/test-11.12.txt
- agent/util-scripts/gold/pbench-register-tool-set/test-11.2.txt
- agent/util-scripts/gold/pbench-register-tool-set/test-11.3.txt
- agent/util-scripts/gold/pbench-register-tool-set/test-11.4.txt
- agent/util-scripts/gold/pbench-register-tool-set/test-11.5.txt
- agent/util-scripts/gold/pbench-register-tool-set/test-11.6.txt
- agent/util-scripts/gold/pbench-register-tool-set/test-11.9.txt
- agent/util-scripts/gold/pbench-register-tool-set/test-11.txt
- agent/util-scripts/gold/pbench-register-tool/test-00.txt
- agent/util-scripts/gold/pbench-register-tool/test-42.txt
- agent/util-scripts/gold/pbench-register-tool/test-43.txt
- agent/util-scripts/gold/pbench-register-tool/test-45.txt
- agent/util-scripts/gold/pbench-register-tool/test-46.txt
- agent/util-scripts/pbench-register-tool
It looks like newer versions of pass process associative arrays in different orders.  So we consistently use a numeric indexing scheme to avoid that behavior, allowing the unit tests to pass in all cases.
We also add the line number where a remotes file is not formatted as expected.
> Fix failing unit tests on some Fedora systems

- web-server/v0.4/README.md
- web-server/v0.4/package.json
We need to add the `--updateSnapshot` switch to the unit tests to make sure Jest updates snapshots across environments.
We also add a description of the README for how to install yarn from on Fedora/CentOS/RHEL boxes.
> Fix dashboard unit tests and update README.md

- agent/util-scripts/gold/pbench-copy-results/test-31.txt
- agent/util-scripts/gold/pbench-copy-results/test-39.txt
- agent/util-scripts/gold/pbench-copy-results/test-40.txt
- agent/util-scripts/gold/pbench-copy-results/test-41.txt
- agent/util-scripts/gold/pbench-metadata-log/test-03.txt
- agent/util-scripts/gold/pbench-move-results/test-33.txt
- agent/util-scripts/pbench-copy-result-tb
- agent/util-scripts/pbench-metadata-log
- agent/util-scripts/test-bin/scp
The scp mock command now only mocks local copies, which are used when copying
remote tool data locally.  The other copies are only recorded.
There was a wayward tmp directory in the sample data which should not be there.
Finally, we fix the various scp commands to use the right options.
> Fix use of scp/ssh options and mock scp cleanly

- web-server/v0.4/package.json
- web-server/v0.4/src/layouts/BasicLayout.js
**Summary**
Upgrading umi and umi plugins to their latest versions ensures compatibility between dependencies. This change also references the `persistStore` via the constructor of `BasicLayout` to ensure the `PersistGate` component opens on initial load.
> Upgrade umi and umi plugins to latest version 

- web-server/v0.4/src/components/MonthSelect/index.js
- web-server/v0.4/src/components/MonthSelect/index.test.js
```
File                  |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line 
components/MonthSelect |      100 |      100 |       75 |      100 |                   |
index.js               |      100 |      100 |       75 |      100 |                   |
```
> Adds unit test for Month Select component

- .travis.yml
- web-server/v0.4/README.md
- web-server/v0.4/e2etests
We enhance the `e2etests` script to keep track of the `yarn start` running in the background and make sure it is stopped before the script exits.
We also fix the yarn version we use to `1.19.1`.
Finally, we update the `README.md` to record the requirement of having `google-chrome-stable` installed for the E2E tests.
> Refine e2e tests to clean up background web server

- agent/tool-scripts/perf
- agent/tool-scripts/postprocess/perf-postprocess
Co-authored-by: sourabhtk37 <sourabhtk37@gmail.com>
Fixes #1297 
The fixe uses [Flamegraph](https://github.com/brendangregg/FlameGraph) an interactive SVG based visualization tool for perf data. For now, we are creating the SVG inside `agent/tool_script/perf` script and the Flamegraph generation files i.e `flamegraph.pl` and `stackcollapse-perf.pl` are also kept in the same directory. (But eventually, it would be better to create a post-process and move the files to appropriate directory _[yet to be discussed]_)
> Creates flamegraph for perf data

- web-server/v0.4/.eslintrc.js
UmiJS allows the use of specialized component file extension references with the `@` character. However, `eslint-plugin-import` rules specify strict rules for referencing file extensions for all import statements. In order to support component file extension references, we can disable this rule as we are not concerned with consistent usage of the default file extension.
> Ignore requirement for file extensions within the import path

- agent/bench-scripts/pbench-run-benchmark
- agent/bench-scripts/postprocess/fio-postprocess
- agent/tool-scripts/postprocess/gold/fio-0/result/reference-result/result.json
- Previously, fio-postprocess tracked mixed i/o (ie. simultaneous
reads and writes on the same test) separately using the 'rw_label'.
This would create two separate records in the samples array with the
same timestamp but different i/o types and values.  The problem is
that the rest of the postprocessing stack is not written to handle
data in this way and does not expect there to be multiple samples in
the array with the same timestamp.  This lead to data corruption in
multiple places and levels of the postprocessing stack.
- Fix the bug by intelligently combining the data where it's
relationship is understood and removing the concept of separate i/o
types and values.
> fio-postprocess: bug fix for mixed i/o data handling

- web-server/v0.4/src/components/PageHeader/index.js
- web-server/v0.4/src/components/PageHeader/index.test.js
Fixes #1337 
``` 
components/PageHeader           |    98.53 |    69.74 |      100 |    98.51 |                   |
index.js                      |    98.53 |    69.74 |      100 |    98.51 |                15 |
```
Coverage reports are currently retrieved in Jest by running the following command: `umi test ./src/components ./src/pages --verbose --maxWorkers=1 --runInBand "--coverage"`
> Adds unit test for PageHeader component

- server/bin/gold/test-26.1.txt
- server/bin/gold/test-26.2.txt
- server/bin/gold/test-26.3.txt
- server/bin/gold/test-26.4.txt
- server/bin/state/config-satellite/pbench-server.cfg
- server/bin/state/config/pbench-server.cfg
- server/bin/state/test-23.config/pbench-server.cfg
- server/bin/state/test-24.config/pbench-server.cfg
- server/bin/state/test-26.1.config/pbench-server.cfg
- server/bin/state/test-26.2.config/pbench-server.cfg
- server/bin/state/test-26.3.config/pbench-server.cfg
- server/bin/state/test-26.4.config/pbench-server.cfg
- server/bin/state/test-5.1.config/pbench-server.cfg
- server/bin/state/test-6.13.config/pbench-server.cfg
- server/bin/state/test-6.14.config/pbench-server.cfg
- server/bin/test-bin/test_logger_type.py
- server/bin/unittests
- server/lib/config/pbench-server-default.cfg
- server/lib/pbench/__init__.py
Fixes #310
The PR is regarding sending the logs to central server instead of using local log files.
To store the logs on Local log files FileHandler was used. I replaced the File Handler with the sysLogHandler to store logs on server.
To store logs on server rsyslog is required. It forwards log messages in an IP network with the help of configuration file in which we can define the IP network of where we want to send the data.
> Centrally log pbench-server

- agent/bench-scripts/gold/pbench-fio/test-04.txt
- agent/bench-scripts/gold/pbench-fio/test-05.txt
- agent/bench-scripts/gold/pbench-fio/test-06.txt
- agent/bench-scripts/gold/pbench-fio/test-07.txt
- agent/bench-scripts/gold/pbench-fio/test-08.txt
- agent/bench-scripts/gold/pbench-fio/test-13.txt
- agent/bench-scripts/gold/pbench-fio/test-15.txt
- agent/bench-scripts/gold/pbench-fio/test-16.txt
- agent/bench-scripts/gold/pbench-fio/test-20.txt
- agent/bench-scripts/gold/pbench-fio/test-28.txt
- agent/bench-scripts/gold/pbench-fio/test-30.txt
- agent/bench-scripts/gold/pbench-fio/test-31.txt
- agent/bench-scripts/gold/pbench-fio/test-32.txt
- agent/bench-scripts/pbench-fio
When using the `serial` job mode, the iteration name passed to the start/stop/post-process tools command included the individual device name targets, but the directory on disk did not include them.  This change corrects that making the iteration name handling consistent.
> Fix handling of pbench-fio iteration name

- .travis.yml
We also take advantage of already installed packages and modules, and move to Bionic, the latest supported Ubuntu distribution in Travis CI.
Depends on PR #1441.
> Move to Python 3.6 language envi in Travis CI

- server/bin/pbench-base.sh
- server/bin/pbench-dispatch.sh
- server/bin/pbench-server-prep-shim-002.sh
- server/bin/pbench-sync-package-tarballs.sh
- server/bin/pbench-sync-satellite.sh
Fixes #1446 
It replace the use of the pattern, echo "" >&4; log_finish; exit 1 with the log_exit method from pbench_base.sh.
> Replace 'echo "" >&4; log_finish; exit n' with log_exit

- web-server/v0.4/config/router.config.js
- web-server/v0.4/mock/api.js
- web-server/v0.4/package.json
- web-server/v0.4/src/components/GlobalHeader/index.js
- web-server/v0.4/src/components/SessionModal/index.js
- web-server/v0.4/src/components/SessionModal/index.less
- web-server/v0.4/src/components/SessionModal/index.test.js
- web-server/v0.4/src/e2e/session.e2e.js
- web-server/v0.4/src/layouts/BasicLayout.js
- web-server/v0.4/src/models/dashboard.js
- web-server/v0.4/src/models/datastore.js
- web-server/v0.4/src/models/global.js
- web-server/v0.4/src/models/search.js
- web-server/v0.4/src/pages/Explore/index.js
- web-server/v0.4/src/pages/SessionPlaceholder/index.js
- web-server/v0.4/src/pages/SessionPlaceholder/index.test.js
- web-server/v0.4/src/services/datastore.js
- web-server/v0.4/src/services/global.js
In order to promote sharing of data and insights throughout the platform, sessions are recording by preserving global dashboard state and then stored within the graphql server. This integration involves handoffs between the dashboard and graphql server to generate a unique link that can be shared to reinitialize a session a user has shared. All generated sessions are then made available within the `Explore` page component for discovery. 
- `SessionPlaceholder` page component for acting as a loading gate for initializing sessions when the user has provided a unique ID within the dashboard url 
- `SessionModal` component for capturing session descriptions and allowing user to copy to their browser for sharing
- `Alert` banner component for displaying active session metadata and allowing …
> User session sharing feature

- web-server/v0.4/src/models/explore.js
- web-server/v0.4/src/pages/Explore/index.js
- web-server/v0.4/src/pages/Explore/index.test.js
- web-server/v0.4/src/services/explore.js
Fixes #1427 
Implements UI for adding a description to a saved session in the Dashboard.
> Adds ability to write a description for a session in the dashboard

- server/bin/pbench-base.sh
- server/bin/pbench-clean-up-dangling-results-links.sh
- server/bin/pbench-copy-sosreports.sh
- server/bin/pbench-dispatch.sh
- server/bin/pbench-edit-prefixes.sh
- server/bin/pbench-satellite-cleanup.sh
- server/bin/pbench-server-prep-shim-002.sh
- server/bin/pbench-sync-satellite.sh
- server/bin/pbench-unpack-tarballs.sh
Fixes #1421
Server bash scripts used "echo" and output redirection to log info and error messages to local files.
This PR does two things:
- It defines two functions, "log_info" and "log_error", in pbench-base.sh.
- It replaces uses of "echo" for logging purposes with one or the other of these two functions.
Note that the messages have not been changed at all and neither have the destinations: after the
change, the same messages are logged to the same places. This means that there is *no* change to
the gold files used for unit testing.
In a future PR, we are planning to change the logging functions in pbench-base.sh, so that they
follow the policy that is already used by server python scripts: logging to a centralized log
service. That is going to involve changes to pbench-base.sh and …
> Log messages using logging functions in bash scripts.

- web-server/v0.4/config/constants.js
- web-server/v0.4/mock/api.js
- web-server/v0.4/src/components/Table/index.js
- web-server/v0.4/src/e2e/controllers.e2e.js
- web-server/v0.4/src/e2e/results.e2e.js
**Feat-** Allow users to search through various controllers in the dashboard, n(10/20/30) items at a time. 
**Fixes-** #1424
> Enable pagination for Table component

- web-server/v0.4/src/e2e/controllers.e2e.js
Currently, the item that we click is not consistent when we run tests each time, that's why some tests pass and some fail. Re-running these tests with an updated item onclick.
> clicks on the current pagination value

- server/bin/gold/test-7.0.1.txt
- server/bin/gold/test-7.4.txt
- server/bin/gold/test-7.5.txt
- server/lib/mappings/run.json
- server/lib/pbench/indexer.py
Fixes #1263 
Added a Marker to the sosreport tar ball if it can't find ```hostname or hostname_-F```
> Add Marker 'Bad-Hostname' field for the sosreport tarball

- web-server/v0.4/src/components/SiderMenu/index.test.js
Fixes #1337 
```
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line 
index.js         |      100 |       75 |      100 |      100 |            21
```
> Adds unit test for SiderMenuWrapper Component

- web-server/v0.4/src/common/menu.js
- web-server/v0.4/src/components/PageHeader/index.js
- web-server/v0.4/src/components/PageHeader/index.test.js
- web-server/v0.4/src/components/_utils/pathTools.js
- web-server/v0.4/src/layouts/BasicLayout.js
Previously, we were using `routes` in PageHeader component, however they were always undefined because they were not passed at the first place from top components. 
Also, there was a small bug where we placed a root pathname '/' which was preventing breadcrumbs from rendering in the first place.
That renders breadcrumbs for the pages present in the sidebar, hence is a step towards fixing #1425.
> Render breadcrumbs 

- web-server/v0.4/src/components/SearchBar/index.test.js
Fixes #1337 
```
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line 
components/SearchBar |    78.95 |      100 |    83.33 |    78.95 |                   |
index.js          |    78.95 |      100 |    83.33 |    78.95 |       33,34,54,55 
```
> Adds unit test for Search Bar component

- agent/bench-scripts/pbench-fio
- agent/util-scripts/getconf.py
- server/bin/getconf.py
- server/bin/unittests
The `pbench-fio` benchmark script was emitting a message directly to the `tty` when the `fio` version could not be determined.  Instead we add it to the `pbench.log` and emit it on `stderr`.
We also define the `PYTHONPATH` once in the server unit tests, and make the python markers in the `getconf.py` modules uniform with other files.
> Don't emit messages directly to the tty

- agent/bench-scripts/pbench-run-benchmark
- agent/lib/PbenchBase.pm
Both invocations of `pbench-metadata-log` need the name of the benchmark.  Without the `$benchmark` environment variable being set, `pbench-metadata-log` fails to create the required metadata in the top-level `metadata.log` file.  Without this metadata, server-side indexing will fail.
See also #1512.
> Correctly invoke pbench-metadata-log 'beg'

- server/ansible/Inventory/group_vars/servers
- server/ansible/Inventory/pbench-server.hosts.example
- server/ansible/roles/pbench-repo-install/tasks/main.yml
- server/ansible/roles/pbench-repo-install/templates/etc/yum.repos.d/pbench-server.repo.j2
- server/ansible/roles/pbench-repo-install/vars/main.yml
- server/ansible/roles/pbench-server-activate-create-crontab/tasks/main.yml
- server/ansible/roles/pbench-server-install-config-file/tasks/main.yml
- server/ansible/roles/pbench-server-vars/tasks/main.yml
- server/ansible/roles/pbench-server-vars/vars/main.yml
There are two commits in this PR:
- The first commit refactors the playbooks to move site-specific variables out of the playbooks and into a group_vars file, accessible from the inventory file. There is now a configfiles variable that is a list of config files to install (in addition to the default file that is part of the distribution): we make use of that for the S3 backup information. We also allow multiple repos now: it makes life easier for developers.
-  The second commit deals with the fallout from the configtools reorg (PR #1472 and PR #1457). We need to define PATH, PYTHONPATH and _PBENCH_SERVER_CONFIG in the environment in order to be able to execute some commands (getconf.py in particular). We also need to use scl to execute these commands on RHEL7 systems.
> Refactoring of server ansible playbooks and fixes from the configtools reorg

- .pre-commit-config.yaml
- .travis.yml
- pyproject.toml
From the web page:
black is an uncompromising python code formatter.  By using it, you agree to
cede control over minutiae of hand-formatting.  In return, Black gives you speed,
determinism, and freedom from pycodestyle nagging about formatting.
You will save time and mental energy for more important matters.
Don't enforce black at the start because we are not ready to enforce
the changes yet.
Signed-off-by: Chuck Short <chucks@redhat.com>
> Add pre-commit hooks for black

- .flake8
- agent/bench-scripts/postprocess/fio-postprocess-viz.py
- agent/bench-scripts/templates/make-fio-jobfile.py
- lib/configtools/__init__.py
- server/bin/gold/test-26.3.txt
- server/bin/pbench-backup-tarballs.py
- server/bin/pbench-index.py
- server/bin/pbench-verify-backup-tarballs.py
- server/bin/test-bin/test_logger_type.py
- server/lib/pbench/__init__.py
- server/lib/pbench/indexer.py
- server/lib/pbench/report.py
- server/lib/s3backup/__init__.py
This is a code refactoring of the indexer module to reduce the number of module level functions that effectively operate as class methods. That is, all the functions took a `PbenchTarBall` object via `ptb` variables.
As a result of this clean up, further cleanup within classes can be performed without cascading effects to all the function/method interfaces.
No functionality was changed.
This change also tightens down the `flake8` checks and proposes fixes for both the agent and server side to address problems found by `flake8`.
Of note, `configtools` has had its missing `expand_range` and `parse_range` code restored.
> Refactor indexer module functions into class methods

- agent/bench-scripts/pbench-specjbb2005
The `pbench-metadata-log` `end` operation looks for a `.iterations` file.  Without that file, we won't index the iteration names properly.
> Fix pbench-specjbb2005's iteration handling

- agent/bench-scripts/pbench-user-benchmark
- agent/bench-scripts/tests/pbench-user-benchmark/test-09.txt
- agent/bench-scripts/tests/pbench-user-benchmark/test-10.txt
- agent/bench-scripts/tests/pbench-user-benchmark/test-11.txt
- agent/bench-scripts/tests/pbench-user-benchmark/test-12.txt
- agent/bench-scripts/tests/pbench-user-benchmark/test-23.txt
- agent/bench-scripts/tests/pbench-user-benchmark/test-24.txt
- agent/bench-scripts/tests/pbench-user-benchmark/test-25.txt
- agent/bench-scripts/tests/pbench-user-benchmark/test-38.txt
All the other benchmarks record the on-disk directory name in the list of iterations.  This change brings `pbench-user-benchmark` in line with the others.
We also add the `iteration_number` field like the other benchmarks have.
> Modify pbench-user-benchmark to use iteration names

- agent/lib/PbenchBase.pm
This allows `pbench-add-metalog-option` to contruct the list of iteration names in the expected format (comma separated with a space).
> Separate run benchmark iteration names by a space

- agent/bench-scripts/test-bin/mock-cmd
- agent/util-scripts/gold/test-tool-trigger/test-19.txt
- agent/util-scripts/pbench-postprocess-tools
The use of the `-Logfile <file>` parameter for `screen` in not available until v4.5 and later.  Don't depend on that feature of `screen` so that we can support older environments easily.
> Drop use of screen -Logfile for old screen vers

- agent/tool-scripts/base-tool
- agent/tool-scripts/datalog/pidstat-datalog
We make sure the `pidstat-datalog` does not `exec` `pidstat`, so that `base-tool` can `kill` the one `pidstat-datalog` parent of the `pidstat` and `pidstat-convert` child processes.  By killing the parent, two
children are also `kill`'d.
This is an alternative to consider in place of #1578.
> Make sure pidstat-datalog does not use exec

- agent/bench-scripts/pbench-trafficgen
- agent/bench-scripts/postprocess/process-iteration-samples
- agent/bench-scripts/tests/pbench-trafficgen/test-22.txt
- Capture the output from the post processing scripts
- Exit if process-iteration-samples generates an unexpected return
code
> pbench-trafficgen: harden post processing

- agent/profile
Fixes #1589
The definition of PYTHONPATH in the profile has to match the
directory where the configtools library is in the installed tree.
We changed the latter to simplify the build, so we need to change
the former to match it.
> Change PYTHONPATH in profile

- pbench/__init__.py
- server/bin/gold/test-27.txt
- server/bin/state/config-satellite/pbench-server.cfg
- server/bin/state/config/pbench-server.cfg
- server/bin/state/test-23.config/pbench-server.cfg
- server/bin/state/test-26.1.config/pbench-server.cfg
- server/bin/state/test-26.3.config/pbench-server.cfg
- server/bin/state/test-26.4.config/pbench-server.cfg
- server/bin/state/test-27.config/pbench-server.cfg
- server/bin/state/test-6.13.config/pbench-server.cfg
- server/bin/state/test-6.14.config/pbench-server.cfg
- server/bin/test-bin/test_logger_level.py
- server/bin/unittests
- server/lib/config/pbench-server-default.cfg
Fixes #1530 
Setting the logging level as DEBUG for unit-scripts and INFO for production use.
> logging level settings for the server scripts

- server/ansible/roles/pbench-server-add-commit-id/tasks/main.yml
- server/ansible/roles/pbench-server-config/tasks/main.yml
- server/ansible/roles/pbench-server-vars/tasks/main.yml
Fixes issue #1624.
Modify the ansible playbook to set the `commit-id' field in the
[pbench-server] section of the server config file on installation.
That is used to tag status reports generated from server scripts.
> Add `commit-id' to server config file.

- server/ansible/roles/pbench-server-add-commit-id/tasks/main.yml
- server/ansible/roles/pbench-server-vars/tasks/main.yml
Supplements PR #1625: the commit-id option
in the [pbench-server] section of the pbench-server.cfg file
now looks like this:
commit-id=<VERSION>-<SEQNO><SHA1>
e.g.
commit-id=0.68-1g72ca85a2
> Add seqno to commit-id in [pbench-server].

- agent/bench-scripts/pbench-fio
- agent/bench-scripts/pbench-uperf
- agent/bench-scripts/tests/Defaults/pbench-agent.cfg
- agent/bench-scripts/tests/pbench-fio/test-04.txt
- agent/bench-scripts/tests/pbench-fio/test-05.txt
- agent/bench-scripts/tests/pbench-fio/test-06.txt
- agent/bench-scripts/tests/pbench-fio/test-07.txt
- agent/bench-scripts/tests/pbench-fio/test-08.txt
- agent/bench-scripts/tests/pbench-fio/test-13.txt
- agent/bench-scripts/tests/pbench-fio/test-15.txt
- agent/bench-scripts/tests/pbench-fio/test-16.txt
- agent/bench-scripts/tests/pbench-fio/test-20.txt
- agent/bench-scripts/tests/pbench-fio/test-28.txt
- agent/bench-scripts/tests/pbench-fio/test-30.txt
- agent/bench-scripts/tests/pbench-fio/test-31.txt
- agent/bench-scripts/tests/pbench-fio/test-32.txt
- agent/bench-scripts/tests/pbench-uperf/test-00.txt
- agent/bench-scripts/tests/pbench-uperf/test-01.txt
- agent/bench-scripts/unittests
- agent/config/pbench-agent-default.cfg
Fixes #1604.
This changes the expected name of the `uperf` RPM from `pbench-uperf` to just `uperf`, while bumping the expected version to `1.0.7`.
We also add a commit for renaming the `pbench-fio` RPM to just `fio`.
> Move to support uperf-1.0.7 and fio-3.19 RPM names

- server/bin/gold/test-7.10.txt
- server/bin/gold/test-7.11.txt
- server/bin/gold/test-7.15.txt
- server/bin/gold/test-7.16.txt
- server/bin/gold/test-7.19.txt
- server/bin/gold/test-7.20.txt
- server/bin/gold/test-7.21.txt
- server/bin/gold/test-7.22.txt
- server/bin/gold/test-7.23.txt
- server/bin/gold/test-7.24.txt
- server/bin/gold/test-7.25.txt
- server/bin/gold/test-7.8.txt
- server/bin/unittests
- server/lib/pbench/indexer.py
Two commits, one to address some `black` formatting ugliness, and a second commit to address problems encountered while indexing in the wild.
First, we have seen the `action_retry_deque` assertion fire, which was fairly useless as it was because no context information was given. So we address that by turning that assertion into a logging "error", adding some additional context information to help (helps debug #1621).
Second, we add the tar ball being indexed to error and exception log messages to make it more convenient to track down the problem when debugging (helps tracking down when #1622 occurs).
Third, there is a problem deriving host names given IP addresses, so we fixed the code to make sure the logic is correct and works in all cases. We also added a new test, `test-7.25`, to …
> Address indexing related behaviors seen in the wild

- server/bin/pbench-backup-tarballs.py
We want to have the environment variable value provided by the command line tool operation, leaving the core code to receive its input from one place, making it easier to test in the future.
We also take the opportunity to use f-strings were possible.
> Refactor backup-tarballs envi var use

- server/bin/gold/test-16.txt
- server/bin/gold/test-17.txt
- server/bin/gold/test-5.2.txt
- server/bin/pbench-unpack-tarballs.sh
- server/bin/state/test-5.2.setup
The new unpack tar balls algorithm no longer sorts by size, but by modification time from newest to oldest.  We update the code comments to reflect the current behavior (which was using "change time") and fix the code to actually use "modification time" (the `%Tk` `find` printf format).
> Stabilize test output for unpack tar balls

- .gitignore
- lib/configtools/__init__.py
- run-unittests
- server/bin/pbench-cull-unpacked-tarballs.py
- server/lib/pbench/indexer.py
- server/lib/pbench/mock.py
- tox.ini
We also modify `run-unittests` to run all the tox tests and linting, properly removing old tox environments before the runs.
> Fix new linting errors

- server/bin/pbench-audit-server.sh
Some tar ball have a `metadata.log` file where the user specified the prefix using either a leading or a trailing slash (or both).  We remove those slashes first before comparing against the actual prefix found.
> Reduce false positives for prefixes from audit

- server/ansible/roles/pbench-server-activate-setup-results-host-info/tasks/main.yml
The -001 structures stopped being produced from the pbench-agent (see
PR #1302) since v0.65 (Sep. 2019). It is about time to get rid of those
structures from the server.
> Setup results-host-info: do not create obsolete -001 structures.

- server/ansible/roles/pbench-server-install-config-file/tasks/main.yml
Instead of having the remotes use getURL to fetch their config files
(which is not always possible, e.g. if the remote is outside the
firewall), fetch the config files locally and store them under a
temporary directory, named partially after the inventory hostname, and
then copy them using ssh to the remotes.
The assumption is that the ansible control machine is inside the
firewall, so it can use getURL to fetch the config files, but it can
also ssh to the remotes to copy the file(s), even if (some of) the
remotes are outside the firewall.
> Modify the config install action to work with ssh

- server/bin/gold/test-7.24.txt
- server/lib/pbench/indexer.py
The pbench dashboard expects a few additional fields that were not originally provided when indexing user-benchmark data.
> Fix user-benchmark data indexing for dashboard

- server/bin/gold/test-20.txt
- server/bin/gold/test-27.txt
- server/bin/pbench-audit-server.sh
Fixes issue #1688
pbench-script uses cnt in every routine without declaring it local, so the various routines stomp on the global count. It needed to declare count locally so that it can keep cnt of each functionality individually.
> pbench-audit-server.sh counts discrepancy

- server/ansible/Inventory/pbench-server.hosts.example
- server/ansible/roles/pbench-clean-yum-cache/tasks/main.yml
- server/ansible/roles/pbench-server-change-ownership/tasks/main.yml
- server/ansible/roles/pbench-server-config/tasks/main.yml
- server/ansible/roles/pbench-server-install-config-file/tasks/main.yml
- server/ansible/roles/pbench-server-install/tasks/main.yml
- server/ansible/roles/pbench-server-user/tasks/main.yml
pbench-clean-yum-cache role: (new)
Add a pbench-clean-yum-cache role: the ansible package module is not
always successful in updating to the latest package, particularly on RHEL7
boxes. This is an attempt to help it do that, but it remains to be seen how
effective it is.
pbench-server-install role:
Import the pbench-clean-yum-cache role so that it is executed before we try
to install/update packages.
pbench-server-user role:
Add some  SELinux settings to the /home/<pbench>/.ssh directory.
Fix comments and add pbench_repo_url_prefix variable to the inventory example
file.
> Fix server ansible roles.

- agent/ansible/Inventory/pbench-agent.hosts.example
- agent/ansible/pbench-agent-config.yml
- agent/ansible/pbench-agent-install.yml
- agent/ansible/roles/pbench-agent-install/tasks/main.yml
- agent/ansible/roles/pbench-clean-yum-cache/tasks/main.yml
- agent/ansible/roles/pbench-repo-install/vars/main.yml
- server/ansible/Inventory/pbench-server.hosts.example
- server/ansible/pbench-server-install.yml
- server/ansible/roles/pbench-clean-yum-cache/tasks/main.yml
- server/ansible/roles/pbench-repo-install/vars/main.yml
Fixes to agent and server playbooks/roles/sample inventiory files.
- recognize CentOS
- use pbench_configuration_environment in the sample inventory file and set its value to either a host-specific value or the configured default ('production')
- stop command from complaining when running `yum clean`
Commits:
1. agent ansible fixes (see above)
2. server ansible fixes (see above)
3. agent ansible: install both pbench-agent and pbench-sysstat
> Fixes to ansible playbooks/roles

- server/bin/pbench-cull-unpacked-tarballs.py
Two aspects:
- When unit testing, force the generator and sort the list before processing.
- For the report, always sort the actions (even when not unit testing). It keeps
the code cleaner and it does not cost much.
> Sort the output of pbench-cull-unpacked-tarballs.py

- agent/tool-scripts/datalog/cpuacct-datalog
This PR deals with fixing datalog-cpuacct directory sequencing by sorting directories. I have also checked all the scripts in datalog directory and they do not seem to suffer from this problem.
> Fixes datalog-cpuacct directory order

- agent/base
- agent/bench-scripts/pbench-dbench
- agent/bench-scripts/pbench-fio
- agent/bench-scripts/pbench-iozone
- agent/bench-scripts/pbench-netperf
- agent/bench-scripts/pbench-uperf
- agent/config/pbench-agent-default.cfg
In case the `benchmark_bin` is not set the `pbench-fio` script uses `/usr/local/bin/fio` and the `pbench-uperf` script uses `/usr/bin/uperf`.  This is not systematic and could lead to confusion, let's not attempt to be clever and simply rely on the system `PATH` when `benchmark_bin` is not set by the user.
> Avoid hardcoded tools location on bench-scripts

- agent/bench-scripts/pbench-uperf
We now properly generate valid XML for the `rr` `${test_type}`, adding the missing `</transaction>` line.
> Fix uperf "rr" (round-robin) test XML

- agent/bench-scripts/tests/pbench-fio/test-04.txt
- agent/bench-scripts/tests/pbench-fio/test-05.txt
- agent/bench-scripts/tests/pbench-fio/test-06.txt
- agent/bench-scripts/tests/pbench-fio/test-07.txt
- agent/bench-scripts/tests/pbench-fio/test-08.txt
- agent/bench-scripts/tests/pbench-fio/test-13.txt
- agent/bench-scripts/tests/pbench-fio/test-15.txt
- agent/bench-scripts/tests/pbench-fio/test-16.txt
- agent/bench-scripts/tests/pbench-fio/test-20.txt
- agent/bench-scripts/tests/pbench-fio/test-28.txt
- agent/bench-scripts/tests/pbench-fio/test-30.txt
- agent/bench-scripts/tests/pbench-fio/test-31.txt
- agent/bench-scripts/tests/pbench-fio/test-32.txt
- agent/config/pbench-agent-default.cfg
The `fio` 3.20 version now properly installs `fio-histo-log-pctiles.py` via `make install`.  The Fedora RPM build of `fio` for the 3.21-1 version is the first build to include that update.
Fixes #1728.
> Require fio 3.21 and later

- agent/ansible/Inventory/pbench-agent.hosts.example
- agent/ansible/pbench-agent-install.yml
- agent/ansible/roles/debug-vars/tasks/main.yml
- agent/ansible/roles/pbench-agent-config/defaults/main.yml
- agent/ansible/roles/pbench-repo-install/defaults/main.yml
Only `pbench_key_url` and `pbench_config_url` are left to be defined by the user (probably in the inventory file). The rest are defaulted but can be overridden.
Comment out the defaulted values in the example inventory file and add explanatory comments.
> Give default values to most of the variables.

- server/lib/config/pbench-server-default.cfg
Fixes issue #1668
Get rid of "use-mail-for-status" as it is no longer being used.
Either we indexes or logs.
> Get rid of "use-mail-for-status"

- server/ansible/roles/pbench-server-add-commit-id/tasks/main.yml
- server/lib/config/pbench-server-default.cfg
Fixes #1767
The default config file and (more crucially) the ansible roles use "commit-id",
but the rest of the code is looking for "commit_id".
Standardize on the underscore version: "commit_id".
> Make spelling of commit_id consistent

- server/bin/gold/test-24.txt
- server/bin/gold/test-8.txt
- server/lib/config/pbench-server-default.cfg
Fixes #1764
Change the backup frequency in the default config file.
Fix the unit tests (8 and 24).
> Set backup cron job frequency to every minute

- agent/profile
* The current code clobbers the `prefix` and `pathins` function if the user happens to have them set.
* The current code doesn't check for an empty PYTHONPATH (or much less likely PATH) and hence incorrectly adds the (dynamic) current working directory to either if they're empty.
* The current call to path insertion is not quoted and will behave incorrectly if the prefix contains whitespace.
Checked with shellcheck and manually sourcing it twice to ensure that it's idempotent.
> Clean up assorted issues with /etc/profile.d/pbench

- agent/util-scripts/gold/test-client-tool-meister/test-53.txt
- agent/util-scripts/gold/test-client-tool-meister/test-56.txt
- agent/util-scripts/gold/test-client-tool-meister/test-57.txt
- agent/util-scripts/pbench-register-tool
- agent/util-scripts/pbench-tool-meister-start
- agent/util-scripts/test-bin/test-client-tool-meister
Fixes issue #1751, where tools with multiple arguments only have the first argument passed to the tool command.
When we load the registered tools into Redis, we process the tool options to make sure they are handled as a single string on the tool command line.
A separate PR for the `b0.69` branch exists as well, PR #1812.
> Fix tool argument handling

- agent/Makefile
- agent/rpm/Makefile
- agent/rpm/exclude.pats
- agent/rpm/patches/stockpile-shebang.patch
- agent/rpm/pbench-agent.spec
- agent/rpm/utils/rpm.mk
- agent/rpm/utils/set-version-release
- agent/util-scripts/pbench-config
Pull the RPM making machinery for the agent into the upstream repo.
```
cd agent/rpm
make rpm
```
should work <s>(but it still uses the roundabout upstream-tarball ways - getting rid of that is TBD)</s>. THere are still some ugly hacks, but it's pretty close: the `agent/Makefile` provides an install target that installs to DESTDIR (by default `/opt/pbench-agent`), The spec file uses this target (modifying DESTDIR) in order to build the RPM. The `agent/rpm/Makefile` provides `srpm` and `rpm` targets to build locally and `copr` and `copr-test` targets to build on COPR (you need an account on COPR and you need to set the env variable COPR_USER to the account name).
That's the good. The bad is that the server needs the same treatment and it has not had it yet. The ugly is the ad-hoc way of …
> Pbench rpm

- .gitignore
- agent/tool-scripts/datalog/cpuacct-datalog
- agent/util-scripts/gold/pbench-register-tool/test-52.txt
- agent/util-scripts/gold/pbench-start-tools/test-51.txt
- agent/util-scripts/pbench-postprocess-tools
- agent/util-scripts/pbench-register-tool
- agent/util-scripts/samples/pbench-start-tools/test-51/pbench/tools-default/tcpdump
- agent/util-scripts/unittests
- server/bin/pbench-cull-unpacked-tarballs.py
- test-requirements.txt
- tox.ini
Fixes issue #1751, where tools with multiple arguments only have the first argument passed to the tool command.
This PR is only for the `b0.69` branch.
> Fix tool argument handling (v0.69)

- agent/tool-scripts/datalog/perf-datalog
Fixes #1811 for the `b0.69` branch.
See also #1814.
> Only emit a warning message on missing debugfs (v0.69)

- agent/util-scripts/gold/test-client-tool-meister/test-53.txt
- agent/util-scripts/gold/test-client-tool-meister/test-56.txt
- agent/util-scripts/gold/test-client-tool-meister/test-57.txt
- agent/util-scripts/gold/test-start-stop-tool-meister/test-51.txt
- agent/util-scripts/gold/test-start-stop-tool-meister/test-52.txt
- agent/util-scripts/pbench-tool-meister-start
- agent/util-scripts/test-bin/ssh
- agent/util-scripts/tool-meister/pbench-tool-meister
- agent/util-scripts/unittests
- lib/pbench/agent/tool_data_sink.py
- lib/pbench/agent/tool_meister.py
Here we replace the `pbench-tool-data-sink` command line interface entirely replacing it with a `fork()` and invocation of the Tool Data Sink library code directly.  We then do the same for the `pbench-tool-meister` command.
In both cases the original commands are copied as-is to the library side of the tree with no modifications.  The new `pbench-tool-meister` command is a very simple trampoline command file required for our SSH tool meister default orchestration.
This demonstrates that neither the Tool Data Sink or the Tool Meister require a CLI interface for their operation as they only need a simple set of arguments passed to them.
> Minimal attempt to remove tool meister commands

- contrib/development/update-gold
When tests fail due to gold files being out of date, the `update-gold` script contributed here makes it easy to pull the newly generated gold file in as the committed gold file for the test.
Note well that one can take in unwanted change with this file, so beware.
> Perhaps useful script for updating gold files

- agent/util-scripts/pbench-sysinfo-dump
This will help us determine what should have been collected, and will allow us to re-run the command to debug any behavioral discrepancies.
> Record the sosreport command that was used

- lib/pbench/server/__init__.py
- lib/pbench/server/api/__init__.py
- lib/pbench/server/indexer.py
- lib/pbench/test/unit/config/pbench-server.cfg
- lib/pbench/test/unit/server/conftest.py
- lib/pbench/test/unit/server/test_requests.py
- server/bin/state/config/pbench-server.cfg
- server/bin/state/test-23.config/pbench-server.cfg
- server/bin/state/test-6.13.config/pbench-server.cfg
- server/bin/state/test-6.14.config/pbench-server.cfg
- server/lib/config/pbench-server-default.cfg
- server/lib/config/pbench-server.cfg.example
This work is an extension of Fuqing's PR https://github.com/distributed-system-analysis/pbench/pull/1726
Description from Original PR:
> Created a two APIs in Pbench server which serves as a middle ware for dashboard Elasticseach and GraphQL calls.
> The server APIs pulls data from Elasticsearch based on the arguments passed in from front end requests.
> And the dashboard will in the future, call server APIs instead to get data instead of making explicit queries.
> Note: elasticsearch and graphql section needs to be specified in pbench-server.cfg with host and port info
> Pbench Server APIs for ES and GraphQL

- lib/pbench/agent/base.py
- lib/pbench/agent/fs.py
- lib/pbench/agent/utils.py
- lib/pbench/cli/agent/__init__.py
- lib/pbench/cli/agent/options.py
- requirements.txt
This branch sets up the base CLI agent bits so we can work on top of it:
- Setup BaseCommand class which is basically the base script that was done in shell script.
- Add setup_logigng method so that we can log errors and communicate with the user.
- Remove unused code
- Use CliContext class to create a click object. We create a click object so we can save the state across different CLI commands.
> Base CLI setup

- agent/util-scripts/pbench-sysinfo-dump
Fixes #1846
Also quote a couple of unquoted instances of ${sos_ver} on the same line for
uniformity's sake.
> Add missing quote

- .gitignore
- tox.ini
When running tests, stop creating the `AUTHORS` and `ChangeLog` files.  See https://docs.openstack.org/pbr/latest/user/packagers.html#versioning.
> Tell pbr to stop creating AUTHORS & ChangeLog

- agent/util-scripts/pbench-sysinfo-dump
The fixes to pbench-sysinfo-dump in PR #1819 introduced a problem where the command line options were not properly spaced from each other, causing the sosreport command to fail.
See also issue #1846 and PR #1848.
> Fix generation of sosreport command

- server/bin/gold/test-24.txt
- server/bin/gold/test-8.txt
Not sure exactly why, but it appears the previous commit, the server RPM work, changes things so that these two tests now fail.
> Test fixes required from previous commit

- server/bin/test-bin/test-find-behavior
The unit test was creating `*.lis` files in the current directory where the unit tests were invoked.  So any aother `*.lis` file in that directory would then influence the test results.  Moved to the specific test environment's `tmp` directory instead.
> Prevent server unit test `test-25` from failing

- agent/bench-scripts/unittests
- agent/tool-scripts/datalog/unittests
- agent/tool-scripts/postprocess/unittests
- agent/tool-scripts/unittests
- agent/util-scripts/unittests
- server/bin/unittests
Upcoming work to convert our infrastructure to Python3 will be leveraging python modules which require the `C.UTF-8` locale.
To ensure that such a switch does not affect the existing code, we make that change here in isolation to prove that out.
> Switch legacy unit tests to use C.UTF-8 locale

- agent/util-scripts/gold/pbench-cleanup/test-64.txt
- agent/util-scripts/gold/pbench-clear-results/test-63.txt
- agent/util-scripts/pbench-cleanup
- agent/util-scripts/pbench-clear-results
- agent/util-scripts/samples/pbench-cleanup/test-64
- agent/util-scripts/samples/pbench-clear-results/test-63/pbench/tools-v1-default/testhost.example.com/mpstat
- agent/util-scripts/unittests
Add a deprecation warning when `pbench-cleanup` is invoked, and change it to just invoke `pbench-clear-results`.  We then add two tests to verify their behavior.
Finally, we change `pbench-clear-results` to explicitly move the generated directory paths instead of relying on a wild-card (dangerous!).
> Deprecate pbench-cleanup & add tests for clear-results

- server/Makefile
- server/ansible/roles/pbench-server-install-config-file/tasks/main.yml
- server/rpm/pbench-server.spec.j2
- The server Makefile installs setup.py, setup.cfg and requirements.txt.
- The spec file includes the above.
- The ansible pbench-server-install-config-file role was missing a
a `become=no` in the `delete local temp dir' task.
- The ansible pbench-server-systemd-service-role does not distinguish
between centos/rhel-7 and everything else: everybody does the same
thing.
> Fixes for server installation failures: RPM and ansible

- server/bin/gold/test-13.txt
- server/bin/gold/test-15.txt
- server/bin/gold/test-2.txt
- server/bin/gold/test-3.txt
- server/bin/gold/test-4.txt
- server/bin/gold/test-5.1.txt
- server/bin/gold/test-5.2.txt
- server/bin/gold/test-5.txt
- server/bin/pbench-server-prep-shim-002.py
Fixes #1877
* logs error in new-style
* instead of using an external errorfile used logger.error
> Resolves logging error in pbench-server-prep-shim

- server/rpm/pbench-server.spec.j2
- We need to create the %{installdir} before copying  ./server/* to it.
- We move the package.json file from %{installdir}/html/static to
%{installdir}/, so we need to get rid of the former in the %files
list.
> Fix breakage

- agent/bench-scripts/test-bin/mock-cmd
- agent/util-scripts/gold/test-client-tool-meister/test-53.txt
- agent/util-scripts/gold/test-client-tool-meister/test-56.txt
- agent/util-scripts/gold/test-client-tool-meister/test-57.txt
- lib/pbench/agent/tool_meister.py
Given that `screen` has grown a little "long in the tooth", and that for RHEL 7 the version of `screen` is so old that it does not contain a fix for a race condition on its socket directory creation, it seems the best course of action is to remove the use of it from the Tool Meister code.
This might mean that certain tools that require a pseudo terminal will stop working, but solving that problem instead of fixing `screen` seems to be more approachable.
> Remove use of `screen` from Tool Meister

- agent/ansible/pbench/agent/roles/pbench_repo_install/defaults/main.yml
- agent/ansible/pbench/agent/roles/pbench_repo_install/templates/etc/yum.repos.d/pbench.repo.j2
- agent/containers/images/Dockerfile.base.j2
- agent/containers/images/Dockerfile.layered.j2
- agent/containers/images/Makefile
- agent/containers/images/repo.yml.j2
We tackle three things with this commit.  This first is that we don't explicitly install `rh-python36`, we simply allow the `pbench-agent` RPM dependencies to drive that installation.
The second change is to make sure we build the name of the user for the COPR repo into the repo name to help debug where RPMs were pulled from at build time.
The last change is to ensure the proper package manager's cache (yum vs dnf) is removed depending on the distribution used.
> Enhance agent container builds

- agent/containers/images/Dockerfile.base.j2
- agent/containers/images/Dockerfile.layered.j2
- agent/containers/images/Makefile
- agent/containers/images/README.md
- agent/containers/images/gen-tags-from-rpm
- agent/containers/images/push
- agent/containers/images/repo.yml.j2
There have been a number of enhancements to how we build containers that need to be available for building the `b0.69` branch.  We were successful using these changes to build the `v0.69.4-agent` release using them.
We had to remove the `atomic-openshift-clients` RPM dependency from the "tool" image since that repo is really per OpenShift version.
> Backport container build enhancements to `b0.69`

- server/requirements.txt
Let's see whether simply explicitly requiring pyesbulk 1.0.0 helps Travis.
The `pyesbulk 2.0.1` module attempts to dynamically determine and import the module used by its caller to create the `Elasticsearch` object parameter. This mechanism fails on the Pbench unit test mock object as it's not in a normal PyPi style module packaging format. The `pyesbulk` fallback is to import the latest `elasticsearch` version; which will work fine with Pbench once we've upgraded to use Elasticsearch V7 but doesn't work for the current `master` branch or `0.71` as we import `elasticsearch1`.
There's no foolproof way to resolve this in `pyesbulk`. It could attempt to import `elasticsearch` and then try `elasticsearch1` if that failed (or vice versa). However it's quite possible to have both …
> Require pyesbulk 1.0.0 for Pbench 0.71

- agent/tool-scripts/datalog/prometheus-metrics-datalog
+ ./prometheus-metrics-datalog:108: SyntaxWarning: "is" with a literal. Did you mean "=="?
+   if pid is 0:
> Fix warning while running unit tests

- agent/test-requirements.txt
- lib/pbench/test/functional/conftest.py
- lib/pbench/test/functional/test_pbench_config.py
- server/test-requirements.txt
Use pytest helpers to create a reproducable envrionment
that we do with the shell scripts. Eventually, this
will replace the shell scripts and the gold files
that we *shudder* use.
> Rejig functional unit tests

- pyproject.toml
- tox.ini
The first item is we now use `/tmp/${USER}/tox` as the working directory (`{toxworkdir}`) to avoid touching the local source tree.  Along with this change, we also tell `black` to store its cache in the `lint` environment via the `XDG_CACHE_HOME` environment variable.
Further, we pass along the `PY_COLORS`, `NO_COLORS`, and `TERM` environment variables so that `tox` runs are well behaved in non-interactive terminal environments.
Still further, we remove the `envars` section, moving those into the proper `setenv` section.
Finally, we address some indentation issues in `tox.ini` itself in a separate commit.
> Address some undesirable tox behaviors

- agent/base
- agent/base.ut.post
- agent/base.ut.pre
- agent/bench-scripts/pbench-iozone
- agent/bench-scripts/unittests
- agent/util-scripts/gold/pbench-copy-results/test-31.txt
- agent/util-scripts/gold/pbench-copy-results/test-39.txt
- agent/util-scripts/gold/pbench-copy-results/test-40.txt
- agent/util-scripts/gold/pbench-copy-results/test-41.txt
- agent/util-scripts/gold/pbench-copy-results/test-49.txt
- agent/util-scripts/pbench-collect-sysinfo
- agent/util-scripts/pbench-metadata-log
- agent/util-scripts/pbench-move-results
- agent/util-scripts/pbench-register-tool
- agent/util-scripts/pbench-register-tool-set
- agent/util-scripts/pbench-sysinfo-dump
- agent/util-scripts/pbench-tool-meister-start
- agent/util-scripts/pbench-tool-meister-stop
- agent/util-scripts/test-bin/test-client-tool-meister
- agent/util-scripts/test-bin/test-start-stop-tool-meister
- agent/util-scripts/unittests
- lib/pbench/agent/tool_data_sink.py
- lib/pbench/cli/agent/commands/results/__init__.py
- lib/pbench/test/unit/agent/task/test_move_results.py
Instead of accepting `hostname` and `full_hostname` as pre-defined environment variables, we rename them to be `_pbench_hostname` (contains `$(hostname -s)`) and `_pbench_full_hostname` (contains `$(hostname -f)`).  This prevents an inadvertent environment variables of the same name from changing the behavior of the agent.
We also consistently use those environment variables where possible to avoid disagreements on the host name used.
Some of the Python 3 code changed, and so `flake8` detected a problem.  Why it wasn't detected before is a mystery, but we fix it here as well.
We also take the opportunity, in separate commits, to stop embedding unit test logic in `agent/base`, and make sure we explicitly ask for the full hostname using `hostname -f`.
> Use `_pbench_` prefixed env var for host names

- lib/pbench/cli/agent/commands/results/__init__.py
- lib/pbench/test/unit/agent/task/test_move_results.py
This PR is dependent on PR #1946.  The first 3 commits are from that PR.
> Fix agent side `test_move_results`

- lib/pbench/server/api/__init__.py
- lib/pbench/test/unit/server/conftest.py
- lib/pbench/test/unit/server/test_requests.py
- server/test-requirements.txt
This all started because logging was not quite set up correctly for the server side API tests.  We use the `caplog` fixture to figure out what is being logged and then added `file` based logging by default so that logs would not leak through to the local system logs via the default `devlog` server configuration during a test run.
In getting the tests to work, we adjust how exceptions are handled so that emitted messages are not so broad.  We use 5xx status codes properly and quiet the logging where possible.
When an internal error is hit, we only report "INTERNAL ERROR" in the response, but log the details.
> Rework pass-thru API implementation a bit

- server/bin/gold/test-5.2.txt
- server/bin/pbench-server-prep-shim-002.sh
Commit c3ad67c101e394784924f14c5bfceb8d239b636f changed the way we get the tarball from the reception area to the archive, from `cp` to `mv` in order to avoid a data copy. But `cp` set the SELinux context from the parent directory, which made the tar ball accessible through HTTP; `mv` does not do that.
Add an explicit `restorecon` to remedy that and fix test-5.2 for the new output.
> Restore the SELinux context of the tarball after the move

- agent/rpm/pbench-agent.spec.j2
- agent/rpm/python-module-mapping.table
- jenkins/Makefile
- jenkins/development.Dockerfile
The Python 3 `colorlog` module was removed with commit 3a851f84, but we failed to remove it from the `pbench-agent` RPM requires list, or from the recently added `pbench-devel` container image.
While we are at it, we added a simple Makefile for building the `pbench-devel` container image and pushing it to Quay.io.
> Remove colorlog; add Makefile for pbench-devel

- agent/rpm/pbench-agent.spec.j2
- jenkins/development.Dockerfile
The `pbench-uperf` bench-script invokes `netstat`, so we need to provide a requirement on the `net-tools` RPM in order to be sure that command is available.
While we are at it, we also add it to the development image used by the Jenkins CI, just in case.
> Add missing `net-tools` req agent RPM

- jenkins/python-setup.sh
- jenkins/run-pytests
- jenkins/run-unittests
We need to add the `lib/python3.*` and `lib64/python3.*` paths.
> Correct the `PYTHONPATH` for Jenkins jobs

- server/ansible/roles/pbench-server-activate-httpd-setup-restart/tasks/main.yml
- server/ansible/roles/pbench-server-firewall/tasks/main.yml
- server/rpm/pbench-server.spec.j2
When I simplified the spec file back in June, I went a bit too far
and lost the js files that we need for visualization. Some of these have
been added back: the rest are needed for the (very) old web-server version
only.
The firewall role added http and https services to the "permanent" setup
but neglected to reload the rules, so they were not valid for the current
boot (although they would work fine after a reboot :-) ).
The pbench-tarballs link from /var/www/html to the archive was not created
by the playbook (it was added manually to the production server). It is
now added by the playbook.
> Fix spec file and ansible roles

- agent/ansible/pbench/agent/roles/pbench_agent_config/README.md
- agent/ansible/pbench/agent/roles/pbench_agent_config/defaults/main.yml
- agent/ansible/pbench/agent/roles/pbench_agent_config/tasks/main.yml
- agent/ansible/pbench/agent/roles/pbench_agent_files_install/tasks/main.yml
The pbench agent currently runs as root, and we don't really have the notion of
separate user for the agent ... yet.
> Remove the pbench user and group from the agent

- agent/bench-scripts/pbench-user-benchmark
- agent/profile
- jenkins/python-setup.sh
When using the `bash` `for <var> in $(ls -1d ...); do` expressions, the shell will assign the variable values not only split by new-lines, but also by spaces.  So if a file name or directory in the path has a space in the name, the `ls -1d` output will not be interpreted correctly.
See also PR #1975.
> Harden against spaces in file names

- agent/config/pbench-agent-default.cfg
- agent/util-scripts/gold/pbench-agent-config-activate/test-14.txt
- agent/util-scripts/pbench-agent-config-ssh-key
- agent/util-scripts/samples/pbench-agent-config-activate/test-14/pbench/tmp/pbench-agent.cfg
- lib/pbench/cli/agent/commands/results/__init__.py
The pbench-agent does not really use a user and group. As described in PR #1997, the agent is really only runnable as `root` today.
> Finish to remove agent user/group

- agent/util-scripts/gold/test-client-tool-meister/test-53.txt
- agent/util-scripts/gold/test-client-tool-meister/test-56.txt
- agent/util-scripts/gold/test-client-tool-meister/test-57.txt
- agent/util-scripts/gold/test-start-stop-tool-meister/test-51.txt
- agent/util-scripts/gold/test-start-stop-tool-meister/test-52.txt
- agent/util-scripts/pbench-tool-meister-start
- agent/util-scripts/test-bin/test-client-tool-meister
- agent/util-scripts/test-bin/test-start-stop-tool-meister
- lib/pbench/agent/tool_data_sink.py
We add support for a caller to override the bind host name used by the Redis Server and Tool Data Sink using the `PBENCH_TM_BIND_HOSTNAME` environment variable.
We also ensure the list of hostnames used by the Redis Server do not map to the same IP address.
> Add support for overriding TM bind hostname

- agent/util-scripts/gold/test-client-tool-meister/test-56.txt
- agent/util-scripts/gold/test-client-tool-meister/test-57.txt
- agent/util-scripts/pbench-tool-meister-start
We have been using `ssh_opts` everywhere except when using `ssh` to start the Tool Meisters remotely.
> Use `ssh_opts` when starting remote tool meisters

- lib/pbench/cli/server/shell.py
- lib/pbench/server/__init__.py
- lib/pbench/server/api/__init__.py
- lib/pbench/server/api/resources/graphql_api.py
- lib/pbench/server/api/resources/query_apis/__init__.py
- lib/pbench/server/api/resources/query_apis/elasticsearch_api.py
- lib/pbench/server/api/resources/query_apis/query_controllers.py
- lib/pbench/server/api/resources/upload_api.py
- lib/pbench/test/unit/server/conftest.py
- lib/pbench/test/unit/server/test_query_controller.py
- lib/pbench/test/unit/server/test_requests.py
- server/requirements.txt
This PR attempts to refactor some of the server API implementations
- Remove global variable `app` 
- Keep `create_app` functionality clean and high level.
- Modularize the API implementations
- Create Separate api module for upload, elasticsearch and graphql
- Remove custom implementation of CORS 
- Use `flask_cors` module to add  CORS decorator
- Use the loaded PbenchServerConfig object instead of reassigning them to app.config
> Refactor server API implementation

- server/ansible/roles/pbench-server-activate-create-results-dir-structure/tasks/main.yml
We need to use `semanage` to set the correct labels on the top level
pbench directory and its children: most of them get `default_t` but
`archive` and `public_html` and their children get `httpd_sys_content_t`.
The sefcontext ansible module is needed for this: it's available from
Galaxy:
ansible-galaxy collection install community.general
The rest of the tasks create the directory structure (I deleted the
setype: setting since it does not survive a restorecon - I now assume
that it is just doing the equivalent of a chcon). At the end we run a
recursive restorecon to set the labels on everything.
> Fix SELinux labels on the pbench directory structure

- server/rpm/pbench-server.spec.j2
The reorganized API resource files need to be represented properly in the RPM spec file.
There are several flake8/black violations elsewhere that somehow got past presubmit checks that I needed to fix to get this in; I know Pete has already fixed at least one of them.
> Fix server spec file

- lib/pbench/cli/server/shell.py
There was bug introduced with an extra parenthesis in shell script when starting the gunicorn app which @dbutenhof noticed when testing
> Fix extra trailing parenthesis when gunicorn app starts

- agent/util-scripts/gold/test-client-tool-meister/test-53.txt
- agent/util-scripts/gold/test-client-tool-meister/test-56.txt
- agent/util-scripts/gold/test-client-tool-meister/test-57.txt
- agent/util-scripts/gold/test-start-stop-tool-meister/test-51.txt
- agent/util-scripts/gold/test-start-stop-tool-meister/test-52.txt
- agent/util-scripts/pbench-tool-meister-start
- agent/util-scripts/test-bin/ssh
- agent/util-scripts/unittests
- lib/pbench/agent/tool_data_sink.py
- lib/pbench/agent/tool_meister.py
The debug-ability of the Tool Meisters running remotely is very difficult without a way to properly capture log output from them.  We take three major steps to address this.
The first step is to not use a Python logger until we will (or would have otherwise) daemonized the process.  This allows us to emit error messages on stderr, which will be exposed in the callers context.  Once we are daemonized, `stdout` and `stderr` are detached from the caller, so logging to some place other than `stdout`/`stderr` is the best option from that point forward.
The second step is to recognize that logging to a file on a remote host is useless unless the operator can get a hold of that log file. However, remote Tool Meisters use a temporary directory, so writing to a file will just be lost when the …
> Fix logging for Tool Meisters

- lib/pbench/agent/tool_meister.py
PR #2014 introduced a bug with a bad reference to the `SysLogHandler`.
> Fix SysLogHandler reference

- lib/pbench/agent/results.py
- lib/pbench/test/unit/agent/conftest.py
- lib/pbench/test/unit/server/conftest.py
The Python 3 based "move-results" code was using the old `configtools` module instead of just using `ConfigParser` directly.  This would end up causing failures in the unit tests because it was calling the `parse_args` method of `configtools` to first parse the command line arguments.  But in principle, we never want to access the command line arguments while running unit tests.  The unit test should provide them for the method under test to properly ensure the correct behavior is tested.
We simply replace the use of `configtools` with `ConfigParser` directly, which ends up simplifying the code as well.
Further, using configtools just for the result directory `metadata.log` is over kill, because `configtools` was there to support multiple configuration files, and there is only one …
> Fix py move-results to use `ConfigParser`

- lib/pbench/server/s3backup/__init__.py
Fix #2034
Commit 8a4417838959ec17d234eff887540dc461386cb2 broke the function
calculate_multipart_etag(): it replaced a (working) while-loop that
was reading the tarball in chunks with a broken for-loop which read
one chunk of the file and then iterated over the bytes of that chunk.
We retain the for-loop but fix the iterator to give us back the next
chunk each time.
> Fix bug when reading a file in chunks

- lib/pbench/test/functional/agent/cli/commands/tools/test_clear_tools.py
Convert pbench-clear-tools to python3 unit tests.
> Add unit tests for pbench-clear-tools

- lib/pbench/server/api/__init__.py
- lib/pbench/server/api/resources/graphql_api.py
- lib/pbench/server/api/resources/query_apis/elasticsearch_api.py
- lib/pbench/server/api/resources/query_apis/query_controllers.py
- lib/pbench/server/api/resources/query_apis/query_month_indices.py
- lib/pbench/test/unit/server/test_query_controller.py
- lib/pbench/test/unit/server/test_query_month_indices.py
In experimentation with a dashboard on my live server, I found that the current use of `@cross_origin` isn't actually working; I suspect this is because documentation suggests it needs to follow `@app.route(...)`, which we don't use.
Instead, change to a global CORS configuration triggered by wrapping the `app` object in a `CORS` object. This demonstrably works, and should keep us out of trouble for a while. (Note that, ideally, we want to set up Apache `mod_wsgi` to allow redirecting the default http and eventually https port to our app for `/api...` paths, which would mean our dashboard wouldn't need CORS -- very good from a security point of view -- though we may still want some sort of CORS support to allow integration of our server with other browser apps that might not be able to …
> CORS fixes and a new API

- server/ansible/roles/pbench-server-add-commit-id/tasks/main.yml
Fixes #2043
The "commit_id" field is supposed to have the form:
```
<version>-<seqno>g<sha1>
```
but was missing the "g".
> Add missing "g" to commit id field in the server config file

- server/ansible/roles/pbench-server-add-commit-id/tasks/main.yml
Fixes #2043
The "commit_id" field is supposed to have the form:
```
<version>-<seqno>g<sha1>
```
but was missing the "g".
This is a forward port of PR #2044.
> Add missing "g" to commit id field in the server config file (forward port of PR#2044)

- agent/util-scripts/gold/pbench-copy-results/test-31.txt
- agent/util-scripts/gold/pbench-copy-results/test-39.txt
- agent/util-scripts/gold/pbench-copy-results/test-40.txt
- agent/util-scripts/gold/pbench-copy-results/test-41.txt
- agent/util-scripts/gold/pbench-copy-results/test-49.txt
- agent/util-scripts/gold/pbench-move-results/test-33.txt
- agent/util-scripts/pbench-copy-result-tb
- agent/util-scripts/pbench-move-results
See https://www.vidarholen.net/contents/blog/?p=632 for a great write-up on the gory details.  Basically, you can't issue an `ssh` in a while loop that reads from `stdin`, one must instruct `ssh` to use `/dev/null`.
Backported from PR #2046.
> Fix move results ssh loop (b0.69)

- agent/util-scripts/gold/pbench-copy-results/test-31.txt
- agent/util-scripts/gold/pbench-copy-results/test-34.txt
- agent/util-scripts/gold/pbench-copy-results/test-37.txt
- agent/util-scripts/gold/pbench-copy-results/test-38.txt
- agent/util-scripts/gold/pbench-copy-results/test-39.txt
- agent/util-scripts/gold/pbench-copy-results/test-40.txt
- agent/util-scripts/gold/pbench-copy-results/test-41.txt
- agent/util-scripts/gold/pbench-copy-results/test-49.txt
- agent/util-scripts/gold/pbench-move-results/test-33.txt
- agent/util-scripts/pbench-copy-result-tb
- agent/util-scripts/pbench-move-results
See https://www.vidarholen.net/contents/blog/?p=632 for a great write-up on the gory details.  Basically, you can't issue an `ssh` in a while loop that reads from `stdin`, one must instruct `ssh` to use `/dev/null`.
> Fix move results ssh loop

- agent/containers/images/Dockerfile.base.j2
- agent/containers/images/Dockerfile.layered.j2
- agent/containers/images/Makefile
- agent/containers/images/README.md
We also address the locale issues in CentOS 8 containers.
> Drop Fedora 31 RPMs/containers, add support for Fedora 33 RPMs/containers

- agent/containers/images/Dockerfile.base.j2
- agent/containers/images/Dockerfile.layered.j2
- agent/containers/images/Makefile
- agent/containers/images/README.md
- agent/containers/images/repo.yml.j2
- agent/containers/images/verify-tags
This is a back port of commits that are in PR #2059 for the `b0.69` branch.
We enable support for Fedora 33 container builds, and fixes for `locale` issues on CentOS 8, along with the apparent rename of the `powertools` repo (used to be `PowerTools`).
> Backport f33 centos8 cont fixes

- server/bin/gold/test-7.0.1.txt
- server/lib/mappings/result-data-sample.json
- server/lib/mappings/result-data.json
These changes to the document templates allow dashboard queries to sort or aggregate on these fields. One field changes from `"text"` to `"keyword"` (because there seems to be unlikely to be any value to `@timestamp_original` in full text search), whereas another uses the Elasticsearch ability to double-map a field as both `"text"` and `"keyword"` so that the description string could be hit by a full text search and can also be used for sorting.
I've re-indexed my test tarballs with these changes and verified that my modified dashboard code works now.
> Modifications to template data types for dashboard

- contrib/analysis/generate-pbench-timeseries-graphs
Don't require use of --tarfile to specify tarfiles.  --tarfile is still useful if there's a tarfile that doesn't have a canonical name.
> Treat files with suffix .tgz, .tar, or .tar.<something> as tarfiles

- contrib/analysis/generate-pbench-timeseries-graphs
Variable named 'l' is discouraged since it's easily confused with '1'.
> Fix flake8 issue with variable name

- lib/pbench/cli/server/shell.py
- server/ansible/roles/pbench-server-activate-httpd-setup-restart/tasks/main.yml
- server/ansible/roles/pbench-server-activate-httpd-setup-restart/tasks/templates/etc/httpd/conf.d/pbench.conf.j2
- server/ansible/roles/pbench-server-vars/tasks/main.yml
- server/lib/config/pbench-server-default.cfg
- server/lib/config/pbench-server.cfg.example
The Pbench server API listens on port 8001; we want to be able to access the API externally through normal HTTP/HTTPS.
With an external reverse proxy gateway (e.g., NGINX) this can be accomplished by redirecting (e.g.) `pbench.example.com:/api/` to the actual server at port 8001 and opening the 8001/tcp port in the server firewall.
Our default Ansible deployment mechanism configures a local Apache which is directly accessed from outside. This PR adds an Apache reverse proxy to allow external API access on port 80.
With these changes, the Pbench gunicorn wsgi server will still listen on port 8001, but this port won't need to be opened externally as Apache will proxy `/api/` to port 8001. This means that all external accesses will go to port 80 (http) or (when we get there) 433 (https).
In …
> Add API reverse proxy configuration to default Ansible Pbench deployment scripts

- agent/bench-scripts/pbench-fio
- agent/bench-scripts/tests/pbench-fio/test-14.txt
- agent/bench-scripts/tests/pbench-fio/test-17.txt
- agent/bench-scripts/tests/pbench-fio/test-18.txt
- agent/bench-scripts/tests/pbench-fio/test-21.txt
- agent/bench-scripts/tests/pbench-fio/test-26.txt
- agent/bench-scripts/tests/pbench-fio/test-27.txt
- agent/bench-scripts/tests/pbench-fio/test-29.txt
- agent/bench-scripts/tests/test-benchmark-clis/test-CL.txt
- docs/guides/UserGuide.rst
the --unique-ports option.  It's also possible to specify <client>:<port>
if it's necessary to support specific ports.  This is needed for
conveniently supporting multiple pods with OpenShift.
> Allow specifying different ports for each client instance by means of

- server/lib/systemd/pbench-server.service
- Run pbench-server service as a pbench user
- Remove some `ExecStartPre` commands and use `RuntimeDirectory` to create a sub-directory inside `/run` for storing gunicorn pid
> Run pbench-server systemd service as a pbench user

- lib/pbench/server/api/resources/query_apis/query_controllers.py
The `parser.parse()` function will return a `datetime` object, filling in any missing date components missing from the input string. This means that when you call `parser.parse()` on the 29th, 30th, or 31st of a month, and you range spans months which do not have those dates, then those months are omitted.
The simple fix is to force the day to be the 1st, avoiding this problem.
Fixes #2084.
> Fix use of date parsing in query API

- .coveragerc
- docs/requirements.txt
- jenkins/branch.name
- jenkins/development.Dockerfile
- jenkins/python-setup.sh
- lint-requirements.txt
- tox.ini
In order for the Jenkins jobs to run correctly, we need to ensure that the `pbench` python3 module is installed, including the CLI binaries that need to be on the `PATH`.
We correct the version of `flake8` to be the one available in Fedora 32 (`3.7.7`), and add the missing RPMs to the development container to avoid unnecessary pip3 installs.  We also create a separate `docs/requirements.txt` file.
Finally, we update the branch name file to properly reference `main` so that we use the right image tag the development container.
> Ensure pbench develop install occurs for tests

- agent/tool-scripts/base-tool
- agent/tool-scripts/tests/blktrace/gold/test-execution.log
- agent/tool-scripts/tests/cpuacct/gold/test-execution.log
- agent/tool-scripts/tests/disk/gold/test-execution.log
- agent/tool-scripts/tests/docker/gold/test-execution.log
- agent/tool-scripts/tests/haproxy-ocp/gold/test-execution.log
- agent/tool-scripts/tests/iostat/gold/test-execution.log
- agent/tool-scripts/tests/jmap/gold/test-execution.log
- agent/tool-scripts/tests/jstack/gold/test-execution.log
- agent/tool-scripts/tests/kvm-spinlock/gold/test-execution.log
- agent/tool-scripts/tests/kvmstat/gold/test-execution.log
- agent/tool-scripts/tests/kvmtrace/gold/test-execution.log
- agent/tool-scripts/tests/mpstat/gold/test-execution.log
- agent/tool-scripts/tests/numastat/gold/test-execution.log
- agent/tool-scripts/tests/openvswitch/gold/test-execution.log
- agent/tool-scripts/tests/perf/gold/test-execution.log
- agent/tool-scripts/tests/pidstat/gold/test-execution.log
- agent/tool-scripts/tests/proc-interrupts/gold/test-execution.log
- agent/tool-scripts/tests/proc-sched_debug/gold/test-execution.log
- agent/tool-scripts/tests/proc-vmstat/gold/test-execution.log
- agent/tool-scripts/tests/prometheus-metrics/gold/test-execution.log
- agent/tool-scripts/tests/qemu-migrate/gold/test-execution.log
- agent/tool-scripts/tests/rabbit/gold/test-execution.log
- agent/tool-scripts/tests/sar/gold/test-execution.log
- agent/tool-scripts/tests/sysfs/gold/test-execution.log
- agent/tool-scripts/tests/user-tool/gold/tools-group/user-tool-foo42/user-tool-foo42-postprocess.out
- agent/tool-scripts/tests/user-tool/gold/tools-group/user-tool-foo42/user-tool-foo42-stop-postprocess.out
- agent/tool-scripts/tests/virsh-migrate/gold/test-execution.log
- agent/tool-scripts/tests/vmstat/gold/test-execution.log
Okay, commit f74a4c3b6 tried to fix the termination of the `turbostat` command but failed to miss one critical change: the `safe_kill` call needs the name of the process to be killed.  That previous commit changed the behavior such that the process name is now "turbostat", but we were still looking for "turbostat-datalog".
Along the way, fix `base-tool` to properly handle relative path arguments which facilitate easier manual testing.
See also PR #2041.
> Fix turbostat for real this time

- .coveragerc
Our Python unit tests generate a coverage report, which currently includes all "non-system" packages, including the vast array of site-packages we reference.
Excluding these from the report raises our reported overall code coverage from 14% to 81%... pretty good improvement for
a one line change in a config file! ;-)
> Exclude site-packages from coverage report

- server/ansible/pbench-repo-install.yml
- server/ansible/pbench-server-disable.yml
- server/ansible/pbench-server-enable.yml
- server/ansible/pbench-server-install.yml
- server/ansible/roles/pbench-repo-install/defaults/main.yml
- server/ansible/roles/pbench-server-activate-setup-results-host-info/tasks/main.yml
- server/ansible/roles/pbench-server-crontab-disable/tasks/main.yml
- server/ansible/roles/pbench-server-crontab-enable/tasks/main.yml
- server/ansible/roles/pbench-server-set-state/tasks/main.yml
Currently, when installing the server, we set the `host-info` state to `active`, which allows `pbench-move`/`copy-results` to start sending tar balls to the server.
This PR sets the `host-info` state to `maintenance`.
It also adds playbooks and roles to explicitly enable and disable the server. The workflow now becomes
```
ansible-playbook ... pbench-server-disable.yml
ansible-playbook ... pbench-server-install.yml
ansible-playbook ... pbench-server-enable.yml
```
Unfortunately, the disable role has no easy way to make sure that the queue is drained: it can check the reception area to make sure it's empty, but various cron jobs may still be running processing tar balls (or might run in the next few minutes): it could check all the state directories to make sure they don't contain any tar …
> When installing the server, set the host-info state to maintenance

- jenkins/development.Dockerfile
- server/bin/gold/test-5.2.txt
- server/bin/pbench-server-prep-shim-002.py
- server/bin/test-lib/selinux.py
- server/bin/unittests
- server/rpm/pbench-server.spec.j2
Fixes #1928 
We not only need to preserve the labels but also all the metadata of the tarball.
> Setting SELinux Labels correctly in prep-shim

- server/rpm/pbench-server.spec.j2
Although the Agent spec file efficiently references directories to be packaged hierarchically, the Server spec file has a full list of the individual packaged files. This is unnecessarily awkward to maintain, and error prone.
The challenge here was some experimentation (the documentation is terrible) to figure out the order of precedence across the `%attr `and `%defattr` with directories and contained individual files. I added some comments in the spec file to clarify.
> Streamline server RPM spec file

- lib/pbench/server/indexing_tarballs.py
- server/bin/pbench-index.py
Fixes #2060
Re-evaluate the list of tar balls to index after
indexing of the current tar ball has finished.
Report the current state of indexing
- SIGHUP
- Current tar ball being processed
- How many remaining
- How many have been completed
> Add SIGHUP handler to pbench indexer

- lib/pbench/server/api/resources/query_apis/elasticsearch_api.py
During the discussion with @gurbirkalsi on es queries from dashboard we found a bug in server elasticsearch api endpoint about how we format search url when `ignore_unavailable` key is present in the params of the json data.
If params present in the json data we were formatting it like this 
`"{self.elasticsearch}/{json_data['indices']}?{json_data['params']}"` 
instead it should be
`"{self.elasticsearch}/{json_data['indices']}?ignore_unavailable={json_data['params']['ignore_unavailable']}"`
> Fix es url formation when params exist in json data

- lib/pbench/cli/agent/__init__.py
- lib/pbench/cli/agent/commands/generate_token.py
- lib/pbench/cli/agent/options.py
- lib/pbench/test/unit/agent/task/test_generate_token.py
- setup.cfg
This pull request is a series of commits culminating in the addition of a simple tool which takes a username/password pair and generates a token for use with the pbench server's REST interface.  The targeted use case for the token is to allow Riya's overhaul of the `pbench-move-results` tool to make an authenticated access to the server.
Most of the commits in this pull request are small, point changes to things which I encountered in the process of implementing the new tool:
- Fix docstring typos in `cli/agent/__init__.py` (no functional changes).
- Tweak Click options for agent config command line option, to make it behave more gracefully.
- Tweak the setup option names to replace hyphens with underscores, since my installation was generating warnings.
The new tool accepts a username …
> Add pbench-generate-token tool

- agent/Makefile
This PR is for a pair of small changes to the Agent makefile which prepares the sources for the RPM build.
The Click-based tools are actually wrapper scripts generated from information in the `setup` configuration during the installation.  They are then individually copied to the destination directory.  Rather than promulgating this practice, this PR collects the Click-based tools into a list and then performs a single, bulk copy of the list.
And, this change adds `pbench-generate-token` to the list.
Note, this change also adds indentation to the rules' command lines which are continued from the previous line.  (I'm not a fan of these -- I would prefer to see them combined into a single command -- but I didn't want to make that level of change without a better understanding of why they …
> Update the agent Makefile for pbench-generate-token and other Click-based tools

- lib/pbench/server/api/resources/users_api.py
- lib/pbench/server/database/models/users.py
- lib/pbench/test/unit/server/test_user_auth.py
Right now, if the authorization header is present during the login request (An attempt at creating another login token) we check the generated auth token with the one in the header. This check is redundant since we already check for the `integrityError` on authorization tokens. 
This PR: 
- Removes the redundant auth token check when Authorization header is present during login. 
- Unit test for an attempt at updating the auth_token externally and confirmed that auth_token can not be updated externally.
> Fix minor bug in the login workflow

- lib/pbench/cli/agent/commands/generate_token.py
- lib/pbench/test/unit/agent/task/test_generate_token.py
This pull request consists of a small commit which tries to produce a better diagnostic when the `pbench-generate-token` tool is unable to connect to the pbench server.
The `requests` package `ConnectionError` exception text is not very friendly, so we catch that exception and raise our own exception which provides a nicer message (not quite as nice as I would like, but better than what was there).
Old message:
```
<urllib3.connection.HTTPConnection object at 0x10a661100>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
```
New message:
```
Cannot connect to 'http://pbench.example.com/api/v1/login'
```
Resolves #2150.
> Improve diagnostic for connection error in pbench-generate-token

- agent/test-requirements.txt
- server/test-requirements.txt
Looks like there are problems with the recently released version `2021.3.24`.
> Fix pytest-helpers-namespace at 2019.1.8

- jenkins/development.Dockerfile
This PR modifies the Dockerfile for the `pbench-devel` container to add a couple of missing dependencies required to build RPMs for the agent and server.
> Add dependencies to pbench-devel required to build RPMs

- lib/pbench/server/api/auth.py
- lib/pbench/server/api/resources/users_api.py
- lib/pbench/test/unit/server/test_user_auth.py
Fixes logout workflow as mentioned in the issue https://github.com/distributed-system-analysis/pbench/issues/2130
Right now the logout workflow returns `401` if an invalid `Authorization` token is presented in a request, however, in order to make logout smooth for the user and not being picky about logging out is less prone to security issues. We almost always want to return success on logout if the token is expired or is already removed from our database and no longer tracked.
> Fix logout response workflow

- lib/pbench/server/api/resources/users_api.py
- lib/pbench/test/unit/server/test_user_auth.py
Fixes issue https://github.com/distributed-system-analysis/pbench/issues/2148
We should return 401, whether it is bad username or password in the user login.
> Return same status code for bad username and bad password

- agent/base
- agent/bench-scripts/unittests
- agent/util-scripts/gold/pbench-move-results/test-22.txt
- agent/util-scripts/gold/pbench-register-tool/test-01.txt
- agent/util-scripts/gold/test-client-tool-meister/test-56.txt
- agent/util-scripts/gold/test-client-tool-meister/test-57.txt
- agent/util-scripts/pbench-move-results
- agent/util-scripts/pbench-register-tool
- agent/util-scripts/test-bin/test-client-tool-meister
- agent/util-scripts/unittests
- agent/util-scripts/validate-hostname
- agent/util-scripts/validate-ipaddress
- lib/pbench/agent/utils.py
- lib/pbench/test/unit/agent/test_validate_hostname.py
From issue #2201, it became apparent that we weren't validating hostnames, which led to weird, but valid, directory names for
controllers being created on the server.  One way this occurs is when the `_pbench_hostname` and or `_pbench_full_hostname` environment variables are defined with invalid values.
We add the new commands `validate-hostname` and `validate-ipaddress` to ensure the definition of those names are correct.
In the process of doing that, we found that we were using invalid host names in two of our unit tests.
----
Derived from PR #2181.
> Add hostname and IP address validation for env

- agent/Makefile
PR #2207 failed to add the `validate-*` scripts it added to the RPM build process.
> Add missing validate-* scripts

- lib/pbench/cli/server/__init__.py
- lib/pbench/cli/server/options.py
- lib/pbench/cli/server/user_create.py
- lib/pbench/test/unit/server/test_user_create.py
- server/Makefile
- setup.cfg
Addresses `create_user` from issue https://github.com/distributed-system-analysis/pbench/issues/2183
This PR lets us create pbench user from command line. 
The `pbench_create_user` tool accepts a username, password, email, first_name, last_name as a required parameters. These can be specified on the command line. However, if any of the parameter is not specified on the command line, the tool will prompt for them. The response to the password prompt is not echoed. The tool also optionally accept `--exist-ok` option, and if specified it will ignore the error if the user already exists and return success.
> Add pbench create user CLI

- lib/pbench/cli/server/user_create.py
- lib/pbench/server/database/models/users.py
- lib/pbench/test/unit/server/test_user_create.py
- Adds an optional role column to the user table in order to distinguish certain users as admins. 
- role column takes a string value indicating the type of user, for example it can be set as `administrator` to indicate the admin user.
- role can only be set via CLI and option is not available via REST API
> Add role column in user table

- agent/bench-scripts/pbench-fio
- agent/bench-scripts/tests/pbench-fio/test-03.opts
- agent/bench-scripts/tests/pbench-fio/test-03.txt
- agent/bench-scripts/tests/pbench-fio/test-14.txt
- agent/bench-scripts/tests/pbench-fio/test-17.txt
- agent/bench-scripts/tests/pbench-fio/test-18.txt
- agent/bench-scripts/tests/pbench-fio/test-21.txt
- agent/bench-scripts/tests/pbench-fio/test-26.txt
- agent/bench-scripts/tests/pbench-fio/test-27.txt
- agent/bench-scripts/tests/pbench-fio/test-29.txt
- agent/bench-scripts/tests/test-benchmark-clis/test-CL.txt
Now that we have tools only registered on the local host, `pbench-fio` cannot validate the tool group on remote hosts when it has been given the `--install` parameter.
We also remove `--install` from `pbench-fio` usage text since it is really an internal interface.
> Don't validate params for `pbench-fio` install

- jenkins/run
We need to use the `podman` option `--pull=always` to ensure we properly fetch the updated `pbench-devel` image when running our CI jobs.
The default behavior is `missing`, which means only pull the image from the repository if it is not found on the local host.
> Ensure we always pull jenkins devel images

- .coveragerc
We tell `coverage` to explicitly check all modules in the `lib/pbench` tree only.  Since we can only measure code coverage when using `pytest`, anyways, we won't see any measurements of modules outside of the `lib/pbench` tree that we care about, so using this option is a simple way to make sure we have a clean data set that considers all of our measurable code.
This change ensures that all of the modules under `lib/pbench` are considered when generating coverage reports, instead of only those modules that were touched by tests.
> Only measure coverage in `lib/pbench`

- agent/util-scripts/pbench-tool-meister-client
- agent/util-scripts/pbench-tool-meister-start
- agent/util-scripts/pbench-tool-meister-stop
- agent/util-scripts/test-bin/test-client-tool-meister
- agent/util-scripts/test-bin/test-start-stop-tool-meister
- lib/pbench/agent/utils.py
- lib/pbench/test/unit/agent/test_utils.py
When we implemented PR #2181, we failed to properly test for the bind/connect style of specification in our tests, and missed the fact that we didn't update `pbench-tool-meister-client` and `pbench-tool-meister-stop` to share the same code as is used by `pbench-tool-meister-start`.
There were 5 initial commits in this PR which should were squashed to one once they were reviewed:
1. Refactor to share a `BaseReturnCode` class in `agent/utils.py`
2. Refactor the `BaseServer` class into the `agent/utils.py` module
3. Add tests that demonstrate things break
4. Fix `pbench-tool-meister-stop`
5. Fix `pbench-tool-meister-client`
This refactoring made it easier to see the progression of changes, facilitating a hopefully easier review.
The final review comment follows below.
----
Prior to this …
> Fix use of `PBENCH_REDIS_SERVER` by both `pbench-tool-meister-client` and `-stop`

- lib/pbench/server/api/resources/endpoint_configure.py
- lib/pbench/server/api/resources/query_apis/__init__.py
- lib/pbench/server/api/resources/query_apis/controllers_list.py
- lib/pbench/server/api/resources/query_apis/datasets_detail.py
- lib/pbench/server/api/resources/query_apis/datasets_list.py
- lib/pbench/server/api/resources/query_apis/elasticsearch_api.py
- lib/pbench/server/api/resources/query_apis/month_indices.py
- lib/pbench/test/unit/server/conftest.py
- lib/pbench/test/unit/server/test_controllers_list.py
- lib/pbench/test/unit/server/test_datasets_detail.py
- lib/pbench/test/unit/server/test_datasets_list.py
- lib/pbench/test/unit/server/test_endpoint_configure.py
- lib/pbench/test/unit/server/test_month_indices.py
- lib/pbench/test/unit/server/test_requests.py
- lib/pbench/test/unit/server/test_schema.py
- server/test-requirements.txt
This change unifies all of our Elasticsearch queries, including the client passthrough, under a class hierarchy that allows factoring
most of the boilerplate into a common superclass.
Getting fancy, I've also built in a JSON parameter schema to help with validation and type checking/conversions.
I've also added type hints.
This will make it easier to implement the remaining APIs consistently. (Note that similar refactoring of the pytests might be beneficial, but I didn't attempt that here.)
> Simplify and consolidate Elasticsearch queries

- agent/Makefile
- lib/pbench/agent/results.py
- lib/pbench/cli/agent/commands/results/__init__.py
- lib/pbench/test/unit/agent/fixtures/copy_result_tb/log.tar.xz.md5
- lib/pbench/test/unit/agent/task/test_copy_result_tb.py
- lib/pbench/test/unit/agent/task/test_make_result_tb.py
- lib/pbench/test/unit/agent/task/test_move_results.py
- lib/pbench/test/unit/agent/task/test_results_push.py
- setup.cfg
This PR mainly deals with using RESTful PUT API instead of ssh for sending Tarballs from agent to server. At the time of sending of tarballs, it consists of an Authorization token (generated with the help of pbench-generate-token command)which will help for authorizing the owner of the Tarballs. 
It uses 'click' for the creation of a command-line interface.
Also consists of config file changes and pytests.
Sorting of the config files is taken care in PR #2190
> Retooling pbench-move-results to use the RESTful PUT API instead of direct ssh

- lib/pbench/server/api/resources/upload_api.py
- lib/pbench/test/unit/server/test_requests.py
- Adds a strict Bearer `Authorization` header requirement to upload API
- Dataset owner's username is extracted from the authorization header
> Add Authorization header to upload PUT API

- agent/rpm/pbench-agent.spec.j2
It looks like we need the latest version of `pip` to install all of the module dependencies we have.  For all but CentOS 7 / RHEL 7 we have the correct version.  So for those environments we now have to install the latest version of `pip3` directly in order for us to have our Python3 dependencies satisfied.
The days of our RHEL 7 support are numbered.
Fixes https://github.com/distributed-system-analysis/pbench/issues/2245.
> Fix CentOS 7 / RHEL 7 pbench-agent installations

- agent/containers/images/Dockerfile.layered.j2
- agent/containers/images/Makefile
- agent/containers/images/pcp.repo.j2
- agent/rpm/pbench-agent.spec.j2
For some reason the bintray.com repos have stopped working, giving us '401 Forbidden' errors.  It appears the new repos are using the jFrog Artifactory instance for PCP.
We also drop the 5.2.2 version requirement for PCP.
----
This PR is based on PR #2248 in order to make both testable.
> Update PCP repo for container builds

- agent/ansible/pbench_agent_config.yml
- agent/ansible/pbench_agent_install.yml
- agent/ansible/pbench_repo_install.yml
Fixes #2077
Do not use `become` or `become_user` in playbooks. Replace them
with `remote_user`.
> Replace use of become/become_user with remote_user

- agent/util-scripts/gold/test-client-tool-meister/test-53.txt
- agent/util-scripts/gold/test-client-tool-meister/test-56.txt
- agent/util-scripts/gold/test-client-tool-meister/test-57.txt
- agent/util-scripts/gold/test-start-stop-tool-meister/test-51.txt
- agent/util-scripts/gold/test-start-stop-tool-meister/test-52.txt
- lib/pbench/agent/redis.py
- lib/pbench/agent/tool_data_sink.py
- lib/pbench/agent/tool_meister.py
We only emit messages on connection failures, on re-established connections, or when we encounter a missing key, and will emit a summary message if it took more than one attempt to connect.
Also fixes #2211.
> Quiet Redis server connections by default

- lib/pbench/server/api/resources/query_apis/__init__.py
- lib/pbench/server/api/resources/query_apis/controllers_list.py
- lib/pbench/server/api/resources/query_apis/datasets_detail.py
- lib/pbench/test/unit/server/test_controllers_list.py
- lib/pbench/test/unit/server/test_datasets_detail.py
Addresses two issues with edge case errors when target datasets aren't found, avoiding "internal error" and unhelpful stack traces.
Closes #2259
Closes #2241
> Improve error handling in Elasticsearch queries

- lib/pbench/agent/results.py
- lib/pbench/agent/tool_meister.py
- lib/pbench/common/utils.py
- lib/pbench/test/unit/common/test_utils.py
- server/bin/pbench-backup-tarballs.py
- server/bin/pbench-server-prep-shim-002.py
- server/bin/pbench-verify-backup-tarballs.py
We were missing the `Content-Length` header on the PUT API request as generated by the CLI `pbench-push-results` command.
We modify the `md5sum` utility method to also return the length so that we won't have to stat the file separately.
----
Fixes #2260.
> Add the `Content-Length` header to the PUT req

- agent/ansible/pbench/agent/galaxy.yml
- agent/ansible/pbench/agent/roles/epel_repo_install/tasks/main.yml
- agent/ansible/pbench_agent_install.yml
- server/ansible/pbench-server-install.yml
- server/ansible/roles/epel_repo_install/tasks/main.yml
Fixes #1987
Separately added to both server and agent roles.
Add it to the pbench_<agent|server>_install.yml playbooks.
Bump the version in galaxy.yml in preparation for a new upload
of the agent roles.
> Add a role to install the EPEL repo

- server/rpm/pbench-server.spec.j2
Fixes #2094
Although `psycopg2` is in the `server/requirements.txt` file, we prefer to install it as part of the RPM installation of pbench-server. The `pip3` install phase of it will then be a no-op.
> Add python3-psycopg2 require in the server spec file

- lib/pbench/server/api/resources/query_apis/__init__.py
- lib/pbench/server/api/resources/query_apis/controllers_list.py
- lib/pbench/server/api/resources/query_apis/datasets_detail.py
- lib/pbench/server/api/resources/query_apis/datasets_list.py
- lib/pbench/server/api/resources/query_apis/month_indices.py
- lib/pbench/server/database/database.py
- lib/pbench/server/database/models/template.py
- lib/pbench/server/database/models/tracker.py
- lib/pbench/server/indexer.py
- lib/pbench/server/templates.py
- lib/pbench/test/unit/server/conftest.py
- lib/pbench/test/unit/server/test_controllers_list.py
- lib/pbench/test/unit/server/test_datasets_detail.py
- lib/pbench/test/unit/server/test_datasets_list.py
- lib/pbench/test/unit/server/test_month_indices.py
- lib/pbench/test/unit/server/test_template_db.py
- lib/pbench/test/unit/server/test_templates.py
- server/bin/pbench-cull-unpacked-tarballs.py
- server/bin/pbench-index.py
- server/bin/pbench-report-status.py
- server/bin/pbench-verify-backup-tarballs.py
- server/bin/unittests
This is separated into staged commits which may or may not make review easier.
1. Refactor PbenchTemplates
Add a new Template DB model that will allow persisting our Elasticsearch templates to be shared between indexing and the server APIs.
This also refactors the templates.py class which supports indexing, with the goal of integrating with the new DB table although the base commit stops short of implementing the integration to allow reviewing the basic refactoring separately.
1. Improve encapsulation
Push some TemplateFile methods down into JsonFile and a new JsonToolFile subclass for cleaner encapsulation.
1. Integrate DB into template management
The resolve() method now attempts to look up the root index name in the templates DB table. If found, it'll check modification timestamps to …
> Add a template DB table and integrate with index template management

- agent/requirements.txt
- agent/rpm/pbench-agent.spec.j2
- agent/rpm/python-module-mapping.table
- agent/util-scripts/pbench-tool-meister-start
- agent/util-scripts/validate-hostname
- jenkins/development.Dockerfile
- lib/pbench/agent/results.py
- lib/pbench/agent/utils.py
- lib/pbench/common/utils.py
- lib/pbench/server/api/__init__.py
- lib/pbench/server/api/resources/upload_api.py
- lib/pbench/test/unit/agent/task/test_copy_result_tb.py
- lib/pbench/test/unit/agent/task/test_results_push.py
- lib/pbench/test/unit/common/test_validate_hostname.py
- lib/pbench/test/unit/server/conftest.py
- lib/pbench/test/unit/server/test_endpoint_configure.py
- lib/pbench/test/unit/server/test_requests.py
The upload API now requires the file name, moving the controller to a required header.  This was chosen with an eye towards the future, where the "controller" value is not needed by the pbench server for processing.  At the time this code was written, the current pbench-agent and the pbench-server use the controller to organize on-disk where the files are placed.  In the future, the controller value will simply be another piece of metadata about the file.
The API is now `/api/v1/upload/<filename>`, with the controller name provided in the `controller` header.  This removes it from prominence in the URI, which is why we did not move it to a URI parameter.
We also change a number of error responses to use the appropriate error codes via `http.HTTPStatus`, and update the messages to be more …
> Rework upload API to move filename to URI

- lib/pbench/common/logger.py
We really don't want to have the module name "dotted" with the module name, they are separate ids, and need to be treated as such.
> Separate logger name from module name

- lib/pbench/agent/results.py
In today's Jam Session, we ran into a curious problem with tarball upload.  As best as we could discern, the Flask server used by `gunicorn` was trying to parse the upload as though it were being sent with `Transfer-Encoding: chunked`, but the stream was clearly not formatted that way.  This lead to a great deal of sleuthing around the agent's use of the Python `requests` package.
Per [RFC 2616](http://pretty-rfc.herokuapp.com/RFC2616#message.length), a request must not contain both `Content-Length` and `Transfer-Encoding` headers; however, the server would like to receive the `Content-Length` header, but the `requests` package may opt to generate the `Transfer-Encoding` header instead, depending on how the data for the request is specified.
This commit replaces the previous …
> Ensure that tarball upload gets desired HTTP headers

- agent/containers/images/visualizers/DockerfileLive
- agent/containers/images/visualizers/DockerfilePostPCP
- agent/containers/images/visualizers/DockerfilePostProm
- agent/containers/images/visualizers/README.md
- agent/containers/images/visualizers/run.py
Adds new options for live-metric-visualizer:
- Can now specify a remote host
- Can select individual hosts for prometheus and pmproxy as well
- Can now change the ports for prometheus and pmproxy
Adds new option for pcp-graf-visualizer:
- Use an external redis server instead of built-in
Also cleans up unnecessary environment variables and moves work/defaults to run.py
All three visualizers updated, tested, and working as expected
> Allow live metric visualization for remote runs

- lib/pbench/cli/server/user_create.py
- lib/pbench/server/api/__init__.py
- lib/pbench/server/api/resources/users_api.py
- lib/pbench/server/database/__init__.py
- server/bin/pbench-backup-tarballs.py
- server/bin/pbench-cull-unpacked-tarballs.py
- server/bin/pbench-import-datasets.py
- server/bin/pbench-index.py
- server/bin/pbench-reindex.py
- server/bin/pbench-report-status.py
- server/bin/pbench-server-prep-shim-002.py
- server/bin/pbench-state-manager.py
- server/bin/pbench-verify-backup-tarballs.py
- Creates a utility init_db method in `lib/pbench/server/api/__init__.py` that other functionalities in our code can use to initialize the standalone db access and make sure all the models are imported before the call to Database.init_db.
> Fix standalone db.init issue

- agent/util-scripts/gold/pbench-copy-results/test-49.txt
- agent/util-scripts/gold/test-add-metalog-%-option/test-48.txt
- agent/util-scripts/pbench-add-metalog-option
- lib/pbench/agent/results.py
- lib/pbench/agent/tool_data_sink.py
- lib/pbench/cli/agent/commands/log/__init__.py
- lib/pbench/common/__init__.py
- lib/pbench/server/indexer.py
- lib/pbench/test/unit/agent/task/test_add_metalog_option.py
- lib/pbench/test/unit/common/test_metadatalog.py
- server/bin/pbench-cull-unpacked-tarballs.py
Instead of trying to prevent any unwanted `%` characters landing in a `metadata.log` file, we just turn off `ConfigParser` interpolation.
> Turn off interpolation of `metadata.log`

- agent/base
- agent/util-scripts/gold/test-client-tool-meister/test-53.txt
- agent/util-scripts/gold/test-client-tool-meister/test-56.txt
- agent/util-scripts/gold/test-client-tool-meister/test-57.txt
- agent/util-scripts/gold/test-start-stop-tool-meister/test-51.txt
- agent/util-scripts/gold/test-start-stop-tool-meister/test-52.txt
- agent/util-scripts/test-bin/hostname
- lib/pbench/agent/tool_data_sink.py
- lib/pbench/agent/tool_meister.py
- lib/pbench/agent/utils.py
Since `hostname -i` will return a space separated list of IP addresses for the given host name, validate all of them instead of assuming incorrectly that only one is returned.
I have not seen this behavior on Fedora derived systems, but on Debian, when you get a container, it auto creates an entry for the current host name in the container's view of its `/etc/hosts`, which has a value of `127.0.1.1` (yes, `.1.1`, go figure).  In this case, `hostname -i` will return the original IP address and the `127.0.1.1` address.
You can make this happen arbitrarily by modifying the `/etc/hosts` of some system to have an alternate IP for localhost or your official DHCP host name. Then `hostname -i` returns N IP addresses.
----
Added a second commit to fix the proper handling of the `hostname` output. …
> Validate all passed in `_pbench_hostname_ip` values

- agent/bench-scripts/templates/make-fio-jobfile.py
- agent/tool-scripts/datalog/haproxy-ocp-datalog
- agent/tool-scripts/datalog/oc-datalog
- agent/tool-scripts/datalog/pprof-datalog
- agent/tool-scripts/datalog/prometheus-metrics-datalog
- lib/pbench/server/indexer.py
- server/bin/pbench-cull-unpacked-tarballs.py
- server/bin/pbench-pp-status
- server/bin/pbench-reindex.py
Apparently LGTM only reports "new" (or newly-fixed) problems, and we now have a backlog of 40 issues.  This PR addresses many of the ones which refer to Python code.  (I did not take on the `.js` ones.)
In some cases, the changes correct the issues that LGTM raised (useless return values, unused variables, imports via both `import` and `from`, an unguarded `next()` call in a generator, a potentially confusing variable shadowing, an `else` on a `for` loop containing no `break`, unused imports).
In other cases, the changes add directives to suppress false positives.  (E.g., [unreachable code](https://github.com/github/codeql/issues/5910).)
And, I made a couple of tiny code improvements, which I couldn't resist....
Note that there are a number of cases which I did not address.  These are …
> Clean up LGTM complaints

- lib/pbench/server/api/resources/query_apis/__init__.py
- lib/pbench/server/api/resources/query_apis/datasets_list.py
- lib/pbench/server/database/models/tracker.py
- lib/pbench/test/unit/server/query_apis/conftest.py
- lib/pbench/test/unit/server/query_apis/test_controllers_list.py
- lib/pbench/test/unit/server/query_apis/test_datasets_detail.py
- lib/pbench/test/unit/server/query_apis/test_datasets_list.py
- lib/pbench/test/unit/server/query_apis/test_month_indices.py
- server/bin/unittests
This began as simply fixing the bad parameter type error, grew to cover a few other minor fixes, such as limiting the attempt to hide `pbench-user-create` failures in the unittests, and then to accommodate my attempt to utilize the `datasets/list` and `datasets/detail` APIs in the dashboard.
This also starts the move towards consolidating unit testing across the `ElasticBase` subclasses by moving them into a subdirectory with their own `conftest.py` fixtures.
> Query fixes

- agent/util-scripts/gold/pbench-register-tool-trigger/test-15.txt
- agent/util-scripts/gold/pbench-register-tool-trigger/test-35.00.txt
- agent/util-scripts/gold/pbench-register-tool-trigger/test-35.01.txt
- agent/util-scripts/gold/pbench-register-tool-trigger/test-35.02.txt
- agent/util-scripts/gold/pbench-register-tool-trigger/test-35.03.txt
- agent/util-scripts/gold/pbench-register-tool-trigger/test-35.04.txt
- agent/util-scripts/gold/pbench-register-tool-trigger/test-35.05.txt
- agent/util-scripts/gold/pbench-register-tool-trigger/test-35.06.txt
- agent/util-scripts/gold/pbench-register-tool-trigger/test-35.07.txt
- agent/util-scripts/gold/pbench-register-tool-trigger/test-35.08.txt
- agent/util-scripts/gold/pbench-register-tool-trigger/test-35.09.txt
- agent/util-scripts/gold/test-pbench-register-tool-trigger/test-35.10.txt
- agent/util-scripts/gold/test-pbench-register-tool-trigger/test-35.11.txt
- agent/util-scripts/gold/test-pbench-register-tool-trigger/test-35.12.txt
- agent/util-scripts/pbench-register-tool-trigger
- agent/util-scripts/test-bin/test-pbench-register-tool-trigger
- agent/util-scripts/unittests
Fixes #2268
Fix pbench-register-tool-trigger to detect missing arguments: at least
one of --start-trigger or --stop-trigger is always required.
Add unit tests for the various cases.
> Fix pbench-register-tool-trigger

- lib/pbench/test/unit/server/query_apis/conftest.py
- lib/pbench/test/unit/server/query_apis/test_controllers_list.py
- lib/pbench/test/unit/server/query_apis/test_datasets_detail.py
- lib/pbench/test/unit/server/query_apis/test_datasets_list.py
- lib/pbench/test/unit/server/query_apis/test_month_indices.py
Webb pointed out a few things about the query unit tests that I decided I wanted to clean up.
- I realized that the clever use of `@pytest.mark.parametrize()` to pass parameters to a fixture was unnecessary, as the fixture is returning a local method that does the heavy lifting anyway.
- By directly raising exceptions that would normally be raised through the requests package `raise_for_status()` method, we're excessively interfering with normal behavior. However, connection errors _are_ raised directly by requests, so I've split off the `HTTPError` exception behavior (`raise_for_status`) from the testing of other exceptions.
- I decided to switch to the `responses` package instead of `requests_mock`, which streamlines some code.
> More query_api unit test cleanup and refactoring

- agent/util-scripts/gold/test-client-tool-meister/test-53.txt
- agent/util-scripts/gold/test-client-tool-meister/test-56.txt
- agent/util-scripts/gold/test-client-tool-meister/test-57.txt
- agent/util-scripts/gold/test-start-stop-tool-meister/test-51.txt
- agent/util-scripts/gold/test-start-stop-tool-meister/test-52.txt
- agent/util-scripts/pbench-tool-meister-start
The unit tests are failing on Fedora 34 because Redis is now persisting changes to the database to disk.  We are really not ready for that right now, so we explicitly turn that off.
> Ensure redis does not persist any data to disk

- agent/util-scripts/tool-meister/pbench-sysinfo-dump
Fixes #2363
Fixes #2371
The command name has changed in versions >= 4.0.
The generated checksum is SHA256 in versions >= 4.1.
> Fixes for sos-report >= 4.0 versions

- agent/util-scripts/pbench-sysinfo-dump
> Backport "Fixes for sos-report >= 4.0 versions" to 0.69
