distributed-system-analysis/pbench

agent/rpm/pbench-agent.spec.j2
Fixes #2343 (again and finally)
The example config file was renamed in PR #2358, but there is still a problem: the %ghost line in the spec file is preventing its installation.  This PR fixes that.
=> pbench-agent.cfg is no longer a ghost

server/user/README.md, server/user/bitrot-detect, server/user/bitrot-detect.service, server/user/bitrot-detect.timer
This is a quick capture of the current bit-rot detection that has been deployed as a stop-gap whilest backup-verification is off.
The first commit contains the originally deployed stop-gap, include a bug where empty or missing `.md5` files for `.tar.xz` files are not detected.
The second commit contains the fixes to address those problems and all the code-review feedback.
=> Quick-n-Dirty bit-rot detection for tar balls

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/query_apis/index_mappings.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/query_apis/test_index_mappings.py, lib/pbench/test/unit/server/test_endpoint_configure.py
API for returning documents mappings.
- The mapping index name need to be specified in the URI `/api/v1/mappings/<index_name>` for example to get `run-data` document mappings one can perform the GET request on `/api/v1/mappings/run`
- Internally we return the mappings by querying the `Template` table instead of making a direct ES query.
=> Documents index mappings api

lib/pbench/test/unit/server/__init__.py, lib/pbench/test/unit/server/query_apis/commons.py, lib/pbench/test/unit/server/query_apis/test_controllers_list.py, lib/pbench/test/unit/server/query_apis/test_datasets_detail.py, lib/pbench/test/unit/server/query_apis/test_datasets_list.py, lib/pbench/test/unit/server/query_apis/test_datasets_publish.py
This PR tries to remove some of the redundant code in our query API tests
=> Remove redundant query API test code

jenkins/development.Dockerfile
This adds the `psycopg2` RPM to the Jenkins container, which is needed in order to test the changes in #2423.
=> Add psycopg2 RPM to Jenkins container

lib/pbench/test/unit/server/query_apis/commons.py
Unlike the production code, the unit test Elasticsearch index URL builder fails to normalize the beginning and end dates to the beginning and end of the month. This can result in missing months and failing to match the mocked URL.
=> Fix unit test date_range method

server/ansible/roles/pbench-server-activate-create-crontab/tasks/main.yml, server/requirements.txt, server/rpm/pbench-server.spec.j2
1. Add missing dependencies to requirements.txt
2. Lock elasticsearch module dependency to workaround bug
3. Limit module versions to eliminate pip version matrix thrashing
4. Remove the /opt/pbench-server prefix on pip install in order to simplify PYTHONPATH (after discussion with Pete this looked like a better alternative than computing an inclusive path later).
Tested by re-installing on our new staging server.
This is a fix for some problems called out in #2422 but not sufficient to close the issue.
=> Server installation cleanup

server/bin/gold/test-2.txt, server/bin/gold/test-3.txt, server/bin/gold/test-4.txt, server/bin/gold/test-5.1.txt, server/bin/gold/test-5.2.txt, server/bin/gold/test-5.txt, server/bin/pbench-tarball-stats.py, server/requirements.txt
Also fix columns when a bucket of data does not have one or more satellites in it.  We also fix the column widths to accommodate a 3 digit percentage (100.00%).
=> Add reporting for the last 2 weeks

lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/api/resources/query_apis/controllers_list.py, lib/pbench/server/api/resources/query_apis/datasets_detail.py, lib/pbench/server/api/resources/query_apis/datasets_list.py, lib/pbench/server/api/resources/query_apis/datasets_publish.py, lib/pbench/server/api/resources/query_apis/elasticsearch_api.py, lib/pbench/server/api/resources/query_apis/index_search.py, lib/pbench/server/api/resources/query_apis/month_indices.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/query_apis/commons.py, lib/pbench/test/unit/server/query_apis/test_datasets_publish.py, lib/pbench/test/unit/server/test_schema.py
I want to reuse Schema for a new API outside of the Elasticsearch query context. I've pulled the conversion/normalization framework up a level to server.api.resources, and reworked the post/put/get delegation to (hopefully) support more general interfaces. (I expect to use GET, PUT, DELETE, and possibly POST for metadata.)
=> Refactor ElasticBase to expose framework elements

jenkins/Pipeline.gy, jenkins/python-setup.sh, server/Makefile, server/bin/pbench-server-put-shim, server/bin/pbench-server-put-shim.py, server/lib/config/pbench-server-default.cfg, server/lib/pbench/process_tb.py, server/lib/pbench/test/conftest.py, server/lib/pbench/test/unit/test_process_tb.py, server/rpm/pbench-server.spec.j2, tox.ini
Fixes #2100
put-shim server will act as an interface between v0.69 pbench-agents and v0.72 pbench-server. It will receive the tarballs using ssh transfer method from the 0.69 agents and will forward them to the 0.72 servers using the Agent's `pbench-results-push` command.
**Note**: This change includes adding a dependency in the 0.69 Server on a 0.71+ Agent. This dependency will include using the `pbench-results-push` command of 0.71+ Agent.
More Details and Discussions about this PR are available on PR #2340. This PR deals with basing the put-shim server on branch b0.69 and structural changes according to that.
=> Pbench put shim server

server/lib/pbench/test/conftest.py, server/lib/pbench/test/unit/test_process_tb.py
Fixes #2454 
Remove "test_" prefix from the `test_logger` fixture in conftest.py file.
=> remove 'test_' prefix from the fixture in conftest

agent/requirements.txt, agent/test-requirements.txt, agent/tool-scripts/base-tool, agent/tool-scripts/tests/blktrace/gold/stdout, agent/tool-scripts/tests/numastat/gold/stdout, agent/tool-scripts/tests/pprof/gold/stdout, agent/tool-scripts/tests/qemu-migrate/gold/stdout, agent/tool-scripts/tests/strace/gold/stdout, agent/tool-scripts/tests/tcpdump/gold/stdout, agent/tool-scripts/tests/virsh-migrate/gold/stdout, agent/tool-scripts/tests/vmstat/gold/stdout
The `pprof` tool requires both `golang` and `ansible` RPMs, but the tool was only checking for `golang`.  We add an explicit check for both now.
In principle the `pbench-agent` should not have any explicit RPM dependencies for RPMs needed by tools.  But, the `pbench-run-bencmark` interface requires the `ansible` RPM, so we happen to satisfy the `pprof` requirement indirectly.
However, we don't want to have the `ansible` Python3 module explicitly listed in the `agent/requirements.txt` file since it is not a direct dependency for any Python3 code of the agent.  So for testing purposes we move the `ansible` module requirement to `test-requirements.txt`.
=> Check for the `ansible` RPM for the `pprof` tool

lib/pbench/cli/agent/commands/tools/list.py, lib/pbench/test/functional/agent/cli/commands/conftest.py, lib/pbench/test/functional/agent/cli/commands/tools/test_tools_list.py
Fixes #2302
Fixes #2345 
Fixes #2346 
This PR consists of five commits:
- the first commit adds some basic functional tests that trigger the uncaught exceptions in the three issues above.
- the next three commits make the changes necessary to fix each one of the issues.
This PR will be followed by a subsequent PR that will fix additional issues in `pbench-list-tools` that do not cause exceptions. No attempt has been made to make the exit status or the output of the program correct: that is left to the subsequent PR. The exit status of this program is, to the extent possible, compatible with the 0.69.9 version.
This PR and the subsequent one replace PR #2453.
=> Fixes for pbench-list-tools

agent/bench-scripts/postprocess/trafficgen-postprocess
This change ensures that the JSON output from `trafficgen-postprocess` is produced in "canonical order", so that it produces consistent results for things like testing.
(I had intended to include this change in #2349, but I forgot.)
Fixes #2451.
(Reviewer invitations:  @ndokos, @dbutenhof, @portante)
=> Canonicalize the JSON output from trafficgen-postprocess

agent/rpm/pbench-agent.spec.j2, server/rpm/pbench-server.spec.j2
This change touches up the RPM spec file template for the Server to enable `dnf remove` to work properly.  Previously, we used the "big hammer" approach of simply (manually/explicitly) removing the entire `%{installdir}` during the `%postun` stage, but this has the undesirable side effect of wiping out any user files which might be in `/opt/pbench-server/` (such as `pbench-server.cfg`).  Instead, we now use better discipline, removing during the `%preun` stage the files which we created during the `%post` stage, so that, during the "uninstall" stage, the directory tree looks like what RPM expects it to look like, which means that all of the entries in the `%files` list are removed implicitly for us (but, things like user files are left alone).
This change also declares the entire …
=> Remove explicit removals from RPM removal

server/requirements.txt, server/rpm/pbench-server.spec.j2
In the spec file:
- make a couple of package Require:s in the spec file conditional, since the packages don't exist on RHEL8.4
- make sure that pip3 is at the latest version
In requirements.txt:
- require >=0.3.9 of flask-restful
- require >=7.13 .1, <7.14 of elasticsearch
=> Changes to spec file and reqs (from jam session 2021-10-07)

lib/pbench/server/api/resources/__init__.py, lib/pbench/test/unit/server/query_apis/commons.py
While attempting to debug a Postman problem with @riya-17 I experimentally removed the "silent=True" option in our JSON payload processing hoping for some insight into the problem, which was that the request from Postman was resulting in no JSON payload. (With `silent=True`, on any parsing problem `get_json` simply returns `None`.) This change exposed a problem in `GET` handling, in that we were still attempting to process a JSON payload when there is none and we won't use it anyway.
I moved payload processing *after* the `GET` shortcut; and I added a `try`/`except` to catch and report any errors here, and to abort with BAD_REQUEST. I also added a new unit test with deliberately malformed JSON.
None of this unfortunately helped to make progress on the original problem, but it seems like a …
=> Cleanup in JSON parameter handling

agent/bench-scripts/templates/fio-shared-fs.job, agent/bench-scripts/templates/fio.job, agent/bench-scripts/tests/pbench-fio/test-04.txt, agent/bench-scripts/tests/pbench-fio/test-05.txt, agent/bench-scripts/tests/pbench-fio/test-06.txt, agent/bench-scripts/tests/pbench-fio/test-07.txt, agent/bench-scripts/tests/pbench-fio/test-08.txt, agent/bench-scripts/tests/pbench-fio/test-13.txt, agent/bench-scripts/tests/pbench-fio/test-15.txt, agent/bench-scripts/tests/pbench-fio/test-16.txt, agent/bench-scripts/tests/pbench-fio/test-20.txt, agent/bench-scripts/tests/pbench-fio/test-28.txt, agent/bench-scripts/tests/pbench-fio/test-30.txt, agent/bench-scripts/tests/pbench-fio/test-31.txt, agent/bench-scripts/tests/pbench-fio/test-32.txt
Addresses issuse #913 and fixes issue #1021.
Note that the generated HTML for `tests/pbench-fio/test-32.txt` changes from using an `xy` chart to a `timeseries` chart because the existing code at [line 73](https://github.com/distributed-system-analysis/pbench/blob/main/agent/bench-scripts/postprocess/fio-postprocess-viz.py#L73) of `fio-postprocess-viz.py` uses `timeseries` when it sees `log_unix_epoch` in the `fio.job` file.
Note that our tests do not run `fio` so we only ensure the option is now showing up in `fio.job` files.
=> Ensure `fio` uses full unix timestamps

agent/bench-scripts/pbench-fio
Originally part of PR #2524, we correct the usage output to be emitted on `stderr` in error conditions, and to `stdout` for the one non-error condition, `--help`.
Further we remove the annoying trailing semi-colons, and remove the extra `shift` statement while processing options.
Lastly, unrecognized parameters now cause an error.
=> Ensure fio usage msg sent to stderr as necessary

agent/bench-scripts/pbench-fio, agent/bench-scripts/pbench-fio.md, agent/bench-scripts/pbench-netperf, agent/bench-scripts/pbench-uperf, agent/bench-scripts/pbench-uperf.md, agent/bench-scripts/tests/pbench-fio/test-05.txt, agent/bench-scripts/tests/pbench-fio/test-06.txt, agent/bench-scripts/tests/pbench-fio/test-07.txt, agent/bench-scripts/tests/pbench-fio/test-08.txt, agent/bench-scripts/tests/pbench-fio/test-13.txt, agent/bench-scripts/tests/pbench-fio/test-16.txt, agent/bench-scripts/tests/pbench-fio/test-20.txt, agent/bench-scripts/tests/pbench-fio/test-30.txt, agent/bench-scripts/tests/pbench-fio/test-31.txt, agent/bench-scripts/tests/pbench-fio/test-32.txt, agent/bench-scripts/tests/pbench-uperf/test-00.txt, agent/bench-scripts/tests/pbench-uperf/test-01.txt, agent/bench-scripts/tests/pbench-uperf/test-52.txt
All three existing benchmark scripts which manipulate network firewalls have been changed to ignore firewalls entirely.
For `pbench-fio`, this means it no longer attempts to add open ports when clients are used.
For `pbench-uperf` and `pbench-netperf`, those scripts no longer disable `firewalld` explicitly.
Any one using `pbench-fio` in client mode, or either `pbench-uperf` or `pbench-netperf`, must be responsible for properly enabling access on the expected ports.
The documentation for `pbench-uperf` and `pbench-fio` have been updated to reflect this new behavior.
Fixed #1217.
=> Stop explicitly manipulating firewalls in `pbench-fio` and `pbench-uperf`

lib/pbench/server/api/resources/endpoint_configure.py, lib/pbench/test/unit/server/test_endpoint_configure.py
It may be that we need to ensure that `pbench-server.cfg` has a valid `host` value for other reasons, but `/api/v1/endpoints` is all about making sure an API client (A) knows about all the endpoints we support and (B) can call them reliably using the recommended path (e.g., through an NGINX reverse proxy).
We had advertised endpoints (in the absence of reverse proxy forwarding headers) relative to the static `pbench-server.cfg`
`host` value; this however is unnecessary as the incoming HTTP Requests object includes the actual access path, which makes a much better fallback. This PR changes the endpoints API to use that value, which has the advantage of working within a container regardless of the pod virtual networking configuration.
=> Fix `/api/v1/endpoints` in container environment

agent/containers/images/visualizers/run.py
Increase Prom retention to 1yr. 
This is especially useful for the "post" PromGrafVisualizer option where you may be looking at older data. Without an increase in retention, when running the visualizer image Prom can delete any original data (provided by the volume mount) older than the default 15d.
=> Increase Prom retention in visualizers

agent/util-scripts/gold/pbench-register-tool-set/test-11.08.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.15.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.16.txt, agent/util-scripts/gold/pbench-register-tool/test-44.txt, agent/util-scripts/gold/pbench-register-tool/test-46.txt, agent/util-scripts/pbench-register-tool, agent/util-scripts/pbench-register-tool-set, agent/util-scripts/unittests
Fixes #2463.
Passing a non-existent remotes files with `--remotes=@somefile` causes  multiple usage messages from `pbench-register-tool`: one per tool in the set. The problem is that `pbench-register-tool-set` does not check  the remote file at all: it just blindly passes it to  `pbench-register-tool` which does detect the error, but since it is called multiple times, it detects and reports the error multiple times. `pbench-register-tool-set` needs to check the file itself and quit if the file is bad (non-existent or ill-formed).
To that end, we add a `--test-arg` option to `pbench-register-tool`  so that it can be used as a checking tool. `pbench-register-tool-set` calls it once with that option and if that call fails, we get the error message(s) from that failed call, …
=> pbench-register-tool-set: check for bad remotes file

agent/requirements.txt
It also quiets a ridiculous warning message, see: https://github.com/redis/redis-py/commit/16cfcc7fced84d2b53edf95af1c40b230b30fc3d
This happens with version 4.x and later of `redis-py`, which is now live on PyPI at this point.
=> Add `hiredis` requirement for performance reasons

agent/bench-scripts/pbench-cyclictest, agent/bench-scripts/pbench-dbench, agent/bench-scripts/pbench-iozone, agent/bench-scripts/pbench-migrate, agent/bench-scripts/pbench-netperf, agent/bench-scripts/pbench-run-benchmark.pl, agent/bench-scripts/tests/pbench-dbench/test-02.txt, agent/bench-scripts/tests/pbench-run-benchmark/test-43.txt, agent/bench-scripts/tests/pbench-run-benchmark/test-44.txt, agent/bench-scripts/tests/pbench-run-benchmark/test-45.txt, agent/bench-scripts/tests/pbench-run-benchmark/test-46.txt, agent/bench-scripts/tests/pbench-run-benchmark/test-47.txt, agent/bench-scripts/tests/test-benchmark-clis/test-CL.txt, docs/guides/UserGuide.rst
There are six benchmark scripts languishing in the pbench-agent with little or no support for them:
1. `pbench-cyclictest`
2. `pbench-dbench`
3. `pbench-iozone`
4. `pbench-migrate`
5. `pbench-netperf`
6. `pbench-run-benchmark`
The goal is to have these deprecated in the `v0.71` release so that we can remove them entirely in the `v0.72` release.
=> Post deprecation notice for unsupported benchmark scripts

agent/util-scripts/gold/pbench-register-tool-set/test-11.17.txt, agent/util-scripts/pbench-register-tool, agent/util-scripts/unittests
Fixes #2538
An empty remotes file specified with `--remotes=@/path/to/file` now
makes `pbench-register-tool` (and also `pbench-register-tool-set`) log
an error message and exit with an error status.
=> pbench-register-tool: treat an empty remotes file as an error

agent/util-scripts/gold/pbench-copy-results/test-31.txt, agent/util-scripts/gold/pbench-copy-results/test-32.txt, agent/util-scripts/gold/pbench-copy-results/test-34.txt, agent/util-scripts/gold/pbench-copy-results/test-37.txt, agent/util-scripts/gold/pbench-copy-results/test-38.txt, agent/util-scripts/gold/pbench-copy-results/test-39.txt, agent/util-scripts/gold/pbench-copy-results/test-40.txt, agent/util-scripts/gold/pbench-copy-results/test-41.txt, agent/util-scripts/gold/pbench-copy-results/test-49.txt, agent/util-scripts/gold/pbench-copy-results/test-50.txt, agent/util-scripts/gold/pbench-move-results/test-20.txt, agent/util-scripts/gold/pbench-move-results/test-33.txt, agent/util-scripts/pbench-make-result-tb, agent/util-scripts/pbench-move-results, agent/util-scripts/unittests
Ahead of the work coming for the pbench server being endowed with the notion of a user, we require results being moved to provide the `--user` option for `pbench-move-results`.
=> Require `--user` for `pbench-move/copy-results`

lib/pbench/test/unit/server/query_apis/commons.py, lib/pbench/test/unit/server/query_apis/test_namespace_and_rows.py
`root_index_name` in the `commons.py` file is hard coded to `result-data-sample` where it needs to be script-based. Like for `namespaces_and_rows` PR we need `result-data-sample` as a `root_index_name` for finding the appropriate indices, while we need `run-toc` as `root_index_name` for finding indices related to that
=> Dynamic `root_index_name`

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/query_apis/metadata_index/__init__.py, lib/pbench/server/api/resources/query_apis/metadata_index/index_mappings.py, lib/pbench/test/unit/server/query_apis/test_index_mappings.py
- Move index_mappings api under lib/pbench/server/api/resources/query_apis/metadata_index directory.
- Replace index name in the index_mappings get URI where <index> parameter is not a direct Elasticsearch root index name, but a key like search, samples, timeseries.
=> Move index_mappings api to appropriate directory

agent/ansible/pbench/agent/roles/pbench_agent_config/tasks/main.yml, agent/ansible/pbench/agent/roles/pbench_firewall_open_ports/README.md, agent/ansible/pbench/agent/roles/pbench_firewall_open_ports/defaults/main.yml, agent/ansible/pbench/agent/roles/pbench_firewall_open_ports/meta/main.yml, agent/ansible/pbench/agent/roles/pbench_firewall_open_ports/tasks/main.yml, agent/ansible/pbench/agent/roles/pbench_repo_install/vars/main.yml, agent/rpm/pbench-agent.spec.j2
- Replace `ansible` dependency by `ansible-core` (more for documentation
than any other reason: `ansible-core` is installed by default on RHEL9)
- Add some python dependencies similar to RHEL8, although I had to
leave out `python3-click` which is not available (yet?)
- Fix the name of the COPR repo for RHEL9 in the ansible roles.
- The second commit adds an ansible role to punch holes in the firewall
for tool meister use
=> Spec file and ansible fixes for RHEL9

jenkins/development.Dockerfile, server/bin/pbench-server-prep-shim-002.py, server/bin/test-lib/selinux.py, server/lib/systemd/pbench-server.service, server/requirements.txt, server/rpm/pbench-server.spec.j2
This PR is for a set of miscellaneous fixes which I made leading up to providing a containerized Pbench Server (see #2585).
- The first change works around a bug in the RHEL 8 `libselinux` implementation, which results in a SEGV when the `restorecon` function is invoked with SELinux disabled (as it is, for whatever reason, in the RHEL 8 container).  The fix is simple and of general applicability, which is why it's included in this PR:  only call `restorecon` if SELinux is enabled.  However, it turns out that the Server's functional test suite mocks the `selinux` module, but it does so incompletely, so I had to add `is_selinux_enabled()` to the mock-module.
- The second change is centered on the `pbench-server.service` file which is used by `systemd` to run the Pbench Server.  Part of it …
=> Miscellaneous fixes in support of a Containerized Pbench Server

lib/pbench/cli/server/__init__.py, lib/pbench/cli/server/tree_manage.py, lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/endpoint_configure.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/__init__.py, lib/pbench/server/api/resources/query_apis/datasets_delete.py, lib/pbench/server/api/resources/query_apis/datasets_publish.py, lib/pbench/server/api/resources/upload_api.py, lib/pbench/server/database/models/datasets.py, lib/pbench/server/filetree.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/database/test_datasets_db.py, lib/pbench/test/unit/server/database/test_datasets_metadata_db.py, lib/pbench/test/unit/server/query_apis/test_datasets_delete.py, lib/pbench/test/unit/server/query_apis/test_datasets_publish.py, lib/pbench/test/unit/server/test_endpoint_configure.py, lib/pbench/test/unit/server/test_file_tree.py, lib/pbench/test/unit/server/test_requests.py, server/Makefile, server/rpm/pbench-server.spec.j2, setup.cfg
The *delete* operation builds on the *publish* operation, but the bulk Elastic operation to delete all of the indexed Elastic documents is only the first stage; we also need to delete the `Dataset` DB row itself and the on-disk file structure representing the dataset (`ARCHIVE` tarball and MD5 file, the unpacked `INCOMING` tarball if any, and the `RESULTS` link).
To accomplish that, this PR adds a new module with a set of related classes to discover and manipulate the on-disk file structure, including the ability to create and delete datasets.
The create operation subsumes the operation of `pbench-server-prep-shim-002` so that it's no longer needed. (NOTE: this PR doesn't actually remove it, as the impact on the legacy test system felt like more churn than really necessary here, however …
=> Implement DELETE and re-implement PUT to no longer require `pbench-server-prep-shim-002`

agent/ansible/Makefile, agent/ansible/pbench/agent/galaxy.yml, agent/ansible/pbench/agent/meta/runtime.yml, agent/ansible/pbench/agent/roles/epel_repo_install/README.md, agent/ansible/pbench/agent/roles/epel_repo_install/tasks/main.yml, agent/ansible/pbench/agent/roles/pbench_agent_config/tasks/main.yml, agent/ansible/pbench/agent/roles/pbench_firewall_open_ports/tasks/main.yml
Two commits:
- the first one deals with a couple of changes that are needed to satisfy Galaxy: some whitespace changes, a missing role README and a `requires_ansible` directive.
- the second one decouples the firewall role from the `pbench_agent_config` role and makes it standalone.
New version of the pbench.agent collection has been uploaded to Galaxy and tested with RHEL9.
=> Cleanup of agent ansible roles

agent/util-scripts/pbench-copy-result-tb
This is a documentation issue, as the pbench-copy-result-tb neither documents its parameters well, nor diagnoses missing
or inappropriate parameters.
This is ultimately a minor issue as (first off) this is a utility command normally run indirectly by pbench-move-results or
pbench-copy-results and (secondly) it's specific to 0.69 and will be retired when we move to a 0.72 production server.
Nevertheless, the behavior can be somewhat improved both by expanding the `--help` message and by improving the diagnostics when we find missing parameters or unexpected data in the temporary tarball staging area.
Resolves #2437
=> pbench-copy-result-tb issue #2437

agent/base
When no tools are registered on the host, we can at least put a warning about it for the user to consider.
=> Add a warning message when no tools are registered

lib/pbench/test/functional/agent/cli/commands/test_cleanup.py, lib/pbench/test/functional/agent/cli/commands/tools/test_clear_tools.py
Several of our unit tests use a custom PyTest plug-in (aka a "[helper](https://pypi.org/project/pytest-helpers-namespace/)") called [`capture()`](https://github.com/distributed-system-analysis/pbench/blob/18b3814d82be22105caadab414fa92ea6d0f3981/lib/pbench/test/functional/conftest.py#L15).  This widget runs a command in a subprocess and returns the contents of `stdout` and `stderr` and the process exit code as a tuple.  As a brilliant example of why anonymous tuples are a bad idea, two of our unit tests contain invocations of the helper where the tuple is unpacked incorrectly and the identities of `stdout` and `stderr` are _reversed_.
This PR simply corrects the ordering of the unpacking, and swaps the references to the resulting streams, such that there is no functional change -- it's a …
=> Correct the plumbing of stderr and stdout in certain unit tests

lib/pbench/agent/base.py, lib/pbench/cli/agent/commands/tools/clear.py, lib/pbench/cli/agent/commands/tools/list.py, lib/pbench/cli/agent/options.py, lib/pbench/test/functional/agent/cli/commands/tools/test_clear_tools.py, lib/pbench/test/functional/agent/cli/commands/tools/test_tools_list.py
This PR is a once-over on `pbench-list-tools` and `pbench-clear-tools`:
- Fixed up docstrings.
- Tweaked and corrected the help text to match the actual functionality.
- Finish by calling the Click `exit()` function instead of `sys.exit()` (and fixed up the `import`'s accordingly).
- Picked lint (fixed import ordering, added an underscore prefix to unused parameters, added type hints).
- If a bad tool group is specified (e.g., to `pbench-clear-tools`, we print a message (with a slightly different formatting) and we no longer print the usage information.
- Added diagnostic messages to most cases where the tools previously exited silently; changed some of the existing messages to make them more useful to end-users.
- Reworked the `is_empty()` function.
- Only changed the unit tests to …
=> Small improvements to `pbench-list-tools` and `pbench-clear-tools`

agent/containers/images/Dockerfile.base.j2, agent/containers/images/Dockerfile.layered.j2, agent/containers/images/Makefile, agent/containers/images/gen-tags-from-rpm
The current build procedure for the Agent containers no longer works.  The first problem is that it insists upon cross-checking all of its default build targets, including Fedora 32 (even if the requested build doesn't include F32...), which doesn't work now that we've removed our support for Fedora 32 from COPR and COPR itself has deprecated Fedora 33 support.  The second problem is that its build targets are specific to the respective target platforms, and so adding a new platform requires cookie-cutter copying the existing targets to create targets for the new platform.
This PR makes the following changes:
- Replace the old cookie-cutter approach with generic templates and pattern rules.  With this change, the Makefile no longer refers to specific platforms or targets except in the …
=> Rework Agent containers build

agent/rpm/Makefile, agent/rpm/rpm.mk
Add a CHROOTS variable to the agent/rpm/Makefile and an option
to the `copr-cli build' command in rpm.mk, to allow
the specification of chroots to include or exclude in a build.
The default setting for the b0.69 branch excludes all RHEL9 builds:
the 0.69 agent does not work on RHEL9 because of an `scp -r' bug.
=> Add option to allow chroot specs for COPR builds (b0.69)

doc.html
Footer text content is overlapping the documentation text content.
To resolve it, just add margin-bottom equivalent to footer height
Old rendering:
New rendering:
.
=> Fixes footer content overlap issue

lib/pbench/agent/base.py, lib/pbench/test/functional/agent/cli/commands/conftest.py, lib/pbench/test/functional/agent/cli/commands/test_config.py, lib/pbench/test/functional/conftest.py
Fixes Issue #2473 
Checking and adding environment value before config file value for pbench-list-tools.
If an environment value for `pbench_run` is present then `pbench-register tool` considers env value and doesn't care about config file value, `pbench-list-tool` on-the-other hand only considers environment value of `pbench_run` if `pbench_run`'s value is None and take config file's value as default.
=> pbench-list-tools and pbench-register-tools inconsistency with env and config values

agent/base
The `hostname --ip-addresses` returns loopback and link-local addresses, which are not useful for agent communication and break the `ipaddress.ip_address()` parser. Instead, use `--all-ip-addresses` which provides similar results but corrects these weaknesses and does not depend on name resolution.
```
-i, --ip-address
Display  the  network  address(es)  of the host name. Note that this works only if the host name can be resolved. Avoid using this option; use
hostname --all-ip-addresses instead.
-I, --all-ip-addresses
Display all network addresses of the host. This option enumerates all configured addresses on all network interfaces. The  loopback  interface
and  IPv6 link-local addresses are omitted. Contrary to option -i, this option does not depend on name resolution. Do not make any …
```
=> Use --all-ip-addresses instead of --ip-address

lib/pbench/cli/agent/commands/tools/clear.py, lib/pbench/test/functional/agent/cli/commands/tools/test_clear_tools.py
Fixes issue #2337 
- Added support for comma-separated lists of `--name` and `--group` option on `pbench-clear-tools` command.
- Removes the tool group directory after a user clears all the tools from the group
=> Fixes for pbench-clear-tools potholes

agent/bench-scripts/pbench-fio, agent/bench-scripts/templates/make-fio-jobfile.py, agent/bench-scripts/tests/pbench-fio/test-04.opts, agent/bench-scripts/tests/pbench-fio/test-04.txt
The "ramp_time" option in fio includes the "\_" character, but currently
the "make-fio-jobfile.py" uses ramptime without the "\_" character
resulting in the default being used instead. Add the "\_" character to
the "make-fio-jobfile.py" while preserving the original in "pbench-fio"
to keep the compatibility.
=> Fix fio's "ramp_time" template handling

jenkins/Pipeline.gy, jenkins/python-setup.sh, jenkins/run
There are several small related issues here; one is that we currently require `--user=root` to run reliably, but we really don't actually "need" to be running our tests as root. This turns out to be mostly required because of the second issue, and with this change is no longer  required.
The main issue is that the container inherits the `HOME` environment variable; for example, in Jenkins, typically `/home/jenkins`. This value is used for `pip install --user` and to install our package with PBR for testing. Because `/home/jenkins` doesn't exist in the container, we require `root` to create the path. Instead, we'll now override the definition of `HOME` in order to redirect the `--user` to `/tmp/jenkins` which we can create without privilege.
In conjunction, this removes the default …
=> Improve Jenkins container run mechanism

server/bin/gold/test-5.2.txt, server/bin/pbench-tarball-stats.py, server/requirements.txt
Currently, the v0.69 branch testing is failing due to a non-determinism in the `server/bin/pbench-tarball-stats.py` output.  For parts of the report, the lists of servers are sorted; and, for other parts they are not.  This change adds the missing sort directives to the output template.
Fixes #2623.
=> Sort all items in the tarball stats report

jenkins/development.Dockerfile
Two quick updates for the Jenkins container (plus a cosmetic fix):
- Switch container registry for the base container from `docker.io` to `quay.io`
- Add `copr-cli` for building RPMs
=> Update the Jenkins development container

lib/pbench/common/selinux.py, lib/pbench/server/filetree.py, lib/pbench/test/unit/server/test_file_tree.py, server/bin/pbench-server-prep-shim-002.py, server/requirements.txt
Fixes #2645.
Basically, there is no real `selinux` python module provided via `pip` install. All that is out there is a "shim" [1], which is really broken.  On module load, it forks an invocation of the predominate `/usr/bin/python3` program [2] to get it's list of site packages, and replaces itself with a module load of the `selinux` module it finds among those site package locations.
The goal of that virtualenv wrapper is to allow a virtualenv using the same python version as the real installed `selinux` module to work "seamlessly."
But if your virtualenv is for a python version different from what is installed on the system, then the `selinux` import will fail with an error trying to load a module that doesn't work with the version of python in the virtualenv.
We no longer use the …
=> Stop using `selinux` virtualenv wrapper

agent/tool-scripts/datalog/mock-bin/oc, agent/tool-scripts/datalog/oc-datalog
The `oc-datalog` was not properly reaping its sub-processes, which left lingering processes after `tox -e datalog` test runs.  Since they would eventually timeout, it wasn't really noticeable.
We also fix the `mock-bin/oc` command to exec the `sleep 120` process so that it is properly reaped (the real `oc` handles its own sub-process clean up).
=> Fix `oc-datalog` to properly reap subprocesses

agent/rpm/pbench-agent.spec.j2
Basic RPM dependencies ensure that python3 and the pip module are always present when our `%post` script runs, however it seems that in some cases the pip3 command is not recognized. Instead, we invoke it directly using `python3 -m pip`.
This also means that the "pip bootstrap" sequence for RHEL 7 (which sometimes didn't "take") is no longer useful.
This modified spec file has been successfully tested on RHEL 7.9, RHEL 8.4, RHEL 9, and Fedora 34. (Though the Fedora 34 suffered from an unrelated pip issue as detailed in #2657.)
Resolves #2609
=> Simplify agent spec file

agent/rpm/pbench-agent.spec.j2, agent/util-scripts/gold/test-client-tool-meister/test-56.txt, agent/util-scripts/gold/test-client-tool-meister/test-57.txt, agent/util-scripts/pbench-tool-meister-start, agent/util-scripts/test-bin/ssh, lib/pbench/agent/utils.py
By default, TDS and Redis are started listening on (and remote hosts are set to connect to) the controller node's `hostname`. If this is not a routable DNS name, Tool Meister start hangs.
Instead, identify a routable IP address for the host by determining the origin of ssh connections to the remote hosts. We need to establish that the remotes are reachable anyway; this allows us to do so early in startup before creating the local TDS and Redis instances.
If "orchestration=create" mode isn't selected, or if `PBENCH_REDIS_SERVER` (`--redis-server`) or `PBENCH_TOOL_DATA_SINK` (`--too-data-sink`) configuration options are specified, these values are used regardless, trusting the external input.
Resolves #2610
=> Support non-DNS controller hosts

agent/Makefile
`pbench-run-benchmark` is a trampline bash script which sets up the environment and then transfers control to a Perl script, `pbench-run-benchmark.pl`.  (This seems to be a unique case in Pbench at the moment....)  Unfortunately, the target of the transfer was never added to the list of files to be installed.  This PR remedies that omission.
=> Add `pbench-run-benchmark.pl` to the Agent's installed files list

agent/util-scripts/gold/test-client-tool-meister/test-53.txt, agent/util-scripts/gold/test-client-tool-meister/test-56.txt, agent/util-scripts/gold/test-client-tool-meister/test-57.txt, agent/util-scripts/gold/test-start-stop-tool-meister/test-51.txt, agent/util-scripts/gold/test-start-stop-tool-meister/test-52.txt, lib/pbench/agent/tool_meister.py
Fixes issue #2085 
- Deletes persistent tool tmp directory on remote hosts when end_tools is called 
- Instead of writing persistent tool local logs on a remote file system, send them to TM via tool data sink on redis channel.
=> Remove persistent tmp directory on remote hosts

agent/test-requirements.txt, lib/pbench/server/api/__init__.py, lib/pbench/test/__init__.py, lib/pbench/test/functional/agent/cli/commands/test_config.py, lib/pbench/test/functional/agent/conftest.py, lib/pbench/test/functional/agent/test_pbench_config.py, lib/pbench/test/unit/agent/conftest.py, lib/pbench/test/unit/agent/task/test_add_metalog_option.py, lib/pbench/test/unit/agent/task/test_copy_result_tb.py, lib/pbench/test/unit/agent/task/test_generate_token.py, lib/pbench/test/unit/agent/task/test_make_result_tb.py, lib/pbench/test/unit/agent/task/test_results_move.py, lib/pbench/test/unit/agent/task/test_results_push.py, lib/pbench/test/unit/agent/test_config.py, lib/pbench/test/unit/agent/test_tool_data_sink.py, lib/pbench/test/unit/agent/test_utils.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/test_requests.py, lib/pbench/test/unit/server/test_user_auth.py, lib/pbench/test/unit/server/test_user_management_cli.py, server/test-requirements.txt
Lots of little changes towards a test suite which can be parallelized.
The first change is to remove the use of the session scoped `pytestconfig`.  Session scoped fixtures make it difficult to share them across test sub-systems (one has to be aware of how different sub-systems will interact, which is prone to error).
As a result of dropping `pytestconfig`, `tmp_path` is used instead to give us a proper temporary directory using a fixture that can handle the coming parallelism.
In order to share fixtures between the agent unit and functional tests, a separate on-disk config method allows both fixtures to leverage the disk setup which is fixed and common.  The environment variable monkey-patching is moved to non-session scoped fixtures.
A similar discipline is applied to the server-side …
=> Scrub the pytests

agent/util-scripts/gold/test-client-tool-meister/test-56.txt, agent/util-scripts/gold/test-client-tool-meister/test-57.txt, lib/pbench/agent/tool_meister.py
The recent PR #2661 (commit 487f4ba) added reporting of left-over files in the Tool Meister's temporary directory.  But if the file-system discovery operation happens to return them in a different order than the unit tests are expecting test 56 and 57 of the agent 'util-scripts' tests will fail.
=> Ensure agent legacy unit tests pass

agent/bench-scripts/tests/Defaults/pbench-agent.cfg, agent/config/pbench-agent-default.cfg, agent/config/pbench-agent.cfg, agent/util-scripts/pbench-copy-result-tb, agent/util-scripts/pbench-move-results, contrib/containerized-pbench/dockerfiles/controller/run.sh, lib/pbench/test/unit/agent/config/pbench-agent.invalid.cfg, lib/pbench/test/unit/agent/conftest.py, server/lib/config/pbench-server-default.cfg
Remove references to the `pbench_results_redirector` configuration setting.
The configuration setting was not used, and it was incorrectly spelled in the default agent config file.  As a result of removing that, we also remove unnecessary `webserver` and `host_path` variables.
Found while reviewing PR #2663.
=> Remove references to the `pbench_results_redirector` configuration setting

.github/ISSUE_TEMPLATE/bug.yaml
This is an effort to standardize bug reporting.
Now onward while filing a bug one has to answer set of questions, which will avoid vague(unclear) bug reports.
This change will help us understand bug easily without having lot of Q&A in the thread.
Note:
- If you want to try out working page of this PR, visit [link](https://github.com/vishalvvr/pbench/issues/new/choose) and click "Get Started", also feel free to file a bug and see how it files an issue :) 
- This is a feature by GitHub called "issue forms", if you want to explore more options refer [syntax](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) page.
=> add bug report issue form

lib/pbench/server/database/models/template.py, lib/pbench/test/unit/server/database/test_datasets_db.py
When the server unit tests run in parallel, there is something about how the Database.base class is modified to have a "logger" that is not working.
It seems a bad idea in general to do this kind of logging in a database class, and we should have the logging at the consumers of the database object.  Given the unit tests are not affected by this change, seems like it is a good opportunity to make this kind of a change.
We also fix a wayward server test.
=> Remove references to logger method of base class

agent/test-requirements.txt, exec-unittests, jenkins/development.Dockerfile.j2, server/bin/unittests, server/bin/utils/run-unittest, server/test-requirements.txt, tox.ini
Parallelize the python & legacy unit tests
We add the use of `pytest-xdist`, which allows us to pick the level of parallelism via the `-n` switch.  By default we use `-n auto` where it determines the parallelism to use based on the number of CPUs.
Use `parallel` to run all the legacy tests.  Each agent legacy sub-test is run as a separate parallel job, and then all the server tests are individually run through GNU `parallel`.
To facilitate the use of `parallel` for the server legacy tests, we break out the core server test harness out into a separate script. This helps to isolate the way tests are run from how the parallelism is achieved.
We also take the opportunity to use `local` in the various `bash` scripts, and make variable references consistent.
Finally, we address `mkdir -p` usage …
=> Parallelize `tox` invocations

lib/pbench/agent/tool_meister.py
With commit 487f4baf1 (PR #2661), the persistent tool sub-process no longer uses on-disk tool output files.
Since those output files are no longer created, we have to remove the remaining references to them when logging a warning message regarding failed persistent tools.  Without this change, the Tool Meister would crash with an exception being raised for missing files.
=> Remove refs to non-existent persistent tool files

tox.ini
This does not help the Jenkins CI job much, since we are using an ephermal mount for the virtualenvs.  It does help a little bit for local development environments.
=> Use an explicit cache directory for pip installs

agent/util-scripts/gold/test-client-tool-meister/test-53.txt, agent/util-scripts/gold/test-client-tool-meister/test-56.txt, agent/util-scripts/gold/test-client-tool-meister/test-57.txt, agent/util-scripts/unittests, lib/pbench/agent/tool_meister.py
If a sub-process that the Tool Meister creates does not terminate correctly, it can cause problems.  One such issue, described in issue #2692, was the result of the `subprocess.kill()` method working but not taking effect immediately.
The algorithm used now is:
1. `subprocess.terminate()`
2. wait with timeout
3. `subprocess.kill()`
4. wait with timeout
5. close process file descriptors
As part of this work, and to help facilitate the proper closing of the sub-process file descriptors, we setup read threads for logging all the stout/stderr data coming from the sub-proceses.
Partial fix for #2691.
=> Correct Tool Meister sub-process termination

agent/util-scripts/pbench-tool-meister-start, agent/util-scripts/test-bin/ssh, agent/util-scripts/test-bin/test-client-tool-meister, lib/pbench/agent/tool_data_sink.py, lib/pbench/agent/tool_meister.py, lib/pbench/common/logger.py
The remote Tool Meister has a defined environment variable to override the default "INFO" debug level; however it was not propagated to the remote over ssh. This adds a command line parameter to directly pass the value to the remote.
The same logic was replicated in the Tool Data Sink; although "create" orchestration always forks this on the same host, this allows a simple and consistent command line hook to enable debug log messages when a client launches either command directly via "existing" orchestration.
This code isn't as elegant as I'd like, but in the name of minimizing the size and mess, I'm going to stop here. I'm hoping to refactor a class out of the `start` methods in both `tool_meister.py` and `tool_data_sink.py`, probably with a common base class to encapsulate some …
=> Use debug-level environment variables

agent/base, lib/pbench/agent/base.py, lib/pbench/test/functional/agent/cli/commands/test_config.py
Issue #2665 
If the `pbench_run` directory specified in pbench_agent config on remote host does not exist, we need to create it. 
We create it in our `lib/pbench/agent/base.BaseCommand` class if the directory does not exists already, however, if the same happens when running `agent/base` file we exit. I think we need to be consistent with our `pbench_run` directory creation.
If any script that runs `agent/base` file and need `pbench_run` directory, the base file will create it (if it does not exists already) when it creates the `tmp` directory (`"$pbench_run/tmp"`)
=> Create pbench_run directory on remote if it doesn't exists

agent/ansible/Makefile, agent/ansible/pbench/agent/Makefile, agent/ansible/pbench/agent/ansible-lint.yml, agent/ansible/pbench/agent/check-readmes, agent/ansible/pbench/agent/galaxy.yml, agent/ansible/pbench/agent/roles/epel_repo_install/tasks/main.yml, agent/ansible/pbench/agent/roles/pbench_agent_config/tasks/main.yml, agent/ansible/pbench/agent/roles/pbench_agent_files_install/tasks/main.yml, agent/ansible/pbench/agent/roles/pbench_agent_install/tasks/main.yml, agent/ansible/pbench/agent/roles/pbench_clean_yum_cache/tasks/main.yml, agent/ansible/pbench/agent/roles/pbench_firewall_open_ports/tasks/main.yml, agent/ansible/pbench/agent/roles/pbench_repo_install/tasks/main.yml
- Modify the roles to pacify ansible-lint and yaml-lint.
- Add a skip list for ansible-lint: a couple of its tests cannot be
satisfied with the current roles.
- Add a Makefile to run these two, and also to check that there is a
README.md file for every role (as well as a top level README.md and
one in the plugins subdir).
- Invoke the above Makefile's default target from the main Makefile in
agent/ansible when testing the collection before it is sent to
Ansible Galaxy. Galaxy is very picky in what it accepts, so it
behooves us to find as many problems as possible *before* sending.
=> Add linting support for agent ansible roles

lib/pbench/agent/base.py
In `lib/pbench/agent/base.py`, the `ssh_opts` and `scp_opts` fields were not being set correctly, and the `date_suffix` had the wrong formatting; we also create `pbench_tmp` using `pathlib`
=> Bring `BaseCommand` behaviors inline with `base`

agent/base, agent/util-scripts/pbench-tool-meister-start, agent/util-scripts/pbench-tool-meister-stop, lib/pbench/agent/utils.py, lib/pbench/common/utils.py, lib/pbench/server/api/resources/upload_api.py, lib/pbench/test/__init__.py, lib/pbench/test/functional/agent/conftest.py, lib/pbench/test/unit/agent/conftest.py, lib/pbench/test/unit/common/test_utils.py, lib/pbench/test/unit/server/conftest.py
This provides `pbench-tool-meister-start` with a framework to consistently and reliably handle errors that occur during the startup process, including a `KeyboardInterrupt` exception. The structured cleanup recovery mechanism from the server PUT operation has been generalized and is leveraged here to ensure orderly shutdown.
The `pbench-tool-meister-stop` command is improved to be a bit more friendly when `--interrupt` is used to signal that it's not a normal termination (e.g., allowing that the "end" command may fail because clients might be in running state).
Behavior of bash benchmark scripts that use Tool Meister are improved with a change to the agent `base` interrupt handler, which now exits rather than returning back into the benchmark code after shutting down the Tool Meister. …
=> Keyboard interrupt handling

agent/bench-scripts/pbench-trafficgen
The old TrafficGen repo has moved:
* From: https://github.com/atheurer/trafficgen.git
* To: https://github.com/perftool-incubator/bench-trafficgen.git
The new installed location is now `/opt/bench-trafficgen/trafficgen`.
=> Move to `perftool-incubator/bench-trafficgen`

agent/base, lib/pbench/agent/base.py
Fixes issue #2665.
We have to unconditionally create the `${pbench_run}` directory in `agent/base` (and `lib/pbench/agent/base.py` to maintain parallel behavior) because too many scripts depend on its existence for their correct function.
In particular, there are bench-scripts which try to report errors but if the `${pbench_run}` directory does not exist already, the `${pbench_log}` file location won't exist and the actual error is lost.
Rather than trying to fix the myriad number of places with this assumption, it is best to just create the directory to meet the assumed state.
=> Ensure `${pbench_run}` directory exists

agent/base, agent/config/pbench-agent-default.cfg
sometimes people might need to disable the "check_install_rpm" check to
use non-rpm tools or tool of a different version. Let's add an
environment variable "PBENCH_IGNORE_CHECK_INSTALL_RPM" to ignore
check_install_rpm failures while adding a note to the log about
not-running-the-expected-tool-version so people need to reproduce with
the expected tool version to file issues.
=> Add environment variable to ignore check_install_rpm

agent/tool-scripts/base-tool
Pulled out as a separate commit from PR #2659.  If you have a `local` statement for a variable where that variable is assigned the result of executing a command, `${?}` will always have a `0` (success) since the `local` statement records its success after the command execution.
=> Correct `check_required_rpm` behavior

lib/pbench/agent/tool_meister.py, lib/pbench/test/unit/agent/test_tool_meister.py
Part of an issue https://github.com/distributed-system-analysis/pbench/issues/2692 
Addresses Peter's comment about retrying the tar command if we encounter an error for the first time
> Let's ignore all warnings on the re-try only. Something like `tar --warning=none`, so that we capture the errors when we try the first time, but the tar up whatever we can on the re-try. And we should do something to remark in the data collection that we encountered warnings on the initial `tar` command.
=> re-try tar command if we encounter an error

agent/util-scripts/pbench-tool-meister-start, lib/pbench/agent/results.py, lib/pbench/agent/tool_data_sink.py, lib/pbench/agent/tool_meister.py
Fixes issue #2724 (deprecation of `find_executable` in Python 3.11).
=> Replace `find_executable` with `shutil.which`

lib/pbench/agent/base.py
Mistake that was noticed in https://github.com/ldoktor/pbench/pull/3, but had existed for a while.
=> Replace `sys.exit()` w `click._.exit()`

agent/util-scripts/pbench-tool-meister-start, lib/pbench/agent/utils.py, lib/pbench/test/unit/agent/test_utils.py
Instead of lobbing a "terminate" message and then almost immediately killing the TDS and Redis, wait (for up to 60 seconds) for the TDS to terminate on its own, giving it time to contact the remote clients and shut down gracefully.
PBENCH-158 #in-progress #time 3h
=> PBENCH-158 Wait for TDS to terminate gracefully

agent/util-scripts/pbench-tool-meister-start
Currently the `args` parameter is required, though this code is not tested in our unit tests.
=> Ensure `args` parameter is sent on terminate

agent/util-scripts/gold/test-client-tool-meister/test-53.txt, agent/util-scripts/gold/test-client-tool-meister/test-56.txt, agent/util-scripts/gold/test-client-tool-meister/test-57.txt, lib/pbench/agent/tool_meister.py, lib/pbench/test/unit/agent/test_tool_meister.py
We were running the constructor for each Tool object once to run the `install()` method, and then again for each "init" and "start" operation.
Now the Tool object constructor runs once, and all code used to determine if a tool is installed correctly results in the `install()` method.
=> Refactor `ToolMeister` to construct Tools once

lib/pbench/agent/constants.py, lib/pbench/agent/tool_data_sink.py
In order to enable other work that relies on the Tool Meister data collected by the Tool Data Sink, we set the "tool-meister-data" key in Redis without any other changes.
This pulls out a very small portion of work from PR #2659.
=> Record the Tool Meister data in Redis

agent/rpm/pbench-agent.spec.j2, agent/rpm/rpm.mk
All distros of interest now make perl-JSON-XS available either in
EPEL (for RHEL7) or in the CRB repo (for RHEL8 and above). The Fedoras
always had it available.
Delete obsolete targets in rpm.mk.
=> Get rid of the `pbench-perl-JSON-XS` dependency

agent/util-scripts/gold/test-client-tool-meister/test-53.txt, agent/util-scripts/gold/test-client-tool-meister/test-56.txt, agent/util-scripts/gold/test-client-tool-meister/test-57.txt, agent/util-scripts/test-bin/mock-cmd, agent/util-scripts/tool-meister/pbench-sysinfo-dump, agent/util-scripts/unittests, lib/pbench/agent/tool_meister.py
There are two environment variables provided by the `agent/base` script which `pbench-sysinfo-dump` was relying on to have in place.  One was explicitly set by the Tool Meister in the environment used to run the script, `pbench_install_dir`, the other was inherited, `_pbench_full_hostname`.
We change `pbench-sysinfo-dump` to use `sysinfo_install_dir` and `sysinfo_full_hostname` instead, with the Tool Meister setting those environment variables explicitly.
We also take the opportunity to remove a useless `_PBENCH_UNIT_TESTS` reference which is not used due to the existence of the mock, `agent/util-scripts/test-bin/pbench-sysinfo-dump`.
=> Remove `pbench-sysinfo-dump` reliance on `base`

agent/util-scripts/gold/test-client-tool-meister/test-53.txt, agent/util-scripts/gold/test-client-tool-meister/test-56.txt, agent/util-scripts/gold/test-client-tool-meister/test-57.txt, agent/util-scripts/gold/test-client-tool-meister/test-61.txt, agent/util-scripts/gold/test-start-stop-tool-meister/test-51.txt, agent/util-scripts/gold/test-start-stop-tool-meister/test-52.txt, agent/util-scripts/unittests, lib/pbench/agent/tool_meister.py, lib/pbench/agent/tool_meister_start.py, lib/pbench/agent/tool_meister_stop.py
In anticipation of the "big hammer" Tool Meister sub-system work, we simplify the PID file names used to make them easy to determine.
Layered on top of PR #2757.
=> Simplify PID file names used by TM sub-system

contrib/analysis/README, contrib/analysis/collect_config_data.py, contrib/analysis/create_sos_with_runids.py, contrib/analysis/merge.py, contrib/analysis/merge_sos_and_perf_parallel.py, contrib/analysis/script.sh
This contains all the steps needed to combine the indexed Pbench data and on-disk configuration data. The output is a set of `.csv` files for each different `fio` result type.  Each `.csv` file contains workload metadata, configuration data and performance results. For example, you may see the following files generated as a result of running `script.sh`:
* `latency_clat.csv`
* `latency_lat.csv`
* `latency_slat.csv`
* `throughput_iops_sec.csv`
=> Steps to collect pbench-fio data

lib/pbench/test/unit/server/conftest.py, server/bin/utils/run-unittest
The `email_validator` package just upgraded to 1.2, which implements stricter validation and in particular now rejects the "@example.com" addresses used in our unit tests.
This adds a mock to replace use of the real `email_validator` package in unit testing so that we're in control (as we should be for all external dependencies). The legacy test fake users are created as `${user}.fake.user@redhat.com` to get by the domain validation and minimize the chances of accidentally using a real alias.
=> Fix unit testing for email_validator

lib/pbench/cli/server/shell.py, server/rpm/pbench-server.spec.j2
PBENCH-504
This is a small change to permanently add error and access logging to our gunicorn server infrastructure: something I've done ad-hoc many times to triage problems and just did yesterday twice during a long session helping Siddardh get his development VM set up (both on his VM and on mine, trying to figure out how I broke a Postman query).
I think we want to aim for something more "elegant", perhaps integrating gunicorn logging into our pbench-server syslog stream; but until someone gets motivated to work that out, this is simple and effective. (And better than nothing... or rather, better than repeatedly undoing "nothing" manually.)
(Note, it's also an experiment in trying to link to Jira from a ticket reference that's not in the header line of a git commit.)
=> Add gunicorn logging

lib/pbench/cli/agent/commands/results/push.py, lib/pbench/common/utils.py, lib/pbench/test/unit/agent/task/test_make_result_tb.py
It turns out that _almost_ all callers of `md5sum()` pass in a `Path`, despite the fact that we declare it to accept a `str`.  Python's "duck typing" allows this to work, because what we actually require is a "path-like", and both `str`'s and `Path`'s qualify...but it's unsatisfying.  This PR makes it clear that `md5sum()` accepts a `Path` (and fixes the two inconsistent usages).
=> Clarify that md5sum() takes a Path not a string

jenkins/ci.fedora.Dockerfile
Not sure how this was working up to now, except that the existing image was not built from this latest sources.
=> Fix CI build image

.github/workflows/codeql-analysis.yml
This is not ideal, but it looks like we have to add the names of branches to this file *in* the branches where this file lives.  Ick.
=> Enable CodeQL only for `main` branch

contrib/analysis/README, contrib/analysis/collect_config_data.py, contrib/analysis/create_sos_with_runids.py, contrib/analysis/merge.py, contrib/analysis/merge_sos_and_perf_parallel.py, contrib/analysis/script.sh
----
`contrib/analysis/script.sh`: Steps to collect pbench-fio data.
Contains all the steps needed to combine the indexed Pbench data and
on-disk configuration data. The output is a set of `.csv` files for each
different fio result type. Each `.csv` file contains workload metadata,
configuration data and performance results. For example, you may see the
following files generated as a result of running `script.sh`.
* `latency_clat.csv`
* `latency_lat.csv`
* `latency_slat.csv`
* `throughput_iops_sec.csv`
The steps taken are listed in `script.sh`.
----
`contrib/analysis/merge_sos_and_perf_parallel.py`: Step 1 of `script.sh`
Responsible for generating a set of JSON documents for the "fio" runs
to consider, the sosreports related to those runs, and the disk used by
those runs.
---- …
=> Initial commit for merging sos and result data

agent/rpm/pbench-agent.spec.j2
Fixes #2798
AFAICT, the python3-devel dependency (which only exists for RHEL7) is
spurious and in fact harmful: there seems to be no python3-devel
package for RHEL7.9, so installation fails with an unsatisfied
dependency, whereas an RPM built without it installs without
problems.
=> Delete the spurious pbench3-devel RPM dependency

agent/rpm/pbench-agent.spec.j2
Fixes #2798
This is a backport of #2799 to b0.71.
AFAICT, the python3-devel dependency (which only exists for RHEL7) is
spurious and in fact harmful: there seems to be no python3-devel
package for RHEL7.9, so installation fails with an unsatisfied
dependency, whereas an RPM built without it installs without
problems.
=> b0.71 backport: Delete the spurious pbench3-devel RPM dependency

lib/pbench/server/api/resources/endpoint_configure.py, lib/pbench/test/unit/server/test_endpoint_configure.py
PBENCH-642
Now that we have a complete "V1" API, there's no further need for the server to help clients access the server's Elasticsearch indices directly; it's time to remove the index information from the endpoints configuration response.
=> Remove "indices" section from endpoints API response

lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/datasets_list.py, lib/pbench/server/api/resources/datasets_metadata.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/datasets_contents.py, lib/pbench/server/api/resources/query_apis/datasets/datasets_mappings.py, lib/pbench/server/api/resources/query_apis/datasets/namespace_and_rows.py, lib/pbench/server/api/resources/query_apis/datasets_detail.py, lib/pbench/test/unit/server/query_apis/test_datasets_contents.py, lib/pbench/test/unit/server/query_apis/test_datasets_delete.py, lib/pbench/test/unit/server/query_apis/test_datasets_mappings.py, lib/pbench/test/unit/server/query_apis/test_datasets_publish.py, lib/pbench/test/unit/server/query_apis/test_namespace_and_rows.py
As mentioned in [#2529](https://github.com/distributed-system-analysis/pbench/issues/2529) comments,
Implemented fix  for this `/datasets/contents` API request :
- Moved `abort()` to the top-level API handling function
- Implemented an `InvalidAPIRequest` Exception.
- Created multiple unit tests for this API based on various edge cases with run_id
Resolves #2529
=> Move abort() call to top-level API handling

lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/query_apis/datasets_search.py, lib/pbench/server/api/resources/upload_api.py, lib/pbench/server/api/resources/users_api.py, lib/pbench/server/database/models/datasets.py, lib/pbench/server/filetree.py, lib/pbench/server/utils.py, lib/pbench/test/unit/server/test_datasets_list.py, lib/pbench/test/unit/server/test_requests.py, lib/pbench/test/unit/server/test_utils.py
PBENCH-638
SQLAlchemy stores SQL dates in "naive UTC" by default; add logic to make this explicit and to add adjustment of aware dates on input and creation of aware UTC dates on retrieval.
Adopt ISO 8601 formatting for dates reported through the API. (This does not include a rigorous analysis of Elasticsearch data, although at least some already appear in ISO 8601 UTC.)
=> Convert server APIs to ISO 8601 UTC dates

lib/pbench/server/api/resources/query_apis/datasets/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/datasets_contents.py, lib/pbench/server/api/resources/query_apis/datasets/datasets_mappings.py, lib/pbench/server/api/resources/query_apis/datasets/namespace_and_rows.py, lib/pbench/test/unit/server/query_apis/test_datasets_contents.py, lib/pbench/test/unit/server/query_apis/test_namespace_and_rows.py
PBENCH-644
To align with the service layer of the old dashboard, the search, mappings, and contents APIs were designed to identify datasets using the Elasticsearch run document MD5 (run_id or run.id) rather than the more straightforward model of relying on the dataset name.
As we approach the verge of using TOC data in the new dashboard, fixing this seems timely.
=> Fix "index map" APIs to use dataset name

lib/pbench/agent/tool_meister.py
From testing we noticed that the `start()` method was not properly returning the exit code from the `driver()` method.  We also remove the gaps in the error codes returned.
=> Fix Tool Meister instance exit code handling

lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/datasets_list.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/__init__.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/query_apis/test_datasets_delete.py, lib/pbench/test/unit/server/query_apis/test_datasets_publish.py, lib/pbench/test/unit/server/test_authorization.py
PBENCH-646
User authorization via ApiBase._check_authorization has always used the "raw" specified username string from the client. It makes more sense to use the validated internal form (the stringified DB row ID), and this in particular will simplify handling of a username that appears in a URL query parameter.
Resolves #2824
=> Convert authorization to use ID rather than string

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/datasets_daterange.py, lib/pbench/server/api/resources/datasets_list.py, lib/pbench/server/api/resources/datasets_metadata.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/test_datasets_daterange.py, lib/pbench/test/unit/server/test_datasets_list.py, lib/pbench/test/unit/server/test_endpoint_configure.py
PBENCH-643
Add a new `datasets/daterange` API to return the earliest and latest creation date of datasets readable by the authenticated user and with specified owner and access filters.
=> New API to fetch date range of accessible datasets

lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/test/unit/server/query_apis/test_datasets_delete.py, lib/pbench/test/unit/server/query_apis/test_datasets_publish.py, lib/pbench/test/unit/server/test_datasets_list.py, lib/pbench/test/unit/server/test_schema.py
PBENCH-648
When I deployed my new server, I found that doing an unauthorized `/datasets/list` query was failing with 500. This is because the `UnauthorizedAccess` exception is handled only in `_dispatch` where we authorized automatically based on a JSON body payload.
My original "vision" had been to make both `UnauthorizedAccess` and `SchemaError` extend `APIAbort` to simplify the logic, but I lost track of that during the review. This PR fixes that, and streamlines the error logic a bit.
=> Fix GET /datasets/list authorization

lib/pbench/agent/tool_meister.py, lib/pbench/agent/tool_meister_start.py, lib/pbench/agent/utils.py
This PR consists of two commits:  the first is a bunch of lint-pickings; the second is some quick fixes for problems identified during the v0.71 Test Day (and subsequent code review):
- a mis-handling of the return status in the `_wait_pid()` function in `tool_meister_start.py`;
- a change to raise an exception if the TDS daemon-child process fails before detaching itself; and,
- a change to raise an exception if the TDS PID file is missing after start up.
I recommend reviewing the commits individually.  The second (and only the second) commit should be backported to v0.71.
(Several of the changes originally in this PR landed in #2797.)
=> Quick v0.71 fixes

lib/pbench/server/api/resources/query_apis/datasets/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/datasets_mappings.py, lib/pbench/server/database/models/template.py, lib/pbench/test/unit/server/query_apis/test_datasets_mappings.py
Remove bit of redundancy in `dataset_mappings` for getting ES mapping properties.
=> Remove minor redundancy in datasets mappings

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/datasets_metadata.py, lib/pbench/test/unit/server/test_datasets_metadata.py, lib/pbench/test/unit/server/test_endpoint_configure.py
PBENCH-669
We started out with all parameters in a JSON request payload to `POST` operations following Elasticsearch conventions. While some new APIs have used both query parameters and embedded Flask URL parameters, there are older APIs that should be retrofitted to that model.
In this PR, I'm addressing `/datasets/metadata` (which seems like a good place to start as the Overview page is on the cusp of using it).
In particular, we'll now `GET`|`PUT` `http://<server>/api/v1/datasets/metadata/<name>`. rather than specifying the dataset name with `?name=<name>`.
=> Move towards embedded URL parameters: metadata

lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/datasets_metadata.py, lib/pbench/server/database/models/datasets.py, lib/pbench/server/database/models/users.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/database/test_datasets_metadata_db.py, lib/pbench/test/unit/server/test_datasets_metadata.py
PBENCH-645
This change re-purposes the `user.*` Dataset Metadata namespace as a per-user key space, where each authenticated client with READ access to a given dataset will be able to write independent metadata attached to that dataset. (Only the owner has UPDATE access to change the "global" metadata keys in the "dashboard.*" namespace.)
At the Metadata internal class level, methods now allow specifying a `User` to associate each item of metadata. At the API level, the user is always the authenticated user (or None for only global metadata).
An unauthenticated client can ask for `user.*` keys, but the value will always be None as authenticated clients will never create global values for the `user.*` namespace and unauthenticated clients can't ever set metadata values.
=> New user metadata namespace for Overview page

agent/util-scripts/gold/test-client-tool-meister/test-53.txt, agent/util-scripts/gold/test-client-tool-meister/test-56.txt, agent/util-scripts/gold/test-client-tool-meister/test-57.txt, agent/util-scripts/gold/test-client-tool-meister/test-61.txt, agent/util-scripts/gold/test-start-stop-tool-meister/test-51.txt, agent/util-scripts/gold/test-start-stop-tool-meister/test-52.txt, lib/pbench/agent/tool_group.py, lib/pbench/agent/tool_meister_start.py
We archive the valid tool group data when we start the Tool Meister sub-system so that we have a record of the inputs used during orchestration.  We don't want to rely on the Tool Data Sink to save that for us.
=> Archive the input tool group data during start

agent/bench-scripts/pbench-specjbb2005, agent/bench-scripts/test-bin/java, agent/bench-scripts/tests/pbench-specjbb2005/test-56.pre, agent/bench-scripts/tests/pbench-specjbb2005/test-56.txt, agent/bench-scripts/tests/pbench-specjbb2005/test-57.txt, agent/bench-scripts/unittests
If the `SPECjbb.props` file has a commented out line we now uncomment it to ensure the requested behaviors take effect.
=> `pbench-specjbb2005` now handles commented props

lib/pbench/agent/tool_meister_stop.py, lib/pbench/test/unit/agent/test_tool_meister_stop.py
When `pbench-tool-meister-stop` is invoked where the Redis server was created locally by `pbench-tool-meister-start`, we always want to use the `localhost` IP address to talk to it.
Fixes issue #2861.
=> Ensure use of `localhost` when stopping Redis

agent/containers/images/Dockerfile.base.j2, agent/containers/images/Dockerfile.layered.j2, agent/containers/images/Makefile, server/containers/images/Dockerfile.base.j2
CentOS Stream 9 has new requirements for where we pull RPMs from, particularly for PCP and Prometheus.  This PR makes the changes required to build the Agent container images for `centos-9`.
=> Tweak container builds for CentOS Stream 9

lib/pbench/cli/agent/commands/generate_token.py
While the server responds to requests with a JSON payload, even for errors, not all responses come from the server.  (E.g., in the event that the server is unresponsive (e.g., because it's not running), the proxy will respond with a `408/Request Timeout`.)  This PR adds a little bit of defense to `generate_token.py` where we decode the response payload.
@dbutenhof, can you give this a try?
Fixes #2839.
=> Handle response payloads which are not JSON in generate_token.py

agent/bench-scripts/driver/linpack, agent/bench-scripts/test-bin/uperf
The review of the back-port PR #2867 found a couple of minor fixes that also need to be applied to `main`.
=> Apply some minor fixes found in review

lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/datasets_list.py, lib/pbench/server/api/resources/datasets_metadata.py, lib/pbench/server/api/resources/query_apis/datasets_detail.py, lib/pbench/server/database/models/datasets.py, lib/pbench/test/unit/server/database/test_datasets_db.py, lib/pbench/test/unit/server/database/test_datasets_metadata_db.py, lib/pbench/test/unit/server/test_datasets_list.py, lib/pbench/test/unit/server/test_datasets_metadata.py, lib/pbench/test/unit/server/test_schema.py
PBENCH-448
This allows API clients to access the entire "dataset" and "server" key namespaces just like "user" and "dashboard"; e.g., to ask for "dataset" to get all the dataset SQL columns as a JSON document.
This also paves the way to adding a full representation of the agent's metadata.log metadata without requiring a specific defined and validated key path for each item.
=> Expand and generalize metadata namespace

agent/rpm/pbench-agent.spec.j2
Both the `pbench-uperf` and `pbench-linpack` commands offer interfaces that rely on `numactl`.
=> Add `numactl` RPM requirement

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/datasets_contents.py, lib/pbench/server/api/resources/query_apis/datasets_delete.py, lib/pbench/server/api/resources/query_apis/datasets_publish.py, lib/pbench/test/unit/server/query_apis/test_datasets_contents.py, lib/pbench/test/unit/server/query_apis/test_datasets_delete.py, lib/pbench/test/unit/server/query_apis/test_datasets_publish.py, lib/pbench/test/unit/server/test_endpoint_configure.py
This PR addresses the remaining items for our efforts to move the resource (dataset name) from a JSON payload to the URI parameter. 
\
Commit_1: Add the dataset resource name to the URI as `/datasets/delete/<dataset>` PBENCH-673
Old: 
```
POST /datasets/delete
{name: <dataset_name>}
```
New: 
```
POST /datasets/delete/<dataset_name>
```
\
Commit_2: Add the dataset resource name to the URI as `/datasets/publish/<dataset>` PBENCH-674
Old: 
```
POST /datasets/publish
{"name": <dataset_name>, "access": <public/private>}
```
New: 
```
POST /datasets/publish/<dataset_name>
{"access": <public/private>}
```
\
Commit_3: Add the dataset resource name to the URI as `/datasets/contents/<dataset>` PBENCH-675
Old: 
```
POST /datasets/contents
{"name": <dataset_name>, "parent": <dataset_parent_name>} …
```
=> PBENCH-667: Use URI parameterization where reasonable

doc/RELEASE_NOTES.md
This new file, `RELEASE_NOTES.md`, is being added to the `/doc` sub-directory so that we can code-review the contents of the release notes like we would any other code change.
The contents of the file will be used for the contents of the [Alpha](https://github.com/distributed-system-analysis/pbench/releases/edit/v0.71.0-alpha.0), [Beta](https://github.com/distributed-system-analysis/pbench/releases/edit/v0.71.0-beta.0), and final releases pages on GitHub.
=> Release Notes for `v0.71.0`

lib/pbench/server/api/resources/upload_api.py, lib/pbench/server/database/models/datasets.py, lib/pbench/server/filetree.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/database/test_datasets_db.py, lib/pbench/test/unit/server/database/test_datasets_metadata_db.py, lib/pbench/test/unit/server/test_datasets_metadata.py, lib/pbench/test/unit/server/test_requests.py
PBENCH-682
The filetree code was already parsing metadata.log in order to obtain the "created" timestamp. This PR formalizes that a bit, converting the entire config hierarchy (sections/settings) as a JSONOBJECT, which is persisted in SQL as a "metalog" key value for the dataset.
The "metalog" key value is exposed as a key in the "dataset" namespace, so that `/datasets/list?metadata=dataset` will return it as part of the JSON representation of the primary Dataset SQL row. As with any other metadata namespace, segments can be addressed directly, e.g., `dataset.metalog.run.controller`.
NOTE: I'm not deeply in love with the name "metalog"; however I didn't want to use the obvious "metadata" as it'll all appear nested inside the outer "metadata" key. I'm open to alternate suggestions! …
=> Expose tarball metadata.log values through API

lib/pbench/test/unit/agent/test_tool_group.py
PBENCH-666
Adding Unit Tests for ToolGroup. Part of PbenchAgent Test Coverage
=> Adding Unit Tests for ToolGroup

agent/rpm/pbench-agent.spec.j2
Centos-Stream-8/9: change the 'ansible' dependency to 'ansible-core'.
Everybody else (at least for now) can get its hands on an 'ansible'
package (EPEL packages it for RHEL: it has a dependency on
'ansible-core' and includes some curated roles).
=> CentOS-Stream-8/9 dependency fixes - backport to b0.71

utils/rpm.mk
Starting with `rpmlint` 2.0.0, the `--file` option was changed to `--rpmlintrc`.  The first encounter with this version of `rpmlint` came with Fedora 36, but will likely show up soon in other distributions.
To work around this change, we take advantage of two behaviors of `rpmlint`, one from the pre-2.0.0 version and one from the new version.
For pre-2.0.0, we set the `XDG_CONFIG_HOME` to `${PBENCH_TOP}/utils` so that our `rpmlint` file containing the configuration we want is found.
For 2.0.0 and later, we copy our `rpmlint` file to a `pbench-common.rpmlintrc` along side the build location of the .spec file.
=> Work around for rpmlint incompatibilities

agent/util-scripts/gold/pbench-register-tool-set/test-11.18.txt, agent/util-scripts/pbench-register-tool-set, agent/util-scripts/unittests
Fixes #2903
Invoking pbench-register-tool-set with a named toolset argument, e.g.
pbench-register-tool-set light
ignores the named argument, and substitutes the default tool set,
resulting in a deprecation warning and registration of the default
tool set.
The option-handling code does one extra shift of the argument list
falling off the end. The fix just eliminates the extra shift.
Also add a simple unit test for this case.
=> Fix pbench-register-tool-set argument handling

agent/util-scripts/gold/pbench-register-tool-set/test-11.19.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.20.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.21.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.22.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.23.txt, agent/util-scripts/unittests
Following a comment by @dbutenhof on PR #2904 (actually, its sibling back-porting to b0.71), this PR adds a few more tests for `pbench-register-tool-set'.
=> Addendum to PR #2904: add more tests

agent/rpm/pbench-agent.spec.j2
`pbench-verify-sysinfo-options` requires the python ifaddr module. Fedora 36 does not install it by default.
`ifaddr` is in `requirements.txt`, but we prefer a distro package if available.
=> Add dependency for Fedora 36

agent/util-scripts/gold/pbench-register-tool-set/test-11.18.txt, agent/util-scripts/pbench-register-tool-set, agent/util-scripts/unittests
Fixes #2903.
Back-port of #2904 (6ba02ca28).
Invoking pbench-register-tool-set with a named toolset argument, e.g.
pbench-register-tool-set light
ignores the named argument, and substitutes the default tool set, resulting in a deprecation warning and registration of the default tool set.
The option-handling code does one extra shift of the argument list falling off the end. The fix just eliminates the extra shift.
Also add a simple unit test for this case.
=> Fix pbench-register-tool-set argument handling - backport of #2904

server/bin/pbench-server-erase.sh
PBENCH-766
This script clears out an existing server installation, reading the configuration from `pbench-server.cfg` (via `pbench-config`) and clearing the PostgreSQL database, the Elasticsearch indices and templates, and the ARCHIVE, INCOMING, and RESULTS file systems.
NOTE: Run `systemctl stop pbench-server` before running this, as root, *then* run this
script under `su --login pbench`, and then exit the `su` and restart the server. The server will initialize the new SQL schema, create the Elasticsearch templates, and so forth, as usual.
It might be noted that while running a self-contained development pod with containerized private server, Elasticsearch, and PostgreSQL would mitigate some of this, we will still be faced with redeployments referencing external backend components that …
=> Simple utility script to reset Server state

lib/pbench/server/api/resources/query_apis/datasets_delete.py, lib/pbench/server/api/resources/upload_api.py, lib/pbench/server/filetree.py, lib/pbench/test/unit/server/query_apis/test_datasets_delete.py, lib/pbench/test/unit/server/test_file_tree.py
PBENCH-769
With the recent change to make tarball MD5 the authoritative "resource id" for datasets, the ambiguity in `FileTree` classes between "tarball" and "dataset" becomes more important. A planned change to allow altering the dataset resource name for display will compound the problem since tarball names are immutable but will no longer match the dataset name.
This change attempts to more clearly separate the two concepts, while redefining the primary access into the file tree to use the resource ID of a dataset, which is the tarball MD5 value and therefore easily accessible in both models.
=> Clarify "tarball" vs "dataset" in FileTree

agent/containers/images/Dockerfile.base.j2, agent/rpm/pbench-agent.spec.j2, agent/rpm/targets.json, utils/rpm.mk
This effectively reverts PR #2893 (and its backport to b0.71 #2896).
Simplify the python dependencies as much as possible:
- RHEL7, RHEL9, CentOS-Stream-9 and the Fedoras have a `python3'
package available from the standard distro repos. The actual version
varies by distro: 3.6 for RHEL7, 3.9.10 for RHEL9/CentOS-Stream-9,
3.10.0 for Fedora 35, 3.10.4 for Fedora 36.
- RHEL8 and CentOS-Stream-8 have python36, python38 and python39
packages available through the module system.
We use the generic `python3` package on most distros, and standardize
on `python39` for RHEL8/CentOS-Stream-8. That is mostly treated using
a jinja2 loop and a (new) `target.json` file that generates the separate
conditionals for RHEL/CentOS Stream 8 on one hand and the rest on the
other.
Unfortunately, I had to treat …
=> Fix agent ansible and  python deps

agent/rpm/pbench-agent.spec.j2, agent/rpm/targets.json, utils/rpm.mk
This PR supersedes #2922.  It revisits the change made in #2901 and uses an approach with less complication and fewer dependencies.
Fixes #2921.
=> Configure the "python" token used in package names based on version

agent/rpm/pbench-agent.spec.j2
This PR is a backport of #2925 to b0.71. It supersedes PR #2902 which is closed.
=> Configure "python" token -  backport to b0.71

agent/bench-scripts/pbench-linpack
The verify_common_bench_script_options fails when tools are not
configured locally, which is usually the case of remote --pre-check-only
=> Avoid verify_common_bench_script_options in linpack pre-check

agent/bench-scripts/pbench-linpack
The verify_common_bench_script_options fails when tools are not
configured locally, which is usually the case of remote --pre-check-only
=> Avoid verify_common_bench_script_options in linpack pre-check (#2929 backport to b0.71)

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/datasets_inventory.py, lib/pbench/server/filetree.py, lib/pbench/test/unit/server/test_datasets_inventory.py, lib/pbench/test/unit/server/test_endpoint_configure.py
Define Pbench server API to access dataset artifacts (including tarball)
PBENCH-625
Add a new `/datasets/inventory/` API to return the files as byte stream for the specified `dataset` with the `path` as URI parameters.
=> GET API for /datasets/inventory/ to access dataset artifacts

agent/containers/images/Dockerfile.base.j2
We want python3.9. This was accidentally omitted from the backport
of #2901.
=> Fix dockerfile

agent/containers/images/Dockerfile.base.j2, agent/containers/images/Makefile
We have restored the ability to build CentOS 7-based containers.
The default container distributions supported are now CentOS 7 (restored), CentOS 8 (no change), CentOS 9 (added), and Fedora 35 (no change).  We removed Fedora 34 which recently was declared EOL.
=> Correct CentOS 7 container builds, update defaults

lib/pbench/server/__init__.py, lib/pbench/server/database/database.py, lib/pbench/server/database/models/datasets.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/database/test_datasets_metadata_db.py, lib/pbench/test/unit/server/query_apis/test_datasets_detail.py, lib/pbench/test/unit/server/test_datasets_metadata.py, lib/pbench/test/unit/server/test_requests.py
PBENCH-749
Having changed the API to use the unique tarball MD5 as the formal resource ID, we're free to allow users to select more meaningfull resource names for filtering and display.
This PR adds a layer allowing the owner of a dataset to use the metadata PUT API to alter the dataset.name and server.deletion metadata keys with basic validity checking:
- The name value must be a UTF-8 string from 1 to 32 characters
- The deletion value must be a valid date/time string that does not exceed the server's maximum dataset lifetime from the dataset's upload timestamp.
=> Allow changing the dataset resource name and deletion date

server/rpm/pbench-server.spec.j2
[As requested](https://github.com/distributed-system-analysis/pbench/pull/2935#discussion_r917191971) in https://github.com/distributed-system-analysis/pbench/pull/2935, here's a separate PR which tweaks a line in `server/rpm/pbench-server.spec.j2` to avoid unnecessarily creating a sub-shell when doing the Pip install of the Server Python requirements.
Note, this PR is layered on top of #2938; once that is merged the first of the commits here will "disappear".
=> Avoid creating a subshell for Server Python requirements installation

agent/ansible/pbench_agent_tool_meister_firewall.yml
It uses the pbench_firewall_open_ports role from the Galaxy
pbench agent collection.
=> Add example playbook to open ports for redis/TDS

agent/containers/images/Makefile, agent/containers/images/push, agent/containers/images/quay-repo, agent/containers/images/repo-fix
PBENCH-703
When we are pushing images to https://quay.io, we ensure that the target repository is created ahead of time, if it does not already exist, as a publicly visible repository, with the `core` team is added as an administrator.
The new `make` target, `repofix`, uses the default distro targets to ensure all the existing repositories have the appropriate visibility and permissions.
=> Update `push` to change permissions on `quay.io`

agent/ansible/pbench_agent_install.yml
It should not be part of the installation: it is part of the preparation of the hosts and therefore belongs in a different playbook.
=> Delete the epel role from pbench_agent_install.yml

agent/ansible/pbench/agent/roles/pbench_repo_install/vars/main.yml
Set up a map with the `ansible_distribution' value  as key and the
COPR chroot name as value. Use the map to calculate the final
component of the baseurl field in the repo file (except for CentOS 7
which is one-of-a-kind).
The map can be extended easily for other distros, RHEL clones or
otherwise.
=> Use the "epel" chroot for "Rocky Linux"

build.sh, dashboard/.eslintignore, dashboard/.eslintrc.json, dashboard/package.json, dashboard/src/App.test.js, jenkins/Pipeline.gy, jenkins/ci.fedora.Dockerfile, jenkins/run, tox.ini
PBENCH-694
This PR is the second try at the first installment in a series of enhancements to the Pbench CI pipeline. The goal is to have the CI perform lint and style checks, run unit tests, build RPMs, build containers, and run functional tests for each of the Agent, Server, and Dashboard. This PR provides the first of those, running lint and style checks as well as unit tests for the Agent, Server, and Dashboard.  (This PR is a split of #2935, deferring the building of RPMs and subsequent stages to a subsequent PR.)
For convenience, this PR consists of a series of commits, but they should be squashed into a single commit when it is merged:
- enhancements to the CI pipeline
- tweaks to the CI dockerfile, adding dependencies of the extended pipeline features
- tweaks to the Dashboard …
=> Enhancements to the CI pipeline (Part 1, Take 2)

lib/pbench/server/api/resources/datasets_metadata.py, lib/pbench/server/database/models/datasets.py, lib/pbench/test/unit/server/test_datasets_metadata.py
PBENCH-837
Setting the "dataset.name" and "server.deletion" keys can produce validation errors which the `PUT /datasets/metadata` API wasn't properly handling, so that the attempt fails with `INTERNAL_SERVER_ERROR` instead of `BAD_REQUEST`.
Add logic to pre-validate so that on validation failure we can fail before modifying any metadata values.
(FYI: I also experimented with the alternative of wrapping the key setting loop in a nested SQLAlchemy transaction that could be cleanly unrolled on error. I didn't manage to get that to work, but it's probably something we should consider trying again later.)
=> Improve handling of key validation errors

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/endpoint_configure.py
PBENCH-844
The `/api/v1/endpoints` generator reads Flask `Rule` objects and uses them to create the API descriptions dynamically. This has gotten complicated as we now have several APIs with multiple rule patterns in order to support defaulting parameters: e.g., `/server/configuration/key`, `/server/configuration/` and `/server/configuration`. The `/datasets/contents` API will support two parameters and allow dropping the second.
The solution is to explicitly collapse these separate `Rule` objects, saving the one with the most parameters defined.
=> Collapse overlapping Flask URI Rule patterns

dashboard/src/actions/overviewActions.js, docs/API/V1/list.md, docs/API/metadata.md, lib/pbench/server/api/resources/datasets_metadata.py, lib/pbench/server/database/models/datasets.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/database/test_datasets_metadata_db.py, lib/pbench/test/unit/server/query_apis/test_datasets_detail.py, lib/pbench/test/unit/server/test_datasets_list.py, lib/pbench/test/unit/server/test_datasets_metadata.py, lib/pbench/test/unit/server/test_requests.py
PBENCH-814
Originally  we had the "dashboard" namespace for global dataset metadata controlled (albeit only by convention) by the dashboard, and the "user" namespace for general use by "other clients".  It's not entirely clear that this separation (as it was only a loose convention) made much sense, and the semantic of "user" was misleading.
After repurposing the "user" namespace for a new user-specific metadata concept, it makes sense to change "dashboard" to something more general.
The API documentation will recommend that each client assign a key under the namespace; e.g., I think the dashboard should be using something like "global.dashboard.seen" rather than just "global.seen".
=> Generalize the "dashboard" namespace

lib/pbench/server/api/resources/datasets_inventory.py, lib/pbench/test/unit/server/test_datasets_inventory.py
PBENCH-848
Fixed the bug in Inventory API - Passing `resource_id` instead of dataset `name`
=> Fixed API to pass resource_id rather than dataset's name

jenkins/Makefile
This PR extends the `jenkins/Makefile` to allow it to build containers in which we can build RPMs for the Server and Agent for all platforms on which we intend to deploy them.  This will allow us to build RPMs locally as part of the CI pipeline, instead of using COPR.
This change adds the targets `image-rpmbuild-all` and `push-rpmbuild-all` which build and push, respectively, containers for each of our favorite versions of our favorite distributions (specifically, RHEL, Fedora, and CentOS) to the a repository in the `pbench` organization in the internal Quay registry.  These are implemented via pattern rules which also allow a container for any particular distribution version to be built and/or pushed individually (as long as the distribution is one of those three, and as long as the base …
=> Initial support for building replacements for COPR chroots

exec-unittests, lib/pbench/client/__init__.py, lib/pbench/test/functional/server/conftest.py, lib/pbench/test/functional/server/test_connect.py, lib/pbench/test/functional/server/test_user.py, lib/pbench/test/unit/client/__init__.py, lib/pbench/test/unit/client/conftest.py, lib/pbench/test/unit/client/test_connect.py, lib/pbench/test/unit/client/test_login.py, server/requirements.txt
PBENCH-810
This adds the beginnings of a simple Pbench Server python client library (with a `Pbench` class) and a few initial functional test modules.
The modules are written in Python using the Pytest framework to give us convenient test modularization and fixtures. We use a fixture to establish a Pbench Server connection, for example.
The functional test modules currently include a simple validation that we can connect to a server and retrieve the server's endpoints, and a test of Pbench Server user operations including register, login, logout, profile access/update, and delete.
The `PBENCH_SERVER` environment variable provides the server host for connection; the `pbench` fixture will cause failure if the environment variable isn't defined, or if connection fails.
=> Pbench Server client library and functional tests

docs/API/V1/README.md, docs/API/V1/contents.md, docs/API/V1/inventory.md, docs/API/V1/list.md, docs/API/V1/server_config.md, lib/pbench/server/__init__.py, lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/datasets_metadata.py, lib/pbench/server/api/resources/server_configuration.py, lib/pbench/server/api/resources/upload_api.py, lib/pbench/server/api/resources/users_api.py, lib/pbench/server/database/database.py, lib/pbench/server/database/models/datasets.py, lib/pbench/server/database/models/server_config.py, lib/pbench/test/unit/server/database/test_server_config_db.py, lib/pbench/test/unit/server/test_authorization.py, lib/pbench/test/unit/server/test_endpoint_configure.py, lib/pbench/test/unit/server/test_server_configuration.py, server/requirements.txt
PBENCH-759
Add a key/value store for server-wide configuration settings. To start, we implement three settings: the maximum dataset retention in days, the current server state, and a "banner" object that can be displayed by clients to inform users of issues, maintenance plans, etc.
The retention period default is taken from the `pbench-server.cfg` file. The default server state is "enabled". There is no default banner.
When the server is `disabled`, most API operations will fail with `SERVICE_UNAVAILABLE`/503, returning a message which can be configured along with the server state. Specific APIs can be excluded from the shutdown, specifically the `/api/v1/server/configuration` API that will allow it to be enabled again. (We also allow login and logout, since an ADMIN user needs to …
=> Provide a server configuration option mechanism

agent/containers/images/Makefile, jenkins/Makefile, utils/utils.mk
As I implement support for building things on/for multiple distribution/version combinations, I find myself reusing the same (or similar) code idioms which drive Make pattern rules where the pattern consists of a tag with the distro name and the major version (like `rhel-9`, `centos-8`, or `fedora-35`).  There's a modest set of boilerplate definitions which support this usage, and, rather than continue to replicate it where it's needed, this PR moves it to a common, utility makefile which can be included by the makefiles which need the definition.
Also, in an upcoming PR, I will need some other standard Make magic, so I've added the definitions which support that (`_empty` and `_space`) to this file, as well.
PBENCH-720
=> Refactor support for distro/version pattern rules in makefiles

lib/pbench/server/api/resources/query_apis/datasets_delete.py, lib/pbench/server/database/models/datasets.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/database/test_datasets_db.py, lib/pbench/test/unit/server/database/test_datasets_metadata_db.py, lib/pbench/test/unit/server/test_datasets_metadata.py, server/bin/gold/test-16.txt, server/bin/gold/test-17.txt, server/bin/gold/test-6.13.txt, server/bin/gold/test-6.14.txt, server/bin/gold/test-6.15.txt, server/bin/gold/test-6.16.txt, server/bin/gold/test-6.17.txt, server/bin/gold/test-6.5.txt, server/bin/gold/test-6.6.txt, server/bin/gold/test-6.9.txt, server/bin/pbench-unpack-tarballs.sh, server/bin/state/test-6.13.db, server/bin/state/test-6.14.db, server/bin/state/test-6.15.db, server/bin/state/test-6.16.db, server/bin/state/test-6.17.db, server/bin/state/test-6.5.db, server/bin/state/test-6.6.db, server/bin/state/test-6.7.db, server/bin/state/test-6.9.db, server/bin/state/test-7.26.db
PBENCH-842
With the impending arrival of the cache manager, we're moving away from a static "unpack" phase. This is a bit of prep work towards that day, removing the dataset SQL table "UNPACKING" and "UNPACKED" states.
This also allows "re-unpacking" after unpacked data has been aged out (another problem we'll no longer have after the cache manager) because the unpack tool is no longer constrained by the state transition rules.
=> Remove the UNPACKING/UNPACKED states

agent/Makefile, agent/rpm/Makefile, agent/rpm/pbench-agent.spec.j2, server/rpm/Makefile, utils/rpm.mk
This PR contains the various bits of mechanism and tweaks required to build RPMs in containers.  (The _next_ step will be to enhance the CI to use the facilities added here -- this doesn't actually hook them up.)
There are several pieces to these changes, but most are small enough and localized enough that it wasn't worth splitting them into separate commits or PRs.
Here are the highlights of the changes:
- `agent/Makefile`:  For no reason which is obvious to me, while the RHEL-9 builds worked fine, the RHEL-8 and RHEL-7 Agent builds failed with a complaint during the SRPM build where we "install" the Python components, because the target location was not a site path nor was it in `PYTHONPATH`.  (Apparently, this doesn't happen when building on or for COPR, but perhaps that's because no …
=> Framework for building RPMs in the CI

agent/bench-scripts/pbench-uperf.md
PBENCH-868
Fixes #2968 
`pbench-uperf` starts with a server port of 20010, not 20000, so we fix the doc to agree with the implementation.
The doc does not mention that the local ports on each system need to be open for `uperf` to operate successfully. That information plus information on how to find the range on a system and how to use `firewall-cmd` to open the range are added.
=> Fix port requirements in pbench-uperf doc

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/datasets_inventory.py, lib/pbench/test/unit/server/test_datasets_inventory.py, lib/pbench/test/unit/server/test_endpoint_configure.py
PBENCH-602
This API URL `http://host/api/v1/datasets/inventory/<dataset>/`  retrieves the raw ARCHIVE tree tarball file of the requested dataset as a byte stream.
=> Accessing results tarballs over http

exec-unittests, lib/pbench/test/unit/agent/test_utils.py
PBENCH-873
This primarily modifies exec-unittests to stop running the legacy test suites entirely. Maintaining them is an ongoing and increasingly awkward task as our server architecture moves away from filesystem-based state.
Interestingly, when I ran `tox`, I started getting test failures in the agent `test_utils.py` because a `BaseServer.kill` call was getting the wrong computed result code. This appears to be because my system restarted today and actually had a process with pid 12345, while that section of the test case runs without a mock for `os.kill`. The failing test is redundant (as well as wrong) because there's a comprehensive set of mocked test cases further down. I removed it.
=> Disable legacy tests

agent/rpm/pbench-agent.spec.j2
PR #2971 removed the stockpile patch file, but the RPM spec file was still referencing it.
=> Restore agent RPM builds

build.sh, dashboard/package.json
This PR addresses some of the issues that we've seen recently with the Dashboard unit testing in the CI.
In particular, the unit tests were failing with
```
Cookie has domain set to the public suffix "localhost" which is a special use domain. To allow this, configure your CookieJar with {allowSpecialUseDomain:true, rejectPublicSuffixes: false}.
at Object.getPublicSuffix (node_modules/tough-cookie/lib/pubsuffix-psl.js:62:11)
at permuteDomain (node_modules/tough-cookie/lib/permuteDomain.js:38:28)
at MemoryCookieStore.findCookies (node_modules/tough-cookie/lib/memstore.js:99:21)
at MemoryCookieStore.findCookies (node_modules/universalify/index.js:5:67)
at CookieJar.getCookies (node_modules/tough-cookie/lib/cookie.js:1407:11)
at CookieJar.getCookies (node_modules/universalify/index.js:5:67) …
```
=> Fix CI Dashboard unit testing

.pre-commit-config.yaml, pyproject.toml
See https://pycqa.github.io/isort/docs/configuration/pre-commit.html.
=> Add `isort` via pre-commit

agent/ansible/collection/roles/pbench_repo_install/defaults/main.yml, agent/ansible/collection/roles/pbench_repo_install/tasks/main.yml, agent/ansible/collection/roles/pbench_repo_install/templates/etc/yum.repos.d/pbench.repo.j2, agent/containers/images/Makefile, agent/containers/images/gen-tags-from-rpm, agent/containers/images/repo.yml.j2
PBENCH-902
In preparation for PR #2937, we remove the use of a default COPR repo name from the `pbench_repo_install` role.  This necessitates a change to the container image build mechanism since it relies on the repo template file from the ansible role.
=> Remove default repo name

agent/containers/images/Makefile, agent/containers/images/gen-tags-from-rpm, utils/rpm.mk
PBENCH-823
The COPR rules are such that you can only have one RPM for a given chroot per repository.  So you can't have a `pbench-agent` `0.69.*` and a `pbench-agent` `0.71.*` RPM available at the same time.
=> Use `major.minor` version in COPR repo name

build.sh, jenkins/Makefile, jenkins/ci.fedora.Dockerfile, jenkins/run, utils/rpm.mk
This PR enhances `build.sh` to extend the CI pipeline to include building binary RPMs for the Agent and the Server.
There are a few related changes which include:
- `build.sh`:
- We create the `${HOME}/.config` directory if it doesn't exist.  Previously, in the container scenarios, we mapped this to a temporary file system; now it just resides on the same file system as ${HOME}, but we cannot be guaranteed that it will exist unless we create it.
- We list the RPMs at the end of the build.  This is a "victory lap" which will be removed in the next PR when the RPMs are actually consumed.
- `jenkins/Makefile`:  A change requested in another PR for a code comment 
- `jenkins/ci.fedora.Dockerfile`:
- Updated to Fedora 35!
- The addition of the `podman-remote` package to allow us to invoke …
=> Add RPM builds to the CI pipeline

server/rpm/Makefile
This PR harmonizes the Pbench Server RPM `Makefile` with the Agent one.
The `Makefile`'s which drive the RPM builds for the Pbench Server and Agent, respectively, are basically a few definitions and an `include` directive for a common makefile.  The Pbench Server is missing the definition of `CHROOTS`, and this change supplies it (along with a copy of the block comment from the Agent `Makefile` which explains the definition).
The `CHROOTS` definition determines which distros are targeted when the RPMs are built using COPR.  Since we are now targeting the Pbench Server for RHEL-9, this change provides the appropriate value for the definition.
Note, however, that we don't actually intend to distribute a Pbench Server RPM from COPR, nor does the CI build procedure use COPR for building RPMs, …
=> Server Makefile housekeeping

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/namespace_and_rows.py, lib/pbench/test/unit/server/query_apis/test_namespace_and_rows.py, lib/pbench/test/unit/server/test_endpoint_configure.py
PBENCH-748
Refactored `SampleNamespace` to GET API and moved the `<dataset>` attribute to the URI from JSON payload. And it'll be like
`GET /datasets/namespace/<dataset>/<dataset_view>`
And also did the same for the `SampleValues` API, since this API has multiple JSON attributes in the payload, it remains as a `POST` request and it'll be like
`POST /datasets/values/<dataset>/<dataset_view>`
=> Pbench refactor namespace values

agent/Makefile, utils/rpmlint
Backport from PR #2882 (a957705ee).
* Remove unused `rpmlint` filter
* Stop using deprecated setuptools method of install
The new way to install our Python3 interfaces is:
/usr/bin/python3 -m pip install --prefix=${dir} -e .
See https://docs.python.org/3.6/installing/index.html#installing-index.
The new interface allows for the `agent/Makefile` to create the python CLI interfaces on environments running Python 3.10 and later.
Why do we use `/usr/bin/python3`?  If you invoke pip inside a virtualenv to install a package, it automatically uninstalls the previous one from where it was installed, and installs it again in the `--prefix` path. That is wrong on so many levels. So, to work around this terrible behavior we have to invoke the non-virtualenv `/usr/bin/python3` so that the …
=> RPM build fixes related to Python 3

dashboard/package.json
Once again our build was [broken by an external update to an NPM package](https://github.com/jashkenas/underscore/issues/2967).  Happily, they were quick to fix it, so it's no longer necessary for us to work around the problem.
However, this PR commits the residue from that effort:
- First, we remove the workaround from the last time we had this firedrill, since it's no longer necessary.
- Second, we add a stub structure to hold the override for the next time (so we don't have to re-remember how to do it).  (The form is different from the last time, because we're now running a current version of `npm` which supports it.)
=> Add a new NPM packaging workaround; remove the previous one

doc/RELEASE_NOTES.md
PBENCH-676
Fixes #2884
Fedora has released an update to the python3 package that fixes the problem. The fix is found in the 3.10.7 version of the package. After updating, the pbench-agent RPM can be installed and various commands (e.g. pbench-user-benchmark) that complained or aborted before, now complete normally.
Details of the fix can be found at https://github.com/fedora-python/cpython/pull/48
=> Add note on Fedora 36 and its python 3.10 problem resolution

agent/containers/images/Dockerfile.layered.j2, agent/containers/images/Makefile, agent/containers/images/README.md, agent/containers/images/apply-tags, agent/containers/images/build-image, agent/containers/images/repo.yml.j2
Replaces PR #3013.
Apparently, the Agent container builds aren't working any more.  This PR restores them to working order.
The principal changes:
- The container build depends on the `pbench.repo.j2` template from the Ansible collection...which, apparently, moved recently (#2991)
- Added a second repository to the `agent/containers/images/repo.yml.j2` template for the "auxillary" RPMs
We also made some smaller changes:
- Added Fedora-36 to the list of default targets
- The `-TEST` suffix will now _really_ disappear when it's not needed
- Removed some redundant dependencies on the `pkgmgr-clean` target
- Tweaked a code comment
- Removed an unnecessary PCP repo enablement
- Enabled a method of quickly executing all `make` targets for container build
=> Get the current Agent container build working again

exec-unittests
The sub-options available to `server` are empty, so the code to handle those needs to be for the agent only.
Pulled out from PR #3008.
=> Correct handling of `tox -- server`

server/rpm/pbench-server.spec.j2
This PR contains some small clean-ups for the Server RPM spec file (template):
- Remove a redundant dependency on `python3-psycopg2` (we already have an unconditional `Requires` for it, so we remove the reference from the conditional one).
- Remove or escape references to `rpmbuild` macros in code-comments.  `rpmbuild` expands macros, even inside comments; normally, this goes unnoticed and isn't a problem, but if the macro expands to multiple lines, the expansion can escape the comment and break the build; therefore, `rpmlint` checks for macros in comments and warns about them.  So, in cases where the context is clear, I simply removed the leading `%` so that the references cease to be macros; in the other case, I added a second `%` which escapes the macro-introducer, which produces the …
=> Small server rpm spec cleanup

jenkins/ci.fedora.Dockerfile
When we run `npm` in the CI container, it complains about being out of date.  At the end of the CI container image build, we attempted to update `npm` to the current release, but the current release has moved on from that point, and now we're getting complaints again.
This PR relaxes the requested `npm` update target, so now we should always get the latest published version.  And, while I was in there, I improved the descriptive comment.
=> Use latest `npm` in CI container image

lib/pbench/server/indexer.py, lib/pbench/test/unit/server/test_indexer.py
When a template key maps to a non-string value, a error is encountered like:
"TypeError: decoding to str: need a bytes-like object, float found"
The code now converts all non-string values to strings, and ignores any keys which don't map to a value with one of the types: `string`, `int`, or `float`.
A set of unit tests for this operation is provided, and the function was renamed to ensure its intended use is clear.
=> Correct UID template resolution

lib/pbench/server/api/resources/endpoint_configure.py, lib/pbench/test/unit/server/auth/conftest.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/test_endpoint_configure.py, server/lib/config/pbench-server.cfg.example
[PBENCH-838](https://issues.redhat.com/browse/PBENCH-838)
Endpoints API now returns the authentication schema for the client (Pbench-dashboard) to use for authenticating the end-user. 
The endpoints API would include the authentication object containing the realm, client, and authentication issuer information. 
```
GET pbench_server_rest_uri/endpoints"
Success: 200,
response = {
authentication = {
"realm": [realm-name],
"client": [client-name],
"issuer": [auth-issuer],
"oidc_secret": [secret-string]
}
...
}
```
Right now the easiest way to store this information on the server side is by adding them to the config file (which is not ideal and soon we need to think about how we want to store and fetch secrets on the server side).
=> PBENCH-838 User auth configuration parameters for the client

build.sh, jenkins/Pipeline.gy, server/pbenchinacan/container-build.sh, server/rpm/pbench-server.spec.j2
This PR enhances the Pbench CI, adding a stage which builds a Pbench Server container image and pushes it to the internal Quay registry.  Access to the repository is granted via "robot" credentials which are managed as a Jenkins "secret".  The container image is tagged with the PR number for PR builds and with the branch name for other builds.
Note, at the moment, there is no mechanism for removing old container images.  However, the registry offers the ability to set an expiration on images; we just need to find out how to set that automatically.  (In the meantime, we can remove them manually -- each time a PR is rebuilt it will replace the previous image, so we won't build them up too fast.)  Ideally, we would only build new images when changes are made to _Server_ code, but that's also …
=> Enhance the Pbench CI to build Server and Agent containers

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/datasets_detail.py, lib/pbench/test/unit/server/query_apis/conftest.py, lib/pbench/test/unit/server/query_apis/test_datasets_detail.py
PBENCH-672
Refactored  `POST /datasets/detail/<dataset>`  to `GET` API with metadata will be provided in `query_schema`.
And modified this `DatasetsDetail` to be an IndexMap subclass that identifies the document IDs and indices using the map rather than a full Elasticsearch query.
=> PBENCH-672 Refactor `/datasets/detail` to GET API

.coveragerc, exec-unittests, jenkins/Pipeline.gy, tox.ini
We also change to not report coverage on test failures, re-create the coverage data base for each `pytest` invocation, and move a few options to the coverage config file.
We want to re-create the coverage database each time because it is too easy to pollute with subsequent runs.  Note that we no longer capture coverage for the Agent `py36` run since the second invocation of `pytest` for the `py39` tox environment will over-write the coverage database.
=> Restrict coverage reporting to only `pbench`

jenkins/Pipeline.gy, lib/pbench/cli/server/shell.py, server/pbenchinacan/container-build.sh, server/pbenchinacan/etc/pbench-server/pbench-server.cfg, server/pbenchinacan/pod-nodata.yml, server/pbenchinacan/pod.yml
This PR extends the CI pipeline by adding a stage which stands up the Pbench Server "pod", performs a trivial functional test (hitting the API to fetch the endpoints), and then shuts it down.  It also removes the pod, its containers, any "dangling" containers, and any "dangling" container images.
Details:
- `Pipeline.gy`
- The container registries' FQDNs are now stored in Jenkins "secrets" instead of being included in the `Pipeline.gy` and script files, and they are referred to in terms of "internal" vs. "external", and the credentials variables are renamed to match.  Unfortunately, when I set the `${PB_SERVER_IMAGE}` value from `${PB_INTERNAL_CONTAINER_REG}` (which is a secret), it triggers a Jenkins warning about a potential leak.  I don't see an actual leak, but we'll need to figure …
=> First container-based Pbench Server functional test

lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/datasets_metadata.py, lib/pbench/server/api/resources/upload_api.py, lib/pbench/server/auth/auth.py, lib/pbench/server/database/models/datasets.py, lib/pbench/server/database/models/users.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/database/test_datasets_db.py, lib/pbench/test/unit/server/database/test_datasets_metadata_db.py, lib/pbench/test/unit/server/query_apis/test_datasets_delete.py, lib/pbench/test/unit/server/query_apis/test_datasets_publish.py, lib/pbench/test/unit/server/test_datasets_metadata.py
Addresses [PBENCH-934](https://issues.redhat.com/browse/PBENCH-934) 
Our Metadata and Dataset tables have a Foreign Key relationship with the users table, and since the user table is going to get dropped we need to remove this dependency. This is an intermediary step for removing users table and improving unit tests mocks.
=> PBENCH-934 Remove user table relationship with dataset and metadata table

agent/tool-scripts/datalog/pprof-datalog, jenkins/python-setup.sh, server/rpm/Makefile, server/rpm/pbench-server.spec.j2, tox.ini
While inspecting the current production deployment we have of the v0.69.* Pbench Server we found that it was using Python 3.6 instead of the intended 3.8.
However, the Jenkins unit test environment will execute the tests under Python 3.9 since the support for running under Python 3.6 is precluded by the Fedora 33 environment used.
We fix the version of Python for the Pbench Server by moving to Python 3.9, using `%py3_shebang_fix` to explicitly use `/usr/bin/python3.9` in the command line interface headers, and using `pip3.9` to do the local module installs.
With an additional correction to the `tox` environments for the Pbench Server, `server` and `py3-server`, all server tests are executed under Python 3.9, since the default for Fedora 33 (the CI container in use) is also Python 3.9.
The …
=> Correct version of Python used by server to 3.9

lib/pbench/test/unit/server/test_requests.py
We are not sure why this wasn't a problem before (possibly due to updated module dependencies), but we are seeing two upload tests fail with "anachronistic" (not yet valid) authentication tokens, which we believe to be due to having generated the token with the `pbench_token` fixture outside of the time freeze context.
Fixed by dropping the time freeze in one test where it wasn't necessary, and generating the authentication token for the other in the past rather than outside the time freeze.
=> Fix failing unit tests

lib/pbench/agent/tool_group.py, lib/pbench/cli/agent/commands/tools/kill.py, lib/pbench/test/unit/agent/task/test_tools_kill.py, lib/pbench/test/unit/agent/test_tool_group.py, setup.cfg
PBENCH-702
A new comprehensive command to hunt down and kill any and all Tool Meister sub-system components running locally or remotely, based on the recorded pbench "result" data directories found in the configured `${pbench_run}` directory hierarchy.
For example, if there are 5 pbench result directories found in `${pbench_run}`, and two of those results have left-over processes still running locally or remotely, this command will find and kill them all without prejudice.
The new `pbench.agent.tool_group.gen_tool_groups` helper module method is added to encapsulate searching for tool group data in result directories.
=> Add the new `pbench-tools-kill` command

client/requirements.txt, jenkins/Pipeline.gy, lib/pbench/client/__init__.py, lib/pbench/test/functional/server/test_connect.py, lib/pbench/test/functional/server/test_user.py, server/exec_functests
PBENCH-960
Add a script to install the pbench module so that we can import it normally, then use pytest to execute the functional tests against the server container.
This is invoked by the Jenkins pipeline after activating the pod.
Right now there are only a few functional tests, primarily dealing with the user resource (including login and logout); but they run.
=> Add a simple server functional test framework

server/lib/config/pbench.httpd.conf, server/lib/config/pbench.httpd.conf.example, server/pbenchinacan/container-build.sh
PBENCH-778
When viewing a Dashboard component page, React displays a pseudo URL path in the browser location bar; however this URL, for example `/dashboard/login`, is not a distinct file on the host system and can't be loaded.
This change introduces a "pbench-in-a-can" Apache config file change that will cause Apache to "rewrite" all URLs under `/dashboard` to redirect to the React App code. The React infrastructure takes care of launching the component.
Since we used to install a `/etc/http/conf.d/pbench.conf` file as part of the Ansible server configuration, and we no longer have server Ansible setup, this also adds an "example" HTTPD configuration file that can be copied during installation. (Note that we probably don't want to automatically install this in the RPM spec file as it …
=> Support browser reload of React component URL

server/bin/pbench-trampoline
When using Python 3.9 on RHEL 8 and it derivatives, one must invoke Python 3.9 via `/usr/bin/python3.9`, and `python3` is either not there or potentially a symlink to `Python 3.6` (in one particular case because PCP was installed first).
We need to use the correct version of Python both in the command and in the `PYTHONPATH`, along with using the `lib64` site packages.
=> Correct use of Python 3.9 for the Server

lib/pbench/server/auth/auth.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/query_apis/commons.py, lib/pbench/test/unit/server/query_apis/test_datasets_detail.py, lib/pbench/test/unit/server/test_datasets_daterange.py, lib/pbench/test/unit/server/test_datasets_list.py, lib/pbench/test/unit/server/test_datasets_metadata.py, lib/pbench/test/unit/server/test_requests.py, lib/pbench/test/unit/server/test_user_auth.py
1. Refactor unit tests to remove register/login/logout API dependency (except for `test_user_auth.py`, that will be removed when we remove the `User` and `Active_tokens` table)
2. Mock Keycloak tokens
PBENCH-901
=> PBENCH-901: Fix unit tests to mock Keycloak interaction for register/login/logout

dashboard/src/actions/authActions.js
A cookie with the Secure attribute is only sent to the server with an encrypted request over the HTTPS protocol.
As our server is of HTTP protocol, the cookies are not being set. These cookies are used to get the user login details. 
With KeyCloak integration, the entire mechanism for maintain the user login details will be changed so there will be no need to maintain these cookies.
=> Removed secure attribute in cookies

dashboard/package.json
PBENCH-966
We need a "homepage" setting in package.json so that React knows where to load artifacts. The "." will load relative to where we put it, although "dashboard" would probably work as well.
=> Fix React loading path

server/exec_functests
Currently, the exit code from functional testing is getting lost, so that the result always appears to be successful.
This change corrects that by capturing the result and using it as the exit code when the script exits.
=> Propagate exit code correctly from functional testing

lib/pbench/server/auth/auth.py
Bug found during the Pbench Hack-a-Thon, where the auth module `get_user_id` is not returning `user_id` as `str` which is what our dataset and metadata tables expect it.
=> Fix the returned user_id type to str

dashboard/src/assets/constants/overviewConstants.js
PBENCH-974
We want to set a convention of clients carving out a second level namespace under "global" and "user". The dashboard already uses this convention for the global namespace; this adds the same convention for the "user" namespace.
=> Fix favorite path

lib/pbench/server/cache_manager.py, lib/pbench/test/unit/server/conftest.py
PBENCH-978
A dataset may be gathered on a host with a scoped IPv6 address (represented in a format like `0::0%eth0`). The default `ConfigParser` used to read the dataset `metadata.log` interprets `%` characters as a substitution of another config value, and raises an exception because the "eth0" key doesn't exist.
Any `ConfigParser` instance used to process `metadata.log` rather than actual config files chould be created with `interpolation=None`.
=> Avoid ConfigParser interpolation

lib/pbench/server/cache_manager.py, lib/pbench/test/unit/agent/task/test_add_metalog_option.py, lib/pbench/test/unit/server/conftest.py
Furthering work from PR #3074, we use the `MetadataLog` class we already had to encapsulate the `metadata.log` manipulation going forward.
=> Leverage the existing `MetadataLog` class

agent/util-scripts/pbench-add-metalog-option, server/bin/pbench-cull-unpacked-tarballs.py, server/lib/pbench/indexer.py
This is a backport of commit 97895ba6d (PR #3074).
We turn of interpolation of the values encountered in the `metadata.log` files since we don't use that feature and some values may contain a `%` character triggering the interpolation by default.
=> Backport `metadata.log` interpolation fix

jenkins/Pipeline.gy, server/pbenchinacan/pod-nodata.yml, server/pbenchinacan/pod.yml
Add a mapping to allow the Dashboard deployment to be pulled into the container from outside.
Also, add policies to always pull the Pbench Server container image (and, in the with-data pod, pull the other two container images as well).
=> Tweak canned Pbench Server pod definition

agent/base
Rather than verify that these functions work as expected in all environments, we just remove them, since they are not currently used.
PBENCH-306
Fixes #1950.
=> Remove unused helper functions from `agent/base`

lib/pbench/cli/server/__init__.py, lib/pbench/cli/server/shell.py, lib/pbench/server/api/resources/datasets_list.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/api/resources/query_apis/datasets_delete.py, lib/pbench/server/database/database.py, lib/pbench/server/database/models/datasets.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/query_apis/test_datasets_detail.py, server/bin/pbench-backup-tarballs, server/bin/pbench-cull-unpacked-tarballs, server/bin/pbench-index, server/bin/pbench-reindex, server/bin/pbench-unpack-tarballs, server/bin/pbench-verify-backup-tarballs, server/lib/config/pbench-server-default.cfg, server/pbenchinacan/etc/pbench-server/pbench-server.cfg
Strictly textual change to avoid needless mention of the specific DB backend.
=> Avoid hard-coding PostgreSQL references

jenkins/Pipeline.gy
PBENCH-1008
Attempt to capture `journalctl` output in Jenkins log for analysis. This is a first pass attempt: in the future we should likely strive for a more "elegant" solution, e.g., exporting a more easily searchable document as a Jenkins artifact.
=> Capture functional test logs

lib/pbench/cli/server/shell.py, lib/pbench/server/database/database.py, lib/pbench/test/unit/server/conftest.py, server/lib/config/pbench-server-default.cfg, server/lib/systemd/pbench-server.service, server/pbenchinacan/etc/pbench-server/pbench-server.cfg
We add a method to wait for the configured `host`:`port` for the PostgreSQL database to accept socket connection.  We'll only wait at most N seconds before giving up (configurable).
We also tackle the following items:
* Add doc strings and type hints where applicable
* Consolidate the server configuration gathering to one location
* Stream-lining the use of the `PbenchServerConfig` object
* Keep the `site.ENABLE_USER_SITE` checks in `main()`
* Narrow exception handling
* Pass along the final gunicorn exit code
=> Add a method to wait for PostgreSQL to show up

agent/containers/images/Dockerfile.base.j2, agent/containers/images/Makefile, agent/containers/images/README.md, agent/rpm/Makefile, jenkins/Makefile, server/rpm/Makefile, utils/rpm.mk, utils/utils.mk
This PR is a sequence of commits which prepare the Agent container builds for use in the CI.  (Actually updating the CI pipeline will come in a subsequent PR.)
-  Housekeeping for building Agent containers
- Make the default-distros lists consistent across the rpmbuild container builds, the builds of the RPMs, and the build of the containerized Agents
- Add `baseimage` convenience targets for the Agent base containers for all default distros
- Enable building the CentOS-7 rpmbuild container
- Force the use of (at least) 9 digits for the Git hash (e.g. on CentOS-7)
-  Agent container build tweaks
- Rework version management
- Combine the `%-base.Dockerfile` rules into a single rule
-  Enable Agent container build to use a local RPM instead of COPR
- Tweak the base image Dockerfile template …
=> Prepare Agent container builds for use in the CI

.flake8, build.sh, dashboard/.eslintrc.json, dashboard/package.json, dashboard/src/modules/components/OverviewComponent/SavedRunsComponent.jsx, dashboard/src/modules/components/TableOfContent/index.jsx, dashboard/src/utils/filterDataset.js, pyproject.toml
PR #3021 hit some lint objections which turned to be confusing.  Since they were in `node_modules`, we assumed that the objections were coming from ESLint; however, it turns out that they were coming from Flake8 -- the objectionable modules were actually Python code and not JavaScript -- and we were none the wiser because `build.sh` wasn't giving any indication of which output came from which tool.
So, this PR addresses these problems and more:
- Tweak `build.sh` to echo the lint commands as they are issued; also, change the order of arguments in the `eslint` command to match its documentation.
- Tell Black and Flake to ignore `dashboard/node_modules/*`
- Move ESLint config from `package.json` to `.eslintrc.json`:  the latter overrides the former, so the stuff in the former was …
=> Linting tweaks

.gitleaks.toml
Add a `.gitleaks` to quiet the Red Hat spam bot.  Some how Red Hat's information security team has identified the `server/pbenchinacan/etc/pbench-server/pbench-server.cfg` file as being a potential "leak" of secure information.
It only contains a user name / password combination for the Pbench Server Gunicorn process running in one container of the ephemeral Pbench-in-a-Can pod to access the PostgreSQL container running in the same pod.
The information security bot apparently is emailing only one person, me, and not all the other forks of the upstream pbench repository, and has only identified branches of my PRs I have created.
I am told this file will stop those from happening, but I remain unconvinced since nothing has been shown to read the upstream pbench repository at all.
=> Add a `.gitleaks` to quiet the Red Hat spam bot

lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/api/resources/query_apis/datasets_publish.py, lib/pbench/test/unit/server/query_apis/test_datasets_publish.py
PBENCH-1020
An overdue API cleanup I'd like to get in before the dashboard implements a "Publish" control. This just moves the "access" parameter from the JSON request body up to a URI query parameter. This will make it visible in the HTTP/gunicorn log and makes it more consistent with our newer APIs.
=> Promote access parameter to query param

jenkins/Pipeline.gy, lib/pbench/cli/server/shell.py, server/lib/config/pbench.httpd.conf, server/pbenchinacan/container-build.sh, server/pbenchinacan/etc/pbench-server/pbench-server.cfg, server/pbenchinacan/pod-nodata.yml, server/pbenchinacan/pod.yml
Commit message for final squashed commit is:
----
By moving to use port 8080 in the Pbench Server container, we allow for
the case of the container deployed by a non-root user using host
networking.
In order to make this work inside the Pbench-in-a-Can pod, we must move
the KeyCloak server to port 8090.  Within a pod, all containers are
executing within the same network namespace.  So we can't have Apache2
(httpd) and KeyCloak listening on port 8080, while only trying to map
the KeyClock port to 8090 external to the pod.  We now use the same
ports internally and externally for clarity and simplicity.
Further, there is only one authentication server URL accessible by both
clients and the Pbench Server.  The code does not need to detect a
fallback, that is up to the entity depoying the …
=> Move Pbench Server to Listen on port 8080

server/lib/pbench/process_tb.py
Including PYTHONPATH, PATH and AGENT-CONFIG file values in put-shim's subprocess command, it is calling `pbench-results-push` on the agent's side and required these values.
=> Adding required options in put-shim subprocess command

lib/pbench/server/auth/__init__.py, lib/pbench/server/auth/auth.py, lib/pbench/test/unit/server/auth/conftest.py
When fetching the OIDC client (Keycloak) public key I was using an authentication token to extract the signing key first. Each time a new token is presented that would require fetching the public key from the beginning. This will not be efficient going forward. We need to archive the public key at the OIDC client and Pbench server initialization and then reuse it every time we want to decode the token offline. 
The change proposed here enables us to extract the public key at the server initialization.
=> Get OIDC client public key only at initialization

lib/pbench/client/__init__.py, lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/upload_api.py, lib/pbench/server/database/models/audit.py, lib/pbench/server/indexer.py, lib/pbench/server/indexing_tarballs.py, lib/pbench/test/functional/server/test_put.py, lib/pbench/test/unit/server/test_requests.py
PBENCH-1029
The 0.69 "pass-through" compatibility server will be uploading datasets to the 1.0 server under a fixed username, which means these datasets won't be visible to other users.
This adds an "access" query parameter to `PUT` that allows the put-shim server to upload all datasets as "public" so that they're visible to be analyzed and claimed.
(NOTE that this implies some follow-on Agent work in pbench-results-move and supporting classes to allow put-shim to specify the new query parameter.)
To "easily" accomplish this, I refactored the upload class on top of our `ApiBase` to handle parameter processing. Some changes were necessary to avoid consuming the entire data stream during validation, but this also allows `PUT` to participate in the new `APIInternalError` UUID mechanism …
=> Allow setting dataset access on upload

agent/util-scripts/gold/pbench-results-move/test-23.txt, agent/util-scripts/gold/pbench-results-push/test-24.txt, lib/pbench/agent/results.py, lib/pbench/cli/agent/commands/results/move.py, lib/pbench/cli/agent/commands/results/push.py, lib/pbench/cli/agent/commands/results/results_options.py, lib/pbench/test/unit/agent/task/test_copy_result_tb.py, lib/pbench/test/unit/agent/task/test_results_move.py, lib/pbench/test/unit/agent/task/test_results_push.py
PBENCH-1034
This PR will help us to send tarball with private/public access.
Public access will mean anyone can access that Tarball while private access will mean, only the owner of the tarball will be able to access that data.
`pbench-results-move --token="token" --access="public"`
=> Send tarball with access param

lib/pbench/server/api/resources/__init__.py, lib/pbench/test/unit/server/database/__init__.py, lib/pbench/test/unit/server/test_api_base.py
Suggested commit message below:
----
If a API is invoked using an unsupported method (e.g. `OPTION`), we
don't want to encounter a stack trace checking for a disabled API looked
up using the wrong method.
Further, we also need to ensure that we have a schema for the given
method before we check if the kind of operation is disabled.
=> Verify allowed methods before checking allowed operation

lib/pbench/server/database/models/datasets.py
When handling exceptions, certain kinds of exceptions in either SQLAlchemy or in PyscoPG2 will cause references to the SQLAlchemy object instance to cause other exceptions.  For example, one might see:
sqlalchemy.exc.PendingRollbackError: This Session's transaction has
been rolled back due to a previous exception during flush. To begin
a new transaction with this Session, first issue Session.rollback().
By moving the log messages after the `rollback()` call, we avoid the extra mess caused.
We also use the `self.logger` where possible, and we enhance the existing state transition error log with the object information, and add a debug log message on the success path.
=> Don't emit logs before `rollback()`

lib/pbench/agent/tool_group.py, lib/pbench/agent/tool_meister_start.py, lib/pbench/agent/utils.py, lib/pbench/test/unit/agent/test_utils.py
The Tool Meister sub-system now verifies that the host names in the requested tool group are valid before proceeding.
=> Add verify host names method used by Tool Meister

lib/pbench/client/__init__.py, lib/pbench/server/auth/auth.py
=> Remove use of `next` keyword as a variable

.github/workflows/gh-pages.yml
The current Github action is for building the Jekyll site and publishing it, we don't need it since our site is already a static website (HTML & CSS).
Also, existing action uploads the entire repo to gh-pages so it is unable to locate our static files.
Update workflow file:
- remove jekyll build step and also specify docs dir to deploy job
- rename workflow to gh-pages.yml
Please validate the [page rendering](https://vishalvvr.github.io/pbench), This page is created from the pbench fork and uses the modified workflow file.
PBENCH-1036
=> fix gh-pages deployment issue

lib/pbench/server/api/resources/datasets_list.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/test_datasets_daterange.py, lib/pbench/test/unit/server/test_datasets_list.py
Suggested commit message:
When results are paginated, the `next_url` value was blindly URL
encoded, but the `metadata` `list` object should be formatted as a
string of comma separated values.
=> Correct datasets list API `next_url` value

lib/pbench/test/functional/server/conftest.py, lib/pbench/test/functional/server/test_put.py, server/exec_functests
Suggested commit message:
The register user fixture is promoted to "module" scope, since it only
needs to happen once. This avoids repeated API calls to create a user
for every test that uses the `login_user` fixture.
Further, we change the `login_user` fixture to logout the user when the
test finishes.
Finally, we run the functional tests so that we can see the progress of
the tests as they operate and execute.
=> Simplify user reg & dump progress in func tests

.github/workflows/gh-pages.yml
We have pbench docs deployed separately on [readthedocs](https://pbench.readthedocs.io). Just want to improve user experience, Instead of navigating to readthedocs page we can also deploy it along with gh-pages/pbench website itself.
After this change we will have
gh-page/pbench website : https://distributed-system-analysis.github.io/pbench
docs: https://distributed-system-analysis.github.io/pbench/docs
Note: This change has no change on [readthedocs](https://pbench.readthedocs.io) deployment, it will also build along with this. 
PBENCH-1043
=> deploy readthedocs page on gh-page

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/users_api.py, lib/pbench/server/auth/auth.py, lib/pbench/test/unit/server/auth/test_auth.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/test_api_base.py
This commit is currently rebased on PR https://github.com/distributed-system-analysis/pbench/pull/3055 "Fix unit tests to mock Keycloak interaction for register/login/logout"
The commit in this PR enables the use of an OIDC token for user authentication. 
Note: This will break the current deployment of the Pbench-server if the following sections are missing from the server config file
```
[authentication]
server_url = keycloak.example.com:0000
realm = pbench
client = pbench-client
``` 
Not only do these sections need to be present but also the auth server URL needs to be active with the specified `realm` and `client` configuration.
Users can use the tokens obtained from the OIDC client (In our case Keycloak broker) and pass them to access the dataset resources they own. However, this …
=> PBENCH-895: Authentication on endpoints to use the tokens from identity provider

lib/pbench/server/api/resources/__init__.py, lib/pbench/server/database/models/datasets.py, lib/pbench/test/unit/server/database/test_datasets_metadata_db.py, lib/pbench/test/unit/server/test_datasets_metadata.py
PBENCH-1049
During the course of making an unrelated change, I "broke" a metadata test case for the "partial success" case of `PUT /datasets/metadata`. The test was still expecting the previous 500/internal-server-error behavior even though this had been changed to a success with an advisory message.
The reason the test "succeeded" was that the product code attempted to report the issue with an error log message, which failed because it involved trying to serialize an `Audit` record via `json.dumps` which apparently is unhappy with the `Audit` (and probably all SQLAlchemy proxy) objects, and the failure caused the API call to terminate with ... an internal server error.
This PR fixes the test and some aspects of the implementation, including making all metadata exceptions extend …
=> Fix PUT metadata partial success

dashboard/src/utils/routeConstants.js
PBENCH-1050
In some cases, routing was dropping the trailing `/` and we were losing the default "/dashboard" base directory on loads. While the mechanism still isn't entirely clear and I suspect there are cleaner ways to solve this in the longer term, Varshini, Webb, and I discovered that simply adding a trailing slash to the dashboard's `HOME` variable resolves the problem.
Closes #3128
=> Make sure dashboard routing stays within the app

jenkins/Pipeline.gy, tox.ini
The requirements for the agent, client, and server are different enough that any new version requirement for the client or server code will cause the `py36` environment to fail installation.  This isolates the use of Python 3.6 so that only the agent requirements are installed.
=> Create a separate tox env for Agent Python 3.6

exec-tests, lib/pbench/server/database/database.py, pytest.ini
There were two categories of warnings being displayed, those related to the xdist plugin, and those related to SQLAlchemy 2.0 migration.
The xdist plugin warnings are due to a bug in pytest-cov, see https://github.com/pytest-dev/pytest-cov/issues/557.  We just ignore them entirely for now, as that issue seems to be quiet.
The SQLAlchemy 2.0 migration warnings have 2 sub-categories.  The first being that `declarative_base` has moved modules, and that warning is removed by using the proper import.
However, once that `declarative_base` warning is removed, one encounters:
.../pbench/server/database/models/datasets.py:875:
RemovedIn20Warning: "Metadata" object is being merged into a
Session along the backref cascade path for relationship
"Dataset.metadatas"; in SQLAlchemy 2.0, this reverse …
=> Silence warnings display by python unit tests

lib/pbench/agent/results.py, lib/pbench/test/unit/agent/task/test_copy_result_tb.py
This is in response to [a request](https://github.com/distributed-system-analysis/pbench/pull/3119#discussion_r1050298738) made in #3119.  (This change was originally part of #3157, but it got booted.)
#3119 added the `--access` option to `pbench-results-push` and `pbench-results-move`.  Click performs the parameter validation and provides the CLI code with a default value if the user doesn't specify one.  Thus, the CLI code always provides a value for the `access` parameter when it calls what will become the "Agent library code" (i.e., `copy_result_tb()`), so the choices made in #3119 make reasonable sense.
However, once we establish a clean split between the Agent CLI and the underlying "library" code, it will become feasible for other projects to make use of the Agent via the API …
=> Make `access` parameter to `copy_result_tb` optional

exec-tests, lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/__init__.py, lib/pbench/test/unit/server/query_apis/commons.py, lib/pbench/test/unit/server/query_apis/test_namespace_and_rows.py
The `Commons` class provides a set of shared tests as a "base" class, of sorts, for various other tests classes to use to help validate behaviors.
However, it wasn't clear what tests were supposed to be skipped or not.
**_It is this author's opinion that we should drop test skipping in the future._**
In the mean time, we have applied some comments, reworked existing skip conditions, added other conditions, and removed unused skips in an attempt to verify what is skipped is expected.
This actually resulted in an _increase_ in the number of skipped tests due to the fact that one of the tests was not actually executing when a parameter was missing.
----
This PR is divided into 5 commits which are intended to be merged as separate commits.
The first commit is a set of changes to doc strings …
=> Apply corrections for when tests are skipped

exec-tests, lib/pbench/common/logger.py, lib/pbench/test/unit/agent/conftest.py, lib/pbench/test/unit/agent/task/test_copy_result_tb.py, lib/pbench/test/unit/agent/task/test_make_result_tb.py, lib/pbench/test/unit/agent/test_tool_data_sink.py, lib/pbench/test/unit/agent/test_tool_meister.py, lib/pbench/test/unit/server/auth/conftest.py, lib/pbench/test/unit/server/auth/test_auth.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/test_api_base.py, lib/pbench/test/unit/server/test_unpack_tarballs.py, lib/pbench/test/unit/server/test_user_management_cli.py, pytest.ini
This work contains some cleanup and some streamlining of the logging behaviors with respect to the python unit tests.
The main goal is to reduce the explicit use of `get_pbench_logger()` in the unit tests to ensure we don't have unexpected logging behaviors in our tests suite.  The secondary goal is to make it easy to identify and control the loggers used for unit tests.
This PR is broken into 5 separate commits (which I'd like to keep separate if we can in case these changes cause problems down the road when issues arise debugging the unit tests), the first being:
----
Don't use xdist plugin for serial pytests
If we use the `-n 1` pytest argument we still run using the `xdist`
plugin, but it just uses one process.  Since the `xdist` plugin changes
the test environment a bit, don't use it …
=> Rework use of `get_pbench_logger` in unit tests

lib/pbench/cli/server/shell.py, server/lib/config/pbench-server-default.cfg
We are now using Nginx and never really used the "apache" section of the pbench server configuration.
We modify the pbench server API shell to print errors to `stderr`.
=> Remove "apache" section; print to `stderr`

server/bin/pbench-verify-backup-tarballs
Just like its sibling, `pbench-backup-tarballs`, we do not attempt to verify any backed up tar balls in S3 if we don't have a bucket defined.
=> Disable backup verify for S3 with no bucket

agent/containers/images/Makefile, jenkins/Pipeline.gy
This PR adds support to the CI for building a single set of Agent containers suitable for running functional tests.
The CI pipeline builds a full set of Agent containers (`base`, `tools`, `tool-meister`, `tool-data-sink`, `workloads`, and `all`) for a single distro (currently Fedora-36) and pushes them to the container registry.  For PR builds, it pushes them to the internal registry; for branch builds (like `main`), it pushes them to the external registry.
Details:
- Modify the Agent containers Makefile:
- allow the image repository and the image tag to be specified by command line arguments
- add a special target for use by the CI for pushing images to the repository: this target pushes the target distribution's container-set to the specified repository using the specified tag, without …
=> Add support for building Agent containers to the CI

jenkins/run-server-func-tests
Currently, `jenkins/run-server-func-tests` only dumps the `journalctl` log if the functional tests fail.  However, if the Pbench Server fails to start (based on the return from the `curl` command), then the script exits without producing the log, which makes diagnosing Server start-up problems awkward.
This PR adjusts the exit handling so that, instead of exiting when the `curl` command fails, the script only runs the functional tests if it succeeds; either way, the exit status (from either the `curl` command or the functional tests) is evaluated, and the dump is produced on a failure in either case.
=> Dump the `journalctl` log if the Server doesn't start

agent/containers/images/Makefile, agent/containers/images/README.md, jenkins/Pipeline.gy
This PR adds a stage at the end of the CI pipeline which runs only for branch (e.g., `main`) builds which, after all the other stages complete successfully, builds all the Agent containers for all of our favorite distros and pushes them to the external/public repo with a tag which matches the branch name (e.g., "main").
In order to accomplish this, we also add a new target, `publish`, to the Agent container `Makefile` (and update the `README.md` accordingly).
NOTE:  the new stage will run only _after_ this branch is merged, so we won't really know whether it works until after we approve it.  🙂
=> Modify the CI pipeline to publish successful branch build Agent containers

lib/pbench/server/api/resources/upload_api.py, lib/pbench/test/unit/server/test_requests.py
PBENCH-495
While uploading some tarballs I had a bash script to automate adding the `content-md5` header to the `upload` API call and my bash script had a bug where it was not reading the content-md5 correctly and an empty value was getting added as the header value. It took some time to realize the bug in my script because the server kept responding that I am missing the `content-md5` header, which was not correct. 
We already have an issue [github issue](https://github.com/distributed-system-analysis/pbench/issues/2311) and Jira regarding this so addressing that here.
=> Check missing content-md5 header value in /upload

server/pbenchinacan/run-pbench-in-a-can
Fixes a bug introduced by PR #3154, "Refactor to expose running in-a-can" (commit 78916486be7f8609330385916fb3f75a356012fe).
=> Use correct image for `run-pbench-in-a-can`

lib/pbench/server/sync.py, lib/pbench/test/unit/server/test_sync.py, server/lib/config/pbench-server-default.cfg, server/pbenchinacan/etc/pbench-server/pbench-server.cfg
Fixes issue #3198.
The root cause was that we have operation names for indexing which all had "INDEX" in the name: "INDEX", "INDEX_TOOL", and "RE_INDEX".
If any dataset had in its list of operations either "INDEX_TOOL" or "RE_INDEX", then any search for "INDEX" would also match those option names because a `contains()` operation was used in the query filter.  If all the operation names did not have any overlaps, that would work.
The fix was to filter locally by the exact operation name.  Since the total number of datasets on the system are rarely in the same operational state, it seems like a point solution that solves the problem efficiently without to many cascading changes.
----
Commits:
* Ensure operation metadata query finds unique vals
* Remove `COPY_SOS` op, add failing index test …
=> Fix repeated indexing

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/datasets_daterange.py, lib/pbench/server/api/resources/datasets_inventory.py, lib/pbench/server/api/resources/datasets_list.py, lib/pbench/server/api/resources/datasets_metadata.py, lib/pbench/server/api/resources/endpoint_configure.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/datasets_contents.py, lib/pbench/server/api/resources/query_apis/datasets/datasets_detail.py, lib/pbench/server/api/resources/query_apis/datasets/datasets_mappings.py, lib/pbench/server/api/resources/query_apis/datasets/namespace_and_rows.py, lib/pbench/server/api/resources/query_apis/datasets_delete.py, lib/pbench/server/api/resources/query_apis/datasets_publish.py, lib/pbench/server/api/resources/query_apis/datasets_search.py, lib/pbench/server/api/resources/server_audit.py, lib/pbench/server/api/resources/server_configuration.py, lib/pbench/server/api/resources/upload_api.py, lib/pbench/server/api/resources/users_api.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/query_apis/test_dataset_search.py, lib/pbench/test/unit/server/query_apis/test_datasets_contents.py, lib/pbench/test/unit/server/query_apis/test_datasets_detail.py, lib/pbench/test/unit/server/query_apis/test_namespace_and_rows.py, lib/pbench/test/unit/server/query_apis/test_query_builder.py, lib/pbench/test/unit/server/test_api_base.py, lib/pbench/test/unit/server/test_authorization.py, lib/pbench/test/unit/server/test_server_configuration.py
The API handling code now retrieves a logger from `flask.current_app` only when needed.
This exposed a small problem with the test environment where the `Flask` app context was not setup properly for the unit tests.
----
Pulled from PR #3114 (see https://github.com/distributed-system-analysis/pbench/pull/3114/commits/913fb7142091d88b21a495c949e4379a8a6c8c3a).
=> Remove the need to pass logger to APIs

jenkins/ci.Dockerfile.j2, jenkins/podman, jenkins/run-alembic-migrations-check
This PR sets up the infrastructure required to run the Alembic migration test like any other test under `tox`.
The principal change is to provide a helper script, `jenkins/podman` which wraps the `podman` command to allow it to be invoked from inside a container run by `jenkins/run`.
The `jenkins/run-alembic-migrations-check` script is modified to use `jenkins/podman` instead of invoking `podman` directly.  This allows the script to be used either directly or under `jenkins/run`.  Since the script relies on the `nc` command, the CI container build is modified to include that command.
The second commit on this branch is a set of tweaks to `jenkins/run-alembic-migrations-check` including some diagnostic output and a timeout on the wait loop.
Once this infrastructure is in place, we can …
=> Set up Alembic test infrastructure

lib/pbench/server/api/__init__.py
This is a follow-on to PR #3170, where, as a reviewer, [I was ~tricked~confused](https://github.com/distributed-system-analysis/pbench/pull/3170#discussion_r1086910380) by the use of a function decorator for an inner function.  This change replaces that usage with a simple declaration and call.
=> Clarify code which installs the Flask application context teardown handler

dashboard/src/actions/overviewActions.js, lib/pbench/client/__init__.py, lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/api/resources/query_apis/datasets_update.py, lib/pbench/test/unit/server/query_apis/test_datasets_contents.py, lib/pbench/test/unit/server/query_apis/test_datasets_update.py, lib/pbench/test/unit/server/test_datasets_metadata.py, lib/pbench/test/unit/server/test_endpoint_configure.py
PBENCH-817
Implemented a mechanism to change the owner of
- An "anonymous" upload of the dataset through the put-shim server, which can be "adopted" by a registered user
- An "orphaned" dataset can be picked up by a different user.
API - `POST  /datasets/change_owner/{dataset}?owner=user` 
And this API requires `ADMIN` access to perform the `change_owner` operation
=> Allow changing dataset ownership API

lib/pbench/server/api/__init__.py, lib/pbench/server/auth/__init__.py, lib/pbench/server/auth/auth.py, lib/pbench/test/unit/server/auth/conftest.py, lib/pbench/test/unit/server/auth/test_auth.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/test_api_base.py
Use the logger from `current_app` when necessary.
Also, remove use of a logger in `Auth.get_secret_key()` and rename since it is only used in this module.
----
Covers first 5 commits in PR #3114:
1. https://github.com/distributed-system-analysis/pbench/pull/3114/commits/87a15ec549fffa0ca9f4ed05bcb4f14ef252b199
2. https://github.com/distributed-system-analysis/pbench/pull/3114/commits/1fbc229b4c524f44fc4cec65437e637e5229a6c0
3. https://github.com/distributed-system-analysis/pbench/pull/3114/commits/5440984e393236c9eed1b48f52a26b0e8a23f995
4. https://github.com/distributed-system-analysis/pbench/pull/3114/commits/518ee268265ce7f1a16757f1b0f23b9d86e71fad
5. https://github.com/distributed-system-analysis/pbench/pull/3114/commits/652a9658fbd3790f6fd7a4fd5593222b6fbdeb8c
=> Remove the need for local logger in `auth` module

.pre-commit-config.yaml, lint-requirements.txt
Suggested commit message to use:
----
First, the reference to `gitlab.com` for `flake8` was incorrect.  It has
been corrected to `github.com`.
If one starts using a different python interpreter (for example, if you
upgrade your linux distribution and that upgrade defaults to a new
version) then your previous pre-commit setup will need to be re-
installed.
Because of the `gitlab.com` reference that was not possible.
The second change is to bump the versions of all the pre-commit programs
used, `black`, `flake8`, and `isort`, to their latest versions.  It is
unfortunate but the existing versions we are using don't work with newer
versions of the Python 3, in particular, Python 3.11, but they do work
with Python 3.9 and later.
=> Address problems with our `pre-commit` config

lib/pbench/test/unit/server/auth/conftest.py, lib/pbench/test/unit/server/auth/test_auth.py, server/requirements.txt
We use pyjwt python library to decode the OIDC tokens internally. OIDC tokens are usually RS256-encoded tokens. However, to decode these types of tokens we also need to install a cryptography library. 
The recommended way to install both these libraries is mentioned here: 
https://pyjwt.readthedocs.io/en/latest/installation.html#installation-cryptography
PBENCH-1071
=> Add cryptography dependency for decoding RSA tokens

lib/pbench/cli/server/shell.py, lib/pbench/test/unit/server/test_shell_cli.py
A mistake was made in PR #3170 which went unnoticed until the functional tests were run (see https://github.com/distributed-system-analysis/pbench/pull/3170/commits/f4299ab55257839f14e49e5099cbb08e3a9925ad#diff-2db83614a5b08b212f0017da6957f4fb794106d2d4473c99f2ac6ec258d5d90bR9).
This PR adds a set of unit tests for `pbench.cli.server.shell` so that any changes to that module can be verified quickly before waiting for the CI job to run functional tests.
Two commits are provided here, the first removes the use of `sys.exit()` from the `main()` method of `shell.py`, since the auto-generated command wrapper for it already takes does that.  This makes writing unit tests a bit easier since we wont have to catch `SystemExit`.
=> First pass unit tests for `shell.py`

jenkins/Pipeline.gy
We are suffering an unsightly (but out of sight) build-up of container images which eventually fills the local storage and causes builds to fail.  This PR adds a pipeline stage which runs at the end of every build to remove any `*pbench-server*` and `*pbench-agent*` container images which don't have running containers associated with them.  This should remove any images built in the current run as well as similar images which weren't removed (for whatever reason) by previous runs, but it should leave behind images _used_ by the build (such as the container image used by `jenkins/run`, the images used to run the RPM builds, the images used as base images for building other images, and the images run in conjunction with the canned Pbench server).
=> Add a pipeline stage to clear out container images

lib/pbench/cli/server/shell.py
We refactor the error handling so that `main()` is a small wrapper which prints out errors, and the heavy lifting of creating the gunicorn process is handled in `run_gunicorn()`.
=> Refactor `shell.py` error handling

lib/pbench/test/unit/server/__init__.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/database/test_datasets_db.py, lib/pbench/test/unit/server/query_apis/test_query_builder.py
_[This PR is a follow-on to PR #3221.]_
The first commit replaces some literals with references to symbolic constants, and makes explicit the ID for the "other user" when it is created.
The second commit is a sequence of hopefully inconsequential changes to satisfy the Python linter.
=> Use symbolic constants for user IDs when creating users in tests. 

lib/pbench/__init__.py, lib/pbench/agent/__init__.py, lib/pbench/server/__init__.py, lib/pbench/test/unit/agent/test_config.py, lib/pbench/test/unit/server/test_shell_cli.py, server/bin/pbench-backup-tarballs, server/bin/pbench-cull-unpacked-tarballs, server/bin/pbench-verify-backup-tarballs
We hide all access to the internal `ConfigParser` object so that all access will be through the `PbenchConfig` object.
=> Hide access to internal conf object

lib/pbench/server/__init__.py, server/bin/pbench-backup-tarballs, server/bin/pbench-cull-unpacked-tarballs, server/bin/pbench-verify-backup-tarballs
We move the `PbenchServerConfig.get_valid_dir_option()` method to a module method, renaming it to `get_resolved_dir()`.  We also move `_get_valid_path` to a module method.
=> Move `get_valid_dir_option` to module method

build.sh, lib/pbench/server/database/alembic.migration, tox.ini
We move to a slightly more general model where we can support specific Alembic operations passed as arguments.
This was very useful to easily run the auto-generated migrations.
=> Add ability to auto-generate alembic migrations

agent/containers/images/Makefile, jenkins/Pipeline.gy, jenkins/set-expiration
This PR modifies the places where the CI pushes containers to the remote registry to also set an automatic expiration date on the pushed containers.  In this way, containers pushed by PR builds will eventually be removed without requiring manual clean-up of the remote registry.  This change only affects Agent and Server containers; it doesn't affect the persistent containers such as the CI's own container and the containers used to build RPMs; it also doesn't affect branch builds which are "published" by the CI, and it doesn't affect containers which are "released".  It only affects containers which are built by the CI for functional testing.
Details:
- Add a script which is basically just a wrapper around a `curl` command which hits a Quay RESTful interface to set the expiration date for …
=> Add expirations on containers pushed to remote registries

lib/pbench/server/api/resources/datasets_daterange.py, lib/pbench/server/api/resources/datasets_list.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/api/resources/query_apis/datasets_delete.py, lib/pbench/server/api/resources/query_apis/datasets_update.py, lib/pbench/server/api/resources/upload_api.py, lib/pbench/server/database/alembic/versions/fa12f45a2a5a_initial_database_schema.py, lib/pbench/server/database/database.py, lib/pbench/server/database/models/datasets.py, lib/pbench/server/indexing_tarballs.py, lib/pbench/server/sync.py, lib/pbench/server/unpack_tarballs.py, lib/pbench/test/functional/server/test_put.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/database/test_datasets_db.py, lib/pbench/test/unit/server/database/test_datasets_metadata_db.py, lib/pbench/test/unit/server/query_apis/test_datasets_update.py, lib/pbench/test/unit/server/test_datasets_daterange.py, lib/pbench/test/unit/server/test_datasets_list.py, lib/pbench/test/unit/server/test_datasets_metadata.py, lib/pbench/test/unit/server/test_indexing_tarballs.py, lib/pbench/test/unit/server/test_requests.py, lib/pbench/test/unit/server/test_sync.py, lib/pbench/test/unit/server/test_unpack_tarballs.py, server/bin/pbench-backup-tarballs
PBENCH-993
This is fairly large, but yet much smaller than it started out. This solves two problems in Pbench Server task scheduling:
1. The default SQLAlchemy transaction model is to start a transaction on any SELECT and end it on any UPDATE or INSERT; this means there's no potential for atomic update. This impacts the management of all internal context, but serious problems have been observed with the "operation" and "state" of the datasets.
2. I began the dataset with the concept of a "state", as the dataset progresses through upload, backup, unpack, index, and delete. I quickly discovered that this wasn't ideal, but had trouble backing off completely from the concept. When I added the DB-based "operation" to replace the old filesystem links, the relationship between "operation" and …
=> Fix operation synchronization

lib/pbench/client/__init__.py, lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/datasets_metadata.py, lib/pbench/server/api/resources/upload_api.py, lib/pbench/server/database/models/datasets.py, lib/pbench/test/functional/server/test_put.py, lib/pbench/test/unit/server/test_datasets_metadata.py, lib/pbench/test/unit/server/test_requests.py
PBENCH-1059
Allow the Agent (or other client) to define metadata keys when initially uploading a dataset to the Pbench Server by specifying the `?metadata` query parameter on the `PUT`.
=> Implement metadata for PUT

lib/pbench/server/api/resources/endpoint_configure.py, lib/pbench/test/functional/server/test_connect.py, lib/pbench/test/unit/server/test_endpoint_configure.py
Addresses issue #3240 
Originally asked [here](https://github.com/distributed-system-analysis/pbench/pull/3233#discussion_r1101403449) 
Commit message:
Remove hyphen from openid-connect section of the endpoints API
- Getting rid of the excess quotes and brackets would make this easier to read
- It also makes easier to reference in Dashboard javascript code when there is 
no hyphen involved (`endpoints.openid` instead of `endpoints['openid-connect']`)
=> Remove hyphen from openid-connect section of the endpoints api

lib/pbench/server/auth/__init__.py, lib/pbench/server/auth/auth.py, lib/pbench/test/unit/server/auth/test_auth.py
- Removes the get_userinfo functionality from the auth module
- Removes the online token validation capability from the server
- OIDC token validation will only happen locally
PBENCH-1074
=> Remove unused userinfo and online token validation

lib/pbench/server/auth/auth.py
And only try to verify auth tokens if we actually have one.
----
Stack trace when `verify_auth()` receives an empty authorization token:
```
2023-02-10T20:01:47.536580 ERROR 115 140622575369088 pbench.server.api auth verify_auth 135 -- Unexpected exception occurred while verifying the auth token '': Not enough segments
Traceback (most recent call last):
File "/home/pbench/.local/lib/python3.9/site-packages/jwt/api_jws.py", line 250, in _load
signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/opt/pbench-server/lib/pbench/server/auth/auth.py", line 133, in verify_auth
user = verify_auth_internal(auth_token)
File …
```
=> Capture `DecodeError` generated by func tests

exec-tests
Currently, one can control what unit tests get run under Tox via a command like the following:
```
tox -- agent python pbench.test.unit.agent.task.test_copy_result_tb
```
Ostensibly, this should run only the tests in the `test_copy_result_tb` module.  Sadly, it does not only that but it also runs 50 or even 500 other tests from `pbench.test.unit.common`, `pbench.test.unit.agent` and `pbench.test.functional.agent`.
This change allows `exec-tests` to skip appending the extra paths to the test list.
However, I have a question for reviewers (i.e., @portante).  The last argument to `tox`/`exec-tests` is named "posargs" and the code comment claims that it is for "positional arguments".  However, the value is inserted after the PyTest `--pyargs` switch, which makes me think that the only …
=> Allow Tox to run a single unit test

lib/pbench/server/indexer.py, lib/pbench/server/report.py, lib/pbench/server/templates.py, lib/pbench/test/unit/server/test_indexing_tarballs.py
We don't want to derive the location of the library directory hierarchy based off of another configuration parameter since there is an explicit configuration parameter for the library directory itself.
=> Use `LIBDIR` (`lib-dir`) config, don't derive it

agent/util-scripts/gold/pbench-results-push/test-24.txt, agent/util-scripts/gold/pbench-results-push/test-36.txt, lib/pbench/agent/results.py, lib/pbench/cli/agent/commands/results/move.py, lib/pbench/cli/agent/commands/results/push.py, lib/pbench/test/unit/agent/task/test_copy_result_tb.py, lib/pbench/test/unit/agent/task/test_results_push.py
Drop controller from PUT agent side
The server no longer relies on the controller
header to PUT, the agent should stop generating
and sending it.
Will be merged after #3193  #3194
=> Drop controller from PUT agent side

lib/pbench/cli/server/shell.py, lib/pbench/common/__init__.py, lib/pbench/server/__init__.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/auth/__init__.py, lib/pbench/server/database/database.py, lib/pbench/server/indexer.py, lib/pbench/test/unit/common/test_wait_for_uri.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/query_apis/conftest.py, lib/pbench/test/unit/server/test_indexer.py, lib/pbench/test/unit/server/test_shell_cli.py, server/lib/config/pbench-server-default.cfg, server/pbenchinacan/etc/pbench-server/pbench-server.cfg
Remove the stack traces posted in the logs by all the cron jobs when the Pbench Server container starts up.  We do this by having the "shell" process first wait for the Elasticsearch instance to show up, and then load / update all the index templates before starting all the cron jobs.  This avoids the stack traces generated by race conditions across the various cron processes.
----
1. Rename `wait_for_database` to `wait_for_uri`
2. Wait for Elasticsearch using URI
3. Add `init_indexing()` module method and use
* The new `init_indexing()` module method is used to ensure that the indexing configuration is working before we start all the cron jobs, thus avoiding stack traces from cron jobs competing to load the indexing templates
----
Commit message:
Ensure Elasticsearch instance setup …
=> Add `init_indexing()` module method and use

agent/util-scripts/gold/pbench-results-move/test-23.txt, agent/util-scripts/gold/pbench-results-push/test-24.txt, lib/pbench/agent/results.py, lib/pbench/cli/agent/commands/results/move.py, lib/pbench/cli/agent/commands/results/push.py, lib/pbench/cli/agent/commands/results/results_options.py, lib/pbench/test/unit/agent/task/test_copy_result_tb.py, lib/pbench/test/unit/agent/task/test_results_move.py, lib/pbench/test/unit/agent/task/test_results_push.py
This PR will allow the Agent (or other client) to define metadata keys when initially uploading a dataset to the Pbench Server by specifying the ?metadata query parameter on the PUT.
This PR is based on #3187 and should be merged after that.
=> Add metadata query parameter on PUT

lib/pbench/cli/agent/commands/generate_token.py, lib/pbench/test/unit/agent/task/test_generate_token.py
This option makes it a bit easier to script the invocation of `pbench-generate-token` where username and/or password prompts are required (the prompt does not get mixed up into the token output).
----
Separated into its own PR from PR #3259.
=> Add `--output` option to `pbench-generate-token`

lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/datasets_list.py, lib/pbench/server/database/database.py, lib/pbench/server/database/models/datasets.py, lib/pbench/test/functional/server/test_put.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/test_datasets_list.py, server/test-requirements.txt
PBENCH-825
Create the new query parameter `?filter` on `/datasets/list` to allow the query to filter on the basis of arbitrary `Metadata` key values. This code experimentally allows a combination of _AND_ and _OR_ as well as exact string and "contains" matches, using symbols in the filter value.
E.g., to find all "fio" runs from 2018, you could do the following. `:fio` is an exact value match on "fio" while `:~2018` requires that the string "2018" appear within the value:
`?filter=dataset.metalog.pbench.script:fio,dataset.metalog.date:~2018`
(We have the `start` and `end` keywords, which provide more exact timestamp matches, but you get the idea.)
Or, to find all datasets that have been favorited by the current user _or_ marked "seen" by the owner (should someone want to to this), the `^` …
=> Filter datasets by metadata

jenkins/run-server-func-tests
This change overhauls `run-server-func-tests` to try to make it clean up properly in all cases (except when we don't want it to), as well as performing some basic housekeeping.
- Bring the `IMAGE_*` environment variable definitions up to date with their usage in `jenkins/run`.
- Group the definitions at the top of the file.
- Add command line argument verification.
- Make the installation of the cleanup handler unconditional but make its execution conditional (this ensures that it covers all cases and prints the "no cleanup" warning when it should).
- Make the cleanup handling cover the `run-pbench-in-a-can` invocation, so that it cleans up start-up problems there, as well.
- The cleanup handler now also runs on `EXIT`; if it was not requested and everything runs successfully, the handler …
=> Overhaul `run-server-func-tests`

jenkins/run-server-func-tests
The previous change in #3268 was incomplete:  in case of an interrupt, we actually need to exit the script (otherwise, apparently, `trap` returns from the handler back to the point of interruption...), and, we need to remove the handler for `exit` in order for that to actually work.  😊 
Note that I've intentionally left the removal of the trap handling to the _end_ of the trap handler:  this enables handling of traps during the handling of traps, which improves the likelihood that the cleanup will happen (if requested...if not requested, it's a pretty small window to hit).  It does create the possibility of being trapped in the trap handler, but I think that retrying the cleanup is worth the risk (FWIW, the `podman` commands run a little faster the each time you interrupt them 😉).
BTW, if …
=> Fix run-server-func-tests to handle interrupts properly

build.sh, dashboard/Makefile, jenkins/runlocal
This PR adds a Makefile for the Pbench Dashboard, to allow it to be built (and re-built) only as needed and to provide an encapsulated interface for running lint and unit tests, etc.
The `build.sh` script which is used (e.g.) by the CI to "build Pbench" is changed to use `make` to clear and install the Dashboard dependences, to run lint, and to run unit tests.  And, a new `make` invocation is added after we build the Server and Agent RPMs to also build the Dashboard deployment.
Also, `jenkins/runlocal` is modified to build the Dashboard, as well.  (Note that, because we're using `make`, the Dashboard deployment would only be built if it is out of date, but we're specifying `clean` as we do for the Server RPM build, so it will be rebuilt from scratch every time.)
Once the Dashboard has …
=> Build the Dashboard

lib/pbench/server/__init__.py, lib/pbench/test/unit/server/conftest.py, server/lib/config/pbench-server-default.cfg
PBENCH-996
In our containerized deployment model, we don't have the commit key in `PbenchServerConfig` so the `/api/v1/endpoints` API populates the `"identification"` field with the default of `"(unknown)"`.
Restore the version by reading the `VERSION` and `SHA1` files written in `/opt/pbench-server` by the installer.
=> Restore endpoints.identification in container

server/lib/pbench/report.py
Rather than throwing an assertion error, just issue a warning when
`pbench-report-status` ends up not sending anything to the configured
Elasticsearch instance.
----
Pulled from PR #3288, #3289, #3290, #3292, and #3293.
=> Warn when report generation does nothing

lib/pbench/common/logger.py
According to the SysLogHandler documentation [1], the `ident` field can be set on every instance of a SysLogHandler to have a "ident" or "tag" prefix to identify the source of the message.
When reviewing logs generated via `journalctl -f`, without the `ident` field set, a log entry generated by the pbench server code might look like:
Mar 01 00:37:23 host.example.com python3[2737452]: \
2023-03-01T00:37:23.909096 DEBUG 2737452 140124701973376 \
my-logger.logger my_func 146 -- foo - debug
Where the "my-logger.logger" string is the logger "name" and the module name _inside_ the log mesasge, but `journalctl` uses an identifer of:
<program name>[<PID>]
after the host name.
This is because `journalctl` emits the log message "ident" field using its trusted fields of `_COMM` ("python3") and …
=> Add the syslog "ident" field back

lib/pbench/client/__init__.py, lib/pbench/server/database/alembic/versions/9cc638cb865c_operationname.py, lib/pbench/test/functional/server/test_put.py
The original `OperationName` ENUM type had the values BACKUP, DELETE, INDEX, REINDEX, TOOLINDEX, UNPACK, and UPLOAD. The BACKUP and UNPACK operations were later removed, and the UPDATE operation was added. However, alembic does not check ENUM values nor does autogenerate provide automated upgrades.
Dropping ENUM values is problematic: it would mean generating code to query the live server database and either drop or change existing rows, which would be difficult to test. Having obsolete values in an ENUM is not problematic, unless the number becomes overwhelming, so this PR doesn't attempt to address that.
However, new server code will attempt to use the UPDATE operation, and this will cause SQLAlchemy failures as the value is unknown. This PR simply adds that value to the ENUM.
=> Correct alembic database state

server/requirements.txt
Commit body below (commit summary is PR title):
PR #3296 (commit 7e78b1d) failed to remove the `boto3` requirement.
=> Remove left over `boto3` requirement

server/pbenchinacan/deploy, server/pbenchinacan/run-pbench-in-a-can
We invoke the Pbench Server container several times during the setup before actually running it in deployment.  The initial invocations of `podman run` currently use the default pull policy while the `PB_SERVER_PULL_POLICY` value is only applied on the deployment run, by which point we've potentially pulled a new image from the remote repository, whether that was desired or not.
Prior to change:
| `PB_SERVER_PULL_POLICY` | Image initially present | Image initially absent | Notes |
| --- | - | - | - |
| always | download once | download twice | If the image is already present, we use the "wrong" (local) image for the setup before downloading the requested one; otherwise, we download it twice.  (Note that re-downloading the same image moves no data). |
| missing | no download | download …
=> Use a consistent pull policy during Server deployment

server/bin/gold/test-27.txt, server/bin/gold/test-5.1.txt, server/bin/gold/test-5.2.txt, server/bin/gold/test-5.txt, server/bin/pbench-cull-unpacked-tarballs.py, server/bin/test-bin/verify_cee, server/bin/unittests
Commit message body follows, summary is PR title:
Instead of using the `Report` class to index a report document, we
change to use individual log entries to record the actions taken by
`pbench-cull-unpacked-tarballs`.
There are three types of JSON records emitted, `summary`, `action_set`,
and `action` (examples below), where a unique "execution ID" is
generated for all report logs, and included as a field value.  This
allows somebody to search for all report logs from a given execution,
e.g. `pbench.report.action.execution_id: ae9baf5d7*` (lucene syntax),
or look for a certain status (`succ`, `fail`, or `part`), e.g.
`NOT pbench.report.action.status:succ`.
ae9baf5d7f271b3a707e28e10d31e7a8: Culled 3 unpacked tar ball \
directories (0 errors) in 0.00 secs -- @cee:\
{
"pbench": {
"report": { …
=> Use normal logs with JSON to report cull behaviors

server/bin/pbench-dispatch.sh
PR #3307 (commit 28efeb02a) missed fixes to quote arguments to `test`.
=> Correct `test` arguments in dispatch

server/pbenchinacan/deploy
Moving toward deploying the Pbench Server under a `systemctl` service module, we need the ability to add a few switches to the Pbench Server's Podman `run` invocation.
This change provides a new environment variable, `PB_SERVER_PODMAN_SWITCHES`, for this.  (This variable is distinct from the existing `EXTRA_PODMAN_SWITCHES` to prevent crosstalk between the options we specify for `jenkins/run` and the options that we want for the Pbench Server deployment.)  If the variable is undefined, then it will expand vacuously and have no effect.
=> Add hook for setting podman switches for Pbench Server deployment

lib/pbench/server/__init__.py, lib/pbench/server/api/resources/upload_api.py, lib/pbench/server/utils.py, lib/pbench/test/unit/server/test_utils.py, server/lib/config/pbench-server-default.cfg
PBENCH-151
We want to rely on easily configurable NGINX size limits for tarball uploads, while the current server code checks an internal limit that defaults to 1Gb.
A quick survey of the production server shows over 5000 files exceeding 1G and 204 tarballs over 10G.
This PR simply removes the internal check. We never had a test for this since we never found a way to fake the content-length header.
=> Drop internal PUT size limit

lib/pbench/server/api/resources/users_api.py, lib/pbench/server/database/models/users.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/test_user_auth.py, server/requirements.txt
The email validator seems to be flaking out on us. We're going to be removing the internal user registration entirely soon, and we don't actually use the email addresses, so validation serves no real purpose. To avoid problems for now, rip out email validation entirely.
=> Disable email validation

server/bin/gold/test-13.txt, server/bin/gold/test-15.txt, server/bin/pbench-dispatch.sh
We move the `log_init` in `pbench-dispatch.sh` up higher so as to catch as many of the early setup problems in the logs as possible.
=> Use `log_init` earlier to capture startup failures

agent/containers/images/Makefile, agent/rpm/Makefile, jenkins/Makefile
This PR drops Fedora 35 from our list of default Linux distributions (it went end-of-life three months ago, and the base container for it is no longer available from Quay.io), and adds Fedora 37 and Fedora 38 to the list.
This affects support for building RPMs (particularly the Agent) and for building Agent containers.
=> Update default Linux distros:  drop F35 and add F37 & F38

server/bin/pbench-sync-satellite.sh
The goal of these changes is to cleanup and make consistent as much as possible code and comments in `pbench-sync-satellite.sh`.
Further changes to this file will be made where this commit helps to reduce the amount of change coming by making it easier to review these mechanical changes.
No logic was changed, just `[ ]` to `[[ ]]`, `$var` to `${var}`, one line's indent was corrected, `(( var++ ))` used, and comments re-wrapped and capitalized.
=> Cleanup & consistency in `*-sync-satellite`

agent/containers/images/Dockerfile.layered.j2, agent/containers/images/container_entrypoint, contrib/containerized-pbench/pbench, contrib/containerized-pbench/pbench_demo
The Agent commands require the environment which the `agent/profile` script sets up.  This script is normally run automatically when a user logs in by virtue of a symbolic link in `/etc/profile.d`; however, when a user invokes containerized Agent commands, although the profile script exists inside the container, there is no login performed, and so the script isn't run...and it is cumbersome to cause it to run inside the container environment in conjunction with running a pbench command (the easiest approach is to create a script (see [`contrib/containerized-pbench/README.md`](https://github.com/distributed-system-analysis/pbench/blob/main/contrib/containerized-pbench/README.md)), but the user has to map that into the container in order to use it; otherwise, the user has to run an …
=> Add an explicit ENTRYPOINT to the Agent "all" containers

server/bin/gold/test-0.3.txt, server/bin/gold/test-0.4.txt, server/bin/gold/test-1.txt, server/bin/gold/test-29.txt, server/bin/gold/test-30.txt, server/bin/gold/test-31.txt, server/bin/gold/test-32.txt, server/bin/gold/test-9.txt, server/bin/pbench-sync-satellite.sh, server/bin/state/config/pbench-server.cfg, server/bin/state/test-0.4.setup, server/bin/unittests
Commit message body below, commit summary is PR title:
Before beginning any `pbench-sync-satellite` operation, each config
option is checked before beginning.  The normal logging is setup first
so that it will also show up in the syslog entries.
The new `test-0.3` covers the verification of the required backup
directory configuration for `pbench-dispatch`, and the new `test-0.4`
covers the verification of the required `pbench-receive-dir-prefix` for
pbench-sync-satellite & pbench-dispatch.
The new `test-9` covers a missing argument to `pbench-sync-satellite`,
and the tests `test-29` .. `test-32` covers handling of the four
required satellite options.
=> Add checks for all required sync satellite configs

lib/pbench/server/__init__.py, lib/pbench/server/indexer.py, lib/pbench/server/indexing_tarballs.py, server/bin/pbench-reindex
"Well ... it's about time!"
"Now would be a good time, Scotty!"
Add an intermediate `utcnow()` module method to expose as an alternative to a string based timestamp.
We also drop the use of `_time()` where possible.
=> Add `utcnow()` module method; drop _time() use

run-unittests, tox.ini
Commit message body below, commit summary in PR title:
Commit 677f8890038b44d00451adf2c297c565a6c81c7c removed the Python3 unit
tests by failed to remove the `py3-server` tox environment.
=> Remove left-over `py3-server` tox env

server/lib/config/pbench-server-default.cfg, server/pbenchinacan/etc/pbench-server/pbench-server.cfg
Remove obsolete settings and comments from server config files.
=> Backport config file cleanup to 0.72 branch

lib/pbench/server/api/resources/upload_api.py, lib/pbench/test/unit/server/test_upload.py
PBENCH-1112
In testing we're seeing duplicate tarball names with distinct MD5 values. We have reduced the importance of duplicate tarball names, relying on the dataset resource ID (MD5) for "uniqueness" internally. However the cache manager still maintains tarball files and MD5 companions on disk, and the upload API has to temporarily store the API payload somewhere. When the duplicate tarballs are uploaded concurrently, the `.open()` fails, leading to an internal server error.
Instead, move temporary upload files into an MD5-based subdirectory, and clean up that directory after upload completes.
__NOTE__: I'm pushing this early as a draft for testing and exposure. I still need to write some unit tests this afternoon before it's formally ready for review.
=> Gracefully handle duplicate name with unique MD5

dashboard/.prettierignore, dashboard/Makefile, dashboard/src/App.css, dashboard/src/actions/overviewActions.js, dashboard/src/actions/tableOfContentActions.js, dashboard/src/assets/constants/paginationConstants.js, dashboard/src/index.css, dashboard/src/modules/components/AlertComponent/index.jsx, dashboard/src/modules/components/AuthComponent/index.less, dashboard/src/modules/components/BackgroundComponent/index.jsx, dashboard/src/modules/components/DatePickerComponent/index.less, dashboard/src/modules/components/HeaderComponent/index.less, dashboard/src/modules/components/LoadingComponent/index.less, dashboard/src/modules/components/OverviewComponent/index.less, dashboard/src/modules/components/TableComponent/index.less, dashboard/src/modules/components/TableOfContent/index.jsx, dashboard/src/modules/components/TableOfContent/index.less, dashboard/src/modules/containers/AuthLayout/index.less, dashboard/src/modules/containers/MainLayout/index.less, dashboard/src/reducers/authReducer.js, dashboard/src/reducers/datasetListReducer.js, dashboard/src/reportWebVitals.js, dashboard/src/store/store.js, dashboard/src/utils/helper.js
We assume that code for the Dashboard is formatted via [Prettier](https://prettier.io/).  This change adds a command to the Dashboard `run_list` Makefile target to check and enforce this.  And, it makes additional changes to conform to Prettier's requirements.
PBENCH-1114
=> Add Prettier formatting check to the Dashboard lint check

lib/pbench/server/api/resources/datasets_list.py, lib/pbench/server/database/database.py, lib/pbench/test/unit/server/test_datasets_list.py
PBENCH-1117
I discovered that the single simplistic `LEFT JOIN` allows combining native `Dataset` and `Metadata` terms in a `SELECT`, but with limitations: because the SQL join constructs a row for each `Metadata` match, matches for, e.g., `server.origin` and `dataset.metalog.pbench.script` or `global.server.legacy` will appear on separate table rows. Each has duplicate `Dataset` columns, but that doesn't help when trying to select across namespaces.
The only effective solution I was able to find was to cascade the joins in order to build a new table with a separate column for each metadata namespace row matching the dataset. This allows a single `SELECT` to work across the columns in the new table.
This broke the `keysummary` code, requiring some adjustment there. With the join now …
=> Fix /datasets?filter to select across namespaces

contrib/containerized-pbench/pbench, contrib/containerized-pbench/pbench_demo
In the `pbench` script:
- Change the container tag from `latest` (which is the latest _release_) to `main` (which is the latest "published" image).
- Use `--security-opt=label=disable` to avoid problems with relabeling the `~/.ssh` directory contents.
In the `pbench_demo` script:
- Move the invocation of `pbench-generate-token` to the beginning of the commands, to help "fail early" in the event of configuration problems.
- Change the run-time from 20s to 5s.
- Add an explanatory comment to a bit of subtlety.
=> Update contrib scripts for Perfconf demo

jenkins/Pipeline.gy
The container images built by the CI are pushed to an external registry and set with an expiration date for auto-deletion.  This is valuable for transient images which are built for PRs, but it is unfortunate for images built from branches in the main repo, such as release branches and `main`. This change moves the setting of the expiration date to its own pipeline stage which is executed only for PRs, so that branch builds will not expire.
PBENCH-1113
=> Move set-expiration of Server container to a conditional pipeline stage (`b0.72` backport)

jenkins/Pipeline.gy
The container images built by the CI are pushed to an external registry and set with an expiration date for auto-deletion.  This is valuable for transient images which are built for PRs, but it is unfortunate for images built from branches in the main repo, such as release branches and `main`. This change moves the setting of the expiration date to its own pipeline stage which is executed only for PRs, so that branch builds will not expire.
PBENCH-1113
=> Move set-expiration of Server container to a conditional pipeline stage

dashboard/src/utils/helper.js, docs/API/V1/README.md, docs/API/V1/contents.md, docs/API/V1/daterange.md, docs/API/V1/delete.md, docs/API/V1/detail.md, docs/API/V1/endpoints.md, docs/API/V1/inventory.md, docs/API/V1/list.md, docs/API/V1/login.md, docs/API/V1/logout.md, docs/API/V1/publish.md, docs/API/V1/register.md, docs/API/V1/server_audit.md, docs/API/V1/server_settings.md, docs/API/V1/update.md, docs/API/V1/upload.md, docs/API/V1/user.md, docs/API/access_model.md, docs/API/metadata.md
PBENCH-829
Fill out and update API documentation.
=> API documentation improvements

jenkins/runlocal
This was introduced in PR #3211...I don't know how we all missed it.
=> Fix a typo in `jenkins/runlocal` which inadvertently revokes RHEL 9 support

agent/config/pbench-agent-default.cfg, lib/pbench/agent/__init__.py, lib/pbench/agent/base.py, lib/pbench/agent/results.py, lib/pbench/cli/agent/commands/results/move.py, lib/pbench/cli/agent/commands/results/push.py, lib/pbench/test/unit/agent/task/test_copy_result_tb.py, lib/pbench/test/unit/agent/task/test_results_push.py
This PR consists of seven commits:
- the first commit disables file logging from all agent python commands. It also cleans up some now unnecessary cruft.
-  the second commit changes `copy_result-tb` to return the server response without interpreting it (although it still raises exceptions on some errors, e.g. connection errors). The response status codes are interpreted in `push.py` and `move.py`. `push.py` is silent on success; it outputs an error message but still exits with 0 on any other OK status; otherwise, it outputs an error message  and exits with 1. `move.py` translates all non-OK responses to exceptions.
- the third commit is undone by that last commit, so it will disappear after the squashing.
- the fourth limits the scope of monkeypatching some `pathlib' components that were …
=> pbench-results-push: logging fixes and better reporting 

lib/pbench/test/unit/agent/task/test_copy_result_tb.py, lib/pbench/test/unit/agent/task/test_results_push.py
Fixes #3374
This is a continuation of #3348, implementing fixes to the pbench_results_push tests. The main one is to subsume some exception tests under the parametrized "normal" case and eliminate redundant tests.
=> Fix various problems in the pbench_results_push tests

server/lib/config/nginx.conf
The `try_files` directive in nginx will issue a 301 response if the given URI (`$uri`) exists as a directory (though this behavior is not explicitly documented).  We remove the directory check and replace it with an explicit check for `index.html`.
=> Remove directory check, replace with index.html

lib/pbench/test/unit/server/auth/test_auth.py
PBENCH-1130
Several tests in `test_auth.py` implicitly depended on previous DB init; they were failing occasionally in CI parallel test runs when scheduled without the prior setup.
Resolves #3381
=> Add explicit test_auth dependencies

lib/pbench/server/database/alembic/versions/5679217a62bb_sync_message.py, lib/pbench/server/database/models/datasets.py, lib/pbench/server/indexing_tarballs.py, lib/pbench/test/unit/server/test_indexing_tarballs.py, lib/pbench/test/unit/server/test_sync.py
PBENCH-1120
A SQL error was observed in deployment where `pbench-index` logged an error on the `INDEX` sync object because a tarball was somehow not present. The message string generated by `indexing_tarballs.py` exceeded the `VARCHAR(255)` column specification.
This isn't an attempt to address the root problem, but to address the symptom of overloading the operation table message column in the future so at least errors are properly recorded.
This reworks some of the `indexing_tarballs.py` messages to avoid redundancy (e.g., naming the dataset or tarball isn't necessary as the records are linked to the `Dataset`), but also removes the limit on the message column as a precaution.
(_NOTE_: it also adds some unit test cases, although these are more documentation than "real tests" as sqlite3, …
=> Avoid Sync message overflow

lib/pbench/server/database/alembic/versions/5679217a62bb_sync_message.py, lib/pbench/server/database/models/datasets.py, lib/pbench/server/indexing_tarballs.py, lib/pbench/test/unit/server/test_indexing_tarballs.py, lib/pbench/test/unit/server/test_sync.py
PBENCH-1120
Cherry-pick to b0.72.
A SQL error was observed in deployment where `pbench-index` logged an error on the `INDEX` sync object because a tarball was somehow not present. The message string generated by `indexing_tarballs.py` exceeded the `VARCHAR(255)` column specification.
This isn't an attempt to address the root problem, but to address the symptom of overloading the operation table message column in the future so at least errors are properly recorded.
This reworks some of the `indexing_tarballs.py` messages to avoid redundancy (e.g., naming the dataset or tarball isn't necessary as the records are linked to the `Dataset`), but also removes the limit on the message column as a precaution.
=> Avoid Sync message overflow (#3389)

docs/API/V1/list.md, jenkins/run-server-func-tests, lib/pbench/client/__init__.py, lib/pbench/server/api/resources/datasets_list.py, lib/pbench/test/functional/server/test_put.py, lib/pbench/test/unit/server/test_datasets_list.py
PBENCH-1124
Support type-cast filter expressions in `GET /datasets`. The primary objective is to support a paginated "Expiring Soon" view in the dashboard, requiring the ability to look for datasets expiring before a fixed timestamp. Previously, `GET /datasets?filter` worked by casting all SQL data to "string" and then comparing against the raw extracted string from the query parameter. Now it's possible to identify a type as well as additional comparison operators. For example, `GET /datasets?filter=server.deletion:<2023-05-01:date` will select all datasets with expiration timestamps earlier than 2023-05-1.
To target this specific capability, the functional tests now override the default `server.deletion` on some uploads and verify that those datasets are returned by the filtered query.
=> Add typed filtering

agent/containers/images/Makefile
Now that Fedora 38 is GA, let's see if we can build it!
=> Add fedora-38 to the default container list for the Agent build

server/requirements.txt
A Flask package update today breaks all Pbench authentication; it's not clear why, and until we can figure it out, let's lock Flask below 2.3 to avoid the issue. This also locks Werkzeug to match because that was causing issues in testing.
=> Lock flask and Werkzeug below 2.3.0 for now

lib/pbench/server/auth/__init__.py, lib/pbench/test/unit/server/auth/test_auth.py
We need to catch an invalid algorithm error when we decode the SSO token and raise it as OpenIDTokenInvalid. This is because we are using HS256 for our internal api key encode-decode. 
PBENCH_1136
=> Add invalid algorithm exception check

lib/pbench/client/__init__.py, lib/pbench/client/types.py, lib/pbench/server/database/alembic.migration, lib/pbench/test/functional/server/test_put.py
PBENCH-1135
Add mechanism and a test case to verify that we can authenticate and identify the client user from an API key, simplistically using `GET /datasets?mine`.
This also adds a new `alembic-migration` command, `show` to display what alembic sees as the "heads" and "history" of the revision chain. I added this when I accidentally constructed multiple heads and got weird errors while I was building the `AuthType.API_KEY` upgrade, but didn't include it in that final PR. It seems useful, so I'm sweeping it in here.
=> Add API Key functional testing

server/requirements.txt
Werkzeug 2.3.1 appears to have resolved our problems using Flask 2.3.x, so restore the original floating dependency on flask.
This doesn't address the issue of whether we want to evaluate setting explicit dependencies across the board; the risk is that this forces us to periodically re-evaluate and update to avoid obsolescence and CVE problems, while the benefit is we don't have the sort of fun surprises recently delivered to us by flask and keycloak-js...
=> Restore floating Flask / Werkzeug dependency

lib/pbench/cli/server/shell.py, lib/pbench/test/unit/server/test_shell_cli.py, server/lib/config/nginx.conf, server/lib/config/pbench-server-default.cfg
To avoid employing SSL certificates in both NGINX and Gunicorn we need to make them communicate over a Unix socket and not over TCP port.
PBENCH-1139
=> Unix socket for the nginx and gunicorn communication

agent/Makefile
Fixes #3404
Add pbench-tools-kill to the click commands in the agent Makefile.
=> Build pbench-tools-kill - Backport of #3405 to b0.72

lib/pbench/server/api/resources/endpoint_configure.py, lib/pbench/test/unit/server/test_endpoint_configure.py, server/lib/config/nginx.conf
Let the Nginx convey schema to our Flask application for building urls instead of hardcoding it in the endpoint_configure.py.
PBENCH-1139
=> Get the uri schema from NGINX 

agent/ansible/collection/roles/pbench_clean_yum_cache/tasks/main.yml, agent/ansible/collection/roles/pbench_repo_install/defaults/main.yml
Fixes #3406 
- Fix an "unknown argument" error that the `command` module raises: it does not like the `warn` argument any longer, so delete the argument.
- Add the version-specific pbench repo to the list of repos that are added to the installation target(s).
=> Ansible fixes b0.72

dashboard/package.json
With 21.1.0-1 the keycloak-masthead dependency has been fixed, so restore the circumflex to allow "21.*" behavior.
=> Restore flexibility in keycloak-js dependency

lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/datasets_list.py, lib/pbench/test/unit/server/test_datasets_list.py
PBENCH-1133
The `GET /datasets` response is optimized for sequential pagination, providing a convenient "next_url" string that can be used directly. However if a client wants to support "random access" pagination, this requires that the client parses the URL string in order to modify the `offset` parameter.
This attempts to make that a bit easier by supplementing the current response payload with a `parameters` field containing the query parameters JSON object, making it easy to update the `offset` parameter.
(Making the unit tests work against the normalized parameter list proved a bit challenging and I ended up saving the original "raw" client parameters in the API `context` so they can be used directly.)
=> Return "raw" API parameters in pagination

.github/codeql/javascript-config.yml, .github/codeql/python-config.yml, .github/workflows/codeql-analysis.yml
- exclude certain Python files
- scan only certain Javascript directories
This (hopefully) addresses the warnings which just started appearing in #3410.
=> Update CodeQL scanning

lib/pbench/server/auth/__init__.py, lib/pbench/test/unit/server/auth/test_auth.py
Jwt exception (specifically `jwt.exception.InvalidAudienceError`) has changed its string message from `Invalid Audience` to `Audience doesn't match`. In the unit test instead of checking the string message check the type of the exception so we don't run into these problems again.
=> Unit test on jwt exception type instead of string

lib/pbench/cli/server/shell.py, lib/pbench/server/api/resources/endpoint_configure.py, lib/pbench/server/auth/__init__.py, lib/pbench/test/unit/server/auth/test_auth.py, lib/pbench/test/unit/server/test_shell_cli.py, server/pbenchinacan/load_keycloak.sh
We missed this change earlier, our `wait_for_oidc_server` function wasn't working at all. We use `[openid]` as a section name in our config file but the `wait_for_oidc_server` function was still using `[openid-connect]` which results in openid not configured error and we were silently ignoring it.
=> Fix the section name in wait_for_oidc_server function

lib/pbench/test/unit/server/auth/test_auth.py
* Check jwt exception type instead of string in the unit tests
Jwt exception (specifically jwt.exception.InvalidAudienceError) has changed its string message from `Invalid Audience` to `Audience doesn't match`. In the unit test instead of checking the string message check the type of the exception.
=> Unit test on jwt exception type instead of string (b0.72 backport of #3417)

agent/ansible/collection/roles/pbench_clean_yum_cache/tasks/main.yml, agent/ansible/collection/roles/pbench_repo_install/defaults/main.yml
Forward port of #3407 from b0.72.
* The `ansible.builtin.command' module does not take a warn argument
The argument gives errors now, so delete it.
* There are now two repos for pbench-agent
The `pbench` repo contains RPMs for `pbench-sysstat` and `screen` (the latter for *some* distros, mainly RHEL8 - RHEL9 picks up screen from EPEL).
The `pbench-<version>` repo contains the RPM for the latest release of `pbench-agent` (and possibly a server RPM although we don't install RPMs for the server: containers have taken over).
=> Ansible fixes

exec-tests, jenkins/run-server-func-tests, lib/pbench/test/functional/server/test_put.py
PBENCH-1148
Allow disabling the `test_delete_all` test by setting the `KEEP_DATASETS` environment variable ... along with some squirrelly mechanism to get this set in the proper context. (Oddly, adding it to the `tox.ini` "safe" list wasn't enough to allow setting it outside; but we're already passing the server address as a command line parameter, so I added a second.)
Ultimately, this translates to a simple `jenkins/runlocal --keep` command.
=> Allow keeping functional test datasets

lib/pbench/server/api/resources/upload_api.py, lib/pbench/test/unit/server/test_upload.py
* Gracefully handle duplicate name with unique MD5
PBENCH-1112
In testing we're seeing duplicate tarball names with distinct MD5 values. We have reduced the importance of duplicate tarball names, relying on the dataset resource ID (MD5) for "uniqueness" internally. However the cache manager still maintains tarball files and MD5 companions on disk, and the upload API has to temporarily store the API payload somewhere. When the duplicate tarballs are uploaded concurrently, the `.open()` fails, leading to an internal server error. We want to minimize the chance of reporting internal server errors where possible.
Instead, move temporarily upload files into an MD5-based subdirectory, and clean up that directory after upload completes.
=> Gracefully handle duplicate name with unique MD5 (#3355)

docs/Agent/config/config.md
pbench-agent configuration for server
=> PBENCH-1153

agent/containers/images/Makefile, agent/containers/images/README.md, agent/rpm/Makefile, agent/rpm/pbench-agent.spec.j2, contrib/containerized-pbench/pbench_demo, jenkins/Makefile, jenkins/Pipeline.gy
Now that Fedora-36 has reached end-of-life, this PR removes support from `main` for building, testing, and publishing F36 artifacts and updates testing to F38.
- Removes F36 from the list of Agent containers which we build by default (the target is still be available if specified explicitly); updates the `README.md` to match.
- Removes F36 from the list of RPMs to be built by default (again, it can still be built by specifying it explicitly).
- Removes F36 from the list of RPM-build containers built by default (again, it can still be built by specifying it explicitly).
- Simplifies a conditional in the Pbench Agent RPM spec file, now that no Fedora versions below 36 are supported.
- Modifies the containerized Agent demo to pull the F38 image instead of the F36 one.
- Switches the CI …
=> Remove Fedora-36 support from the Agent

lib/pbench/client/__init__.py, lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/intake_base.py, lib/pbench/server/api/resources/relay.py, lib/pbench/server/api/resources/upload.py, lib/pbench/test/unit/server/test_endpoint_configure.py, lib/pbench/test/unit/server/test_relay.py, lib/pbench/test/unit/server/test_upload.py
PBENCH-1143
This API integrates with the file-relay server by assuming that the client (e.g., the `pbench-results-move` command) creates *two* separate files on the relay. The main artifact is the tarball, identified only by the tarball's computed SHA256 hash, as `http://relay.example.com/<name>/<sha256>`. However the Pbench Server needs the MD5 for the formal `resource_id` and a *name* for the dataset before we can begin "intake". We also want a mechanism to override the default "private" access level, and to set metadata, so by convention we add a second JSON file to which I'm referring as the "Relay configuration file". This provides the dataset "metadata" we require, including the tarball URI:
```json
{
"name": "tarball.tar.xz",
"md5": "myMD5",
"access": "private",
"metadata": …
```
=> Implement POST /api/v1/relay

lib/pbench/server/api/resources/datasets_inventory.py, lib/pbench/test/unit/server/test_datasets_inventory.py
PBENCH-1169
Help clients with the output of `GET /datasets/<id>/inventory/` by "tuning" the `Content-Disposition` header automatically generated by Werkzeug's `send_file` API.
I started thinking I would construct the header and looking into how to add headers to the `Response` object constructed by `send_file`. It actually does a good job of guessing the filename, but I decided to help it by providing the name we want, and I'm designating the raw tarfile as an `attachment` that we can't reasonably expect a client (especially the UI) to do anything with "inline" (the default).
=> Touch up Content-Disposition header

contrib/containerized-pbench/pbench_demo
Fixes #3445
pbench_demo uses an image downloaded from Quay.io. It assumes that the image will contain `pbench-generate-token` which is available currently but it is deprecated and will not be available in the future.  In particular, the specified image
`quay.io/pbench/pbench-agent-all-fedora-36:main` does *not* contain the script. We need to make use of
`quay.io/pbench/pbench-agent-all-fedora-36:b0.72` instead.
PBENCH-1129
=> Fix the image tag

docs/Server/API/README.md, docs/Server/API/V1/README.md, docs/Server/API/V1/contents.md, docs/Server/API/V1/inventory.md, docs/Server/API/V1/relay.md, docs/Server/API/V1/upload.md
PBENCH-819
This is primarily a minor "cleanup pass" to make some specific example paths more generic and retire a long-standing story.
Along the way I also found a few places I'd missed during the REST API changes so I fixed them as well. Finally, I added a `relay.md` API file for the new Relay API.
Any other bugs, omissions, or other comments in API documentation could also be considered "in scope" here.
=> Some API documentation fixes

agent/util-scripts/gold/test-client-tool-meister/test-53.txt, agent/util-scripts/gold/test-client-tool-meister/test-56.txt, agent/util-scripts/gold/test-client-tool-meister/test-57.txt, agent/util-scripts/gold/test-client-tool-meister/test-61.txt, agent/util-scripts/gold/test-start-stop-tool-meister/test-51.txt, agent/util-scripts/gold/test-start-stop-tool-meister/test-52.txt, agent/util-scripts/pbench-postprocess-tools, lib/pbench/agent/tool_meister.py, lib/pbench/test/unit/agent/test_tool_meister.py
The tool meister was treating tools options as a concatenated string that was passed as a single argument to `pbench-start/stop-tools`. They are now split into separate arguments, allowing the scripts to work correctly.
`pbench-postprocess-tools` was being called without any tool options. Instead of burrowing even deeper into the filesystem to grab the options, we get rid of most of that by rewriting it to use `pbench-list-tools -g <group> -o` and parsing the output of that script. The parsing is ugly but is arguably less ugly than the file system ad-hockery that we used to go through.
This has undergone some "field" testing but could certainly use more. All the tests are now passing in Jenkins (although see the last commit for some problems).
PBENCH-1172
=> Fixes for user-tool

dashboard/src/modules/components/FooterComponent/index.jsx, dashboard/src/modules/components/FooterComponent/index.less, dashboard/src/modules/containers/MainLayout/index.jsx
PBENCH-1092
Specify version number of the dashboard in the footer
Include the version number in the footer
=> Specify version number of the dashboard in footer

agent/test-constraints-3.6.txt, jenkins/Makefile, tox.ini
Now that Fedora-36 has reached end-of-life, we need to update the default container image used by the CI and `jenkins/run` to F38.
However, initial attempts at this proved to be problematic.  So, this PR contains two sets of changes:
- a change to the `jenkins/Makefile` to switch the base image for the CI container from F36 to F38; and
- a pair of changes to restrict the legacy Agent testing on Python 3.6 to use older versions of certain packages.
The version restriction has basically no effect under F36, so this PR can be merged without adverse affects.  Once it has been merged, I'll build and push a new version of the CI container, switching it from the F36 base to the F38 base -- this will break all `main`-branch CI builds which haven't yet been rebased on this PR.
PBENCH-1161
=> Update CI container to Fedora-38

agent/tool-scripts/postprocess/gold/fio-0/result/reference-result/result.json, agent/tool-scripts/postprocess/gold/uperf-0/result.json, agent/tool-scripts/postprocess/gold/uperf-1/result.json, build.sh
With the change in #3433 from a F36 base to F38, some of the floating point calculations in the Agent legacy post-processing tests are off by "half a bit" relative to their gold files. This PR modifies the gold files to match.
Also, apparently F38 brings an updated `tox` which processes the Alembic check script invocation differently, so this PR contains a tweak to address that, as well.
PBENCH-1161
=> Adapt to the change from F36 to F38 in the CI base container. 

agent/Makefile, agent/constraints.txt, agent/rpm/pbench-agent.spec.j2
Add it to the agent Makefile and to the pip invocation in the agent spec file.
Tested by installing the resulting RPM and running an end-to-end smoke test (register tools, run pbench-user-benchmark, push results) on RHEL7.9, RHEL8.7, RHEL8.8, RHEL9.2, CentOS Stream 8, CentOS Stream 9, Fedora 37 and Fedora 38.
=> Add a constraints.txt file to limit python-daemon to versions < 3.0.0

dashboard/src/assets/constants/copyTextConstants.js, dashboard/src/modules/components/ProfileComponent/ClipboardCopy.jsx, dashboard/src/modules/components/ProfileComponent/KeyListTable.jsx, dashboard/src/modules/components/ProfileComponent/index.less
PBENCH-1166
Dashboard API key copy button
The copy icon on the API Key table doesn't appear to have any effect.
=> Dashboard API key copy button

docs/Agent/user-guide/man_page.md
Add man_page.md file for the pbench-agent commands. 
Note: This PR doesn't cover all the pbench-agent commands. For the 1st iteration, decided to cover the commonly used pbench-agent commands. If needed we can add more in subsequent iterations
=> Man pages for pbench-agent commands

dashboard/src/modules/components/ProfileComponent/index.jsx, dashboard/src/modules/components/ProfileComponent/index.less
User Profile Page UI
Removed Account Creation Date section from the user profile page
=> User Profile Page UI

server/pbenchinacan/container-build.sh
PBENCH-1188
Running now on an up-to-date Fedora 38 laptop, I'm finally able to use `jenkins/runlocal` without overriding the `BASE_IMAGE`... except that I had to manually install the `openssl` package on my laptop, and it apparently also needs to be manually installed inside the container base image.
=> Add OpenSSL to container build

lib/pbench/server/auth/__init__.py, lib/pbench/server/auth/auth.py, lib/pbench/test/unit/server/auth/test_auth.py
PBENCH-1182
JWT added yet another `DecodeError` in our API Key validation path in some recent update. Instead of continuing to add specific errors to be converted into a specific internal exception, just handle all exceptions in the primary OIDC decode by attempting the token as an API key. If that fails, report the API key validation error, and re-raise the original OIDC error.
(Note that `verify_auth` will in turn just report this error and act as if no authentication token was given.)
=> Fix JWT OIDC decode yet again

server/pbenchinacan/load_keycloak.sh
PBENCH-1185
Starting relatively recently, Keycloak has a distinct callback URI setting for "post logout", which I noticed while debugging my Postman configuration on the staging server. Adding the proper "post logout callback URI" solved the problem and allowed a clean logout. Then it only took me an hour of searching to figure out how to specify this in the REST call; to say that it's "not excessively well documented" is understating the point ...
=> Fix dashboard logout

agent/requirements.txt, agent/util-scripts/gold/pbench-results-move/test-23.txt, agent/util-scripts/gold/pbench-results-push/test-24.txt, docs/Agent/user-guide/man_page.md, lib/pbench/agent/results.py, lib/pbench/cli/agent/commands/results/move.py, lib/pbench/cli/agent/commands/results/push.py, lib/pbench/cli/agent/commands/results/results_options.py, lib/pbench/test/unit/agent/task/test_copy_result_tb.py, lib/pbench/test/unit/agent/task/test_results_move.py, lib/pbench/test/unit/agent/task/test_results_push.py, server/requirements.txt
PBENCH-1142
This changes the Pbench Agent `results` mechanism to support a new mode, refactoring the `CopyResults` class into a hierarchy with `CopyResultToServer` and `CopyResultToRelay` and an overloaded `push` to do the work. The `--token` option is now required only when `--relay` is not specified.
In addition to `--relay <relay>` to push a manifest and tarball to a Relay, I added a `--server <server>` to override the default config file value, which should allow us to deploy a containerized Pbench Agent without needing to map in a customized config file just to set the Pbench Server URI.
The agent "man pages" have been updated with the new options, and some general cleanup left over from #3442.
_NOTE_: with this change we have a full end-to-end relay mechanism, but it's simplistic. …
=> Add basic relay support to Pbench Agent

agent/requirements.txt, exec-tests, lib/pbench/cli/agent/commands/results/move.py, lib/pbench/cli/agent/commands/results/push.py, lib/pbench/test/functional/agent/cli/commands/triggers/test_register_tool_trigger.py, server/requirements.txt
PBENCH-1190
The Pbench Agent depends on a version of the `requests` package of at least 2.27 for the `requests.exceptions.JSONDecodeError` exception. We'd like to require 2.31 as that resolves a CVE, however Pbench Agent supports Python 3.6 which won't work with 2.31. Adding to this mix, the `pquisby` package requires exactly 2.25.
For now, in order to move forward with Quisby, we remove the version constraints from `requests` for Pbench and remove the reference to the `JSONDecodeError` exception.
(Note that a secondary level of mess here is that the Pbench CI installs *all* our `requirements*.txt` files in the same environment, even though Pbench Agent and Pbench Server don't really operate in the same environment and should be completely separate. This currently prevents us from having …
=> Work around requests version conflict

lib/pbench/server/api/resources/datasets_inventory.py, lib/pbench/server/api/resources/intake_base.py, lib/pbench/server/cache_manager.py, lib/pbench/test/unit/server/test_cache_manager.py, lib/pbench/test/unit/server/test_datasets_inventory.py
Using Tarball.extract in Inventory API for extracting files from tarballs.
Fixing Tests for the same
=> PBENCH-1014 Using Tarball.extract in Inventory API for extracting files from tarball

agent/util-scripts/gold/test-client-tool-meister/test-53.txt, agent/util-scripts/gold/test-client-tool-meister/test-56.txt, agent/util-scripts/gold/test-client-tool-meister/test-57.txt, agent/util-scripts/gold/test-client-tool-meister/test-61.txt, agent/util-scripts/gold/test-start-stop-tool-meister/test-51.txt, agent/util-scripts/gold/test-start-stop-tool-meister/test-52.txt, agent/util-scripts/pbench-postprocess-tools, lib/pbench/agent/tool_meister.py, lib/pbench/test/unit/agent/test_tool_meister.py
The tool meister was treating tools options as a concatenated string that was passed as a single argument to `pbench-`[`install`|`start`|`stop`]`-tools`. They are now split into separate arguments, allowing the scripts to work correctly.
`pbench-postprocess-tools` was being called with empty tool options. Instead of burrowing even deeper into the filesystem to grab the options, we get rid of most of that by rewriting it to use `pbench-list-tools -g <group> -o` and parsing the output of that script. The parsing is ugly but is arguably less ugly than the file system ad-hockery that we used to go through.
`test_install` was using a `NullObject` for a logger, but the `install` method now logs its command. So we set up a basic logger to satisfy that need.
Two other tests (`test_start` and …
=> Fixes for user-tool (forward port to main of #3440)

dashboard/src/actions/tableOfContentActions.js, dashboard/src/modules/components/TableOfContent/index.jsx, dashboard/src/reducers/tableOfContentReducer.js, lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/endpoint_configure.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/datasets_contents.py, lib/pbench/test/unit/server/query_apis/test_datasets_contents.py
PBENCH-624
We're not quite ready to rebuild the `/datasets/{dataset}/contents` API on the cache manager. (I actually tried; it's not all there, and currently would need to be built via a full tarball unpack each time we build a `CacheManager` instance, while the changes to persist it via SQL or Redis, which I'd like to do soon, seemed too big a lift right now.)
However, we have planned for some time to supplement the TOC information with a uri element for each file and subdirectory; this much smaller change makes the code match the API documentation.
=> Add URI to TOC API

jenkins/runlocal, server/pbenchinacan/container-build.sh
This PR changes `jenkins/runlocal` to make it independent of the host distro and version.  There is also a change to free the `containerbuild.sh` script of dependence on a particular tag for the `ubi9` base image.
Note to reviewers:  currently `jenkins/runlocal` rebuilds everything from scratch, by first building the `distclean` and `clean` targets for the Pbench Server RPM and the Dashboard deployment, respectively, which makes the run take substantially longer and is pointless if there haven't been any changes to the sources.  I propose removing those two targets, which will speed up the cycle time.  The Make magic _should_ cause those things to be rebuilt if there are changes to them, and the developer also has the option of building those targets manually if s/he wants a fresh build. …
=> Make `jenkins/runlocal` platform independent

agent/util-scripts/gold/test-start-stop-tool-meister/test-51.txt, agent/util-scripts/gold/test-start-stop-tool-meister/test-52.txt, agent/util-scripts/unittests, exec-tests, server/pbenchinacan/deploy
This PR addresses an instability in Agent legacy tests `test-51` and `test-52`.
In `graceful_shutdown()` in [`tool_meister_stop.py`](https://github.com/distributed-system-analysis/pbench/blob/3b8bf2f018434c8b242a2639ab4d7a4f8548ed9e/lib/pbench/agent/tool_meister_stop.py#L96), the code issues a debug log message if it has to wait for the Tool Data Sync to exit.  However, if, by the time control reaches this point, the TDS has already exited, then the PID file will have been removed, and the attempt to read it produces an exception which is discarded and the wait is skipped.
This results in a race condition which may or may not produce the log message output.  There is no correctness issue associated with the presence or absence of the message in the log, but the legacy unit test system …
=> Fix transient "Area 51" failures

dashboard/server/index.js, server/pbenchinacan/load_keycloak.sh
PBENCH-1203
The shift to HTTPS and Keycloak has broken our dashboard local dev mode hack in two ways:
1. The `axios.get` call in the express mirror server needs to either load certificates or disable validation. This adds the CI private CA key.
2. Login requires that the Keycloak be configured with the address of the dashboard code, which in this mode is `http://localhost:3000`. This adds that redirect to the Keycloak configuration
=> Re-enable the dev dashboard

agent/ansible/ansible-lint.yml, agent/ansible/collection/galaxy.yml, agent/ansible/collection/roles/pbench_agent_install/tasks/main.yml, agent/ansible/collection/roles/pbench_repo_install/defaults/main.yml, agent/ansible/collection/roles/pbench_repo_install/tasks/main.yml, agent/ansible/collection/roles/pbench_repo_install/templates/etc/yum.repos.d/pbench.repo.j2
- repo.name -> repo.tag
- assert that `pbench_repo_name' is defined (users have to define it in their inventory)
- use `latest' when installing packages and stop ansible-lint from complaining about it
These fixes are incorporated  into the `pbench.agent` collection, v1.0.11, available from Galaxy.
PBENCH-1129
=> Fixes to ansible roles (b0.72)

jenkins/run-server-func-tests, lib/pbench/server/api/__init__.py, lib/pbench/server/auth/auth.py, lib/pbench/test/functional/server/conftest.py, lib/pbench/test/functional/server/test_audit.py, lib/pbench/test/unit/server/auth/test_auth.py, server/lib/config/pbench-server-default.cfg, server/pbenchinacan/etc/pbench-server/pbench-server.cfg, server/pbenchinacan/run-pbench-in-a-can
PBENCH-1197
With the change to SSO, we've lost our own private realm and the ability to manage roles within it. We may be able to restore roles through Keycloak and LDAP groups, but this provides a temporary "quick and dirty" mechanism to define ADMIN roles for a server based on the username provided and cached from OIDC tokens.
We define a simple `admin-role` config variable which can be defined to a comma-separated list of usernames to be granted ADMIN role. This value is processed by the authorization code when it caches local `User` objects for validation.
I've added a functional test for the `audit` API, which requires ADMIN role, both to prove that it works and to provide a long-delayed minimal validation of auditing. (I decided not to merge this into the overloaded "datasets" test …
=> Add ADMIN roles through config file

agent/ansible/ansible-lint.yml, agent/ansible/collection/galaxy.yml, agent/ansible/collection/roles/pbench_agent_install/tasks/main.yml, agent/ansible/collection/roles/pbench_repo_install/defaults/main.yml, agent/ansible/collection/roles/pbench_repo_install/tasks/main.yml, agent/ansible/collection/roles/pbench_repo_install/templates/etc/yum.repos.d/pbench.repo.j2
- repo.name -> repo.tag
- assert that `pbench_repo_name' is defined (users have to define it in their inventory)
- use `latest' when installing packages and stop ansible-lint from complaining about it
These fixes are incorporated into the `pbench.agent` collection, v1.0.11, available from Galaxy.
PBENCH-1129
=> Fixes to ansible roles (fwd port of #3478)

.pre-commit-config.yaml, server/rpm/pbench-server.spec.j2
python3.9 is needed as a build requirement. That may be required in b0.72 and main as well, but we'll cross that bridge when/if we need to.
pre-commit was failing with weird errors. After clearing the cache, I was asked to login to gitlab: the config was different from main and was trying to get flake8 from gitlab. I copied the config from main (which is using github for both flake8 and black) into the b0.69 branch and that seems to work.
=> Fix server RPM builds on Fedora (b0.69)

lib/pbench/server/auth/__init__.py, lib/pbench/test/unit/server/conftest.py, server/lib/config/nginx.conf
This PR provides two small changes identified during Pbench Server "Ops review" sessions.
The first change raises the max request payload size to 100Gb.  The existing limit of 10Gb is too small for certain users' requests.
The other changes is a follow-on to #3427.  This PR replaces a couple of `urljoin()` calls with simple string concatenation, since that function doesn't behave as expected when the configured OIDC server URL contains a partial path.
=> Correct OIDC URL generation and raise max payload size

lib/pbench/server/api/resources/relay.py, lib/pbench/test/unit/server/test_relay.py
PBENCH-1205
The requests package reports connection failures by exception, and the relay module wasn't catching those, causing them to be handled "upstream" and result in internal server errors.
Instead, catch the exceptions locally and report that the URI didn't respond.
=> Gracefully handle connection errors in RELAY API

lib/pbench/server/api/resources/intake_base.py, lib/pbench/server/api/resources/query_apis/datasets/datasets_contents.py, lib/pbench/test/functional/server/test_datasets.py, lib/pbench/test/unit/server/query_apis/test_datasets_contents.py, lib/pbench/test/unit/server/test_relay.py, lib/pbench/test/unit/server/test_upload.py
PBENCH-1204
This stems from a request from the UI to help optimize a partial refresh after using the relay upload dialog, by providing identification of the new dataset. Although a client using the traditional `PUT /upload` already knows the name and MD5, the returned information may be helpful.
This also reports the tarball download URI (which is the best encapsulation of the results "identity") in the response `location` header to make it easy to retrieve.
=> Provide dataset summary info on upload

lib/pbench/server/auth/__init__.py, lib/pbench/test/unit/server/auth/test_auth.py, server/lib/config/pbench-server-default.cfg, server/pbenchinacan/etc/pbench-server/pbench-server.cfg
In the course of recovering from our latest challenges with the Staging server, we noticed warnings triggered by the Pbench Server accesses to the OIDC server indicating that TLS verification was disabled...which, in fact, it was...which is undesirable.  It turns out that there are two places in the Pbench Server code where it connects to the OIDC server -- once during startup to make sure that the service is available and once somewhat later to fetch the public key for token decryption -- and the first was performing TLS verification but the second wasn't.
This PR provides a common mechanism for both sets of accesses to use to determine whether and how to use TLS verification.  Both relevant places in the code now pull the path to the CA from the Pbench Server configuration; if the path …
=> Fix OIDC access to verify TLS connection

jenkins/Makefile, jenkins/Pipeline.gy, server/pbenchinacan/container-build.sh
It turns out that the default when committing a container build to a saved image is to retain the working container.  This is never reused and just ends up taking up disk space.
This PR adds the `--rm` switch to the `commit` command to our `buildah`-based container builds to ensure that the working container is removed when the container image is created.
It also adds a `buildah rm --all` command to the CI pipeline cleanup step to ensure that we don't have an unsightly buildup of containers on the Jenkins executors.
=> Remove working containers when commiting a container image

lib/pbench/server/auth/auth.py, lib/pbench/test/unit/server/auth/test_auth.py, lib/pbench/test/unit/server/test_datasets_list.py
PBENCH-1198
With the move from a private Keycloak ID provider to Red Hat SSO, we find that several user UUID values (from the old and new ID provider) are attempting to claim the same username. The current user "cache" doesn't allow for this, nor in general does it seem we really want to be casually mapping multiple "users" across ID providers into the same "Pbench identity" just because they share a username.
Instead, diagnose this problem with an authorization failure and an explicit error message instead of letting the Auth module hide the error and silently treat the client connection as unauthenticated.
Note that we can manually fix this by renaming the old user entry in SQL, which will allow the server to recognize the new SSO login. We can then reassign any existing datasets from …
=> Gracefully report duplicate usernames

server/lib/config/nginx.conf
This change raises the Nginx maximum request payload size from 10G to 100G to better accommodate certain individuals' results dataset sizes.
PBENCH-1199
=> Raise the Nginx max body size to 100G (`b0.72`)

server/pbenchinacan/etc/pbench-server/pbench-server.cfg
PBENCH-1206
Webb noticed a crontab "roles" definition in the canned cfg file, which never belonged there.
=> Sweep one missed piece of crontab fluff

lib/pbench/cli/agent/commands/results/move.py, lib/pbench/cli/agent/commands/results/push.py
Replace `requests.exceptions.JSONDecodeError` by generic `Exception`.
See #3469 for some details. The upstream issue is
https://github.com/psf/requests/issues/5794
and the PR is
https://github.com/psf/requests/pull/5856
but we are running older versions of `requests' in various places.
=> Partial backport of #3469 (agent side only) to b0.72

lib/pbench/server/api/resources/datasets_compare.py, lib/pbench/server/api/resources/datasets_visualize.py, lib/pbench/test/functional/server/test_datasets.py, lib/pbench/test/unit/server/test_datasets_compare.py, lib/pbench/test/unit/server/test_datasets_visualize.py
PBENCH-1210
Right now we only support visualizing and comparing `uperf` benchmark data with Quisby. However as we expand that support within the server, the UI code will need to be able to identify the schema of the output data, which depends on the benchmark.
As a simple solution, add a `"benchmark"` field to the response data which the client can read.
=> Identify benchmark type

jenkins/run-server-func-tests, lib/pbench/client/__init__.py, lib/pbench/server/api/resources/datasets_compare.py, lib/pbench/server/api/resources/datasets_visualize.py, lib/pbench/server/api/resources/endpoint_configure.py, lib/pbench/server/api/resources/intake_base.py, lib/pbench/server/api/resources/query_apis/datasets/__init__.py, lib/pbench/server/database/models/datasets.py, lib/pbench/test/functional/server/test_connect.py, lib/pbench/test/functional/server/test_datasets.py, lib/pbench/test/unit/server/test_datasets_visualize.py, lib/pbench/test/unit/server/test_endpoint_configure.py, lib/pbench/test/unit/server/test_upload.py
PBENCH-1186
PBENCH-1187
A bit of a catch-all. First, this simplifies and standardizes the dashboard's need to identify a benchmark. Eventually we'll be "smart enough" to go beyond the Pbench benchmark wrapper (as we intend to move away from relying on them) and `dataset.metalog.pbench.script` will become unreliable. This adds a new `server.benchmark`, which right now is the same but can be extended beyond that in the future.
The dashboard would also like to be able to identify which benchmark types the current server can support, in advance, and we'd like to avoid hardcoding that knowledge in the dashboard. For this purpose, I've added a "visualization" key in the endpoints response to indicate the benchmark types supported by the current server's `datasets_visualize` and …
=> Improve client benchmark identification

lib/pbench/server/api/resources/intake_base.py, lib/pbench/test/unit/server/test_upload.py
PBENCH-1219
Large uploads can time out, causing the client (e.g., the 0.69 passthrough server's dispatch) to retry. Eventually, this will result in an `OK` (200) response, which is good. However if we retry before the original operation finishes (it may be still running, despite the client timeout), we catch the already existing "temporary intake directory" as a `CONFLICT` error.
Unfortunately, the cleanup logic doesn't recognize this distinction, and still deleted the intake directory on exit. Timed correctly, this could break the original upload: at best, it results in a noisy termination with complaints that the previously-existing temporary directory no longer exists.
Fix this problem by attempting to delete only when this API instance has successfully created the temporary directory. …
=> Fix corruption during CONFLICT upload

lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/__init__.py, lib/pbench/test/functional/server/test_datasets.py
PBENCH-1215
Webb pointed out a broken functional test in #3496. Once it was testing what I had wanted it to test, I realized that it wasn't quite working. This contains some server and functional test changes to make archive-only dataset queries work correctly and to be sure that's adequately tested in the functional test cases.
=> Fix some problems with archive-only behavior 

agent/config/pbench-agent-default.cfg, agent/config/pbench-agent.cfg, agent/containers/images/container_build.sh, contrib/containerized-pbench/pbench, lib/pbench/agent/results.py
PBENCH-1209
The staging server and local development servers now use HTTPS with certs signed by a private pbench CA. An HTTPS connection can't be validated without a reference to this CA.
The primary change here is in the `contrib/containerized-pbench/pbench` script which now looks for a private CA definition, maps the CA bundle file into the container, and defines `REQUESTS_CA_BUNDLE` within the container.
In an attempt to handle RPM installs, there's also logic to support a new `[results]` section `pbench_ca` configuration variable to define a CA path that will be used to verify the `PUT` to a server.
Note, this isn't being used for the `--relay` path, as that's currently not using `https` and we'll need to figure out how we want to configure this in the future.
=> Allow for private CA on the Agent side

server/lib/config/nginx.conf
The recent "Ops Review" revealed a mysterious behavior around the "inner" Nginx proxy:  whenever we had a request timeout, we immediately had a second failure which returned a `413` response to the client.  We initially thought that this was a configuration problem in the "outer" proxy, but that proved to be unfounded.  Then I stumbled onto [this explanation](https://github.com/SpiderLabs/ModSecurity/issues/2170#issuecomment-536553266):  because the `client_max_body_size` is increased only for the Pbench Server API routes, when the request times out and is redirected to the internal `50X.html` page, the maximum request size changes back to the default, and the _redirected_ request fails with a `413` instead of the appropriate `504`.
This PR adds `client_max_body_size` to the two internal …
=> Increase Nginx limits for internal responses

server/lib/config/nginx.conf
This is a backport of #3504 which addresses a problem where a timed-out upload request returns a `413` instead of a `504`.
=> Increase Nginx limits for internal responses on b0.72

lib/pbench/server/cache_manager.py
In the Cache Manager `make_cache_object()` function there is a possible use-before-assignment hazard.  This PR addresses that by ensuring that, in the unlikely event that the assignment fails, we won't execute the use.
(This was a part of #3501, but I decided to pull it out into its own PR.)
=> Fix possible use-before-assign bug

contrib/containerized-pbench/pbench_demo
This PR is a follow-on to #3494, which removed the use of `PB_AGENT_SERVER_LOC` from the containerized Agent `pbench` wrapper script (it turns out that the demo was depending on it...).  Now that we have the `--server` option on `pbench-results-move`, we use that in the demo script (instead of dynamically creating an Agent config file) to specify the server location.
While making the above addition, I also dusted off the demo file:
- I reworked the header comment to clarify the purpose of the file (i.e., it's more _documentation_ than **_tool_**) and to explicitly list the required input environment variables.
- I removed the explicit override of the container image -- that's a feature of the `pbench` script, and if the user wants it s/he can define it in the environment when running the …
=> Update the `pbench_demo` script to add `--server`

lib/pbench/server/api/resources/datasets_compare.py, lib/pbench/server/api/resources/datasets_visualize.py, lib/pbench/test/unit/server/test_datasets_visualize.py
PBENCH-1229
The intake code ensures that all dataset (even `server.archiveonly` datasets) will have a `server.benchmark` value representing the core benchmark used in the run. The visualization code uses this value to determine compatibility.
However on the staging server, we have pre-existing datasets without the `server.benchmark` metadata, and the "internal server error" failure mode is unpleasant.
To be a bit more friendly, this adds a wrapper that will first check the `server.benchmark` metadata directly, but failing that will check for the normal Pbench Agent `dataset.metalog.pbench.script` metadata so that older `pbench-uperf` runs will be recognized. Failing that, the wrapper falls back to "unknown" so that we'll never have to deal with a `None` value.
=> Support benchmark type fallback

lib/pbench/cli/server/shell.py, lib/pbench/profiling.conf.py
This PR adds support for performing execution profiling of Pbench Server API requests.
The profiling is performed by the Python Standard Library `cProfile` package.  Profiling is controlled via Gunicorn pre- and post-request hook functions, which are installed via a Gunicorn configuration file (which is actually Python code...pretty cool).
**_How to use it_**:  if the `PB_PROFILE_DUMP_FILE` environment variable is defined when `shell.py` executes, it adds the configuration file to the Gunicorn command line, and everything else is handled automagically.
Profiling data is collected only during a single API request, starting when that request is invoked and ending when the request is complete.  If the environment variable is defined to a file path, then the profile data is dumped to that …
=> Add support for Python profiling of Server requests

lib/pbench/server/__init__.py, lib/pbench/server/cache_manager.py, lib/pbench/test/unit/server/test_cache_manager.py
The recent "Ops Review" session revealed that upload requests time out if the file approaches 7Gb in size.  Profiling the execution indicates that the bulk of the time is spent extracting the `metadata.log` file from the results tarball.  This is due to a "feature" of tar archives:  the same file may appear more than once, and so an extraction has to search the entire archive to ensure that the member being extracted is the most up-to-date (i.e., last) one, and this is punishing as the archive size grows.  (Also, the Python Standard library `tarfile` package is not as performant as the standalone `tar(1)` utility, and this costs additional time.)
This PR changes the Server to spawn a subprocess to run the `tar(1)` utility, which allows us to specify the `--occurrence` option which allows …
=> Attempt to improve upload performance

client/requirements.txt, pytest.ini, server/test-requirements.txt, test-requirements.txt, tox.ini
After some difficulties I had with a hanging test in #3501, I've decided to add a timeout mechanism to the PyTest tests.  This is trivially done simply by adding a requirement for the `pytest-timeout` plugin and setting a timeout value in the `pytest.ini` file.  Once this change is merged, the PyTest tests will henceforth be aborted if they run longer than 300 seconds (5 minutes).  Note that affects only tests run under PyTest, which includes the unit tests and the functional tests but not the Agent "legacy" tests (which, I think, already provide timeouts).  Hopefully 5 minutes is long enough for individual tests; if not, we can easily increase the limit.
In the course of making this change, I noted that we have a bunch of redundancy and similar silliness in our Python requirements files …
=> Add `pytest-timeout` and refactor `requirements.txt` files

lib/pbench/server/api/resources/intake_base.py, lib/pbench/test/functional/server/test_datasets.py, lib/pbench/test/unit/server/test_relay.py, lib/pbench/test/unit/server/test_upload.py
PBENCH-1231
After accidentally observing an uploaded dataset that was marked "archiveonly" not indexed (because the file name didn't match the result directory name), we decided that the intake process should make the reasons more obvious.
I've handled this by adding "notes", which are recorded both in the successful JSON response payload and in the finalized audit record. While I was at it, I exposed our decisions regarding the canonical benchmarked workload name and the computed expiration date.
While doing this, I stripped the rather prolific logging of `INTAKE` to just two, a "pre" log identifying the file and user, and a "post" log providing the summary file system status (adding the size of the tarball).
I debated logging the "notes", but didn't. On one hand, it would make the info …
=> "Note" non-fatal INTAKE behaviors

server/pbenchinacan/etc/pbench-server/pbench-server.cfg, server/pbenchinacan/load_keycloak.sh, server/pbenchinacan/run-pbench-in-a-can
By default, the canned Pbench Server deployment configures all accesses -- Server, PostgreSQL, Elasticsearch, browser, and especially Keycloak -- with the assumption that all accesses to and fro will be on `localhost`.  This works fine for functional test, but for development (at least for me...), the client/browser is not necessarily running on the host where the servers are running.  This means that the Dashboard code is served from the Pbench Server using an IPv4 address instead of `localhost`...which means that, for the Keycloak login dance, the redirect back from the Keycloak Server to the Dashboard has to match a valid redirect pattern which references the Dashboard using the IPv4 address of the Pbench Server and not just `localhost`.
This PR addresses this by enhancing the …
=> Enhance configuration of Keycloak valid redirects list in the canned deployment

dashboard/src/actions/relayActions.js, lib/pbench/server/api/resources/intake_base.py, lib/pbench/server/api/resources/relay.py, lib/pbench/test/unit/server/test_relay.py
PBENCH-1238
As a stopgap for "final" Relay support under the agent, we plan to establish a known project Relay Server (e.g., on our AWS host) for testing. That server has limited storage, and substantial use. To avoid requiring constant manual management of space, our plan is to implement a mechanism to cause the Pbench Server to delete files from the Relay Server after intake, and to change the Pbench Dashboard relay action to always supply that option. Note that this PR adds the `?delete=t` to the dashboard *unconditionally*; in the future we can consider adding a checkbox to allow users to control the behavior, especially when they own a private relay server.
=> Allow deletion of uploaded relay datasets

agent/containers/images/container_entrypoint, lib/pbench/server/auth/__init__.py, lib/pbench/test/unit/server/conftest.py, server/pbenchinacan/container-build.sh, server/pbenchinacan/deploy-dependencies, server/pbenchinacan/load_keycloak.sh, server/requirements.txt
This PR consists of a bunch of tiny fixes of minimal consequence which I've gradually accumulated over the last month.  They were things which I ran into in the course of making other changes, but, since they had nothing to do with the changes I was making, I kept them on a side branch.  At this point, there are enough of them to warrant putting up a review.
- Remove unused definitions from the Server container build and from `load_keycloak.sh`
- Correct a docstring
- Correct the import of the `urllib3` package and add a requirement for it:  the package is apparently included inside the `requests` package, and we were referencing it there instead of declaring our own dependency on it.
- Add defaults to the `deploy-dependencies` script:  this script is normally invoked by a higher-level …
=> Nits and stuff

lib/pbench/server/api/resources/datasets_inventory.py, lib/pbench/test/functional/server/test_datasets.py, lib/pbench/test/unit/server/test_datasets_inventory.py
PBENCH-1240
Now that the dashboard supports download of tarball inventory, I observed that the generated filename included a dataset-name prefix. This is because the content disposition header allows only a name, not a path, and the browser is trying to be "helpful" by converting the `<dataset-name>/<filename>` string, replacing the disallowed `/` with `_`. The result is ugly and unexpected.
NOTE: although the Mozilla guidelines try to suggest that the filename must be enclosed in quotes, this conflicts with the RFC, and Werkzeug's `send_file` is "reluctant" to include quotes (plus it's ugly to construct). Therefore, this doesn't attempt to insert the (presumably unnecessary) quotes. (And note also that, despite the ugly name, the current TOC download works without a quoted filename in …
=> Remove directory from disposition header

lib/pbench/server/api/resources/intake_base.py, lib/pbench/server/cache_manager.py, lib/pbench/test/unit/server/test_cache_manager.py, lib/pbench/test/unit/server/test_upload.py
PBENCH-1239
In Pbench ops review, after staging the latest `main` and with the intent of testing the new `Tarball.extract` on a large dataset, we pushed a >7Gb `uperf` tarball. This failed with an internal error, leaving a partial tarball copy in the `ARCHIVE` controller directory, revealing several related problems:
1. The cache manager was using `shlib.copy2`, which copies the tarball from the staging area into the archive tree. Because `nginx` also caches the entire data stream, this *triples* the storage requirements to upload a tarball.
2. On copy failure, the cache manager did not delete the partial file.
3. While the initial data stream save code handled an `ENOSPC` specially, after mapping trouble in Werkzeug it was reported as a "server internal error", which is not ideal.
4. The …
=> Handle ENOSPC more cleanly

server/requirements.txt
`pquisby` version 0.0.13 introduced a packaging problem which breaks the Pbench Server.  This was not resolved in version 0.0.14, so, until it's resolved, we're rev-locking to <0.0.13.
Problem symptom:
```
File "/var/tmp/jenkins/tox/py39/lib/python3.9/site-packages/pbench/server/api/resources/datasets_compare.py", line 6, in <module>
from pquisby.lib.post_processing import BenchmarkName, InputType, QuisbyProcessing
File "/var/tmp/jenkins/tox/py39/lib/python3.9/site-packages/pquisby/lib/post_processing.py", line 4, in <module>
from src.pquisby.lib.benchmarks.fio.fio import extract_fio_run_data
ModuleNotFoundError: No module named 'src'
```
=> Rev-lock the `pquisby` version until its packaging is resolved

server/lib/config/nginx.conf
Currently, attempts to load the Pbench Dashboard (e.g., from the Staging server) via requests like
```
GET /Dashboard/
```
or
```
GET /dashboard
```
will each fail (with a `404` and a blank page, respectively).
To improve the user experience, this PR adds a `location` directive which rewrites the URI, down-casing the "dashboard" and adding the trailing slash if it is missing.  This returns a `301`/`Moved Permanently` response to the browser which causes it to retry at the correct location (which then gets routed properly).
This change also changes the existing Dashboard `location` to require the trailing slash and makes the match preferred over the regex matches, to avoid recursive rewrites.
(BTW, this change has already been deployed on the current Staging Pbench Server instance, if you …
=> Add Nginx magic for Dashboard access

server/bin/service-key.py
PBENCH-1245
Add a simple script to create a fake `User` object and an associated API key, mimicking the server API key generator. (Which can't be used directly as it relies on Flask `app` context.)
The service account `User` record can be created with a generated UUID value that's "likely unique" but could in theory overlap with an SSO OIDC UUID, or you can specify an arbitrary string as a "user ID".
For example, these both work:
service-key.py --label passthrough pbench
service-key.py --label passthrough --identity NOTYOURAVERAGEUUID passthrough
=> Hack to create "service accounts"

lib/pbench/server/api/resources/endpoint_configure.py, lib/pbench/test/functional/server/test_connect.py, lib/pbench/test/unit/server/test_endpoint_configure.py, server/requirements.txt
PBENCH-1212
(This Jira issue was originally a placeholder in case changes had to be made to the `comparison` or `visualize` APIs for `fio` support. It seemed likely that wouldn't be necessary, and I'm appropriating the Jira to unlock the `pquisby` package version and adjust tests.)
First, unlock the `pquisby` package version to allow consuming the 0.0.17 version with `fio` support added.
Both unit and functional tests validate the set of benchmarked workloads for which Pbench claims support, and needed to be updated for the addition of `fio`. The `endpoints` API was also reporting the workloads in order from Pquisby's ENUM, and to make the tests a bit more supportable I sorted the list we report.
=> Adapt to Quisby fio support

agent/requirements.txt
Temporary fix to unblock v0.72 users.
See also PR #3526.
JIRA-1250
=> Version lock redis to <5.0.0

agent/containers/images/Dockerfile.base.j2, agent/containers/images/Dockerfile.layered.j2, agent/containers/images/Makefile, agent/containers/images/pcp.repo.j2
Previously, we pulled the PCP RPM from their upstream repository; unfortunately, that repo no longer exists.  Instead, we will now pull the RPM from the distro which corresponds to the base image that we're building on.  This means that we won't be providing the latest-and-greatest PCP, and it means that the different versions of the containerized Agent may provide different versions of PCP (e.g., the RHEL-7-based image will provide PCP v4 while the CentOS Stream 9 image will provide PCP v6).  Hopefully, this won't result in any surprise or disappointment.  (If it does, people can use an Agent container built from a different base image, or they are free to build their own container image using ours as base images and install whatever version of PCP they want in their own layer.)  This PR …
=> Update containerized Agent build for PCP and CA

server/bin/move-index.py
PBENCH-1252
Fix the `IndexMap` model constructor call to use `kwargs` since SQLAlchemy's declarative base model doesn't support positional parameters.
_NOTE_: this tool has been run on the staging server, and worked. We'll use it again when we upgrade the current b0.72 "archive server" instance to a true 1.0 server.
=> Fix index-map migration tool

lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/api/resources/query_apis/dataset.py, lib/pbench/server/database/models/datasets.py, lib/pbench/test/functional/server/test_datasets.py, lib/pbench/test/unit/server/query_apis/test_datasets_delete.py, lib/pbench/test/unit/server/query_apis/test_datasets_update.py
PBENCH-1247
The bulk Elasticsearch API operations (update and delete) have never had clean handling of un-indexed datasets. The functional tests, for example, expected "publish" of the archive-only datasets to fail. This was partly because I did too much "common stuff" inside the bulk action generator. Additionally, a dataset where indexing fails becomes somewhat "stranded" as we expect it to be indexed, but it isn't.
This PR refactors the checks in order to move some common operations out of the action generators with additional checks for eligibility and cleanup. We don't prevent publish, for example, due to lack of an index map if the dataset is archive-only, or if indexing failed, and we'll still do the necessary finalization.
=> Fix publish/delete of unindexed datasets

agent/requirements.txt
The release of v0.73 of the agent is imminent and for now, this fix is required. A more permanent fix will be made in future releases.
See also PR #3525.
JIRA-1250
=> Version lock redis to <5.0.0 -b0.73 branch

server/requirements.txt
PBENCH-1260
The pquisby PyPi package has been unstable. Right now the Pbench Server on main supports uperf visualization, which is adequately supported by pquisby 0.0.17. Unless we hit critical bugs in the support, we won't need a higher version until fio support is finalized. Minimize our support overhead in the meantime by locking the package to the version we know works for us.
=> Lock pquisby version

lib/pbench/server/database/models/__init__.py, lib/pbench/server/database/models/api_keys.py, lib/pbench/server/database/models/audit.py, lib/pbench/server/database/models/datasets.py, lib/pbench/server/database/models/index_map.py, lib/pbench/server/database/models/server_settings.py, lib/pbench/server/database/models/templates.py, lib/pbench/server/database/models/users.py, lib/pbench/test/unit/server/database/test_audit_db.py, lib/pbench/test/unit/server/database/test_datasets_metadata_db.py, lib/pbench/test/unit/server/database/test_index_map_db.py, lib/pbench/test/unit/server/database/test_server_settings.py, lib/pbench/test/unit/server/database/test_template_db.py, lib/pbench/test/unit/server/database/test_users_db.py, lib/pbench/test/unit/server/test_upload.py
PBENCH-1251
This is mostly a fix for the ops review problem discovered today, that our carefully unit-tested logic to decode SQLAlchemy `IntegrityError` instances to identify the specific violated constraint (specifically, duplicate vs null) doesn't work in a production environment.
The root problem is that the text strings reported differ between the unit test environment (`sqlite3` engine) and the production environment (`postgresql` engine). Take this opportunity to consolidate into a centralized decoder, which requires making the "SQL related" exception constructors consistent across all of our SQLAlchemy model classes.
And while I did briefly consider consolidating a single set of "SQL related" exceptions, I like having the per-class exception hierarchy to lean on even though there …
=> Fix the SQL constraint violation logic

agent/containers/images/repo.yml.j2
The build used to produce Agent container images for releases uses RPMs pulled from DNF repositories on COPR.  The build generates a `.repo` file which allows DNF to access the appropriate Agent RPM.  The `.repo` file is constructed by the build from a template.  The parameters for the template are provided by a `.yml` file which the build also generates.
In #3479, the `.repo` template was modified, and one of the parameters names was changed from `name` to `tag`.  However, that PR was aimed at Ansible functionality, and the requirements for the Agent release container build were overlooked.
The `.repo` file is generated with two entries, and, without the related change, both entries end up with the same label.  This results in the second entry superseding the first entry, such that the …
=> Correct COPR repo file generation in Agent container builds (`b0.73`)

lib/pbench/server/cache_manager.py, lib/pbench/test/functional/server/test_datasets.py
PBENCH-1268
The content-disposition filename for the tarball was generated using the base dataset name without the canonical ".tar.xz" suffix. Fix it, and validate the expected response header in the functional test.
=> Fix content-disposition filename for tarball

agent/util-scripts/gold/pbench-results-move/test-23.txt, agent/util-scripts/gold/pbench-results-move/test-35.txt, agent/util-scripts/gold/pbench-results-push/test-24.txt, exec-tests, lib/pbench/cli/agent/commands/results/move.py, lib/pbench/cli/agent/commands/results/push.py, lib/pbench/cli/agent/commands/results/results_options.py, lib/pbench/test/unit/agent/task/test_results_move.py, lib/pbench/test/unit/agent/task/test_results_push.py
PBENCH-1272
When an automated tool chain uses `pbench-results-move --relay` (or, less commonly, `pbench-results-push --relay`), the command offers a "helpful" message on `stdout` identifying each dataset name and the associated relay URI. This would require automated tooling to parse each line of output.
This adds `--brief` which will print only the raw URIs, one per line, allowing tooling to easily process the data.
=> Support "brief" URL output on move/push

server/pbenchinacan/container-build.sh
PBENCH-1277
This week the CI (and `runlocal`) builds have started failing because the `ubi9` base image system can't install `rsyslog-mmjsonparse` anymore. It's unclear exactly what changed, and specifying `ubi9.0.0` or `ubi9.1` isn't reverting to the previous behavior, which I think means "something else" I haven't discovered has changed environmentally.
For now, this PR just changes the default `BASE_IMAGE` to centos stream9, which works fine, and will get the CI moving again.
We can revist this investigation later.
=> Workaround for UBI9 container setup trouble

dashboard/src/App.js, dashboard/src/modules/components/HeaderComponent/index.jsx, dashboard/src/modules/components/LoadingComponent/index.less, dashboard/src/modules/components/SidebarComponent/sideMenuOptions.js, dashboard/src/modules/components/TableComponent/index.jsx, dashboard/src/utils/routeConstants.js
PBENCH-1263
Spinner and Page Navigation issues
- On clicking `Header logo`, it will re-direct to `home` page
-  `All Runs` on side menu will show `Coming soon` text
-  Spinner is center aligned
-  Breadcrumb on Results page removed
- Ordered Route constants
=> Spinner and Page Navigation issues

dashboard/src/actions/comparisonActions.js, dashboard/src/assets/constants/compareConstants.js, dashboard/src/assets/constants/toastConstants.js, dashboard/src/modules/components/ComparisonComponent/ChartGallery.jsx, dashboard/src/modules/components/ComparisonComponent/ChartModal.jsx, dashboard/src/modules/components/ComparisonComponent/PanelContent.jsx, dashboard/src/reducers/comparisonReducer.js, server/requirements.txt
PBENCH-1214
Generate charts for Fio benchmark
=> Generate charts for Fio benchmark

jenkins/Pipeline.gy, lib/pbench/cli/server/tree_manage.py, lib/pbench/server/api/resources/datasets_inventory.py, lib/pbench/server/cache_manager.py, lib/pbench/server/indexing_tarballs.py, lib/pbench/test/unit/server/test_cache_manager.py, lib/pbench/test/unit/server/test_datasets_inventory.py, lib/pbench/test/unit/server/test_datasets_visualize.py, lib/pbench/test/unit/server/test_indexing_tarballs.py, server/lib/systemd/pbench-reclaim.service, server/lib/systemd/pbench-reclaim.timer, server/pbenchinacan/container-build.sh
PBENCH-1249
On large datasets, our direct tarball extraction method can time out the API call. Unlike on a long intake, there is no persistent artifact so a retry will always time out as well. This applies to any `get_inventory` call, and therefore to the `/inventory`, `/visualize`, and `/compare` APIs; and given the central importance of those APIs for our Server 1.0 story, that's not an acceptable failure mode.
This PR mitigates that problem with a "compromise" partial cache manager, leveraging the existing `unpack` method but adding a file lock to manage shared access. The idea is that any consumer of tarball contents (including the indexer) will unpack the entire tarball, but leave a "last reference" timestamp. A periodic timer service will check the cache unpack timestamps, and …
=> Quick cache manager

lib/pbench/server/__init__.py, lib/pbench/server/api/resources/intake_base.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/test_indexing_tarballs.py, lib/pbench/test/unit/server/test_relay.py, lib/pbench/test/unit/server/test_upload.py, server/lib/config/pbench-server-default.cfg, server/pbenchinacan/run-pbench-in-a-can
Lost in the v0.69 -> v1.0 transition was the mechanism for making backup copies of result tarballs loaded on to the Server.  This gap is currently covered by the fact that the "pass-through" server is v0.69-based and so it makes a backup of the result before pushing it to the "index" server.  As things stand, once we upgrade the "index" server to a full-blown v1.0 and have users push results to it directly, we won't have any provision for creating backups.  This PR closes that gap.
This change adds a `pbench-backup-dir` configuration option which points to a directory to receive copies of result tarballs.  (This directory should be placed on a file system different from the archive directory (preferably on different hardware), although this can easily be effected via a mount point.)  This …
=> Implement backup for the Server

lib/pbench/server/__init__.py, lib/pbench/server/api/resources/intake_base.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/test_datasets_metadata.py, lib/pbench/test/unit/server/test_relay.py, lib/pbench/test/unit/server/test_upload.py
This is a follow-on to #3553:  that places all the backup files in a single directory using the original dataset names.  Unfortunately, we have no guarantee that dataset names are unique, and so this could lead to conflicts and overwritten files.  This PR modifies the previous to place each backup in a subdirectory named using the dataset resource ID.  Since each resource ID is unique to its dataset, this ensures that there are no conflicts.  This also has the side-effect that we no longer need to store the `*.md5` files, since the hash value is now embedded in the file path.
This PR consists of two commits.  The second is described above; the first is a few small changes to appease the linter.
PBENCH-1259
=> Use subdirectories to hold backup files

lib/pbench/client/__init__.py, lib/pbench/server/api/resources/datasets_list.py, lib/pbench/test/functional/server/test_datasets.py, lib/pbench/test/unit/server/test_datasets_list.py
PBENCH-1278
`dataset.owner` is a "synthetic" metadata key, which actually represents the `username` column of the `User` row linked by the dataset's `owner_id` foreign key. The metadata system generates this when constructing the `Dataset` JSON object as it's useful data, and that's been sufficient to allow selection of `?metadata=dataset.owner`.
However, `dataset.owner` is not a native `Dataset` column and therefore the key doesn't appear in the `?keysummary` output (and isn't selectable for display in the UI), and can't be used either in `?filter` or `?sort`, which is unfortunate.
This PR adds a join and some minor special casing logic to ensure that the key is reported by `?keysummary`, and to allow `?filter=dataset.owner:drb` (or likely less useful constructs like …
=> Implement filter by `dataset.owner` metadata

server/pbenchinacan/container-build.sh
This PR reverts the change made in #3554 which is no longer needed, now that our Subscription Manager subscription has been renewed.  (The subscription is required in order for us to access the `rhel-9-for-x86_64-appstream-rpms` DNF repo which contains a number of packages (such as `rsyslog-mmjsonparse`) that we need for building on a UBI base image.)
=> Return to using a UBI-9 base image for the Server Container

contrib/server/operations/pbench-upload-results.py
PBENCH-1279
A utility to bulk-migrate Pbench results tarballs to a Pbench Server using the `PUT` API. This supports checkpointing to more efficiently retry after a failure, and filtering by file system modification date.
=> Tarball migration utility

README.md, docs/Agent/agent.md, docs/Dashboard/user_guide.md, docs/Server/API/access_model.md, docs/Server/API/api.md, docs/Server/server.md
PBENCH-1282
This is just merging a random assortment of minor doc changes I've been accumulating for several months, before we package "Server 1.0".
=> Miscellaneous doc cleanup

lib/pbench/server/api/resources/datasets_list.py, lib/pbench/test/unit/server/test_datasets_list.py
PBENCH-1287
We noticed a 400 error on use of `?mine` from an unauthenticaated client, which is misleading. There was nothing wrong with the request itself, but `?mine` requires an authenticated client. Change it to 401 (UNAUTHORIZED).
=> Fix error for unauthenticated `/datasets?mine`

contrib/server/operations/pbench-upload-results.py, docs/Server/API/V1/metadata.md, docs/Server/API/V1/upload.md, lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/datasets_list.py, lib/pbench/server/api/resources/intake_base.py, lib/pbench/server/api/resources/relay.py, lib/pbench/server/api/resources/upload.py, lib/pbench/test/functional/server/test_datasets.py, lib/pbench/test/unit/server/test_datasets_list.py, lib/pbench/test/unit/server/test_upload.py
PBENCH-1283
Normally metadata keys are set through `PUT /datasets/<id>/metadata` using an `application/json` request body, allowing the full expressiveness of JSON, specifically to specify sub-objects, integers, floating point numbers, and boolean literals.
I added the `?metadata` query parameter on `PUT /upload/<name>` to allow a client to specify metadata during the upload instead of waiting; however the nature of the HTTP interface constrains these to text strings, which can be limiting.
This PR generalizes the typed "metadata expression" syntax developed to support generalized metadata `?filter` expressions on `GET /datasets` to allow both quoting value strings and typing them. For example, one could now set a JSON value using
``` …
```
=> Allow typed metadata on upload

lib/pbench/server/api/resources/datasets_inventory.py, lib/pbench/server/cache_manager.py, lib/pbench/test/unit/server/test_cache_manager.py, lib/pbench/test/unit/server/test_datasets_inventory.py, server/requirements.txt
PBENCH-1291
Pbench Agent postprocessing creates `result.html` files, which display a table of result data for each iteration. Each row contains a relative link to the iteration directory, with the intention of linking to the web server directory listing. Because the `result.html` was loaded using the `inventory` API as `/datasets/<id>/inventory/result.html`, the relative path access also routes to the `inventory` API, which doesn't support directories and therefore fails.
It's hard to fix this to work like the old server without some way to interact with the dashboard UI code (ideally it would open the appropriate directory in the TOC view). Nevertheless, this PR implements a change that improves the behavior a bit (it's no longer an error), by handling this request as an HTML `301` …
=> Redirect DIR `/inventory/path` to `/contents/path`

lib/pbench/server/auth/__init__.py, lib/pbench/server/auth/auth.py, lib/pbench/server/database/models/users.py, lib/pbench/test/unit/server/auth/test_auth.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/test_upload.py, server/lib/config/pbench-server-default.cfg, server/pbenchinacan/etc/pbench-server/pbench-server.cfg, server/pbenchinacan/load_keycloak.sh, server/pbenchinacan/run-pbench-in-a-can
PBENCH-1296
We've discovered that the configuration of our `auth.redhat.com` Keycloak client does not give us the `client` name as an id in the decoded JWT token's `aud` claim, which was causing the server to reject apparently valid tokens.
This appears to violate the OIDC specification, but for flexibility (and expediency) this PR separates the configuration of "OIDC client name" and "expected `aud` claim" so that we can accommodate either behavior without further code changes. (That is, the openid `client` and `audience` values could be identical if we know the OIDC server follows the specification.)
=> Separate `audience` from `client`

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/intake_base.py, lib/pbench/test/unit/agent/task/test_results_push.py, lib/pbench/test/unit/server/test_upload.py
Previously, out-of-storage errors on the Server resulted in a `500`/`INTERNAL_ERROR` driven by a `413`/`REQUEST_ENTITY_TOO_LARGE` HTTP status.  This PR changes that to use a `507`/`INSUFFICIENT_STORAGE` status, which we report directly to the user instead of triggering an `INTERNAL_ERROR`.  This is for the initial upload as well as for the backup.
This gives the end-user a clearer picture of the nature of the failure.
PBENCH-1299
=> Report Server out of space errors via `507` instead of `413`/`500`

lib/pbench/server/api/resources/datasets_list.py, lib/pbench/test/functional/server/test_datasets.py, lib/pbench/test/unit/server/test_datasets_list.py
PBENCH-1297
`GET /datasets` supports sorting of the output, but SQL dislikes `order by` on a JSON field value. The solution is to cast the field `.as_string()`, but this PR goes a step further to allow sorting based on converting a field value to `int`, `float`, `bool`, or `date` as well as the default `str`: for example, `GET /datasets?sort=dataset.metalog.run.start_time:desc:date` will produce a list of datasets sorted in descending order by the recorded collection start timestamp in the Pbench Agent `metadata.log` file. (This works even if some datasets lack a `dataset.metalog.run.start_time` file: SQL will return `null` values at the beginning of the list.)
=> Implement typed sorting on dataset metadata

contrib/server/operations/pbench-upload-results.py, lib/pbench/cli/server/tree_manage.py, lib/pbench/server/cache_manager.py, lib/pbench/server/database/models/datasets.py, lib/pbench/test/unit/server/test_cache_manager.py, server/lib/systemd/pbench-reclaim.service, server/requirements.txt
PBENCH-1301
This could be refined, but I want to get it up for review. I'd love to get it on the staging server for testing with more limited disk space, although I can ask for 95% or 880Gib on my laptop and see it free cache. (I'm out all next week, but I may spend a bit of time trying to clean this up: e.g., trying to add some unit tests.)
First, this adds code to track the unpacked size of tarballs to help with managing cache goals. This is based on a `du -s -B1` of the unpacked directory tree, and stored as metadata.
When asked to unpack, it will check whether there's sufficient space on the cache device, and if not it will reclaim cache with a goal sufficient to accommodate the target dataset.
The `pbench-tree-manage` command can now target either % free or bytes free, and the …
=> Make cache management more dynamic

lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/auth/auth.py, lib/pbench/test/unit/server/test_schema.py
PBENCH-1303
This adds an `except` clause to explicitly ignore an expired OIDC token: it was being reported with a stack trace, which is disruptive and unnecessary as it's a normal and expected periodic event. (Tokens are supposed to expire, and can be refreshed by the client.)
Also, to make it easier to attach the server's client API error `WARNING` messages to the associated NGINX messages, report the HTTP status.
We'll now see client API errors reported like this:
```
Upload client error 400: 'File extension not supported, must be .tar.xz'
```
I nearly made a similar change to the server internal error before deciding it would be redundant (and broke `caplog` fixture tests which weren't worth changing), but in tracking down the initial attempt I found some lint warnings about …
=> Some logging cleanup

lib/pbench/common/__init__.py, lib/pbench/server/api/resources/__init__.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/indexer.py, lib/pbench/server/report.py, lib/pbench/test/unit/common/test_wait_for_uri.py, server/lib/config/pbench-server-default.cfg
Now that we are deploying on an OpenSearch service which requires a username/password, remove assumptions around the contents of the ES URL configuration in the Server code.
- Remove the check for a port from `wait_for_uri()`; add defaulting for the port number if it is omitted.
- Rework `_get_es_hosts()` to return the whole URL instead of the decomposed dict; move the specification of the timeout value to its caller.
- Add a `ca_bundle` configuration option to the `Indexing` configuration section and pointed the default value for it to `/etc/pki/tls/certs/ca-bundle.crt`.
- Provide the `ca_bundle` value to the instantiations of the `Elasticsearch` client and to the `Requests` methods which target Elasticsearch/OpenSearch services.
- Remove the unused `logger` parameter from `get_es()` and …
=> Correct URL handling for Elasticsearch/OpenSearch

lib/pbench/test/unit/server/test_cache_manager.py
We've got occasional parallel dependency failures; fix a couple more. Perhaps these are the last ones.
=> Fix some unit tests

server/pbenchinacan/container-build.sh, server/rpm/pbench-server.spec.j2
During a side trip trying to get the Pbench 1.0 Server deployed on RHEL 8.9, we tried to build the Server container image on a UBI 8 base instead of the usual UBI 9 one and ran into troubles.  This PR makes the build work.
It turns out that -8 uses a different version of EPEL from what -9 uses, so this changes the `container-build.sh` script to add the necessary logic to support that.
Also, we tumbled to the fact that the Server no longer depends on `util-linux-core` (which we couldn't locate easily in the -8 EPEL), so this change removes that dependency from the RPM spec file.
For the record, this change received only the lightest testing:  it passes the CI but mostly because the changes are unused in normal operation.  If someone actually tries to use a UBI 8-based Server, they will run …
=> Add support for UBI 8 base image to Pbench Server container image build

lib/pbench/server/api/resources/query_apis/datasets/__init__.py, lib/pbench/test/unit/server/query_apis/test_namespace_and_rows.py
PBENCH-1308
An Opensearch-based query like `/api/v1/datasets/{dataset}/values/iterations` requires that the `{dataset}` have at least one `result-data-sample` indexed document. However it doesn't actually check that this is true. This leads to an Opensearch query with a bad URL fragment causing an Opensearch error we report as an internal server error.
This change detects early that the dataset has no indices for the required index root name, and fails with a meaningful message.
=> Handle missing Opensearch indices

dashboard/src/actions/datasetListActions.js
PBENCH-1306
Sort datasets by uploaded time
=> Sort datasets by uploaded time

dashboard/src/modules/components/OverviewComponent/NewRunsComponent.jsx, dashboard/src/modules/components/OverviewComponent/common-component.jsx
PBENCH-1307
End time column update
Server deletion date is obtained as string in the format `YYYY-MM-DD` from the response, removed the formatting.
Edit feature is available for Server deletion column so it would be better to maintain the column.
=> End time column update

contrib/server/operations/pbench-upload-results.py, lib/pbench/server/cache_manager.py, lib/pbench/server/indexing_tarballs.py, lib/pbench/server/sync.py, lib/pbench/test/unit/server/test_cache_manager.py, lib/pbench/test/unit/server/test_indexing_tarballs.py
This addresses several issues encountered while monitoring the migration of tarballs from the passthrough server backup directories to the new production server.
First, I've seen `PUT /upload` problems more frequently than anticipated, and when transferring thousands of tarballs the error details get easily hidden: I've improved the way they're captured and reported at the end. Also, having observed many of the NGINX `html` format response messages, I decided to try scraping the text for the `<title>` tag text, which seems to contain the real error message, using BeautifulSoup.
Second, I ran into a set of tarballs from 2020 which seem to have `metadata.log` files which don't contain `run.controller` values. These, it turns out, fall into a hole in intake processing. Without a …
=> Operations cleanup

dashboard/src/App.js, dashboard/src/actions/comparisonActions.js, dashboard/src/modules/components/ComparisonComponent/PanelContent.jsx, dashboard/src/modules/components/ComparisonComponent/common-components.jsx, dashboard/src/modules/components/ComparisonComponent/index.jsx, dashboard/src/modules/components/TableComponent/index.jsx
PBENCH-1300
Visualization Page Pagination
=> Visualization Page Pagination

dashboard/src/actions/overviewActions.js
PBENCH-1313
Display metadata modal is empty
Added `mine` filter
=> Metadata Modal is empty

lib/pbench/server/cache_manager.py, lib/pbench/test/unit/server/test_cache_manager.py
Make sure we can't end up with undefined `metadata`.
=> Another tweak to intake metadata problems

lib/pbench/cli/server/tree_manage.py, lib/pbench/server/cache_manager.py, lib/pbench/server/indexer.py
Minimize cache logging: details were useful when cache management first went in, but are now disruptive during ops review.
=> Minor logging cleanup

server/lib/config/nginx.conf, server/pbenchinacan/run-pbench-in-a-can
PBENCH-1316
Our deployed containerized server maps `/var/lib` (the default NGINX cache location) to `/home`, which has only 26Gb free. Instead, map NGINX cache to our large Pbench volume at `/srv/pbench/nginx` in order to be able to transfer larger datasets.
=> Move nginx cache into /srv/pbench

lib/pbench/server/cache_manager.py
PBENCH-1318
The reclaimer defaulted to 20%, which is inappropriate for an unpack reclaim where we want to free just enough for the unpacked dataset size.
Also, to help diagnose, add the last referenced cache date to the reclaim log message.
=> Fix unpack cache reclaimer

lib/pbench/server/api/resources/datasets_compare.py, lib/pbench/server/api/resources/datasets_inventory.py, lib/pbench/server/api/resources/datasets_visualize.py, lib/pbench/server/cache_manager.py, lib/pbench/test/unit/server/test_cache_manager.py, lib/pbench/test/unit/server/test_datasets_compare.py, lib/pbench/test/unit/server/test_datasets_inventory.py, lib/pbench/test/unit/server/test_datasets_visualize.py
PBENCH-1317
We found a case where a cache lock could "leak" when an error occurs reading a file in the visualize and compare APIs. The file read has now been repackaged with a `finally` to be sure the stream is closed and unlocked on error.
=> Protect the cache lock better

lib/pbench/cli/server/report.py, lib/pbench/server/cache_manager.py, server/Makefile, setup.cfg
This will report on the state of the ARCHIVE, BACKUP, and CACHE on-disk trees in addition to the state of the SQL database. (I'm going to leave analyzing and reporting on the Opensearch database for another time, since this is "off books" weekend upstream work!)
This packages the ad hoc SQL queries I've been doing to monitor the server as a CLI utility, plus some more.
Here's the output of `pbench-report-generator --all` on the production server:
```
Archive report:
117,446 tarballs consuming 21.7 TB
The smallest tarball is 1.0 kB, pbench-user-benchmark__2020.04.03T11.05.44
The biggest tarball is 41.1 GB, uperf_Azure_RHEL-8.10.0-20240116.45_x86_64_gen2_pci_netvsc_quick_D240125T014727_2024.01.25T01.47.28
Backup report:
117,447 tarballs consuming 21.7 TB
Cache report:
97,464 datasets …
```
=> Add simple report generator

lib/pbench/cli/server/report.py, lib/pbench/cli/server/tree_manage.py, lib/pbench/server/api/resources/datasets_contents.py, lib/pbench/server/cache_manager.py, lib/pbench/test/unit/server/test_cache_manager.py, lib/pbench/test/unit/server/test_datasets_compare.py, lib/pbench/test/unit/server/test_datasets_contents.py
PBENCH-1321
The `/datasets/{id}/contents` API includes into several unexpectedly expensive steps:
1. Finding the tarball (by MD5 value) within the `ARCHIVE` tree using a `glob`
2. Fully discovering all tarballs within the controller directory
3. Unpacking the tarball into a cache directory using `tar`
4. Building a "map" of the contents of the unpacked tarball subtree
This PR includes mitigations for all but the `tar` unpack step:
1. Use the `server.tarball-path` metadata instead of searching the disk
2. Only discover the target tarball rather than the entire controller
3. Skip the "map" and evaluate the actual target path within the cache
Finding a tarball within our 30Tb `ARCHIVE` tree can take many minutes, while identifying the controller directory from the tarball path takes a …
=> Make `contents` API scale

dashboard/package.json, dashboard/src/modules/components/OverviewComponent/NewRunsComponent.jsx, dashboard/src/modules/components/OverviewComponent/SavedRunsComponent.jsx, dashboard/src/modules/components/OverviewComponent/common-component.jsx
PBECNH-1311
Expiration date update
=> Expiration date update

lib/pbench/cli/server/__init__.py, lib/pbench/cli/server/options.py, lib/pbench/cli/server/report.py, lib/pbench/cli/server/tree_manage.py, lib/pbench/server/api/resources/intake_base.py, lib/pbench/server/cache_manager.py, lib/pbench/server/database/models/datasets.py, lib/pbench/server/indexing_tarballs.py
I added a simple `server.unpack-perf` metadata, which is a JSON block like `{"min": <seconds>, "max": <seconds>, "count": <unpack_count>}`, and then played with the report generator to get some statistics.
I also wrote a report of the `Audit` table contents to summarize the operations, statuses, and users involved in the Pbench Server.
The sample below is for a `runlocal`, with a few small-ish tarballs. The big catch in deploying this would be that none of the existing datasets will have `server.unpack-perf` until they're unpacked again, which somewhat reduces the value of the statistics until they get unpacked again (e.g., for TOC or visualize).
Nevertheless, I figured I might as well post it for consideration. Some of the statistics (and how they're calculated and/or represented) are no …
=> Track and report unpack performance

lib/pbench/cli/server/audit.py, server/Makefile, setup.cfg
Another late night ops side project: this queries the `Audit` log with filters and displays the results either in detail or summary, optionally with pagination.
```
/opt/pbench-server/bin/pbench-audit --since 2024-02-29 --until 2024-03-01 --name upload --summary
[...]
[2024-02-29 19:35:07] upload uperf_HyperV_RHEL-9.4.0-20240225.8_x86_64_gen2_hv_netvsc_quick_D240227T172431_2024.02.27T09.24.31 FAILURE (legacy) [2.584 seconds]
[2024-02-29 19:36:09] upload uperf_HyperV_RHEL-9.4.0-20240225.8_x86_64_gen2_hv_netvsc_quick_D240227T172431_2024.02.27T09.24.31 SUCCESS (legacy) [4.093 seconds]
Reported 428 audit events:
BEGIN        214
SUCCESS         24
FAILURE        190
```
Or (full form):
```
/opt/pbench-server/bin/pbench-audit -C /opt/pbench-server/lib/config/pbench-server.cfg --since …
```
=> Audit log formatter

lib/pbench/agent/tool_meister_client.py
the 100s timeout is too short for some systems (reported on slightly outdated aarch64).
Note I tested it with 200s which was still failing. With 300s it succeeded 5/5.
=> Increase the TM SIGNAL_RESPONSE_TIMEOUT

lib/pbench/cli/server/report.py
When I added a keyword to select "upload" or "creation" time statistics, I omitted "statistics" from the effect of `--all`, but I've come to regret that minor inconvenience. This PR makes `--all` include `--statistics=creation` by default.
=> All means "all"

lib/pbench/cli/server/report.py
It's been a bit annoying that `--statistics=creation` reports a total count that's less than the actual number of datasets. This is because when we report by creation date, we rely on a `JOIN` between `Dataset` and `Metadata`, where the creation date comes from the `metadata.log` `pbench.date` field, which is missing from some datasets (a bit over 4,000 on the production server).
This PR changes `--statistics=creation` to count all rows returned by the SQL query, but to separately report the number of empty rows where the metadata was missing: e.g.,
```console
[pbench@n002 /]$ pbench-report-generator --statistics=creation
Dataset statistics by creation date:
154,737 from 2012-04-13 19:21 to 2024-06-13 11:26
(count includes 4,019 datasets without a date)
```
=> Account for "dateless" datasets

lib/pbench/cli/server/report.py, server/requirements.txt
Add a new `--agent` option and generator to report on the Pbench Agent versions present on the server. By default we report on the "main" versions, like "0.50" and "0.73"; by adding `--detail` it'll report the much longer list of full agent versions ("v0.73-2g6da0cfc8d") as well as "nonsense" version metadata like "system".
This also recognizes the `--since` and `--until` options to report on agent versions that appear within a specific time range.
The report is sorted by the last date a given version was seen, which makes it a bit easier to see that only 0.73 has been used since March 08 2024.
```console
Dataset statistics by Pbench Agent version:
Count            Version            First       Last    
---------- ----------------------- ----------- -----------
1          0.37 …
```
=> Add report of Pbench Agent version statistics

dashboard/package.json
After ten months, I finally got tired of [the Dependabot warnings](https://github.com/distributed-system-analysis/pbench/security/dependabot/16), so here's a PR to update the Dashboard's dependency on `axios` to at least the version which addresses [CVE-2023-45857](https://nvd.nist.gov/vuln/detail/CVE-2023-45857).  (See also the [GitHub advisory](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx).)
I assume (boldly) that when we actually build the Dashboard, we pull a safe version of `axios` (since the `package.json` file is specifying only the _minimum_ -- not the "locked" -- version), so I don't think this issue actually affects us (and, even if it did, we run the Dashboard in limited quantities in what I think is a safe environment...), so I didn't bother to actually test this change. …
=> Update Dashboard dependency on Axios
