rpm/README.org
=> Add configtools to the list as the fourth directory of interest.

README.md
Replaces the auto-generated one from the Waffle.io site: https://github.com/distributed-system-analysis/pbench/pull/7
=> Update to reference Waffle.io

agent/config/pbench-agent.conf.example
Remove some unused stuff.
Add example definitions to DEFAULT section for keys that
are used in the other sections.
=> Rename pbench-agent.conf to pbench-agent.conf.example

agent/bench-scripts/pbench_cyclictest
Also, fix redirect of verbose output since we can't use tee anymore,
and use a double "kill -9" to help ensure it really dies.
Change-Id: I6650947798c318f1176c8dfc3911a83deacffd30
=> Add support for rteval

agent/bench-scripts/pbench_cyclictest
Reverts distributed-system-analysis/pbench#26
Temporarily reverting this until we can verify we have properly open-sourced the first drop of code.
=> Revert "Add support for rteval"

bgtasks/deploy, bgtasks/pbench/bin/pbench-base.sh, doc/Makefile, doc/profile
These are a few changes we needed to make based on an actual
deployment of pbench, and attempts to build the documentation.
=> A few bug fixes found while deploying

agent/bench-scripts/pbench_fio
in #106 I made small typo, corrected here. Sorry for that
=> corrected typo in pbench_fio

bgtasks/pbench/bin/pbench-base.sh, bgtasks/pbench/bin/pbench-unpack-tarballs
This is preparation for merging in the index changes.
Create WONT-INDEX.nn subdirs for different index-pbench return codes.
Also delete some test code from pbench-unpack-tarballs.
=> Clean up WONT-INDEX subdirs and testing code in pbench-unpack-tarballs.

agent/tool-scripts/kvmtrace, agent/tool-scripts/sar, agent/tool-scripts/turbostat, agent/util-scripts/gold/register-tool/test-00.txt
This should fix issue https://github.com/distributed-system-analysis/pbench/issues/112
=> Remove the use of yum in tool scripts

agent/tool-scripts/datalog/openvswitch-datalog
=> Jeremyeder fix openvswitch dump ports

agent/tool-scripts/perf
=> fix syntax to freq argument

agent/util-scripts/pbench-postprocess-tools
They have been renamed to pbench-*-tools.
Issue #188
=> Fix calls to start/stop/postprocess-tool in the remote case.

agent/util-scripts/pbench-clear-tools
=> Fix clear-tools calls in remote case: should be pbench-clear-tools.

agent/profile
=> Check for pbench-register-tool-set.

agent/tool-scripts/sar
=> Fix quoting of patterns for pidstat.

web-server/v0.3/css/jschart.css, web-server/v0.3/demo.html, web-server/v0.3/js/jschart.js
There are a bunch of minor improvements in this code as well as an added feature for histograms and a fix for Issue #249
=> Jschart cleanup/optimization/fixes

agent/util-scripts/gold/pbench-agent-config-activate/test-14.txt, agent/util-scripts/pbench-agent-config-activate, agent/util-scripts/samples/pbench-agent-config-activate/test-14/tmp/pbench-agent.cfg, agent/util-scripts/unittests
A typo in pbench-agent-config-activate made it in to the repo, making the script fail.
Add a unit test to catch it.
=> Fix pbench-agent-config-activate and add unit test.

.travis.yml, agent/profile
The new convention is <file>.cfg, so the file is named
pbench-agent.cfg.
=> Change the name of the config file in profile.

agent/bench-scripts/pbench-fio, agent/bench-scripts/pbench-iozone, agent/bench-scripts/pbench-netperf
Issue #289.
pbench-fio: 2.2.11
pbench-iozone: 3.430
pbench-netperf: 2.7.0
=> Bump versions for various benchmarks.

agent/bench-scripts/pbench-fio, agent/bench-scripts/templates/fio.job, agent/bench-scripts/templates/make-fio-jobfile.py
Update to PR #316 to handle systems with ConfigParser and not configparser.
=> fio templating

agent/util-scripts/gold/pbench-list-triggers/test-16.txt, agent/util-scripts/gold/pbench-list-triggers/test-17.txt, agent/util-scripts/gold/pbench-list-triggers/test-18.txt, agent/util-scripts/gold/pbench-register-tool-trigger/test-15.txt, agent/util-scripts/gold/pbench-tool-trigger-test/test-19.txt, agent/util-scripts/pbench-list-triggers, agent/util-scripts/pbench-tool-trigger, agent/util-scripts/pbench-tool-trigger-test, agent/util-scripts/samples/pbench-list-triggers/test-16/tool-triggers, agent/util-scripts/samples/pbench-list-triggers/test-16/tools-default/perf, agent/util-scripts/samples/pbench-list-triggers/test-16/tools-default/proc-interrupts, agent/util-scripts/samples/pbench-list-triggers/test-16/tools-default/proc-vmstat, agent/util-scripts/samples/pbench-list-triggers/test-16/tools-default/turbostat, agent/util-scripts/samples/pbench-list-triggers/test-17/tool-triggers, agent/util-scripts/samples/pbench-list-triggers/test-17/tools-default/perf, agent/util-scripts/samples/pbench-list-triggers/test-17/tools-default/proc-interrupts, agent/util-scripts/samples/pbench-list-triggers/test-17/tools-default/proc-vmstat, agent/util-scripts/samples/pbench-list-triggers/test-17/tools-default/turbostat, agent/util-scripts/samples/pbench-list-triggers/test-18/tool-triggers, agent/util-scripts/samples/pbench-list-triggers/test-18/tools-default/perf, agent/util-scripts/samples/pbench-list-triggers/test-18/tools-default/proc-interrupts, agent/util-scripts/samples/pbench-list-triggers/test-18/tools-default/proc-vmstat, agent/util-scripts/samples/pbench-list-triggers/test-18/tools-default/turbostat, agent/util-scripts/samples/pbench-tool-trigger-test/test-19/opt/config/pbench-agent.cfg, agent/util-scripts/samples/pbench-tool-trigger-test/test-19/tool-triggers, agent/util-scripts/unittests
Issue #296.
This still needs unit tests.
=> Fixes for pbench-tool-trigger and pbench-list-triggers

agent/bench-scripts/gold/pbench-moongen/test-03.txt, agent/bench-scripts/pbench-moongen, agent/bench-scripts/postprocess/moongen-postprocess, agent/bench-scripts/test-bin/mock-MoonGen
Changes to pbench-moongen in support of changes pending merge into moongen.  Addresses (partially) #399.
=> pbench-moongen updates

agent/base, agent/bench-scripts/pbench-mpt
As discussed I am sending the pull request to integrate mpt with pbench. This is a work in progress (WIP) and more changes will follow.
I will share additional considerations/concerns/ideas about the request in the comments.
=> Integrates messaging-performance-tool into pbench (WIP)

web-server/v0.3/js/jschart.js
These two changes specifically address #412
=> Add jschart features to enhance dataset value analysis

agent/util-scripts/pbench-sysinfo-dump
=> Collect the kernel config file

agent/bench-scripts/pbench-fio, agent/bench-scripts/postprocess/fio-postprocess
It is now called only from fio-postprocess.
=> Don't call fiologparser_hist.py twice

agent/bench-scripts/postprocess/BenchPostprocess.pm
This includes other clean-ups for BenchPostprocess,
including checks for empty arrays at several places.
The process of finding a common time range among
multiple data series is also improved.
Note that I have not attempted to update unit tests yet.  I suspect it is going to be a big update for the "gold" files.
=> Fix for issue406

agent/bench-scripts/postprocess/BenchPostprocess.pm
=> BenchPostprocess.pm: fix div by zero and other small clean-ups

agent/tool-scripts/datalog/openshift-metrics-datalog, agent/tool-scripts/openshift-metrics, agent/tool-scripts/postprocess/openshift-metrics-postprocess
openshift metrics tool to collect statistics from the /metrics endpoint which can be used to profile the behavior of the kubernetes apiserver.Postprocessing is done to convert the data in to csv so as to ingest
into elasticsearch.
=> openshift-metrics tool for pbench

server/pbench/bin/pbench-rsync-satellite
=> Specify the sorting columns explicitly

agent/bench-scripts/pbench-uperf
=> pbench-uperf: allow any process-iteration-samples failure to re-try

agent/bench-scripts/postprocess/generate-benchmark-summary
=> generate-benchmark-summary: skip over missing result.json iterations

agent/bench-scripts/postprocess/generate-benchmark-summary
=> Close using the proper file variable

agent/util-scripts/pbench-collect-sysinfo
=> fix for generating compressed tarball

server/pbench/bin/gold/test-10.txt, server/pbench/bin/gold/test-11.txt, server/pbench/bin/gold/test-6.4.txt, server/pbench/bin/gold/test-6.txt, server/pbench/bin/pbench-base.sh, server/pbench/bin/pbench-rsync-satellite, server/pbench/bin/pbench-satellite-cleanup
This is a rebased version of PR #563, with modified comments and with some commits reordered and squashed. @tenstormavi: please make sure that the code is identical between these two and (assuming that that is true) please update your PR with this version. Let me know if there are any problems.
=> Speed up rsync

contrib/ansible/openshift/pbench_register.yml, contrib/ansible/openshift/register.sh
Registers prometheus-metrics, disk and haproxy-ocp tool on openshift cluster.
=> Register prometheus-metrics, haproxy-ocp and disk tool on openshift cluster

contrib/ansible/openshift/README.md, contrib/ansible/openshift/register.sh
=> Register perf tool on all the nodes

web-server/v0.3/js/jschart.js
=> jschart.updates

contrib/ansible/openshift/register.sh
This will avoid duplication of data and avoid indexing the same data
in to elasticsearch.
=> Register prometheus-metrics on just one master

server/pbench/bin/job_pool.sh, server/pbench/bin/pbench-dispatch, server/pbench/bin/pbench-move-unpacked, server/pbench/bin/pbench-unpack-tarballs, server/pbench/bin/unittests
Fix #576 
This is the final PR.
I have changed the unpack tarball script as well as added a new pbench-move-unpacked script to hide the copying latency. Some checks and comments will be added further, though the scripts are working fine for the purpose.
=> Hide latency of copying unpacked tarballs

server/pbench/bin/gold/test-8.txt, server/pbench/bin/pbench-server-activate-create-results-dir-structure
The unit test actually caught the thinko, but *I* didn't,
even after the unit test whacked me over the head with it.
=> Fix thinko and unit test.

agent/util-scripts/pbench-move-results
Workaround for segfault in multithreaded xz.
Issue #679.
=> pbench-move-results: Add --xz-single-threaded option

server/pbench/bin/pbench-dispatch, server/pbench/bin/pbench-move-unpacked, server/pbench/bin/pbench-unpack-tarballs
=> pbench server scripts: rectify the misnamed 'list' variables

server/pbench/bin/pbench-unpack-tarballs
=> pbench-unpack-tarballs: refactor code to reduce duplication

agent/util-scripts/gold/pbench-collect-sysinfo/test-25.txt, agent/util-scripts/gold/pbench-collect-sysinfo/test-26.txt, agent/util-scripts/gold/pbench-collect-sysinfo/test-27.txt, agent/util-scripts/gold/pbench-collect-sysinfo/test-28.txt, agent/util-scripts/gold/pbench-collect-sysinfo/test-29.txt, agent/util-scripts/gold/pbench-collect-sysinfo/test-30.txt, agent/util-scripts/pbench-collect-sysinfo, agent/util-scripts/pbench-sysinfo-dump
This commit also updates the unit tests to reflect the changes.
Fixes #588
=> Log the things pbench-collect-sysinfo is collecting

agent/base, agent/bench-scripts/pbench-dbench, agent/bench-scripts/pbench-migrate, agent/bench-scripts/pbench-netperf, agent/bench-scripts/pbench-uperf, agent/config/pbench-agent.cfg.example, agent/util-scripts/pbench-edit-prefix, agent/util-scripts/pbench-move-results
=> pbench agent scripts: fix using of -p with scp command

agent/util-scripts/gold/pbench-metadata-log/test-02.txt, agent/util-scripts/gold/pbench-metadata-log/test-03.txt, agent/util-scripts/gold/pbench-metadata-log/test-04.txt, agent/util-scripts/gold/pbench-metadata-log/test-22.txt, agent/util-scripts/pbench-metadata-log
=> pbench-metadata-log: use the remote hostnames that the user specified

agent/util-scripts/gold/pbench-collect-sysinfo/test-23.txt, agent/util-scripts/pbench-collect-sysinfo
Fixes #655.
Also, fix unit test.
=> pbench-collect-sysinfo: Fix usage string

server/pbench/bin/pbench-dispatch
=> fix of pbench-dispatch: missing $

server/pbench/bin/pbench-dispatch, server/pbench/bin/pbench-satellite-cleanup, server/pbench/bin/pbench-sync-package-tarballs, server/pbench/bin/pbench-sync-satellite
This PR will fix the following things:
1. Error of bad file descriptor.
2. Include timestamp in logging for wast debugging.
=> Fix bug and better logging

contrib/ansible/openshift/pbench_register.yml
update pbench_registry.yaml to create /var/lib/pbench-agent/tools-default  
on pbench-controller
=> update pbench_registry.yaml to create /var/lib/pbench-agent/tools-default 

agent/tool-scripts/external-data-source
Fixes #379 
This tool will provide a way to get the data from an external data source like collectd etc. The user needs to pass the type and URL while registering the tool.
=> Add new tool called external-data-source

agent/bench-scripts/gold/pbench-fio/test-04.txt, agent/bench-scripts/gold/pbench-fio/test-05.txt, agent/bench-scripts/gold/pbench-fio/test-06.txt, agent/bench-scripts/pbench-fio, agent/bench-scripts/templates/fio.job, agent/bench-scripts/templates/make-fio-jobfile.py
=> pbench-fio: fix numjobs

agent/tool-scripts/pprof, contrib/ansible/openshift/README.md, contrib/ansible/openshift/register.sh
Not ready for merge as it is now, need to find a way to add the nodes to monitor with pprof as this currently uses all nodes.
Will [fix issue 675](https://github.com/distributed-system-analysis/pbench/issues/675).
=> [WIP] OCP RBAC pprof changes

agent/tool-scripts/pprof
=> missed some tmp dirs for pprof tool

agent/util-scripts/gold/pbench-copy-results/test-32.txt, agent/util-scripts/pbench-move-results, agent/util-scripts/unittests
Fixes #882.
Add unit test for --help as well.
=> Add --user and --help to pbench-{move,copy}-results usage

server/pbench/bin/pbench-base.sh
Set TZ to UTC in pbench-base.sh.
=> Force all the server scripts to use UTC

agent/tool-scripts/pprof
=> Ensure pprof executes commands once per interval

agent/tool-scripts/pprof
=> Use ${tool_bin} instead of "go" in pprof

server/pbench/bin/gold/test-12.txt, server/pbench/bin/pbench-dispatch, server/pbench/bin/pbench-server-prep-shim-001, server/pbench/bin/pbench-server-prep-shim-002
And remove wayward reference to `${prefix}` in shim 002.
=> Fix shim 001 to move prefix file to .prefix

agent/bench-scripts/pbench-fio
fixes issue 908
I don't think this requires immediate changes to gold files unless any of unit tests do multiple targets with remote clients (but maybe this should be added to unit tests?)
=> support multiple targets while using remote clients

server/pbench/lib/pbench/__init__.py
This is just to prevent a large error message from bloating the log
file. It does not solve the underlying problem which is that we sent
a payload that was bigger than the max that ES was willing to accept.
=> Limit the length of ES error messages

agent/tool-scripts/datalog/prometheus-metrics-datalog, agent/tool-scripts/prometheus-metrics
Fixes https://github.com/distributed-system-analysis/pbench/issues/1002
=> Allow insecure certs for prom2json

web-server/v0.4/package.json, web-server/v0.4/src/components/SiderMenu/SiderMenu.js, web-server/v0.4/src/e2e/home.e2e.js, web-server/v0.4/src/e2e/login.e2e.js, web-server/v0.4/src/index.ejs, web-server/v0.4/src/layouts/BasicLayout.js, web-server/v0.4/src/layouts/UserLayout.js
Includes changes to naming references within
configuration and layout files throughout the
dashboard.
=> Rename "PDash" references to "Pbench Dashboard"

agent/tool-scripts/postprocess/gold/index.html
This updates the `index.html` file in the `gold` sub-directory of the `tool-scripts/postprocess` tree to have all of the generated `.html` files in one place to make it easy to review via a web-browser.
=> Update gold index.html file

agent/bench-scripts/gold/pbench-fio/test-17.txt, agent/bench-scripts/gold/pbench-fio/test-18.txt, agent/bench-scripts/gold/pbench-trafficgen/test-21.txt, agent/bench-scripts/gold/pbench-trafficgen/test-22.txt, agent/bench-scripts/gold/pbench-trafficgen/test-26.txt, agent/bench-scripts/gold/pbench-uperf/test-15.txt, agent/bench-scripts/gold/pbench-uperf/test-16.txt, agent/bench-scripts/pbench-cyclictest, agent/bench-scripts/pbench-dbench, agent/bench-scripts/pbench-fio, agent/bench-scripts/pbench-iozone, agent/bench-scripts/pbench-linpack, agent/bench-scripts/pbench-migrate, agent/bench-scripts/pbench-moongen, agent/bench-scripts/pbench-netperf, agent/bench-scripts/pbench-run-benchmark, agent/bench-scripts/pbench-specjbb2005, agent/bench-scripts/pbench-trafficgen, agent/bench-scripts/pbench-uperf, agent/bench-scripts/unittests, agent/util-scripts/pbench-collect-sysinfo
=> Fix trafficgen metadata

web-server/v0.4/src/models/dashboard.js, web-server/v0.4/src/routes/Dashboard/Summary.js, web-server/v0.4/src/services/dashboard.js
Fixes #1038 
Uses Elasticsearch indexed table of contents of a tar ball to display in Tree structure
=> fixes: #1038 replace file system hierarchy view with a react-based tree visualizer

web-server/v0.4/src/common/menu.js, web-server/v0.4/src/common/router.js, web-server/v0.4/src/services/dashboard.js, web-server/v0.4/src/services/global.js
Previously this was causing issues in routing and retrieving the
dashboard config file due to missing route name or slash.
=> Update base URL paths for controller and search routes

web-server/v0.4/package.json, web-server/v0.4/src/routes/Dashboard/Controllers.js, web-server/v0.4/src/routes/Dashboard/Results.js, web-server/v0.4/src/routes/Dashboard/RunComparison.js, web-server/v0.4/src/routes/Dashboard/Summary.js
Previously users were not receiving an indication of no data returned
for a bad query.
This commit also contains small UX improvements to the PDF generation
modal and table of contents tab. Ant Design has also been upgraded to
support updates to internal components used throughout the dashboard.
=> Fix and improve search UX for controllers and results

server/lib/pbench/__init__.py
The environment option is really optional, so don't bother enforcing its
presence.
For the others, make sure we just raise BadConfig() exception as we
don't need a stack trace.
=> Don't require pbench-server 'environment' option

agent/bench-scripts/gold/pbench-trafficgen/test-22.txt, agent/bench-scripts/gold/test-benchmark-clis/test-CL.txt, agent/bench-scripts/pbench-trafficgen, agent/util-scripts/pbench-tool-trigger
Updates tool-trigger to allow sample number
Updates pbench-trafficgen to use tool triggers and specify the benchmark period that tools are used
=> Trafficgen trigger config

web-server/v0.4/src/pages/Dashboard/Summary.js
Rendered lists of children elements should contain a unique "key" prop
=> Resolve "each child in a list should have a unique key prop" console error/log message

agent/bench-scripts/pbench-gen-iterations, agent/bench-scripts/pbench-run-benchmark, agent/bench-scripts/pbench-run-benchmark-sample, agent/lib/PbenchAnsible.pm, agent/lib/PbenchBase.pm, agent/lib/PbenchCDM.pm
* Perl sytnax fixes for RHEL8, explicit `%{}` when using "`keys`"
* Implement `pbench-metadata-log`
* Perl fixes, use "`exists`"
=> Updates for pbench-run-benchmark

web-server/v0.4/src/models/dashboard.js, web-server/v0.4/src/pages/Dashboard/ComparisonSelect.js, web-server/v0.4/src/pages/Dashboard/Controllers.js, web-server/v0.4/src/pages/Dashboard/Results.js, web-server/v0.4/src/pages/Dashboard/RunComparison.js, web-server/v0.4/src/pages/Dashboard/Summary.js, web-server/v0.4/src/services/dashboard.js, web-server/v0.4/src/utils/parse.js
Handle removed spaces in result.json field names, which is only "closest sample"
for now.
Enables the UI to work with PR #1090.
=> Fix UI 'closest sample' references

web-server/v0.4/src/models/dashboard.js, web-server/v0.4/src/models/search.js, web-server/v0.4/src/services/dashboard.js
... and the other optional parameters as well.
We also fix the other fetch of run.prefix which could be undefined.
=> Handle @metadata.controller_dir properly

web-server/prisma/.gitignore, web-server/prisma/README.md, web-server/prisma/datamodel.prisma, web-server/prisma/index.js, web-server/prisma/package-lock.json, web-server/prisma/package.json, web-server/prisma/prisma.yml
Integrates Prisma as a GraphQL API server in order to
provide backend functionality through defined dashboard
datamodels.
=> Initial dashboard backend GraphQL infrastructure

web-server/v0.4/package.json, web-server/v0.4/src/components/RowSelection/index.js, web-server/v0.4/src/components/TableFilterSelection/index.js, web-server/v0.4/src/models/dashboard.js, web-server/v0.4/src/pages/ComparisonSelect/index.js, web-server/v0.4/src/pages/ComparisonSelect/index.test.js, web-server/v0.4/src/utils/parse.js
Improve filtering UX with new component for managing filter state and interaction with Table component.
Moves parsing logic to utility definition for use with
filtering updates.
=> Improve dashboard filtering UX

agent/bench-scripts/pbench-run-benchmark, agent/bench-scripts/pbench-run-benchmark-sample, agent/bench-scripts/postprocess/fio-postprocess-cdm, agent/config/benchmark/fio.json, agent/config/benchmark/pbench.json, agent/lib/PbenchBase.pm, agent/lib/PbenchCDM.pm, agent/tool-scripts/postprocess/iostat-postprocess-cdm, agent/util-scripts/cdm-get-iterations, agent/util-scripts/cdm-get-result, agent/util-scripts/pbench-import-cdm
This PR includes an update to CDM, sample query scripts for CDM, and a postprocess-only mode for pbench-run-benchmark, which we can use to defer postprocessing on the server (once that is automated, we can disable postprocessing when running under pbench-agent).
A follow-up PR will be made to sync up to Sysstat v12
=> Runbench cdmv4

agent/bench-scripts/gold/pbench-moongen/test-03.txt, agent/bench-scripts/gold/test-benchmark-clis/test-CL.txt, agent/bench-scripts/pbench-moongen
Initial patch addressing #1183
=> pbench-moongen: add deprecation warning

web-server/v0.4/src/components/PageHeader/index.js, web-server/v0.4/src/pages/ComparisonSelect/index.js, web-server/v0.4/src/utils/parse.js
Fixes #1166 
- The user can select as many controllers as they choose and the PageHeaderLayout component will wrap the title appropriately. 
- The title may be useful to confirm the controllers the user selected. 
- Displays controller tag next to each result selected.
=> Renders title properly in case of multiple controller selection

web-server/v0.4/src/app.js, web-server/v0.4/src/components/TableFilterSelection/index.js, web-server/v0.4/src/models/dashboard.js, web-server/v0.4/src/models/global.js, web-server/v0.4/src/pages/ComparisonSelect/index.test.js, web-server/v0.4/src/pages/Controllers/index.js, web-server/v0.4/src/pages/Controllers/index.test.js, web-server/v0.4/src/pages/Results/index.js, web-server/v0.4/src/pages/Results/index.test.js, web-server/v0.4/src/pages/RunComparison/index.js, web-server/v0.4/src/pages/Search/index.js, web-server/v0.4/src/pages/Search/index.test.js, web-server/v0.4/src/pages/Summary/index.js, web-server/v0.4/src/pages/Summary/index.test.js, web-server/v0.4/src/polyfill.js
This PR establishes baseline styling conventions enforced by configurations defined in `.prettierrc` and automatically runs via the pre-commit hook integration with Husky. As a result of this integration, we should not see styling changes in future PRs as they are automatically written to staged files once the user has passed the JavaScript linting hook.
=> Apply prettier configuration to all js source files

web-server/v0.4/package.json, web-server/v0.4/src/pages/RunComparison/index.js, web-server/v0.4/src/pages/RunComparison/index.test.js, web-server/v0.4/src/services/dashboard.js, web-server/v0.4/src/services/global.js, web-server/v0.4/src/services/search.js, web-server/v0.4/src/utils/request.js, web-server/v0.4/unittests
umi-request combines fetch and axios libraries to provide features
such as caching, timeout, and error handling.
`request.js` now implements a custom error handler to extend the default
handler shipped with umi-request for redirecting the user to the
appropriate exception pages.
=> Integrate umi-request for handling network request errors

agent/util-scripts/pbench-sysinfo-dump
=> Fix collection of sosreports to recognize tb names

web-server/v0.4/package.json, web-server/v0.4/src/components/TimeseriesGraph/index.js, web-server/v0.4/src/pages/RunComparison/index.js
`TimeseriesGraph` defines jschart as a React component and handles data
visualization according to the React lifecycle of the component.
Initial rendering occurs when the component mounts and reloading occurs
when new data, series names, or axis series data is passed to the
component.
=> Wrap jschart with React component for handling reloading/resetting

web-server/v0.4/README.md, web-server/v0.4/package.json, web-server/v0.4/src/e2e/controllers.e2e.js, web-server/v0.4/src/e2e/results.e2e.js, web-server/v0.4/src/e2e/search.e2e.js
Puppeteer is a Node library that provides an API to control the browser.
e2e testing covers all potiential user workflows related to a page
component and expectations for how page components should function.
Functionality provided by third party libraries are not covered within
these tests as we expect library maintainers to provide coverage for
functionality.
Before implementing e2e testing for the comparisonselect and
runcomparison page components, we require error handling for results
selected that are not supported by our comparison methodology (ex.
user-benchmark type). Once the error handler is integrated, we can write
generalized e2e tests using server data.
=> e2e testing for controller, results, and search pages using Puppeteer

web-server/v0.4/src/components/TableFilterSelection/index.js, web-server/v0.4/src/models/dashboard.js, web-server/v0.4/src/pages/ComparisonSelect/index.js, web-server/v0.4/src/utils/parse.js
Port selection is handled via new helper methods in `parse.js` and
referenced within the `TableFilterSelection` component.
=> Add iteration port filtering

agent/util-scripts/pbench-move-results
=> pbench-move-results: Quote variables in conditional expressions

agent/bench-scripts/gold/pbench-fio/test-07.txt, agent/bench-scripts/gold/pbench-fio/test-08.txt, agent/bench-scripts/gold/pbench-fio/test-30.txt, agent/bench-scripts/gold/pbench-fio/test-31.txt, agent/bench-scripts/pbench-fio.md, agent/bench-scripts/templates/fio-shared-fs.job, agent/bench-scripts/templates/fio.job, agent/bench-scripts/unittests
=> Make shared-fs fio job file work similar to non-shared

web-server/v0.4/package.json, web-server/v0.4/src/e2e/controllers.e2e.js, web-server/v0.4/src/e2e/results.e2e.js, web-server/v0.4/src/pages/Controllers/index.js, web-server/v0.4/src/pages/Search/index.js
Adjusts e2e tests to read persistent datastore via the localstorage key created with the pathname. This PR addresses issues #1275 and #1276.
=> Resolve e2e tests on dashboard entrypoints

README.md
minor fix: removed link to waffle.io in readme.
=> removed broken link in readme

agent/bench-scripts/postprocess/fio-postprocess-cdm
=> fio-postprocess-cdm: fix syntax error

agent/bench-scripts/postprocess/fio-postprocess
Removed the use of perl Switch in fio-postprocess
=> Remove switch

agent/util-scripts/pbench-agent-config-ssh-key
=> Fix permissions of `id_rsa` key file

web-server/v0.4/src/components/MonthSelect/index.js
=> Enforce latest indexed month as default selected value for controller view

agent/util-scripts/gold/pbench-copy-results/test-31.txt, agent/util-scripts/gold/pbench-copy-results/test-39.txt, agent/util-scripts/gold/pbench-copy-results/test-40.txt, agent/util-scripts/gold/pbench-copy-results/test-41.txt, agent/util-scripts/pbench-make-result-tb
Fixes #1391 
Adds timestamp for the time tarball is created
=> add timestamp for tarball

server/bin/gold/test-2.txt, server/bin/gold/test-3.txt, server/bin/gold/test-4.txt, server/bin/gold/test-5.1.txt, server/bin/gold/test-5.2.txt, server/bin/gold/test-5.txt, server/bin/gold/test-9.1.txt, server/bin/gold/test-9.2.txt, server/bin/gold/test-9.3.txt, server/bin/gold/test-9.4.txt, server/bin/gold/test-9.5.txt, server/bin/gold/test-9.6.txt, server/bin/gold/test-9.7.txt, server/bin/pbench-verify-backup-tarballs.py
Reverts distributed-system-analysis/pbench#1396
=> Revert "Remove redundant fetch of MD5s from verify backup"

CONTRIBUTION.md
Refers #1077 
The **_CONTRIBUTION.md_** file will help new people easily get started with contributions.
The google doc for the same can be found [here](https://docs.google.com/document/d/19nzpS7x7Piy9aZZBbl-eEZvtYAfW7fkqmLzZHpBRbkg/edit?usp=sharing).
=> Creates CONTRIBUTION.md

agent/base, agent/bench-scripts/unittests, agent/tool-scripts/datalog/unittests, agent/tool-scripts/postprocess/unittests, agent/tool-scripts/prometheus-metrics, contrib/containerized-pbench/dockerfiles/agent/Dockerfile, contrib/containerized-pbench/dockerfiles/controller/Dockerfile, server/bin/pbench-remote-sync-package-tarballs, server/bin/pbench-server-activate-create-results-dir-structure, server/bin/pbench-server-set-result-state, server/bin/pbench-trampoline
- Removed installation of which from Dockerfiles
Signed-off-by: T K Sourab <tsourab@redhat.com>
Fixes #1420
=> Replace `which` cmd with `command -v`

server/bin/gold/test-10.txt, server/bin/gold/test-11.txt, server/bin/gold/test-2.txt, server/bin/gold/test-3.txt, server/bin/gold/test-4.txt, server/bin/gold/test-5.1.txt, server/bin/gold/test-5.2.txt, server/bin/gold/test-5.txt, server/bin/pbench-sync-satellite.sh
Fixes #1443 
There is a missing log_finish to finish logging messages in pbench-sync-satellite.sh
=> Bug : Missing log_finish in pbench-sync-satellite.sh

web-server/v0.4/src/pages/Search/index.js
Fixes #1116 for the search page.
=> Feat: fixes 'each child should have a unique key error' in search page

agent/bench-scripts/pbench-specjbb2005
Add --config longoption to getopts check and fix sed regex for props file settings.
=> Fix specjbb2005 bugs

web-server/v0.4/src/e2e/controllers.e2e.js
I had a look at [this](https://github.com/puppeteer/puppeteer/issues/1805) issue in the official puppeteer docs. To fix this, they use `waitFor()`. I have used `waitForSelector()` method to wait till the element is visible to the page, also `waitFor()` before selecting rows. Fixes #1482.
=> Fix pagination e2e bug

web-server/v0.4/src/pages/Explore/index.js
=> fix maximum depth error on Explore page

web-server/v0.4/src/components/GlobalHeader/index.js, web-server/v0.4/src/components/SiderMenu/index.js, web-server/v0.4/src/layouts/BasicLayout.js
=> import link, fix side bar collapse issue

web-server/v0.4/src/app.js, web-server/v0.4/src/models/user.js, web-server/v0.4/src/pages/Controllers/index.js, web-server/v0.4/src/pages/Controllers/index.test.js, web-server/v0.4/src/pages/Results/index.js, web-server/v0.4/src/pages/Results/index.test.js
=> User favouriting controllers and results

.flake8, .pre-commit-config.yaml, .travis.yml, doc/CONTRIBUTING.md, requirements.txt
Add flake8 configuration file so that we can start
to correct pep8 errors.
=> Add .flake8

agent/util-scripts/gold/pbench-register-tool-set/test-11.1.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.12.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.14.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.2.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.3.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.4.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.5.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.6.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.9.txt, agent/util-scripts/gold/pbench-register-tool-set/test-11.txt, agent/util-scripts/pbench-register-tool-set
=> Add single quotes to perf tool options

agent/bench-scripts/pbench-uperf
Fixes #1510 by emitting one group for write and another read.
=> Fix uperf XML for bidirec test type

agent/util-scripts/pbench-postprocess-tools
An alternative to consider instead of #1563.
=> Capture new .screen.d with tool data

agent/config/pbench-agent-default.cfg
=> Change the fio version that pbench will use

agent/config/benchmark/fio.json, agent/config/pbench-agent-default.cfg
=> Bump fio version to 3.19.

.flake8, .pre-commit-config.yaml, .travis.yml, agent/bench-scripts/postprocess/fio-postprocess-viz.py, agent/bench-scripts/templates/make-fio-jobfile.py, agent/util-scripts/getconf.py, lib/configtools/__init__.py, pyproject.toml, server/bin/getconf.py, server/bin/pbench-backup-tarballs.py, server/bin/pbench-base.py, server/bin/pbench-index.py, server/bin/pbench-report-status.py, server/bin/pbench-satellite-state-change.py, server/bin/pbench-verify-backup-tarballs.py, server/bin/test-bin/test_logger_type.py, server/lib/pbench/__init__.py, server/lib/pbench/indexer.py, server/lib/pbench/mock.py, server/lib/pbench/report.py, server/lib/s3backup/__init__.py, web-server/v0.3/demo.py
* Running black against pbench.
* Running flake8 against pbench.
* Enforce flake8 and black when going forward.
=> Run black and flake8 against pbench directory

agent/util-scripts/pbench-clear-tools
Should be '-r' rather than '-n'.
=> Fix typo in usage

server/bin/pbench-backup-tarballs.py, server/bin/pbench-base.py, server/bin/pbench-index.py, server/bin/pbench-report-status.py, server/bin/pbench-satellite-state-change.py, server/bin/pbench-verify-backup-tarballs.py
Fixes issue #1585 
Format the following scripts using f-strings -
=> formatted scripts using f-strings

server/bin/pbench-server-prep-shim-002.sh
If the reception area and the archive area are on the same volume, using a `cp` command will ALWAYS copy the data. But if we use a `mv` command then we can avoid a data copy when the reception and archive areas share a volume.  When the reception and archive areas are on separate volumes, a `mv` will just do a "copy-n-delete".
We change the algorithm to first copy the `.md5` file to the destination so that we have a well defined set of clean steps when the tar ball copy fails.
=> Use mv instead of cp to avoid a data copy

server/bin/gold/test-24.txt, server/bin/gold/test-8.txt, server/lib/config/pbench-server-default.cfg
=> Add audit-server cron, spacing out others

agent/bench-scripts/pbench-fio, agent/bench-scripts/pbench-uperf, pbench/__init__.py, pbench/cli/agent/cmd.py, pbench/cli/agent/shell.py, pbench/server/indexer.py, pbench/server/mock.py, server/bin/pbench-cull-unpacked-tarballs.py
Fix unittest failures after merge from master.
=> Fix unittest failures

server/bin/gold/test-28.txt, server/bin/pbench-base.sh, server/bin/pbench-remote-sync-package-tarballs, server/bin/pbench-sync-satellite.sh, server/bin/state/test-28.config/pbench-server.cfg, server/bin/test-bin/ssh, server/bin/unittests
=> Improves handling of ssh error in sync-satellite logs

lib/pbench/server/__init__.py, lib/pbench/server/api/__init__.py, lib/pbench/test/unit/server/conftest.py, server/bin/gold/test-1.txt, server/bin/gold/test-2.txt, server/bin/gold/test-3.txt, server/bin/gold/test-4.txt, server/bin/gold/test-6.1.txt, server/bin/gold/test-6.2.txt, server/bin/pbench-backup-tarballs.py, server/bin/pbench-base.py, server/bin/pbench-check-tb-age.py, server/bin/pbench-cull-unpacked-tarballs.py, server/bin/pbench-index.py, server/bin/pbench-reindex.py, server/bin/pbench-verify-backup-tarballs.py
=> Use pathlib where possible

agent/base
While working on #1248, the tabs vs spaces issue in the file was adding extra changes in the diffs.  This PR pulls those changes out separately to reduce them.
This commit should only contain whitespace changes (tabs to spaces).
=> Fix tabs vs spaces in agent/base

README.md, server/lib/systemd/pbench-server.service
Fixes: https://github.com/distributed-system-analysis/pbench/issues/1736
=> Fix project name to Pbench.

lib/pbench/cli/server/shell.py
=> Make shell.py into a package that exports a main().

agent/tool-scripts/datalog/perf-datalog
=> Only emit a warning message on missing debugfs

agent/tool-scripts/node-exporter, agent/util-scripts/pbench-tool-meister-start, lib/pbench/agent/tool_data_sink.py, lib/pbench/agent/tool_meister.py, lib/pbench/agent/toolmetadata.py
These are the changes specified for tool-meister branch
=> CODE REVIEW CHANGES

lib/pbench/cli/server/shell.py, lib/pbench/server/api/__init__.py, requirements.txt, server/lib/config/nginx.conf.example, server/lib/config/pbench-server-default.cfg, server/lib/systemd/pbench-server.service.default, server/lib/systemd/pbench-server.service.rhel7
- Runs the pbench-server systemd service with wsgi gunicorn server
- Add example configuration for Nginx 
- Addresses the issue https://github.com/distributed-system-analysis/pbench/issues/1801
=> Add gunicorn wsgi server configuration

lib/pbench/agent/tool_data_sink.py
Close a race condition where the thread creating the internal Bottle server has not had a chance to create the object before the main thread attempts to invoke it's `stop` method.
Fixes #1853.
=> Ensure Tool Data Sink internal server object exists

agent/templates/prometheus.yml, agent/tool-scripts/dcgm, agent/tool-scripts/node-exporter, agent/util-scripts/pbench-tool-meister-start, lib/pbench/agent/tool_data_sink.py, lib/pbench/agent/tool_meister.py
Code review changes requested for persistent tooling additions
=> Post-Merge Review Changes

agent/util-scripts/gold/test-client-tool-meister/test-53.txt, agent/util-scripts/unittests
Fixes #1807
Sort the test log output.
=> Fix util-scripts test-53

css/style.css, index.css, index.html, js/drawer.js
=> Adds drawer option to sub cards in documentation page

lib/pbench/server/api/__init__.py, lib/pbench/test/unit/server/test_requests.py
Addresses the issue https://github.com/distributed-system-analysis/pbench/issues/1860
Specifically it makes the following changes
- Replaces the md5sum header name to standard `Content-MD5`
- First writes the md5sum on the disk before writing the tarfile content
- Writes the tarfile content with tempfile before actually writing on disk
- Replaces upload POST request with PUT request and remove hostname from header req
- The new upload URI will be /upload/ctrl/<string:controller_name>
- The controller name will be specified by the user when building the URI
=> Replace POST /upload to PUT /upload/ctrl/<controller> and write md5sum on disk on server

server/rpm/pbench-server.spec.j2
In light of PR#1873, the %files list needed fixing.
=> Fix %files list

lib/pbench/agent/results.py, lib/pbench/cli/agent/commands/results/__init__.py, lib/pbench/test/unit/agent/task/test_copy_result_tb.py, lib/pbench/test/unit/agent/task/test_move_results.py
Agent cli was using post request to `/upload` endpoint, however it should now be updated PUT request to `/upload/ctrl/<controller>` endpoint
=> Update agent cli to reflect server upload http changes

agent/requirements.txt, lib/pbench/agent/base.py, lib/pbench/agent/utils.py, lib/pbench/cli/agent/commands/tools/clear.py
Rejig logging a bit so that we set the agent logging in the base class.
=> Agent logging

start.html
Fixes #1909 
This PR currently contains two commits:
- The first commit reformats the HTML without any changes in the rendered output. The reformatted HTML is easier to manipulate manually (although still very labor-intensive).
- The second commit is the actual changes in content.
=> Installation guide updates

agent/tool-scripts/datalog/prometheus-metrics-datalog
We have run `black` on it, made sure it passes `flake8`.
This was pulled out of PR #1936.
=> Cleanup `datalog/prometheus-metrics-datalog`

js/tab.js, learn.html, start.html
=> Adds ability to reference tabs on 'Getting Started' and 'Learn More' page

css/style.css, doc.html
Fixes responsiveness of [documentation(agent installation)](https://distributed-system-analysis.github.io/pbench/doc.html) tab
Fixes #1951
=> Fixes responsiveness of documentation(agent installation) tab

contrib/analysis/generate-pbench-timeseries-graphs
Generate time series graphs from pbench .csv files.
*generate-pbench-timeseries-graphs* -- generate graphs from .csv files from Pbench raw output
Usage (for now): process-timeseries [files...] | bash
Lots of TODOs:
1. Command line arguments for image size, max # of data sets, what else?
2. Actually feed the output into gnuplot rather than just sending it to stdout
3. Optionally sort data sets by max value or max average
4. Combine multiple samples into 1.
This will require that generate-pbench-timeseries-graphs enumerate the files
(or accept the file list on stdin rather than command line) because the command
line won't be able to accept all of the files in a data set.
5. Handle .csv files from perf and any other tools I've missed.
6. Allow scaling of Y and possibly X axis.
7. Allow …
=> Contribute generate-pbench-timeseries-graphs from `.csv` files in a pbench result hierarchy

css/style.css, js/accordion.js
=> fixes accordion cards functionality

README.md, agent/tool-scripts/README.md, doc/CONTRIBUTING.md
Mostyly typos and grammar fixes.
Clean up some incorrect statements as well, mostly by deleting them.
=> Fix typos, grammar etc in *.md files

lib/pbench/common/logger.py
While working PR #1914, we found that our log formatter was not handling records that already had a formatted `asctime` field.  When we compared the code against what the default Python 3 (3.6 version used, the lowest version we support), we found that we were not handling this properly.
This change updates the code to more closely match the behavior of the 3.6 logger using the logging interfaces as intended.  Well, with one exception, we ignore the specified `datafmt` and always use UTC time in the ISO format.
Fixes #2003.
=> Fix the Python 3 logger to handle time properly

contrib/analysis/generate-pbench-timeseries-graphs
* Extract .csv files from tarballs (must be local right now)
* Optional specify files on command line
* Add -m/-M for file name patterns that must/must not match
* Add -L max label length
* Add -O output directory
* Place .png files above .csv directory
* Fix a number of errors in the pattern list
* Skip non-tool .csv files more cleanly
=> Phase 2 of generate-pbench-timeseries-graphs:

lib/pbench/agent/tool_data_sink.py
The quay org had a name change from "prom" to "prometheus"
=> Prometheus quick fix

server/bin/gold/test-24.txt, server/bin/gold/test-8.txt, server/lib/config/pbench-server-default.cfg
Update unit tests test-8 and test-24 as well.
=> Make the backup cron job run every minute

agent/bench-scripts/templates/make-fio-jobfile.py, contrib/agent/bench-scripts/pbench-bzt, lib/pbench/server/indexer.py
See https://lgtm.com/projects/g/distributed-system-analysis/pbench/alerts/?mode=list&severity=error
=> Address lgtm.com errors

.coveragerc, agent/containers/images/Makefile, agent/containers/images/README.md, agent/tool-scripts/postprocess/unittests, jenkins/Pipeline.gy, jenkins/python-setup.sh, jenkins/run, jenkins/run-pytests, tox.ini
Add the ability to run pytest coverage report.
Jenkins integration take from https://mdyzma.github.io/2017/10/14/python-app-and-jenkins/.
=> Add coverage support

.coveragerc, agent/containers/images/Makefile, agent/containers/images/README.md, agent/tool-scripts/postprocess/unittests, jenkins/Pipeline.gy, jenkins/python-setup.sh, jenkins/run, jenkins/run-pytests, tox.ini
Reverts distributed-system-analysis/pbench#2050
=> Revert "Add coverage support"

server/bin/pbench-index.py
=> Adding signal Handlers in pbench-index.py

agent/bench-scripts/pbench-fio, agent/bench-scripts/postprocess/fio-postprocess-viz.py, agent/bench-scripts/test-bin/fio-histo-log-pctiles.py, agent/bench-scripts/tests/pbench-fio/test-04.txt, agent/bench-scripts/tests/pbench-fio/test-15.txt, agent/bench-scripts/tests/pbench-fio/test-28.txt, agent/bench-scripts/tests/pbench-fio/test-32.txt
=> pbench-fio: compute localhost latency profiles

agent/containers/images/visualizers/DockerfileLive, agent/containers/images/visualizers/DockerfilePostPCP, agent/containers/images/visualizers/README.md, agent/containers/images/visualizers/run.py
Available at quay.io/pbench/pcp-graf-visualizer
Also a couple minor changes to existing images
- Updated to Fedora 33
- Also address issue #2078
=> PCP Post-Run Visualization Update

contrib/analysis/generate-pbench-timeseries-graphs
Fix some errors from lgtm bot and update todo list
=> Fix unused variables from lgtm bot

agent/tool-scripts/jaeger, agent/tool-scripts/meta.json
This is a hodge-podge merge to consolidate all the edits.
=> Review jaeger register

agent/util-scripts/gold/test-client-tool-meister/test-53.txt, agent/util-scripts/gold/test-client-tool-meister/test-56.txt, agent/util-scripts/gold/test-client-tool-meister/test-57.txt, agent/util-scripts/test-bin/dcgm-exporter, agent/util-scripts/test-bin/mock-cmd
This is work pulled over from the `comp-150` branch.
=> Share mocks between persistent tools

Demo/src/demo_script.sh, Demo/src/test_client.py
Added Xiaoxiong's demo script for running node1_server.py and then connecting to two other hosts to run test_client.py. Modified the test client to iterate making requests to the server for an interval and a duration.
=> demo script executable and test_client.py changes

agent/containers/images/visualizers/DockerfilePostProm, agent/containers/images/visualizers/README.md, agent/containers/images/visualizers/combo.json, agent/containers/images/visualizers/dcgm.json
Only requires Prometheus data folder to be mounted now (no seperate promtheus.yml)
Also fixed DCGM panel formatting and fixed the GPU Mem Cpy Utilization panel
=> PromGrafVisualizer Input Update + DCGM Panel Bug Fix

Demo/src/READ_ME.txt, Demo/src/test_client.py, lib/pbench/agent/tool_data_sink.py
Also modified the Demo README to include an example Docker command for running Jaeger with persistent Badger storage. Fixed an issue in the test_client.py script where the request spans do not appear as children of the main span.
=> Added Badger environment variables to jaeger-all-in-one subprocess

server/rpm/pbench-server.spec.j2
=> Make pip install into `%{installdir}`

agent/util-scripts/unittests
See https://github.com/distributed-system-analysis/pbench/pull/2283#discussion_r626739807.
=> Add expected exit status to unittests failures

lib/pbench/server/api/resources/upload_api.py
We add support for returning `INSUFFICIENT_STORAGE` (`507`) when writing a tar ball to disk and the server runs out of space (the specific exception is caught and handled only while writing the tar ball contents to disk).
While we are at it, we replace the use of `logger.exception()` with `logger.error()`, since the `flask.abort()` method also emits a stack trace.  This avoids have 2 stack traces emitted in the logs for the same error.
=> Handle `ENOSPC` and report exceptions once

lib/pbench/server/api/__init__.py, lib/pbench/server/api/auth.py, lib/pbench/server/api/resources/endpoint_configure.py, lib/pbench/server/api/resources/graphql_api.py, lib/pbench/server/api/resources/users_api.py, lib/pbench/server/database/models/users.py, lib/pbench/test/unit/server/test_user_auth.py
- Attempt at refactoring few pieces of convoluted server API code
- Change Http status codes to use the respective symbolic names
=> Some Refactor and change Http codes to use symbolic names

lib/pbench/cli/server/shell.py, lib/pbench/server/api/auth.py, lib/pbench/test/unit/agent/task/test_copy_result_tb.py, lib/pbench/test/unit/agent/task/test_generate_token.py, lib/pbench/test/unit/agent/test_tool_data_sink.py, lib/pbench/test/unit/server/test_requests.py, lib/pbench/test/unit/server/test_user_auth.py, server/lib/config/pbench-server-default.cfg
=> Add gunicorn worker timeout and replace all http numeric status

lib/pbench/server/api/auth.py, lib/pbench/server/api/resources/query_apis/__init__.py, lib/pbench/server/api/resources/query_apis/controllers_list.py, lib/pbench/server/api/resources/query_apis/datasets_detail.py, lib/pbench/server/api/resources/query_apis/datasets_list.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/query_apis/conftest.py, lib/pbench/test/unit/server/query_apis/test_controllers_list.py, lib/pbench/test/unit/server/query_apis/test_datasets_detail.py, lib/pbench/test/unit/server/query_apis/test_datasets_list.py, lib/pbench/test/unit/server/test_requests.py, lib/pbench/test/unit/server/test_schema.py
Adds a strict Bearer Authorization requirement on all the elasticsearch Post/Get APIs
=> Add Authorization header requirement on all the es APIs

agent/util-scripts/pbench-make-result-tb
=> Fix stand-alone use of `pbench-make-result-tb`

agent/rpm/pbench-agent.spec.j2
=> Remove write permission on agent installed files

lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/query_apis/commons.py, lib/pbench/test/unit/server/query_apis/test_datasets_publish.py, lib/pbench/test/unit/server/test_requests.py
Fixes issue https://github.com/distributed-system-analysis/pbench/issues/2246 "Add malformed authorization unit test for PUT API"
=> Add malformed authorization unit test

agent/containers/images/image-test-script.sh
Modified Peter's old demo script to serve as a pbench image test script.
Walks a user through a semi-automated image testing process with simple input prompts.
^^^ ORIGINAL GOAL ^^^
Now a full demo/test script with more options, defaults, error checking, greater clarity, and an example workflow to collect meaningful data.
=> Adding pbench image test script

agent/bench-scripts/pbench-fio
_From @webbnh's post in https://github.com/distributed-system-analysis/pbench/pull/2535#discussion_r747677569_
=> Remove use of `wc -w` sub-process

doc.html
Documentation changes for PR #2545.
=> Remove deprecated benchmark scripts

agent/util-scripts/pbench-clear-tools
=> Added missing `-r` option in `Pbench-clear-tools`

agent/profile
Addresses issue https://github.com/distributed-system-analysis/pbench/issues/2383
=> Make sure /usr/sbin is present in system PATH

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/__init__.py, lib/pbench/server/api/resources/query_apis/datasets/datasets_contents.py, lib/pbench/test/unit/server/conftest.py, lib/pbench/test/unit/server/query_apis/test_datasets_contents.py, lib/pbench/test/unit/server/query_apis/test_datasets_mappings.py, lib/pbench/test/unit/server/test_endpoint_configure.py
Fixes #2393 
The table of content API aims at listing the whole directory structure of a result on the request of the user.
=> TableOfContent (ToC) Server API

jenkins/python-setup.sh, jenkins/run, jenkins/run-unittests, server/bin/unittests
These 4 commits represent a series of fixes to get the test infrastructure running in the Jenkins CI environment where the executors are now running on RHEL 8.4 and 8.5.
Each individual commit describes what it is trying to address.
=> Jenkins CI fixes

agent/test-requirements.txt, server/requirements.txt, server/test-requirements.txt
=> Sort python requirements files

agent/bench-scripts/postprocess/user-benchmark-wrapper, agent/bench-scripts/test-bin/mock-postprocess/dbench-postprocess, agent/bench-scripts/test-bin/mock-postprocess/uperf-postprocess, agent/tool-scripts/datalog/haproxy-ocp-datalog, agent/tool-scripts/datalog/oc-datalog, agent/tool-scripts/datalog/pprof-datalog, agent/tool-scripts/datalog/prometheus-metrics-datalog, agent/tool-scripts/pcp, agent/util-scripts/pbench-add-metalog-option, agent/util-scripts/pbench-tool-meister-start, agent/util-scripts/pbench-tool-meister-stop, pyproject.toml, server/bin/pbench-pp-status
We also apply `black` and `flake8` to them.
=> Use `black` on some additional files

agent/base
And fix a tab vs spaces problem and local variable declarations.
=> Normalize variable references in `agent/base`

exec-unittests
Fix a minor but critical typo...
=> Include "common" pytests in tox exec-unittests

.github/workflows/codeql-analysis.yml
This file is auto-generated by the GitHub button.
=> Turn on CodeQL analysis

agent/util-scripts/unittests
Foundational change ahead of pR #2743.
=> Remove unused `common` directories

lib/pbench/agent/tool_data_sink.py
Like the Tool Meister module, employ a `NamedTuple` for the Tool Data Sink parameters.
Layered on PR #2755.
=> Employ a `NamedTuple` for TDS parameters

lib/pbench/agent/tool_meister_start.py
We apply a small refactoring to the Tool Meister start logic to bring  together the required environment variables in one place, and only  create the local Tool Meister working directory when we are asked to  orchestrate the sub-system setup.
Layered on PR #2756.
=> Refactor Tool Meister start to consolidate logic

lib/pbench/agent/tool_data_sink.py, lib/pbench/agent/tool_meister.py
This PR addresses small items I encountered in the course of working towards what is now #2766.
They are mostly non-functional or functional-with-no-net-impact.  There are a couple which are functional changes, but even those cases should produce no detectable change in behavior.  And, there are some typos fixed.
=> Small changes to improve code quality

lib/pbench/test/unit/agent/test_config.py
This test aims to increase the test coverage for PbenchAgentConfig class.
=> Pbench Agent Test Coverage: PbenchAgentConfig tests

web-server/v0.3/demo.html
=> Use HTTPS for D3 loads (back-port)

exec-unittests
This is a simple backport of commit 9e9dec8a4.
=> Backport testing of source tree builds

agent/containers/images/Dockerfile.base.j2, agent/containers/images/Dockerfile.layered.j2, agent/containers/images/Makefile, lib/pbench/cli/agent/commands/generate_token.py, server/containers/images/Dockerfile.base.j2
This PR contains two commits which backport the changes from #2858 and #2862, respectively.
=> Backport container build fixes and generate-token tweaks

dashboard/jsdoc.json, dashboard/package.json, dashboard/src/utils/dateFunctions.js, dashboard/src/utils/filterDataset.js, dashboard/src/utils/helper.js
Documented the helper methods using jsDoc.A new run script added.The user can now run `npm run jsdoc` to generate the HTML version of documentation.
The documentation format looks like this:-
Description of the Function
Datatype of the parameters passed into the function along with a short description of each parameter
Return type of the function along with a small description
=> Documentation for helper methods of Pbench_dashboard

lib/pbench/server/api/__init__.py, lib/pbench/server/api/resources/query_apis/datasets_detail.py, lib/pbench/test/unit/server/query_apis/test_datasets_detail.py, lib/pbench/test/unit/server/test_endpoint_configure.py
URI parameterization of the dataset name in the `dataset/details` endpoint
=> Dataset name in the URI for /datasets/details endpoint

dashboard/src/modules/components/TableComponent/common-components.jsx, dashboard/src/modules/components/TableComponent/index.jsx
While unit testing, i encountered a problem that few elements, which are either having no particular label or elements who are having non-unique labels are very difficult to target.So to make them easy to target(and therefore, easy to test),I have given all such elements an aria-label attribute, by which we can target those elements easily.
=> Added notion of aria-label to elements of browsing page that are not easily targetable

dashboard/src/App.js, dashboard/src/modules/components/TableComponent/common-components.jsx, dashboard/src/modules/components/TableComponent/index.jsx
PR #2850 which was an incremental clean up on PR #2733, induced a bug in search feature of browsing page.The redirect feature on Alert also got removed.This PR is an attempt to fix those bugs.There is an addition of two important edge case also.
=> Minor Bug fixes in dashboard

lib/pbench/server/filetree.py, lib/pbench/test/unit/server/test_file_tree.py
PBENCH-774
The logic to discover and link INCOMING directories and RESULTS links was too far out, and weren't being used by `find_dataset`. Refactor this into object construction so it doesn't get missed.
=> Fix FileTree.find_dataset to link unpacked data

lib/pbench/test/unit/common/config/hostport-missing-port.cfg, lib/pbench/test/unit/common/config/hostport-missing.cfg, lib/pbench/test/unit/common/config/hostport.cfg, lib/pbench/test/unit/common/config/logdir.cfg, lib/pbench/test/unit/common/test_config.py
PBENCH-213
Increases the test coverage for the PbenchConfig class.
Removed unnecessary file usage along the script.
=> PbenchConfig unit-test Test Coverage

contrib/analysis/collect_config_data.py, contrib/analysis/merge.py, contrib/analysis/merge_sos_and_perf_parallel.py
Convert multiple try-except blocks to 1 try-except block in a loop to avoid code duplication
Change mode of all to_csv method calls to 'w' so files are overwritten each execution - eliminating the problem of non-uniqueness that was arising after multiple executions.
[23-06-2022.md](https://github.com/distributed-system-analysis/pbench/files/8987479/23-06-2022.md)
@portante
=> Style changes and Elimination of timeout errors on execution

docs/gh-pages/contact.html, docs/gh-pages/doc.html, docs/gh-pages/learn.html, docs/gh-pages/start.html, docs/index.html
The year 2015 was from very first commit of the repo.
I added link to RH official project list because we want to help combating a recent supply chain attack.
=> Added link to list of official RH projects, changed time

dashboard/src/App.css, dashboard/src/actions/overviewActions.js, dashboard/src/actions/toastActions.js, dashboard/src/assets/constants/overviewConstants.js, dashboard/src/modules/components/OverviewComponent/NewRunsComponent.jsx, dashboard/src/modules/components/OverviewComponent/SavedRunsComponent.jsx, dashboard/src/modules/components/OverviewComponent/common-component.jsx, dashboard/src/modules/components/OverviewComponent/index.jsx, dashboard/src/modules/components/OverviewComponent/index.less, dashboard/src/modules/components/TableComponent/index.jsx, dashboard/src/utils/dateFunctions.js, dashboard/src/utils/filterDataset.js
PBENCH-845
Saved Runs
List the Saved runs with three dots functionality
=> Saved Runs of Overview Page

.pre-commit-config.yaml, agent/bench-scripts/test-bin/mock-postprocess/trafficgen-postprocess
During another review, I ran across a couple of vestiges of trafficgen, and then I found another.  This PR removes them.
=> Remove trafficgen vestiges

dashboard/src/modules/components/TableComponent/index.jsx
Removed unknown property which caused the CI build to fail
=> CI build error

lib/pbench/test/unit/server/test_requests.py
The `verify_logs` method in `test_requests.py` now looks for the expected warning message explicitly.
=> Correct method of verifying log messages

lib/pbench/server/filetree.py, lib/pbench/test/unit/server/test_file_tree.py
PBENCH-864
This PR deals with adding core unpack functionality to Tarball.unpack in FileTree, which includes unpacking of tarball in the incoming tree. It also includes Test around this Functionality.
Further work related to this issue is followed in PR [2975](https://github.com/distributed-system-analysis/pbench/pull/2975). This PR includes getting rid of old functionality and making use of this one.
=> Add unpack functionality to Tarball.unpack

lib/pbench/test/unit/server/test_indexer.py
During the review of PR #3032 a few additional unit tests were identified.
=> Add additional `expand_uid_template` unit tests

lib/pbench/test/unit/agent/test_tool_group.py
No code was harmed while implementing this PR, just 4 spaces removed from the beginning of each line, but then `black` attacked it.
=> Correct `test_tool_group.py` code indentation

dashboard/src/modules/components/OverviewComponent/NewRunsComponent.jsx, dashboard/src/modules/components/OverviewComponent/SavedRunsComponent.jsx, dashboard/src/modules/components/OverviewComponent/common-component.jsx, dashboard/src/modules/components/OverviewComponent/index.jsx, dashboard/src/modules/components/OverviewComponent/index.less
PBENCH-990
Empty State UI of Overview Page
Update the no result view of overview page
=> Empty State UI of Overview Page

docs/index.rst
Fix index.rst to remove invalid pbench dashboard repo information.
=> Delete incorrect desc of pbench dashboard repo

lib/pbench/server/templates.py
PBENCH-450
Elasticsearch templates are loaded into SQL dynamically. There's a `find` to determine whether each template already exists in the database; however during startup it's possible for two independent tasks (e.g., indexer and backup) to do this at the same time. Both might find that the template doesn't exist, and attempt to create it. This sometimes results in a hang condition.
The duplication is not really a problem as both tasks would be loading the same templates. Instead of failing, simply issue a `warning` log (to help detect when this happens) and continue.
=> Fix duplicate template error

lib/pbench/client/__init__.py, lib/pbench/server/api/resources/upload_api.py, lib/pbench/server/unpack_tarballs.py
PBENCH-1027
Rescue a few minor fixes and diagnostics from the languishing #3103.
=> Fix sync status management

lib/pbench/test/functional/server/test_put.py
Correct an infinite loop condition.
----
This is a follow-up based on https://github.com/distributed-system-analysis/pbench/pull/3133#discussion_r1061626532.
=> Refactor `test_index_all` server func test

lib/pbench/server/api/resources/__init__.py
In the course of reviewing PR #3122, I ran across some code which looked suspect.  As that PR has already been merged, I'm offering this PR as an amendment to those changes.
Discussion with Peter suggests that the issue which I'm addressing was a botched merge.  The results of my changes are to remove the surplus code, with a little added optimization.
=> Amendments to PR #3122

dashboard/src/actions/overviewActions.js, dashboard/src/modules/components/OverviewComponent/NewRunsComponent.jsx, dashboard/src/modules/components/OverviewComponent/SavedRunsComponent.jsx
PBENCH-1016
Publish command in dashboard Overview Page
The dashboard currently allows deleting a dataset from the overview page pull down menu. It should also allow "publish".
=> Publish command in dashboard Overview Page

lib/pbench/server/api/resources/datasets_list.py
See https://github.com/distributed-system-analysis/pbench/pull/3114/commits/186e640a860842636f3ac330807a8e0ecd9126ab from PR #3114.
=> Remove wayward info log messages, fix doc strings

server/lib/config/pbench-server-default.cfg, server/pbenchinacan/etc/pbench-server/pbench-server.cfg
=> Remove unused `bulk_action_count`

lib/pbench/server/database/__init__.py
Pulled from https://github.com/distributed-system-analysis/pbench/pull/3114/commits/511cf82af8ecf8017084870468cc9397ccdfb4da in PR #3114.
=> Merge imports from same module

lib/pbench/server/api/__init__.py
See "About the First Parameter" at:
https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask
See also https://github.com/distributed-system-analysis/pbench/pull/3114/commits/889cbfd7b8dc3380a5cde80ac36aacd6252d71b4 in PR #3114.
=> Use recommended Flask application name

lib/pbench/cli/server/shell.py, lib/pbench/server/database/__init__.py, lib/pbench/test/unit/server/conftest.py
Cleanup of doc strings for `database/__init__.py`.
=> Use helper `init_db` in API shell startup

lib/pbench/server/__init__.py, lib/pbench/server/api/resources/upload_api.py
We also move `rest_max_content_length` to a property.
----
This is a refactoring to pull out this change separately for consideration from the other changes in PR #3170.
=> Move default retention day config to a property

server/bin/gold/test-0.1.txt, server/bin/gold/test-0.2.txt, server/bin/gold/test-0.txt, server/bin/gold/test-1.txt, server/bin/gold/test-10.txt, server/bin/gold/test-11.txt, server/bin/gold/test-16.txt, server/bin/gold/test-17.txt, server/bin/gold/test-2.txt, server/bin/gold/test-22.txt, server/bin/gold/test-3.txt, server/bin/gold/test-4.txt, server/bin/gold/test-5.1.txt, server/bin/gold/test-5.2.txt, server/bin/gold/test-5.txt, server/bin/pbench-base.sh, server/bin/pbench-dispatch.sh, server/bin/pbench-satellite-cleanup.sh, server/bin/pbench-sync-package-tarballs.sh, server/bin/pbench-sync-satellite.sh, server/bin/pbench-unpack-tarballs.sh, server/bin/state/test-11.setup, server/bin/test-bin/failing-mv, server/bin/unittests
=> Change sync-satellite reception area

lib/pbench/cli/server/shell.py, lib/pbench/server/__init__.py, lib/pbench/server/api/__init__.py
This PR has been rearranged based on code-review feedback.  The final change is much simpler.  Thank you @webbnh for your review comments.
The original PR was derived from https://github.com/distributed-system-analysis/pbench/pull/3114/commits/b601dff81c549ed0f36b321e482587aef40c5787 from PR https://github.com/distributed-system-analysis/pbench/pull/3114#discussion_r1060917966.
=> Remove `_get_conf` and `get_conf` entirely

server/pbenchinacan/load_keycloak.sh
Simplifies the Keycloak build script a bit more
- Remove the need for 2 redundant loops from the script
- Remove the need to check health uri when building OIDC keycloak server
- Quite the keycloak output down
=> simplify keycloak build script

lib/pbench/test/functional/server/test_put.py
We also move the state/status checks to 45 seconds past the minute since the cron jobs run on the minute and we give them 3/4 of the minute to run before we perform a check (makes it so that in the server logs we get overlapping API calls with the cron job logs making easier to read the logs).
=> Enhance `test_index_all` to print state & status

server/pbenchinacan/load_keycloak.sh
Update the keycloak.sh to to not create a private client.
- Instead of creating a private pbench-server-client, it now creates pbench-dashboard public client.
Addresses issue #3242
=> Make the OAuth2 client public in our Keycloak config

lib/pbench/server/database/alembic/env.py, lib/pbench/server/database/database.py
We move the use of alembic migrations onto the main Pbench Server startup path, but only applied for non-sqlite databases.
=> Rely on alembic migrations to setup database

lib/pbench/server/api/resources/upload_api.py
----
Addresses a comment from https://github.com/distributed-system-analysis/pbench/pull/3138/files#r1065065651.
=> Apply small dictionary usage pattern improvement

server/bin/pbench-base.sh
Pulled out from PRs #3289, #3290, #3292, and #3293.
=> Group logging functions

server/bin/pbench-base.sh
Also ensure variables are referenced as `${}` and consistently use `[[`
tests.
----
Pulled from PRs #3290, #3292, and #3293.
=> Use local variables in `pbench-base.sh`

server/bin/gold/test-11.txt, server/bin/gold/test-5.2.txt, server/bin/pbench-base.sh, server/bin/pbench-dispatch.sh, server/bin/pbench-sync-satellite.sh, server/bin/pbench-unpack-tarballs.sh
=> Add server `warn` and `debug` logging interfaces

dashboard/src/modules/components/AuthComponent/LoginForm.jsx, dashboard/src/modules/components/AuthComponent/common-components.jsx
PBENCH-1095
Submit Login Form
On pressing the enter key submit the login form
=> Submit Login Form

dashboard/src/modules/components/AuthComponent/LoginForm.jsx, dashboard/src/modules/components/AuthComponent/SignupForm.jsx, dashboard/src/modules/components/AuthComponent/index.less, dashboard/src/modules/components/AuthComponent/signupFormData.js
PBENCH-1096
Signup page Bugs
- Make the scroll visible on sign up form
- Show password for both "Password" and "Confirm password" fields
- Include "Sign up" option in the Login form
=>  Signup page Bugs

server/lib/config/pbench-server-default.cfg, server/pbenchinacan/etc/pbench-server/pbench-server.cfg
Remove some obsolete config settings from the default and canned config files.
=> Config file changes

dashboard/src/modules/components/LoadingComponent/index.less, dashboard/src/modules/components/TableComponent/index.jsx
Pagination Component
Pagination overlapping on the Browsing page table
=> Pagination Component

server/lib/config/nginx.conf
See commits 114d32109 (PR #3364) and 6a5b263c0 (PR #3370).
=> Backport nginx `v2` configuration

lib/pbench/server/auth/auth.py
This PR follows up on https://github.com/distributed-system-analysis/pbench/pull/3399#discussion_r1176916933, making token validation slightly more robust:  we will now check if the bearer token is a valid API key after _any_ failure to validate it as an OIDC access token.
=> Check for API key on any failure to validate access token

docs/Agent/user-guide/guides/end-to-end-workflow.md
=> PBENCH-1155

dashboard/src/actions/overviewActions.js
PBENCH-1165
Dashboard PUT /datasets/<id>/metadata payload has extra JSON level
Bug Fix
=> Update metadata keys 

dashboard/src/actions/relayActions.js
=> Bug fix in Relay Modal

agent/containers/images/Dockerfile.base.j2, agent/containers/images/Dockerfile.layered.j2, agent/containers/images/Makefile, agent/containers/images/pcp.repo.j2
=> Backport agent containers to `b0.72`

dashboard/src/modules/components/OverviewComponent/NewRunsComponent.jsx, dashboard/src/modules/components/OverviewComponent/SavedRunsComponent.jsx, dashboard/src/modules/components/OverviewComponent/common-component.jsx
PBENCH-1253
Edit Server deletion date not working
=> Edit Server Deletion Bug

dashboard/src/actions/overviewActions.js
PBENCH-1254
Update metadata on dataset name and severer date changes
=> Update metadata on dataset name and server date changes

agent/containers/images/Dockerfile.base.j2, agent/containers/images/Dockerfile.layered.j2, agent/containers/images/Makefile, agent/containers/images/pcp.repo.j2
=> Backport agent containers to `b0.73`

.github/workflows/codeql-analysis.yml
=> Enable CodeQL runs on `b0.73` release branch

dashboard/src/modules/components/OverviewComponent/common-component.jsx, dashboard/src/modules/components/RelayUIComponent/index.jsx, dashboard/src/modules/components/RelayUIComponent/index.less
=> Relay  modal text update

agent/ansible/collection/roles/pbench_repo_install/templates/etc/yum.repos.d/pbench.repo.j2, agent/containers/images/repo.yml.j2
This is a forward port of #3544.
=> Correct COPR repo file generation in Agent container builds

dashboard/src/modules/components/OverviewComponent/NewRunsComponent.jsx, dashboard/src/modules/components/OverviewComponent/index.jsx
PBENCH-1265
New and Unmanaged runs header
=> New and Unmanaged runs header

dashboard/src/actions/overviewActions.js, dashboard/src/modules/components/OverviewComponent/NewRunsComponent.jsx, dashboard/src/modules/components/OverviewComponent/SavedRunsComponent.jsx, dashboard/src/modules/components/OverviewComponent/common-component.jsx, dashboard/src/modules/components/OverviewComponent/index.less
PBENCH-1264
- Included Metadata in saved runs
- Refactored the metadata helper functions
- Added key New runs row
=> Metadata in saved runs

dashboard/src/modules/components/ProfileComponent/NewKeyModal.jsx, dashboard/src/modules/components/ProfileComponent/index.less
PBENCH-1183
API key Popup Create Button
=> API key Popup Create Button

dashboard/src/App.js, dashboard/src/modules/components/ComparisonComponent/index.jsx, dashboard/src/modules/components/SidebarComponent/sideMenuOptions.js, dashboard/src/modules/components/TableComponent/index.jsx, dashboard/src/modules/components/TableComponent/index.less, dashboard/src/utils/routeConstants.js
PBENCH-1288
Dashboard bugs - Part I
- Remove Coming Soon pages
- Discard All runs option from side menu. Let's have Results
- Include Hand icon for ToC page navigation from the table
- Check the Visualisation page initial load
=> Dashboard bugs

dashboard/src/actions/comparisonActions.js
PBENCH - 1293
Fio - Latency data metric unit
=> Fio - Latency data metric unit

dashboard/src/modules/components/SidebarComponent/index.jsx, dashboard/src/modules/components/SidebarComponent/sideMenuOptions.js
=> Update Side Menu

dashboard/src/actions/datasetListActions.js, dashboard/src/actions/overviewActions.js
PBENCH-1309
Overview page displays Public datasets
=> Overview page displays Public datasets
